### ISSUE TITLE
[CI Problem] [Flaky Test] test_qlinear_average_pool[cuda]

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#10019]
### Flakiness
Test test_qlinear_average_pool[cuda]

happened multiple times:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9993/1/pipeline/
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9982/3/pipeline/

cc @sfvaroglu @mbrookhart

**Comment by masahi** [comment]
I've hit this too https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9986/11/pipeline

**Comment by junrushao1994** [comment]
It happens very frequently. I'm going to temporarily disable this test to unblock CI jobs, so no need to hurry. Feel free to get this test fixed any time
