### ISSUE TITLE
[CI Problem] Broken build `arm_nnfunctions.h: No such file or directory`

### ISSUE THREAD

**Issue by masahi** [apache/tvm#10029]
Seems all recent jobs are stuck with this problem. Not clear why it happened.

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9986/12/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10027/1/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10028/3/pipeline

**Comment by masahi** [comment]
The build is passing now, apparently it was a temporary issue. https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9986/13/pipeline

**Comment by junrushao1994** [comment]
Still seeing occurrence of this failure: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10030/1/pipeline. Probably flaky

**Comment by masahi** [comment]
Let's close this one since this is a dup of #10020 and they have more context.

**Comment by junrushao1994** [comment]
Sounds good!
