### ISSUE TITLE
[AOT] Explicitly support heterogeneous execution with AOT Executor

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10034]
Currently, `AOTExecutor` only supports heterogeneous execution by leveraging `tir.call_extern` via BYOC. In order to properly model a heterogeneous environment (in particular, to model multiple disjoint memories and leverage #8404), `AOTExecutor` needs to formally support invoking the [Device API](https://github.com/apache/tvm/blob/main/include/tvm/runtime/device_api.h). It's currently not possible to do this from TIR via the AOT run-function.

- [ ] Open a discuss forum post to debate how to properly model this in TIR, considering `VirtualDevice`
- [ ] Write up a formal RFC
- [ ] (yet TBD)

cc @Mousius @alanmacd @lhutton1

**Comment by driazati** [comment]
@areusch is this still planned?
