### ISSUE TITLE
[C source target] Remove reliance on `tir.disable_vectorize`

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10039]
Right now when using microTVM with the C codegen we must always pass:

```
tvm.transform.PassContext(
    opt_level=3,
    config={"tir.disable_vectorize": True},
)
```

There is no reason we shouldn't be able to auto-detect the C backend and not run vectorization in this case.

**Comment by Mousius** [comment]
> There is no reason we shouldn't be able to auto-detect the C backend and not run vectorization in this case.

Could we ask the `Target` to hold the overrides so we don't have to introduce lots of `if (target == 'c')` logic?
