### ISSUE TITLE
[microTVM] Document end-to-end workflow with Project API

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10035]
#9654 [documented](https://tvm.apache.org/docs/arch/microtvm_project_api.html) the Project API server plus utilities that could be used to implement instances of an API server. This issue tracks a related task: writing up the end-to-end microTVM flow, from model import to deployment to auto-tuning using a Project API server. Ideally this documentation should list examples using both `tvmc` and Python APIs.

**Comment by mehrdadh** [comment]
@areusch we can close this one since we have `tvmc micro` tutorial now:
https://tvm.apache.org/docs/how_to/work_with_microtvm/micro_tvmc.html#sphx-glr-how-to-work-with-microtvm-micro-tvmc-py
