### ISSUE TITLE
[Tracking Issue] Capturing dependent libraries of code-generated TIR

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10040]
See pre-RFC: https://discuss.tvm.apache.org/t/tvm-capturing-dependent-libraries-of-code-generated-tir-initially-for-use-in-model-library-format/11080

cc @Hzfengsy @junrushao

**Comment by driazati** [comment]
@areusch is this still planned?

**Comment by areusch** [comment]
i think this is preempting the RFC that hasn't been landed yet
