### ISSUE TITLE
[Tracking Issue] Export pre-codegen TIR in Model Library Format

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10041]
This issue tracks pre-RFC discussion: https://discuss.tvm.apache.org/t/why-c-unpacked-api-not-work-anymore/11845/11

cc @Hzfengsy @junrushao

**Comment by areusch** [comment]
cc @SebastianBoblestETAS

**Comment by driazati** [comment]
@areusch is this still planned?

**Comment by SebastianBoblest** [comment]
We use something similar internally but I think it is no longer planned to implement this in the public repo.

**Comment by driazati** [comment]
Cool we should close this then, if plans change we can reopen it
