### ISSUE TITLE
[microTVM] Support `tvmc tune` with micro targets

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10054]
`tvmc` commands are currently supported for all core micro workflows except AutoTVM. this issue tracks work to bring support for `tvmc tune` to microTVM.

cc @alanmacd @gromero @mehrdadh

**Comment by PhilippvK** [comment]
@areusch  I would like to ask a first questing regarding this issue:

Would it make more sense to introduce a new subcommand under the `tvmc micro` namespace (e.g. `tvmc micro tune`) to be consistent with the other commands to compile and deploy for MicroTVM or should the already existing `tvmc tune` be extended to support MicroTVM through the Project API?

The first approach would probably lead to a lot of duplicate functionality in the command line parser as most options would be the same as for non-MicroTVM tuning.

**Comment by PhilippvK** [comment]
@areusch Can you tell me if someone (i.e. at OctoML) is currently working on this. I am asking because I have a working prototype for this feature since several months.

**Comment by areusch** [comment]
hey @PhilippvK ah sorry for the bad categorization. i don't think anyone is actively working on this right now. if you want to upstream your prototype, that would be awesome! could you cc the following reviewers?

cc @alanmacd @leandron @mehrdadh
