### ISSUE TITLE
[Bug] tests/python/contrib/test_popen_pool.py::test_popen_pool_executor_async is flaky

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10103]
This test (from #8851) seems flaky by design, does it really matter which task finishes first in absolute time?

example failure on main:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2391/pipeline

older PR failures:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9802/11/
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9909/5/

cc @tqchen @vinx13 @shingjan

**Comment by shingjan** [comment]
the `timeout` parameter could be the source of flakiness.

**Comment by vinx13** [comment]
Which one finishing first doesn't really matter, it is merely to show that they are concurrent. I think it is fine to remove this test case. @shingjan would you like to send a PR?

**Comment by shingjan** [comment]
PR sent out here: https://github.com/apache/tvm/pull/10160 @vinx13 @driazati
