### ISSUE TITLE
[Tracking Issue] Upgrade Zephyr Vagrant box to Zephyr 2.7

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#10126]
### This issue is to track progress for updating the Zephyr boxes to 2.7 following the update in https://github.com/apache/tvm/pull/10117
- [ ] P1. Title of this piece of the feature (PR link if available)

**Comment by mehrdadh** [comment]
working on this: https://github.com/apache/tvm/pull/10138

**Comment by mehrdadh** [comment]
@Mousius we can close this now!

**Comment by Mousius** [comment]
Thanks @mehrdadh !
