### ISSUE TITLE
Add RVM build/testing to automated CI docker build

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10136]
There have been a few instances where we've discovered that the microTVM Reference VMs can't be rebuilt from the [Vagrantfile](https://github.com/apache/tvm/blob/main/apps/microtvm/reference-vm/zephyr/Vagrantfile)s. We should add a build to the set of nightly builds (akin to the CI image rebuild) so that we can understand when script problems cause them to be unreproducible.

cc @mehrdadh

**Comment by mehrdadh** [comment]
I can help with this. Feel free to assign it to me.
