### ISSUE TITLE
[Docs] Autogenerate Relay Reference Docs From "Describe" Attributes

### ISSUE THREAD

**Issue by AndrewZhaoLuo** [apache/tvm#10161]
Relay has many operators.

In this thread: https://discuss.tvm.apache.org/t/should-relay-nn-operators-be-documented-in-the-language-reference/12001/4

@u99127 points out most operators in relay are not really documented in `relay_op.rst`.

This issue is meant to track the task of autogenerating the list of relay ops in `relay_op.rst`. Technically all ops and their attributes can already be found in the op registry which can be programatically retrieved. An example is here:

https://github.com/AndrewZhaoLuo/TVM-Sandbox/blob/main/relay/example_list_all_ops.py

Criteria for completion:
`relay_op.rst` can be autogenerated with all current operators

**Comment by JOE1994** [comment]
I'd like to try working on this one if that's okay :cat:

**Comment by AndrewZhaoLuo** [comment]
It's yours @JOE1994  B)

**Comment by JOE1994** [comment]
I truly apologize for being irresponsible while having the ticket assigned to myself.
I'll unassign myself from this ticket.
