### ISSUE TITLE
[Tracking Issue] Document TVM RPC and add debug utilities

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10212]
This issue tracks work to add documentation for the TVM RPC protocol and create debugging tools to help people understand what RPC traffic is flowing across a link. Ideas:
- A Python or C++ library which processes RPC traffic and prints a human-readable representation
- A Wireshark filter which allows you to view traffic there

**Comment by areusch** [comment]
cc @kparzysz-quic @gromero @mehrdadh @jroesch @tqchen

**Comment by leandron** [comment]
It would be cool to standardise the RPC command lines under a potential `tvmc rpc ...` as well, so that we don't require users to memorise Python module paths to be used as command line entry points. Can this be added under this umbrella task?

**Comment by pfk-beta** [comment]
I'd move some documentation from github READMEs to official docs site, e.g. https://github.com/apache/tvm/blob/main/jvm/README.md , https://github.com/apache/tvm/blob/main/apps/android_rpc/README.md ,
