### ISSUE TITLE
[CI Problem] tests/python/contrib/test_cmsisnn/test_fully_connected.py::test_op_int8 is flaky

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10213]
Recent failures on main:
* https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2495/pipeline/
* https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2490/pipeline

Failures happened in the compile step on different parameterizations: `10-0.0128-0.11-RELU-True-12-in_shape1` and `10-0.0128-0.11-RELU-False-128-in_shape1`. I tried to get the logs from the Jenkins execution workspace (e.g. https://ci.tlcpack.ai/job/tvm/job/main/2490/execution/node/295/ws/) but couldn't find them there. #10214 changes the invocation so it will log to the console on failures which would help debug things like this.

cc @ashutosh-arm

**Comment by ashutosh-arm** [comment]
@Mousius @grant-arm for visibility.
