### ISSUE TITLE
[Bug] [MicroTVM] ProjectOption type hints are currently pointless.

### ISSUE THREAD

**Issue by PhilippvK** [apache/tvm#10270]
### Expected behavior

In the `microtvm_api_server.py` for various MicroTVM project API templates options are defined in the following way:

```
server.ProjectOption(
    "warning_as_error",
    optional=["generate_project"],
    type="bool",
    help="Treat warnings as errors and raise an Exception.",
),
```

As every of these options gets a certain `type` it may be assumed that these type hints are actually used by TVM and not only for documentation.

### Actual behavior

However the only purpose of the `type` field in this option is restricting the allowed value of these options passed as `--project-option ` command line arguments:

https://github.com/apache/tvm/blob/64e94abcbb9578bf2ace2e6e1e1e618bd09d2605/python/tvm/driver/tvmc/project.py#L74-L75

The following is a consequence of the described problem:

Using `--project-option warning_as_error=false` vs. `--project-option warning_as_error=true` on the TVMC command line (e.g. with `tvmc micro create project mlf.tar [zephyr|arduino]`) both results in warnings being turned into errors.

The reason behind this that the true/false targuments are still strings when beeing interpreted as a bool here: `options["warning_as_error"]`. However `bool("false")  == bool("true") == True`. Instead either `bool(distutils.util.strtobool(options["warning_as_error"]))` or a custom map similar to

https://github.com/apache/tvm/blob/64e94abcbb9578bf2ace2e6e1e1e618bd09d2605/python/tvm/driver/tvmc/pass_config.py#L80-L83

needs to be applied at some stage. (Implicitly during the command line parsing (https://github.com/apache/tvm/blob/main/python/tvm/driver/tvmc/project.py) or explicitly `microtvm_api_server.py`)

The missing type conversions would also affect every `ProjectOption` with `type="int"`, however currently those values (e.g. for `gdbserver_port`) are converted to a string anyway aka. it accedentially works as expected.

### Environment

TVM commit (`55849e651e3dff6cffeb7fd14aa89699e9575d10`) using `./docker/bash.sh tlcpack/ci-qemu:v0.10 for Zephyr and Arduino support`

### Steps to reproduce

- Build TVM as usual with MicroTVM support
- Download model and generate MLF:

  ```
  wget https://github.com/tensorflow/tflite-micro/raw/main/tensorflow/lite/micro/examples/magic_wand/magic_wand.tflite
  tvmc compile magic_wand.tflite \
      --target='c -keys=cpu -link-params=0 -model=host' \
      --runtime=crt \
      --runtime-crt-system-lib 1 \
      --executor='graph' \
      --executor-graph-link-params 0 \
      --output model.tar \
      --output-format mlf \
      --pass-config tir.disable_vectorize=1 \
      --disabled-pass=AlterOpLayout
  ```

- Apply a small patch to the Zephy version number to trigger a warning being printed:

  ```
  diff --git a/opt/zephyrproject/zephyr/VERSION.old b/opt/zephyrproject/zephyr/VERSION
  index 1e4d35466..a934c886c 100644
  --- a/opt/zephyrproject/zephyr/VERSION.old
  +++ b/opt/zephyrproject/zephyr/VERSION
  @@ -1,4 +1,4 @@
  -VERSION_MAJOR = 2
  +VERSION_MAJOR = 3
   VERSION_MINOR = 7
   PATCHLEVEL = 1
   VERSION_TWEAK = 0
  ```

- Relevant command:

  ```
  python -m tvm.driver.tvmc micro create -f project model.tar zephyr --project-option project_type=host_driven zephyr_board=qemu_x86
  python -m tvm.driver.tvmc micro create -f project model.tar zephyr --project-option project_type=host_driven zephyr_board=qemu_x86 --project-option warning_as_error=false
  python -m tvm.driver.tvmc micro create -f project model.tar zephyr --project-option project_type=host_driven zephyr_board=qemu_x86 --project-option warning_as_error=true
  ```

- Resulting output:

  ```
  WARNING:__main__:Zephyr version found is not supported: found 3.7, expected 2.7.
  Error: Option 'project_type' is required but was not specified. Use --list-options to see all required options.
  Error: Option 'project_type' is required but was not specified. Use --list-options to see all required options.
  ```

- Expected output:

  ```
  WARNING:__main__:Zephyr version found is not supported: found 3.7, expected 2.7.
  WARNING:__main__:Zephyr version found is not supported: found 3.7, expected 2.7.
  Error: Option 'project_type' is required but was not specified. Use --list-options to see all required options.
  ```

cc @alanmacd @gromero @mehrdadh

**Comment by gromero** [comment]
@PhilippvK Hi. Apologies for taking so long to reply your issue. Since there is no cc tagging me and I missed the notification from GH when the issue was created I just found it by chance now when eyeballing other TVM issues.

Thanks for the detailed investigation and for reporting the issue.

The errors in `Resulting output:` are actually not issues, i.e. your passing twice  the `--project-option` option and so only the last one specified is considered, so `tvmc` in the second and third commands is only considering  `warning_as_error={true,false}`, hence it complains about `project_type` missing. If you add `project_type=` at the end of the command, then it will complain about `zephyr_board=` missing -- the next required option that will be missing. Hence `tvmc` is working as designed there. 

That said, your code analysis is correct and there is a bug there that needs to get fixed.

So, I would say that the ` Resulting output:` currently (HEAD) is:

```
gromero@amd:~/scripts$ tvmc micro create -f /tmp/sine_mps3 ./sine_mps3.tar zephyr --project-option project_type=host_driven zephyr_board=mps3_an547 warning_as_error=false
The following error occured on the Project API server side: 
 calling method generate_project: JSON-RPC error # -32000: Zephyr version found is not supported: found 3.7, expected 2.7.
Traceback (most recent call last):
  File "/home/gromero/git/tvm/python/tvm/micro/project_api/server.py", line 481, in serve_one_request  # <--- Outermost server-side stack frame
    self._dispatch_request(request)
  File "/home/gromero/git/tvm/python/tvm/micro/project_api/server.py", line 593, in _dispatch_request
    return_value = dispatch_method(**params)
  File "/home/gromero/git/tvm/python/tvm/micro/project_api/server.py", line 621, in _dispatch_generate_project
    return self._handler.generate_project(
  File "/home/gromero/git/tvm/build/microtvm_template_projects/zephyr/microtvm_api_server.py", line 433, in generate_project
    raise server.ServerError(message=message)
tvm.micro.project_api.server.ServerError: JSON-RPC error # -32000: Zephyr version found is not supported: found 3.7, expected 2.7.

gromero@amd:~/scripts$
```

but the `Expected output:" is:

```
gromero@amd:~/scripts$ tvmc micro create -f /tmp/sine_mps3 ./sine_mps3.tar zephyr --project-option project_type=host_driven zephyr_board=mps3_an547 warning_as_error=false
WARNING:__main__:Zephyr version found is not supported: found 3.7, expected 2.7.
gromero@amd:~/scripts$
```

i.e. as you said the issue is that option `warning_as_error=false` is not working properly.

Since you've done all the analysis and also reported it, are you interested in sending a PR to fix it? I like the solution of using a simple dict map and I think such a map could be a global as `CMAKE_BOOL_MAP` and defined right above `class Handle()`, for instance so in the future other options can take advantage of it too. If so, I'm happy to review it, just cc me so I don't missing it please.

I'll also cc @leandron @mehrdadh @areusch @alanmacd fyi.

Cheers.

**Comment by PhilippvK** [comment]
@gromero My bad. Sorry for messing this up.

> Since you've done all the analysis and also reported it, are you interested in sending a PR to fix it? I like the solution of using a simple dict map and I think such a map could be a global as CMAKE_BOOL_MAP and defined right above class Handle(), for instance so in the future other options can take advantage of it too

I would be happy to create a PR for this. However I think that the main issue is not fully solved by your suggested solution as it would only resolve boolean options correctly while options of type `int` would still be accessed as string. So we should either actually make use of the type hints in `server.ProjectOption` to implicitly convert those options to the chosen type or alternatively mention somewhere, that the user has to parse/cast them manually.

What do you think about this?

Another short question: What do you mean with `class Handle()`?
