### ISSUE TITLE
[Flaky Test] microTVM demos timeout intermittently

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10312]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). As per [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures, these failures will be disabled in a PR that references this issue until the test owners can fix the source of the flakiness.

### Test(s)

- `tests/scripts/task_demo_microtvm.sh` (doesn't run under pytest)

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10305/1/pipeline/
- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2534/pipeline

cc @Mousius @mehrdadh

**Comment by driazati** [comment]
Also is it possible to wrap this test in pytest via Python's `subprocess`? If it is run outside pytest we don't track the test results in Jenkins' result page (i.e. so we can automatically list failures, test times, etc.)

**Comment by manupa-arm** [comment]
@driazati #10337 we discovered and fixed a bug that might be the cause.
I did ran it few times with this fix and did not experience it being flaky

I've re-enabled this test but lets observe for a bit

**Comment by mehrdadh** [comment]
@driazati It's been 21 days since https://github.com/apache/tvm/pull/10337 is merged. Can we close this issue?

**Comment by driazati** [comment]
sure, I haven't seen any timeouts lately so I'm fine calling this fixed
