### ISSUE TITLE
[CI Problem] Flaky test `test_task_scheduler_gradient`

### ISSUE THREAD

**Issue by masahi** [apache/tvm#10356]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10351/1/pipeline

I definitely saw that multiple times recently.

**Comment by zxybazh** [comment]
I think it's a floating point issue because the 1st gradient is too close to 0 and the autoscheduler would randomly pick a task in that case. Changing the `objective_func` to `1e5 * costs[0]` can fix the test I think.
