### ISSUE TITLE
[Bug][AutoScheduler] `name_it != name_to_arg.end()` check failed with `layout_free_placeholders`

### ISSUE THREAD

**Issue by LyricZhao** [apache/tvm#10369]
Hi, I'm trying to optimize 1x1 convolution with TVM Ansor, with `layout_free_placeholders` attributes for weights, the scheduler dumps an assertion error `Check failed: (name_it != name_to_arg.end()) is false`.

The code is as following:
```python
import tvm
from tvm import auto_scheduler, te


# [1x1 Convolution]
@auto_scheduler.register_workload
def buggy_conv(n: int, ic: int, oc: int, h: int, w: int):
    X = te.placeholder((n, ic, h, w))
    W = te.placeholder((oc, ic))
    assert len(X.shape) >= 2
    assert len(W.shape) == 2
    r = te.reduce_axis((0, X.shape[1]), name=f'r')
    Z = te.compute(
        (n, oc, h, w),
        # Not working
        lambda *i: te.sum(
            X[i[0], r, i[2], i[3]] * W[i[1], r],
            axis=[r]
        ),
        # Below works
        # lambda i, j, k, l: te.sum(
        #     X[i, r, k, l] * W[j, r],
        #     axis=[r]
        # ),
        attrs={'layout_free_placeholders': [W]},  # Remove this line also works
        name=f'conv_out'
    )
    return [X, W, Z]


if __name__ == '__main__':
    target = tvm.target.Target(target='llvm', host='llvm')
    task = auto_scheduler.SearchTask(func=buggy_conv, args=(32, 64, 128, 32, 32), target=target)
    tune_options = auto_scheduler.TuningOptions(
        num_measure_trials=256,
        num_measures_per_round=64,
        verbose=2,
    )
    task.tune(tune_options)
```

What's more strange, change lambda parameters from `*i` to `i, j, k, l` also works.

**Comment by LyricZhao** [comment]
I'm using commit id `cb7f773218c26c3092cc275ef28e71839ebd18e3` or TVM 0.8 release tag (both have this problem).

The logging information is in [https://pastebin.ubuntu.com/p/QWsqqjnXTz/](https://pastebin.ubuntu.com/p/QWsqqjnXTz), and we can see that every schedule fails to be measured with an error of `name_it != name_to_arg.end()`.

Thanks for your reply!

**Comment by happyme531** [comment]
Got the same error with latest TVM build.  
https://discuss.tvm.apache.org/t/most-tasks-failed-with-autoscheduler-on-mali-g610-gpu/

**Comment by happyme531** [comment]
```cpp
/*!
 * \brief Parse shape and axis names from layout string
 */
inline void ParseKernelLayout(const String& layout, Array<PrimExpr>* shape,
                              std::vector<std::string>* axes) {
  int32_t factor = 0;
  std::string axis = "";
  for (char c : std::string(layout)) {
    if (c >= 'A' && c <= 'z') {
      axis += c;
      if (factor != 0) {
        shape->push_back(factor);
        factor = 0;
      }
    } else if (c >= '0' && c <= '9') {
      factor = factor * 10 + c - '0';
      if (!axis.empty()) {
        axes->push_back(axis);
        axis = "";
      }
    } else {
      LOG(FATAL) << "Invalid layout " << layout;
    }
  }
  if (!axis.empty()) {
    axes->push_back(axis);
  }
  std::cout << "layout " << layout << "\n";
  std::cout << "axes:";
  for (auto x : *axes) {
    std::cout << x << " ";
  }
  std::cout << std::endl;
}
```

```log
layout 768i1256k
axes:i k 
layout 2i11i11i11i11i11i12k16k128i18k3i1
axes:i i i i i i k k i k i 
layout 2i11i11i11i11i11i12k16k128i18k3i1
axes:i i i i i i k k i k i 
```
It looks like the naming convention for axes is messed up somewhere, seems for my case an axis is named "i1" and totally broken with `ParseKernelLayout`.

**Comment by happyme531** [comment]
> ```c++
> /*!
>  * \brief Parse shape and axis names from layout string
>  */
> inline void ParseKernelLayout(const String& layout, Array<PrimExpr>* shape,
>                               std::vector<std::string>* axes) {
>   int32_t factor = 0;
>   std::string axis = "";
>   for (char c : std::string(layout)) {
>     if (c >= 'A' && c <= 'z') {
>       axis += c;
>       if (factor != 0) {
>         shape->push_back(factor);
>         factor = 0;
>       }
>     } else if (c >= '0' && c <= '9') {
>       factor = factor * 10 + c - '0';
>       if (!axis.empty()) {
>         axes->push_back(axis);
>         axis = "";
>       }
>     } else {
>       LOG(FATAL) << "Invalid layout " << layout;
>     }
>   }
>   if (!axis.empty()) {
>     axes->push_back(axis);
>   }
>   std::cout << "layout " << layout << "\n";
>   std::cout << "axes:";
>   for (auto x : *axes) {
>     std::cout << x << " ";
>   }
>   std::cout << std::endl;
> }
> ```
> 
> ```
> layout 768i1256k
> axes:i k 
> layout 2i11i11i11i11i11i12k16k128i18k3i1
> axes:i i i i i i k k i k i 
> layout 2i11i11i11i11i11i12k16k128i18k3i1
> axes:i i i i i i k k i k i 
> ```
> 
> It looks like the naming convention for axes is messed up somewhere, seems for my case an axis is named "i1" and totally broken with `ParseKernelLayout`.

This explains why changing parameters from i[0],i[1] to i, j, k, l works.
