### ISSUE TITLE
[Bug] [VTA] [TSIM] cannot run tsim-example in the current TVM version 0.9

### ISSUE THREAD

**Issue by vzyknc** [apache/tvm#10384]
I recently tried to reproduce TSIM test framework, and I found that when libhw.so and libsw.so were loaded, there would be an error that the global FFI PackedFunc could not be found. Does anyone know what's going on? After I tried to fall back to version 0.6, the problem disappeared. Is this because of some changes in the design of the runtime? How can I fix this bug?

TVM v0.9 Ubuntu1804 gcc-8.4 cmake 2.22 verilator 4.022 chisel3 scala 2.11

**Comment by xiongdl** [comment]
Hi,
I meet the similar error when running VTA test with tsim target.

python vta/tests/python/integration/test_benchmark_topi_conv2d.py
python: symbol lookup error: $VTA_HW_PATH/build/libvta_hw.so: undefined symbol: VTAMemDPI

 Do you fix the bug?

**Comment by driazati** [comment]
Can you check if this error still occurs on `main`? Closing this issue in case it's fixed, but if not please re-open and if necessary share some more details about how we can reproduce the error

**Comment by jmluu** [comment]
> Hi, I meet the similar error when running VTA test with tsim target.
> 
> python vta/tests/python/integration/test_benchmark_topi_conv2d.py python: symbol lookup error: $VTA_HW_PATH/build/libvta_hw.so: undefined symbol: VTAMemDPI
> 
> Do you fix the bug?

Same error.  Did you solve the problem ?
