### ISSUE TITLE
[Bug] relay.create_executor("debug" to run conv2d_transpose failed

### ISSUE THREAD

**Issue by zhangwm-pt** [apache/tvm#10422]
I use `pytest test_op_level2.py::test_conv2d_transpose_nchw_run` to run tests/python/relay/test_op_level2.py.
Default `relay.create_executor("graph"` is OK, but if I modify it to be `relay.create_executor("debug"` ,test failed.

### Expected behavior

test pass, same with graph

### Actual behavior

> test_op_level2.py:880:
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> ../../../python/tvm/relay/backend/interpreter.py:247: in _apply_args
>     return func(relay_args)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <tvm.runtime.packed_func.PackedFunc object at 0x7f204bdc5f78>
> args = ([Constant([[[[5.22145569e-01 4.33856517e-01 5.83649397e-01 8.09219182e-02
>     7.39040315e-01 9.55327690e-01 8.0291241... [[0.39237568 0.9553286  0.69658566]
>    [0.00525846 0.1238898  0.40223128]
>    [0.2080836  0.15559652 0.6325646 ]]]])],)
> temp_args = [[Constant([[[[5.22145569e-01 4.33856517e-01 5.83649397e-01 8.09219182e-02
>     7.39040315e-01 9.55327690e-01 8.0291241...  [[0.39237568 0.9553286  0.69658566]
>    [0.00525846 0.1238898  0.40223128]
>    [0.2080836  0.15559652 0.6325646 ]]]])]]
> values = <tvm._ffi._ctypes.packed_func.TVMValue_Array_1 object at 0x7f204bdd3e18>
> tcodes = <tvm._ffi._ctypes.packed_func.c_int_Array_1 object at 0x7f204bdd3510>
> 

> E           TVMError:
> E           ---------------------------------------------------------------
> E           An error occurred during the execution of TVM.
> E           For more information, please see: https://tvm.apache.org/docs/errors.html
> E           ---------------------------------------------------------------
> E
> E             Check failed: ret == 0 (-1 vs. 0) : Assert fail: (3 == int32(arg2.shape[1])), Argument arg2.shape[1] has an unsatisfied constraint: (3 == int32(arg2.shape[1]))
> 
> ../../../python/tvm/_ffi/_ctypes/packed_func.py:237: TVMError

### Environment

ubuntu 18.04

### Steps to reproduce

`mkdir build; cd build; cmake ..;make`
`pytest test_op_level2.py::test_conv2d_transpose_nchw_run`

**Comment by masahi** [comment]
I think the `debug` one is not meant to be a fully featured executor.
