### ISSUE TITLE
[VOTE] Replace codeowners with more relevant automation

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10471]
Hi all,

This is a formal vote thread to determine committer and PMC support for [[RFC] Replace codeowners with more relevant automation](https://github.com/apache/tvm-rfcs/pull/58). Replying +1 here means you support the RFC and we should merge it. This vote thread is due to the fact that the RFC proposes a change in the way the community operates (namely the way code-review works). This also signals the final comment period on that RFC, which will conclude with this vote.

We'll leave this vote thread open for a week, and make a decision then.

Thanks,
Andrew 

Please vote:
+1 I support the RFC
0 I'm happy either way
-1 I do not support the RFC and it should not be merged.

@apache/tvm-committers

**Comment by mbrookhart** [comment]
+1

**Comment by masahi** [comment]
+1

**Comment by junrushao1994** [comment]
+1

**Comment by tmoreau89** [comment]
+1

**Comment by shingjan** [comment]
+1

**Comment by hogepodge** [comment]
enthusiastic +1

**Comment by mehrdadh** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by kparzysz-quic** [comment]
I'm not particularly unhappy with the current situation, but it could be improved.
+1

**Comment by jcf94** [comment]
+1

**Comment by comaniac** [comment]
+1

**Comment by AndrewZhaoLuo** [comment]
+1

**Comment by Lunderberg** [comment]
+1

**Comment by manupa-arm** [comment]
+1

**Comment by Hzfengsy** [comment]
+1

**Comment by areusch** [comment]
Hi all,

The vote result is +16:
+1: 16 votes (5 binding)
0: no votes
-1: no votes

Therefore the resolution is accepted and the RFC will be merged.

Thanks!
Andrew
