### ISSUE TITLE
[Flaky Test] ethosu `test_networks_without_usmp` and `test_mean`

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10487]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). As per [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures, these failures will be disabled in a PR that references this issue until the test owners can fix the source of the flakiness.

### Test(s)

- `tests/python/contrib/test_ethosu/test_networks.py::test_networks_without_usmp[ethos-u55-256-model_url3-2185584-5] `
- `tests/python/contrib/test_ethosu/test_codegen.py::test_mean[ifm_shape6-axis6-True-False-ethos-u55-256]`
- `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_clz`

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2671/pipeline
- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2670/pipeline
- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2660/pipeline

cc @lhutton1 @grant-arm

**Comment by manupa-arm** [comment]
@driazati would it be possible to disable only the failing tests ? (See https://docs.pytest.org/en/latest/how-to/skipping.html#skip-xfail-with-parametrize)

**Comment by manupa-arm** [comment]
@driazati what is the reasoning to bundling these varying failures to single issue ? 

I cant see a commonality between the tests bundled here.

**Comment by driazati** [comment]
> @driazati would it be possible to disable only the failing tests ? (See https://docs.pytest.org/en/latest/how-to/skipping.html#skip-xfail-with-parametrize)

Sure we can do that moving forward, but if a test fails on more than 1 parameterized version I think we should still stick with disabling the whole test to reduce the chance of further flaky failures.



> @driazati what is the reasoning to bundling these varying failures to single issue ?
> 
> I cant see a commonality between the failures bundled here.

No particular reason other than the tests are in a similar category, but we can be more granular with reporting in the future (so 1-issue-per-test pretty much, unless errors are the same)

**Comment by manupa-arm** [comment]
@driazati,

> Sure we can do that moving forward, but if a test fails on more than 1 parameterized version I think we should still stick with disabling the whole test to reduce the chance of further flaky failures.

I dont have a strong view eitherway, dependy on the policy going forward, we might restructure the tests.

> No particular reason other than the tests are in a similar category, but we can be more granular with reporting in the future (so 1-issue-per-test pretty much, unless errors are the same)

I think its better to report errors that are similiar because the work done to correct these are orthogonal.

> https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2671/pipeline/

This one seems like corrupt download. TVM has a lot of tests that downloads models for tests and they can fail due to external reasons (i.e. network, CI node limitations). Either we need to decide against using such tests (i.e. holding binary models in-tree) or be a bit lenient on network failures (accepting that they happen once in a while), because I dont see a way to resolve this issue.

**Comment by manupa-arm** [comment]
https://github.com/apache/tvm/pull/10565/ -- Im re-enabling this for now.

**Comment by driazati** [comment]
We definitely should audit network usage in CI and try to consolidate on more stable platforms (e.g. move any resources into S3 or something). i'm a little hesitant to re-enable these tests though without a little bit of mitigation (probably a network retry on a failed download is best in this case). But I agree in general some issues aren't solvable and we need to accept some level of flakiness, but it's currently too high. Also note that the tests still run with `xfail` so you can inspect recent run logs for results but failures aren't reported.
