### ISSUE TITLE
[Bug] NotImplementedError ['aten::__lshift__', 'aten::__rshift__', 'aten::__ior__', `aten::fmod`, `aten::remainder`]

### ISSUE THREAD

**Issue by interesaaat** [apache/tvm#10499]
Hi,

I am running a pytorch model and I am getting this error.

File "/home/hummingbird/tvm/python/tvm/relay/frontend/pytorch.py", line 3991, in from_pytorch
    converter.report_missing_conversion(op_names)
  File "/home/hummingbird/tvm/python/tvm/relay/frontend/pytorch.py", line 3197, in report_missing_conversion
    raise NotImplementedError(msg)
NotImplementedError: The following operators are not implemented: ['aten::__lshift__', 'aten::__rshift__', 'aten::unique_consecutive', 'aten::__ior__']

My versions are:
torch: 1.10.0
tvm: 0.9.dev708+g17652d341

@masahi 

Thanks!

**Comment by masahi** [comment]
@interesaaat Can we remove `aten::unique_consecutive` from the list now? Other ops seem trivial.

**Comment by interesaaat** [comment]
Yes let's remove unique_consecutive. I will open another issue if it will
be really needed.
