### ISSUE TITLE
[Flakey] tests/python/frontend/pytorch/test_forward.py::test_forward_roi_align

### ISSUE THREAD

**Issue by tkonolige** [apache/tvm#10554]
tests/python/frontend/pytorch/test_forward.py::test_forward_roi_align appears to be flakey: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10550/1/pipeline.

@areusch @driazati

**Comment by driazati** [comment]
cc @masahi any ideas why the numerics wouldnt be stable across tests / if we can just increase the tolerance a bit on this test?

**Comment by masahi** [comment]
hmm, I don't recall flaky-ness from this test. As long as we use the random input, there is always non-zero prob of failing, I'd say.

**Comment by driazati** [comment]
closing since we haven't seen this failure lately
