### ISSUE TITLE
[Bug] [AOT] Ordering of the function in generated C code is variable

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#10568]
Every time you build a relay module using AOT codegen, the order in C file changes. This is specially  important for microTVM because it makes debugging difficult since debug pointers change per execution.

cc @areusch

**Comment by sezgin1947** [comment]
I am suffering from the same problem.

**Comment by mehrdadh** [comment]
https://github.com/apache/tvm/pull/10590 fixed this
