### ISSUE TITLE
[Flaky Test] `tests/python/relay/test_prng.py::test_threefry_split`

### ISSUE THREAD

**Issue by zxybazh** [apache/tvm#10572]
### Test(s)

- `tests/python/relay/test_prng.py::test_threefry_split[llvm]`
- `tests/python/relay/test_prng.py::test_threefry_sequential_generate[llvm]`
- `tests/python/relay/test_prng.py::test_threefry_sequential_generate_remaining[llvm]`
- `tests/python/relay/test_prng.py::test_threefry_generate_out_size`

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10534/2/pipeline/

My change in #10534 was irrelavant to the tests.
These flaky tests failed at the same time on `CPU`, `GPU` and `i386` integration tests. And after I update the PR removing two lines of output, the tests *magically* passed.

**Comment by driazati** [comment]
Thanks for reporting! These failures also happened on main (e.g. https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2702) but should be fixed now if you rebase after #10535

**Comment by zxybazh** [comment]
Thanks for the update, I'll close the issue given a fix has been applied.
