### ISSUE TITLE
[Flaky Test] `tests/python/frontend/paddlepaddle/test_forward.py::test_forward_gather`

### ISSUE THREAD

**Issue by zxybazh** [apache/tvm#10570]
### Test(s)

- `tests/python/frontend/paddlepaddle/test_forward.py::test_forward_gather`

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10534/3/

In PR #10534 I did not touch anything beyond relay lowering and re-triggering CI could pass the test.

**Comment by driazati** [comment]
we haven't seen this failure lately and the test is not skipped so closing this issue
