### ISSUE TITLE
[Flaky Test] `tests/python/unittest/test_auto_scheduler_task_scheduler.py::test_task_scheduler_gradient`

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10583]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). As per [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures, these failures will be disabled in a PR that references this issue until the test owners can fix the source of the flakiness.

### Test(s)

- `tests/python/unittest/test_auto_scheduler_task_scheduler.py::test_task_scheduler_gradient `

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2733/pipeline#step-494-log-1221

This was also reported in #10356 and supposed to be fixed by #10360 but looks like it needs some more work

cc @masahi @zxybazh

**Comment by zxybazh** [comment]
Hi, thanks for the update. I'll take another look to see the cause of error.

**Comment by driazati** [comment]
skip has been removed, closing
