### ISSUE TITLE
[Bug] [OpenCL] module.benchmark stuck on some platforms

### ISSUE THREAD

**Issue by JishinMaster** [apache/tvm#10594]
Dear All,

Thanks again for the great work on the project.

I have been using TVM for a while, and recently encountered a strange behavior on the latest version on new HW/SW environment.
All of my machines are using Ubuntu 20.04 with the 5.13 kernel, with python 3.8.10.

I have a laptop with an Ivy Bridge CPU and Kepler GPU (GT650m), with the r418 driver.
I have a desktop with a skylake CPU and a RTX2080, with the r510 driver.

On the older platform, everything tunes and works fine, either CPU, GPU with CUDA, GPU with OpenCL.
On the newer one, CPU and CUDA works fine, but as soon as I use OpenCL, either from my own code (which uses module.module.time_evaluator) or the tune_relay_mobile_gpu.py sample (in which I remove the "-device=mali"), it tunes fine, but gets stuck on module.benchmark.
I have encountered the same problem on another recent laptop with an Intel Xe GPU (and no Nvidia GPU or software stack installed).
I have tried both with a clean virtualenv (hence latest xgboost, tensorflow, numpy, etc), and with the same one as my old laptop.

Have you encountered this behavior?

**Comment by masahi** [comment]
I've run opencl models on tigerlake and had no issue. This is more appropriate to discuss in https://discuss.tvm.apache.org/

If you have a repro script, I can quickly run it on my tigerlake.
