### ISSUE TITLE
[Flaky Test][Ethosu] Possible flaky test: tests/python/contrib/test_ethosu/test_codegen.py -k test_tflite_fully_connected

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#10606]
This test failed on my PR: `test_tflite_fully_connected[RELU-False-32-ifm_shape1-ethos-u55-128`

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10590/2/pipeline

cc @dchauhan-arm

**Comment by lhutton1** [comment]
Thanks for reporting this @mehrdadh, in #10640 we added a seed to all the codegen tests which should fix the issue with this test

**Comment by u99127** [comment]
I'd suggest closing this as fixed and reopen if we see this again ?
