### ISSUE TITLE
[Bug] TVM avg_poolnd gives different output with PyTorch when both ceil_mode and count_include_pad are True

### ISSUE THREAD

**Issue by JoeyTPChou** [apache/tvm#10614]
The issue is being discussed in this [thread](https://discuss.tvm.apache.org/t/relay-op-nn-avgpool2d-in-pytorch-gives-different-results-than-tvm/12272)  and was created to track down the issue easily. To avoid duplicating content, please refer to the discussion thread for more detail.

**Comment by leeexyz** [comment]
Hi @JoeyTPChou, I cannot reproduce the issue you encountered by using the referred [case](https://discuss.tvm.apache.org/t/relay-op-nn-avgpool2d-in-pytorch-gives-different-results-than-tvm/12272?u=leeexyz) in the latest [main](https://github.com/apache/tvm/tree/ae285c6f08ff8e01dd8abf875d33cb365dfb1111). May I know the commit id that you use?

**Comment by petuca** [comment]
Same story here. I can't reproduce the issue on my latest commit. I got the same shapes and results for predictions and output.  Is this issue solved? 
@leeexyz @JoeyTPChou @masahi

**Comment by nenadnikolicsimaai** [comment]
A bit late, but I can confirm that [script](https://discuss.tvm.apache.org/t/relay-op-nn-avgpool2d-in-pytorch-gives-different-results-than-tvm/12272?u=leeexyz) discussed in the thread runs correctly now
