### ISSUE TITLE
[Bug][ONNX] MatMul in dense_alter_op

### ISSUE THREAD

**Issue by ganler** [apache/tvm#10651]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

Here's a simple `MatMul` operation where:
- data tensor: [3]
- weight tensor's shape: [3, 1]

```python
import torch

class Net(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.weight = torch.nn.Parameter(torch.randn(3, 1))

    def forward(self, x):
        return torch.matmul(x, self.weight)

net = Net().eval()

i = torch.zeros((3), dtype=torch.float)
o = net(i)
print(i.shape, o.shape)

with torch.no_grad():
    torch.onnx.export(net, (i), "output.onnx", verbose=True, opset_version=14)
```

### Expected behavior

Should be compiled by TVM, as it follows correct ONNX specification and can be executed by PyTorch and ONNXRuntime.

### Actual behavior

```
...
File "/home/ganler/Documents/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 81, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/ganler/Documents/tvm/python/tvm/relay/op/nn/_nn.py", line 112, in alter_op_layout_dense
    return topi.nn.dense_alter_layout(attrs, inputs, tinfos, out_type)
  File "/home/ganler/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ganler/Documents/tvm/python/tvm/target/generic_func.py", line 286, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "/home/ganler/Documents/tvm/python/tvm/topi/x86/dense_alter_op.py", line 48, in _alter_dense_layout
    M, K = get_const_tuple(data_tensor.shape)
ValueError: not enough values to unpack (expected 2, got 1)
```

This is simply because in 

https://github.com/apache/tvm/blob/894772975ab33443cf25f40d9f1e2f7b96224978/python/tvm/topi/x86/dense_alter_op.py#L48

This optimization assumes data tensor's rank is 2. Maybe we simply need to add `unsqueeze()` to data tensor when converting such ONNX models.

### Environment

678e76b3efd57b171940f0017bee89451e381785 TVM with LLVM.

cc: @masahi @junrushao1994 @kevinthesun

**Comment by masahi** [comment]
What happens if you use the PT frontend?

**Comment by masahi** [comment]
I think relay `dense` op type rel should reject such input shapes, I wonder why it doesn't...

**Comment by ganler** [comment]
> I think relay `dense` op type rel should reject such input shapes, I wonder why it doesn't...

It seems it tries to convert this MatMul operation into a dense operation...

**Comment by ganler** [comment]
> What happens if you use the PT frontend?

It seems that cannot work as well

```python
import torch

class Net(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.weight = torch.nn.Parameter(torch.randn(3, 1))

    def forward(self, x):
        return torch.matmul(x, self.weight)


net = Net().eval()

import tvm
from tvm import relay
from tvm.relay.frontend import from_pytorch

scripted_model = torch.jit.trace(net, i).eval()
mod = from_pytorch(scripted_model, [("x", (3,))])

with tvm.transform.PassContext(opt_level=4):
    relay.build_module.create_executor("graph", mod, tvm.cpu(), target='llvm').evaluate()
```

log

```
  File "test.py", line 87, in <module>
    relay.build_module.create_executor("graph", mod, tvm.cpu(), target='llvm').evaluate()
  File "/home/ganler/Documents/tvm/python/tvm/relay/backend/interpreter.py", line 171, in evaluate
    return self._make_executor()
  File "/home/ganler/Documents/tvm/python/tvm/relay/build_module.py", line 618, in _make_executor
    self.mod = InferType()(self.mod)
  File "/home/ganler/Documents/tvm/python/tvm/ir/transform.py", line 161, in __call__
    return _ffi_transform_api.RunPass(self, mod)
  File "/home/ganler/Documents/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  2: TVMFuncCall
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::$_6>(tvm::transform::$_6, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::runtime::TVMMovableArgValueWithContext_::operator tvm::IRModule<tvm::IRModule>() const
  4: TVMFuncCall
  3: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::IRModule (tvm::transform::Pass, tvm::IRModule)>::AssignTypedLambda<tvm::transform::$_6>(tvm::transform::$_6, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  2: tvm::runtime::TVMMovableArgValueWithContext_::operator tvm::IRModule<tvm::IRModule>() const
  1: tvm::runtime::TVMMovableArgValue_::operator tvm::IRModule<tvm::IRModule, void>() const
  0: tvm::IRModule tvm::runtime::TVMPODValue_::AsObjectRef<tvm::IRModule>() const
  File "/home/ganler/Documents/tvm/include/tvm/runtime/packed_func.h", line 777
TVMError: In function transform.RunPass(0: transform.Pass, 1: IRModule) -> IRModule: error while converting argument 1: [02:31:28] /home/ganler/Documents/tvm/include/tvm/runtime/packed_func.h:1863: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (!checked_type.defined()) is false: Expected IRModule, but got Array
```

**Comment by masahi** [comment]
Yeah with this code I get the same error as onnx:

```
import torch

class Net(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.weight = torch.nn.Parameter(torch.randn(3, 1))

    def forward(self, x):
        return torch.matmul(x, self.weight)


net = Net().eval()

import tvm
from tvm import relay
from tvm.relay.frontend import from_pytorch

scripted_model = torch.jit.trace(net, torch.randn((3,))).eval()
mod, params = from_pytorch(scripted_model, [("x", (3,))])

with tvm.transform.PassContext(opt_level=4):
    relay.build_module.create_executor("graph", mod, tvm.cpu(), target='llvm').evaluate()
```

```
  File "/home/masa/projects/dev/tvm/python/tvm/topi/x86/dense_alter_op.py", line 48, in _alter_dense_layout
    M, K = get_const_tuple(data_tensor.shape)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by petuca** [comment]
I successfully managed to reproduce the issue just like you.
I tried to use your ideas for solving this problem. First I tried to put the unsqueeze() in code in dense_alter_op.py file before the breaking part. Nothing happened and the problem is the same just like in the beginning (also tried the squeeze() for inversly solving). 
The variable 'tinfos' has the two tensor arrays of dimensions [3, ] and [1,3]. Debugging step by step concluded that variable 'tinfos' doesn't assign any value to the destination variables. Tried to separate arrays and assign them with multiple approaches without success. Also attempt to transform the arrays without success.
I have the same approach to the different models (ONNX and PyTorch) and the both of two models have the same results. I think that the problem is much deeper then simple problem of unsqueezing in dense_alter_op.py file. 

Do you have some ideas how to solve this in another way?

CC: @masahi @ganler

**Comment by ganler** [comment]
@petuca I am pretty sure https://github.com/apache/tvm/pull/11174 can fix it for ONNX.

**Comment by ganler** [comment]
This was originally a fuzz bug but still excited to see fuzz bugs can be real-world cases.

**Comment by petuca** [comment]
This problem is solved only for ONNX models, but still not working for PyTorch and we closed the issue. Should we open new issue for PyTorch or wait for some PyTorch upgrades?

@masahi @ganler

**Comment by masahi** [comment]
@petuca This was originally for ONNX specifically, so I think it's reasonable to close it. It would be great if you can send a PR to PyTorch frontend with the same fix as ONNX.

**Comment by ganler** [comment]
@masahi @petuca I will send a PR soon since I think the fix could be similiar.

**Comment by petuca** [comment]
I think that's a good solution. #11347 
I came up with the same idea. Hope that PR would be accepted.
@ganler
