### ISSUE TITLE
[ci] Add ability to skip parameters on specific tests

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10667]
This is possible via vanilla pytest with: https://docs.pytest.org/en/latest/how-to/skipping.html#skip-xfail-with-parametrize, but that doesn't work directly for TVM since parameters are often shared (e.g. https://github.com/apache/tvm/blob/main/tests/python/relay/test_op_level10.py#L625)

cc @Mousius @areusch @gigiblender

**Comment by areusch** [comment]
cc @Lunderberg

**Comment by Lunderberg** [comment]
Hmm.  I've often added `pytest.xfail` inside the test itself, but I agree that it would be nice to have that as part of the test definition rather than the test body.

**Comment by driazati** [comment]
https://github.com/apache/tvm/blob/main/python/tvm/testing/utils.py#L1809-L1841 actually does this pretty much so we can close this issue (skips in the body based on the whole name of the test including the parameter values)

**Comment by Lunderberg** [comment]
Ooh, I like it.  That's definitely a cleaner way that I had been thinking.
