### ISSUE TITLE
[ci] Use mold or lld when available

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10679]
`mold` and `lld` can be a much faster alternative to `ld` from gcc. We should modify our CMakeLists.txt to detect and use these when possible. cc @yelite @driazati 

cc @driazati

**Comment by gromero** [comment]
wow yeah, thought about it some days ago, about using `mold`. That would great to experiment `mold` on TVM!

**Comment by junrushao1994** [comment]
@areusch @driazati This issue is closed automatically upon merge of #10683
