### ISSUE TITLE
[Bug] `test_vitis_ai_codegen.py` frontend tests run even when `USE_VITIS_AI OFF`

### ISSUE THREAD

**Issue by leandron** [apache/tvm#10757]
The series of tests under `tests/python/contrib/test_vitis_ai/test_vitis_ai_codegen.py` are set to run conditional to the presence of `pyxir` module in the namespace, which is true for many of our CI containers including `ci_cpu`.

However, in case we have TVM built with `USE_VITIS_AI OFF` and try to run the same tests, it will fail with:
```
E           AttributeError: Invalid config option 'relay.ext.vitis_ai.options.target' candidates are: relay.ext.verilator.options 
,relay.ext.cmsisnn.options ,tir.usmp.enable ,tir.usmp.algorithm ,relay.ext.ethos-u.options ,tir.detect_global_barrier 
,relay.FuseOps.max_depth ,tir.HoistIfThenElse ,relay.fallback_device_type ,tir.LoopPartition ,tir.InjectDoubleBuffer 
,relay.backend.use_meta_schedule ,relay.backend.use_auto_scheduler ,tir.UnrollLoop ,tir.noalias ,tir.instrument_bound_checkers 
,tir.disable_vectorize ,tir.disable_cse_tir ,tir.is_entry_func ,relay.ext.ethos-n.options ,relay.FuseOps.link_params ,tir.disable_assert 
,tir.disable_storage_rewrite ,tir.add_lower_pass ,tir.debug_keep_trivial_loop
```

The error is expected once TVM was built with `USE_VITIS_AI OFF`, but I guess the test module could be improved and skipped properly to cover this situation.

I'm facing this issue when trying to progress while we wait for https://github.com/apache/tvm/issues/10696 to be fixed.

cc @jtuyls @anilmartha

**Comment by lhutton1** [comment]
Just as a suggestion, I believe ACL uses similar logic to check if TVM was built with the expected configuration to run the tests. The skip functionality in the tests is implemented here: https://github.com/apache/tvm/blob/main/tests/python/contrib/test_arm_compute_lib/infrastructure.py#L159

**Comment by lhutton1** [comment]
Ah apologies I see there is already something similar: https://github.com/apache/tvm/blob/main/tests/python/contrib/test_vitis_ai/infrastructure.py#L60

**Comment by leandron** [comment]
With #10802 merged, we can close this now.
