### ISSUE TITLE
Add version selector to docs.tvm.ai

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10754]
Many docs sites allow users to select the version of the project for which docs are shown. We don't currently support this on our docs site, and it's becoming more confusing now that we're pushing docs immediately after merge. It would be great to implement something similar to Read The Docs style selector here.

**Comment by junrushao1994** [comment]
i love this feature too!! PyTorch and TensorFlow both provide similar functionalities and it's super helpful to look up historic API documentation specifically when APIs of some sub-system is in flex
