### ISSUE TITLE
[Flaky Test] `tests/python/contrib/test_ethosu/test_lut_optimizer.py::test_lut_optimizer_runs_in_compilation_pipeline`

### ISSUE THREAD

**Issue by driazati** [apache/tvm#10777]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). As per [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures), these failures will be disabled in a PR that references this issue until the test owners can fix the source of the flakiness.

### Test(s)

- `tests/python/contrib/test_ethosu/test_lut_optimizer.py::test_lut_optimizer_runs_in_compilation_pipeline` - failed with a segfault

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/2854/pipeline

cc @lhutton1

**Comment by lhutton1** [comment]
Thanks for reporting @driazati, cc @ekalda @manupa-arm for visibility

**Comment by manupa-arm** [comment]
Ah it seems like a xdist worker crashed again

**Comment by lhutton1** [comment]
closing this as the test has been running upstream for a while with no new reports of failure
