### ISSUE TITLE
[Bug] unable to retrive function from static lib via system lib

### ISSUE THREAD

**Issue by jinfagang** [apache/tvm#10840]
Normally, from docs it says, the static lib can be get function out using this:

```
tvm::runtime::Module mod_tvmlib =
      (*tvm::runtime::Registry::Get("runtime.SystemLib"))();
```

But I can not get the function I need from static lib.

```
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (this->func_fc1 != nullptr) is false: 
Stack trace:

```

I have generated the static lib, with target:

```
llvm --system-lib
```

Anyone knows why?

BTW, does the python API outs now?

![image](https://user-images.githubusercontent.com/21303438/160972374-0a9f6a00-ec5c-4244-9dd6-107d8fc3e937.png)

**Comment by rpitonak** [comment]
Did you find the solution? I have the same error

**Comment by Civitasv** [comment]
Same error.
