### ISSUE TITLE
TVM with an LLVM Back-end giving error on resnet50

### ISSUE THREAD

**Issue by Kamran-10xe** [apache/tvm#10957]
Hi, 
I have been trying to go through the tutorial which helps compile the RESNET50 using an LLVM Back-end. The LLVM Back-end I am using is a cross compiler for RISC-V. So I am trying to generate the assembly for RISC-V from RESNET50. When I try to compile the code using the following command:
`tvmc compile --target "llvm -march=rv64imv -mcpu=generic-rv64" --output resnet50-v2-7-tvm.tar resnet50-v2-7.onnx`
It gives the following error:
`LLVM ERROR: CPU 'generic' is not supported. Use generic-rv64`
I have also tried to specify the target using:
`--target=llvm --target-llvm-mcpu=generic-rv64`
But, the error remains the same. 
The LLVM I am using is only built for RISC-V and I have used it many times so I don't know, where the issue is,  but I don't think the issue would be with LLVM.

**Comment by joschi2804** [comment]
Hi, 

I've got the same error as you. My LLVM is also built only for RISC-V. 
Have you found already a solution for it?

BR

**Comment by okias** [comment]
Similar issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/7769 . You could eventually try LLVM 15, but the same tests are failing, so not really different except error code.

**Comment by masahi** [comment]
The error is coming from LLVM.

**Comment by aleeshajaganath** [comment]
The right command to use for cross compilation of riscv64 is 
`tvmc compile --target="llvm -mtriple=riscv64-unknown-linux-gnu -mcpu=generic-rv64 -mabi=lp64d -mattr=+64bit,+m,+a,+f,+d,+c" --output cross_compiled.tar /home/bmw/aleesha/models/resnet18.onnx --cross-compiler riscv64-unknown-linux-gnu-g++`
this is generation compiled  models successfully
