### ISSUE TITLE
[CI Image] Rebuild Docker images to get pytest-lazy-fixture installed

### ISSUE THREAD

**Issue by gromero** [apache/tvm#10984]
- [ ] S0. Reason: a blocked PR. PR https://github.com/apache/tvm/pull/10865 is blocked because it requires the `pytest-lazy-fixture` plugin to be present in the CI so  the tests added by this PR can pass the checks. PR https://github.com/apache/tvm/pull/10970 added  `pytest-lazy-fixture` to the install scripts  and now the CI images need to get updated properly so the pytest plugin is available in the CI images.

- [ ] S1. Tag of nightly build: TAG. Docker hub (`ci_cpu`, `ci_i386`, `ci_arm`, and `ci_gpu`): https://hub.docker.com/layers/tlcpackstaging/{ci_cpu,ci_i386,ci_arm,ci_gpu}

- [ ] S2. The nightly is built on TVM commit: 40296599cd02d9960b97de6a69519eb25651b98b. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/290/pipeline/56

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...

- [ ] S4. Retag `20220413-055910-597000c74` to ci-cpu:v0.84, ci-i386:v0.77 and ci-arm:v0.10
Note: ci-gpu got updated to this tag in https://github.com/apache/tvm/pull/10992

```
docker pull tlcpackstaging/ci_cpu:20220413-055910-597000c74
docker tag tlcpackstaging/ci_cpu:20220413-055910-597000c74 tlcpack/ci-cpu:v0.84
docker push tlcpack/ci-cpu:v0.84

docker pull tlcpackstaging/ci_i386:20220413-055910-597000c74
docker tag tlcpackstaging/ci_i386:20220413-055910-597000c74 tlcpack/ci-i386:v0.77
docker push tlcpack/ci-i386:v0.77

docker pull tlcpackstaging/ci_arm:20220413-055910-597000c74
docker tag tlcpackstaging/ci_arm:20220413-055910-597000c74 tlcpack/ci-arm:v0.10
docker push tlcpack/ci-arm:v0.10
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the image versions in the `Jenkinsfile`

**Comment by gromero** [comment]
Addressed by https://github.com/apache/tvm/commit/41319ab6926226fa9b458621e8100e4db4b6be24 , so closing this one.

**Comment by Mousius** [comment]
We can leave this open until #10999 is merged @gromero, it should auto close it when the PR has landed 😸

**Comment by gromero** [comment]
@Mousius ok!
