### ISSUE TITLE
Can TVM also be used for dynamic models?

### ISSUE THREAD

**Issue by milad1378yz** [apache/tvm#11008]
I used two ways to use TVM on the BERT model
The first is to use the provider in onnxruntime and the second is to use the following link:
[https://tvm.apache.org/docs/how_to/deploy_models/deploy_sparse.html](url)
In the first method, I encountered the following error:
Incompatible broadcast type TensorType([-1, -1, 768], float32) and TensorType([1, 511, 768], float32)
This means that dynamic input cannot be given to the model.
In the second method, in the Configure Settings section, the batch_size and len_size values must be specified, which contradicts the dynamic input.
My question is, is there a way to use TVM for dynamic models like BERT?

**Comment by masahi** [comment]
Please post a question like this to https://discuss.tvm.apache.org/

Models with dynamic input can be compiled, but performance on dynamic shape is terrible since we cannot tune such workload currently.
