### ISSUE TITLE
[CI Problem] CI/MacOS fails with UnsatisfiableError: ... specifications were found to be incompatible with the existing python installation

### ISSUE THREAD

**Issue by grant-arm** [apache/tvm#11131]
CI/MacOS fails with the following error that appears to be unrelated to the changes included in the PRs that are failing: 
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tvm -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.10
```

### Branch/PR Failing

https://github.com/apache/tvm/pull/11128
https://github.com/apache/tvm/pull/11124
https://github.com/apache/tvm/pull/11123

### Jenkins Link

https://github.com/apache/tvm/runs/6177166348?check_suite_focus=true

### Flakiness

This doesn't seem to be flaky. It seems to be happening consistently.

@driazati @leandron

**Comment by AndrewZhaoLuo** [comment]
python 3.10 does not work with tvm script right now. see issue https://github.com/apache/tvm/issues/8577
