### ISSUE TITLE
[Bug] linker verbose in tvmc compile

### ISSUE THREAD

**Issue by pfk-beta** [apache/tvm#11143]
Hello,
When I'm trying to compile module with tvmc, I'm getting following error:
```
RuntimeError: Compilation error:
ld: error: /tmp/tmpho6xgmda/lib0.o is incompatible with aarch64linux
ld: error: /tmp/tmpho6xgmda/devc.o is incompatible with aarch64linux
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

Would be great, that enabling verbosity in compile command, will trigger runing linker with verbosity

**Comment by gromero** [comment]
@pfk-beta Please provide more details on how you've generated such a linker error so it's easy to reproduce your steps and work on it. Thank you.

**Comment by pfk-beta** [comment]
I don't remember an exact setup, when I was doing that stuff. Currently my setup is working correctly. So I will close the issue. But if you think about improving TVM at all, we should think about verbosity when needed.
