### ISSUE TITLE
[Bug] `python setup.py install` fails with "can't copy '../configs/': doesn't exist or not a regular file"

### ISSUE THREAD

**Issue by leandron** [apache/tvm#11186]
Our current mechanisms used to add `data_files` to the setuptools configuration is only handling file names correctly. This is because when it was implemented, only files like `libtvm.so` were added. In recent implementations we added directories as libraries, which don't match with the `data_files` syntax, meaning that if we try to run `python setup.py install`, it will fail with "error: can't copy '../configs/': doesn't exist or not a regular file".

The bug is symptomatic after my PR https://github.com/apache/tvm/pull/11063, but the problem was always there, meaning that if we had `USE_MICRO ON` set at build time, we would notice this long ago.

I'm raising this bug because I couldn't find a quick solution to push as a PR. `data_files` is bit fiddly in the way the handle directory structures to preserve them.

One option would be unifying the use of the MANIFEST file used currently only for the wheel, but I see the current mechanism is implemented on purpose to differentiate wheel from local installation. @tqchen do you remember if we have any specific reason why we can't just use the MANIFEST file for all non-Conda installations? I tried it locally and it seems to work.

This is the relevant snippet:
https://github.com/apache/tvm/blob/6b45f8dc4ad0cfecf07dbd031b1e55fe4c9b02c5/python/setup.py#L167-L197

cc @driazati @tqchen @areusch @Mousius @manupa-arm for visibility.

**Comment by areusch** [comment]
@tqchen @junrushao1994 any ideas about the MANIFEST/conda question above?

**Comment by leandron** [comment]
> @tqchen @junrushao1994 any ideas about the MANIFEST/conda question above?

Gente ping on this one.

**Comment by tqchen** [comment]
sorry I was a bit late to this, I do not remember historical context for it and perhaps it is merely due to the fact that the problem did not appear before. So we could indeed go with the manifest solution.

**Comment by leandron** [comment]
> sorry I was a bit late to this, I do not remember historical context for it and perhaps it is merely due to the fact that the problem did not appear before. So we could indeed go with the manifest solution.

Thanks, I’ll make a couple more tests locally and push a PR if I’m confident with the results.

**Comment by ShownX** [comment]
Confirmed this issue.

**Comment by areusch** [comment]
cc @hpanda-naut

**Comment by leandron** [comment]
Closing as duplicated with #11726
