### ISSUE TITLE
[CI Image] Update ci_lint with blocklint

### ISSUE THREAD

**Issue by grant-arm** [apache/tvm#11200]
- [ ] S0. Reason: https://github.com/apache/tvm/pull/11128 updates ci_lint by adding blocklint

- [ ] S1. Tag of nightly build: TAG. [20220503-055912-f00c8db5c-validated](https://hub.docker.com/layers/ci_lint/tlcpackstaging/ci_lint/20220503-055912-f00c8db5c-validated/images/sha256-8d221cad6ce09422caa134176faa977956c74487f737420f57ad63f1a76861c2?context=explore)

- [ ] S2. The nightly is built on TVM commit: TVM_COMMIT. https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/311/pipeline

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...

- [ ] S4. Retag TAG to VERSION:
```
docker pull tlcpackstaging/IMAGE_NAME:TAG
docker tag tlcpackstaging/IMAGE_NAME:TAG tlcpack/IMAGE_NAME:VERSION
docker push tlcpack/IMAGE_NAME:VERSION
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the IMAGE_NAME version on Jenkins

@leandron @driazati

**Comment by Mousius** [comment]
I'll do this alongside https://github.com/apache/tvm/issues/11202 @grant-arm 😸

**Comment by grant-arm** [comment]
Thanks @Mousius
