### ISSUE TITLE
[Flaky Test] `tests/python/frontend/paddlepaddle/test_forward.py::test_forward_gather_nd`

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#11251]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/paddlepaddle/test_forward.py::test_forward_gather_nd`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/PR-11193/8/display/redirect

**Comment by driazati** [comment]
definitely flaky since it failed on main https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3198/pipeline/

cc @jiangjiajun
