### ISSUE TITLE
[CI Problem] No space left on device while building ci_gpu

### ISSUE THREAD

**Issue by ashutosh-arm** [apache/tvm#11274]
### Branch/PR Failing

https://github.com/apache/tvm/pull/11273

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11273/2/pipeline/
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11273/1/pipeline/

### Flakiness

I have seen in two runs on the same PR so far.

cc: @driazati @Mousius @leandron @areusch

**Comment by driazati** [comment]
both jobs got assigned to the same node `i-0600c287f09ab5d81` which hadn't had its Docker pruned in a while (200+ GB of old images were taking up space). I've manually cleaned it and I'll put up a PR soon to automatically run `docker system prune` on old images

**Comment by ashutosh-arm** [comment]
Thanks @driazati for quickly looking into it.
