### ISSUE TITLE
[Bug] [build with llvm] undefined symbol when import tvm

### ISSUE THREAD

**Issue by Zhiwei35** [apache/tvm#11284]
hi, I am new to tvm. I was **building tvm with llvm 6.0 or 7.0 targeting intel CPU and no error occurred in "make" cmd**, my OS is **centos7**, but **when I typed “import tvm”, error occurred**:
```
Python 3.7.13 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
import tvm
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
File "/home/zxxx/tvm/python/tvm/__init__.py", line 26, in <module>
from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
File "/home/xxx/tvm/python/tvm/_ffi/__init__.py", line 28, in <module>
    from .base import register_error
File "/home/xxx/tvm/python/tvm/_ffi/base.py", line 71, in <module>
   _LIB, _LIB_NAME = _load_lib()
File "/home/xxx/tvm/python/tvm/_ffi/base.py", line 57, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
File "/home/xxx/miniconda3/envs/xxx/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xxx/tvm/build/libtvm.so: undefined symbol: _ZNKSt3__114error_category10equivalentERKNS_10error_codeEi
```
BTW, when **I build tvm without llvm, the import is well**. Did i use wrong llvm pre-built binary?I used * [SuSE Linux Enterprise Server 11SP3 x86_64](https://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-sles11.3.tar.xz) [(.sig)](https://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-sles11.3.tar.xz.sig)

Anybody can help me? Thanks for your time!

**Comment by ganler** [comment]
Hi @Zhiwei35, maybe you can try newer versions of LLVM (e.g., LLVM11, you can find pre-compiled binary at https://releases.llvm.org/download.html).

**Comment by Zhiwei35** [comment]
> Hi @Zhiwei35, maybe you can try newer versions of LLVM (e.g., LLVM11, you can find pre-compiled binary at https://releases.llvm.org/download.html).

Thanks reply, I tried llvm10 pre-compiled binary whose postfix is "x86_64-linux-sles11.3.tar.xz" , and when I typed "import tvm", still OSerror: "OSError: /home/xxxxx/tvm/build/libtvm.so: undefined symbol: _ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info"

I also tried llvm14 12 11 pre-compiled binary whose postfix are all "x86_64-linux-sles12.4.tar.xz" but when I typed "clang -v", it crashed, and reported "can't load open shared library: libatomic.so.1: cannot open shared object file: No such file or directory". I have no root access, so I have to downgrade llvm until 10.

Thanks for your time

**Comment by ganler** [comment]
@Zhiwei35 I see. Could you please provide more detials? (e.g., how you build tvm)l & your env). 

BTW, let's move the discussion to tvm discuss. GitHub issues are often used for bug/feature tracking :-).

**Comment by Zhiwei35** [comment]
> 

No Problem, I will provide details later, and the tvm disscuss link is https://discuss.tvm.apache.org/t/issue-undefined-symbol-when-import-tvm/12742. thx

**Comment by Zhiwei35** [comment]
@ganler hi, could you pls take a minute to look my question in [tvm discuss](https://discuss.tvm.apache.org/t/issue-undefined-symbol-when-import-tvm/12742)? Thanks very much.
