### ISSUE TITLE
[Bug] benchmark_hexagon.py not running on CI

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#11295]
We need to rename the file and fix error to run on CI:
https://github.com/apache/tvm/blob/main/tests/python/contrib/test_hexagon/benchmark_hexagon.py

@cconvey

**Comment by cconvey** [comment]
@mehrdadh : Thanks for reporting this!  Can you say more about what renaming is needed and what the error is that needs fixing?

**Comment by mehrdadh** [comment]
this is fixed now:
https://github.com/apache/tvm/blob/main/tests/python/contrib/test_hexagon/test_benchmark_maxpool2d.py
https://github.com/apache/tvm/blob/main/tests/python/contrib/test_hexagon/test_benchmark_elemwise_add.py
