### ISSUE TITLE
[CI Image] Updates to ci_cpu and ci_qemu to reflect CMSIS-NN SHA upgrade

### ISSUE THREAD

**Issue by ashutosh-arm** [apache/tvm#11338]
- [ ] S0. Reason: (https://github.com/apache/tvm/pull/11273)

- [ ] S1. Tag of nightly build: 20220517-094028-de21c8f2e

- [ ] S2. The nightly is built on TVM commit: de21c8f2ef507587fdcc99b851404de5aeeb5a16

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/331/pipeline/

- [ ] S4. Retag TAG to VERSION:

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the ci_cpu and ci_qemu version on Jenkins

**Comment by leandron** [comment]
Fixed in https://github.com/apache/tvm/pull/11336
