### ISSUE TITLE
[Bug] _test_tflite2_quantized_depthwise_convolution is unused

### ISSUE THREAD

**Issue by leandron** [apache/tvm#11356]
Creating this issue as a reminder that tests in the TFLite frontend seem to be missing `_test_tflite2_quantized_depthwise_convolution`, which shows lack of coverage for that particular operator.

**Comment by valmirnjr** [comment]
Hi @leandron , I'd like to work on this issue. When I try to run `test_forward_quantized_convolution` I see that `_test_tflite2_quantized_depthwise_convolution` fails. Is this the problem?

> $ pytest tests/python/frontend/tflite/test_forward.py::test_forward_quantized_convolution
> [11:41:02] ../src/target/target_kind.cc:163: Warning: Unable to detect CUDA version, default to "-arch=sm_20" instead
> enabled targets: llvm
> pytest marker: 
> ======================================== test session starts ========================================
> platform linux -- Python 3.8.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
> rootdir: /home/valmir/Documentos/Projects/tvm
> collected 1 item                                                                                    
> 
> tests/python/frontend/tflite/test_forward.py F                                                [100%]
> 
> ============================================= FAILURES ==============================================
> ________________________________ test_forward_quantized_convolution _________________________________
> 
>     def test_forward_quantized_convolution():
>         for int_quant_dtype in [tf.int8, tf.int16]:
> >           _test_tflite2_quantized_convolution(
>                 (1, 28, 28, 1),
>                 (1, 1),
>                 12,
>                 data_format="NHWC",
>                 int_quant_dtype=int_quant_dtype,
>             )
> 
> tests/python/frontend/tflite/test_forward.py:945: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> tests/python/frontend/tflite/test_forward.py:937: in _test_tflite2_quantized_convolution
>     tvm_output = run_tvm_graph(tflite_model_quant, data, data_in.name.replace(":0", ""))
> tests/python/frontend/tflite/test_forward.py:239: in run_tvm_graph
>     m.set_input(e, tvm.nd.array(input_data[i].astype(input_data[i].dtype)))
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by blackkker** [comment]
@leandron I think you can closed this issue.

**Comment by leandron** [comment]
Closed by https://github.com/apache/tvm/pull/12145
