### ISSUE TITLE
[Bug] tvm.nd.ndarray to numpy taking too much time?

### ISSUE THREAD

**Issue by Uhao-P** [apache/tvm#11352]
target = 'cuda'
    dev = tvm.cuda(0)
    with tvm.transform.PassContext(opt_level=3):
        lib = relay.build(mod, target=target, params=params)

    dtype = "float32"
    m = graph_executor.GraphModule(lib["default"](dev))

    m.set_input(input_name, tvm.nd.array(img.astype(dtype)))
    m.run()
    t1 = time.time()
    tvm_output = m.get_output(0)  # shape: 184,720,3
    t2 = time.time()
    print(t2 - t1)  # 180ms
    pred = torch.argmax(torch.from_numpy(tvm_output.numpy()), 1).squeeze(0).cpu().data.numpy()

**Comment by masahi** [comment]
`m.run()` is non-blocking on cuda, so `m.get_output(0)` actually involves waiting for the execution to finish.
