### ISSUE TITLE
ImportError: cannot import name 'EarlyStopException' from 'xgboost.core'[Bug] 

### ISSUE THREAD

**Issue by WuZheng326** [apache/tvm#11409]
When I was running the AutoSchedule demo:

https://tvm.apache.org/docs/how_to/tune_with_autoscheduler/tune_network_cuda.html#sphx-glr-how-to-tune-with-autoscheduler-tune-network-cuda-py

I met this bug: ImportError: cannot import name 'EarlyStopException' from 'xgboost.core'

My TVM version is 0.9 dev, and Xgboost version is 1.6.1

What is wrong with the AutoSchedule？

**Comment by schell** [comment]
I just ran into this as well. My guess is that `xgboost==1.6.1` has removed `EarlyStopException`.

**Comment by WuZheng326** [comment]
你好，我是吴峥，已收到您的邮件，我会尽快给您回复。

**Comment by WuZheng326** [comment]
> I just ran into this as well. My guess is that `xgboost==1.6.1` has removed `EarlyStopException`.

yes, I reinstall xgboost 1.5.0, and find that works
https://discuss.tvm.apache.org/t/auto-scheduler-ansor-xgboost-cost-model-import-error/12635

**Comment by schell** [comment]
Yes, I can confirm that `xgboost<1.6.1` fixes this.
