### ISSUE TITLE
[VOTE] Quarterly Releases RFC

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11415]
This is a formal vote thread to determine committer and PMC support for [Quarterly Releases RFC](https://github.com/apache/tvm-rfcs/pull/67). Replying +1 here means you support the RFC and we should merge it. This vote thread is due to the fact that the RFC proposes a change in the way the community operates (namely the way we do releases). This also signals the final comment period on that RFC, which will conclude with this vote. All are welcomed to vote here, though members of the PMC have binding votes which determine the outcome of the RFC.

We'll leave this vote thread open for a week, and make a decision then.

Thanks,
Andrew

Please vote:
+1 I support the RFC
0 I'm happy either way
-1 I do not support the RFC and it should not be merged.

@apache/tvm-committers

**Comment by leandron** [comment]
+1

(binding)

**Comment by tqchen** [comment]
+1

**Comment by AndrewZhaoLuo** [comment]
+1

**Comment by comaniac** [comment]
+1

**Comment by masahi** [comment]
+1

**Comment by jroesch** [comment]
+1

**Comment by csullivan** [comment]
+1

**Comment by jwfromm** [comment]
+1

**Comment by lhutton1** [comment]
+1

**Comment by zxybazh** [comment]
+1

**Comment by areusch** [comment]
+1

The voting period has concluded with the following results:

+1 (6 binding*): 
Leandro*
Tianqi*
Andrew Luo
Cody*
Masa*
Jared*
Chris Sullivan
Josh Fromm
Luke Hutton
Xiyou
Andrew*

0:  none

-1: none

The vote has passed and the RFC is accepted.

**Comment by tvm-archiver** [comment]
+1

(Binding)
