### ISSUE TITLE
[Bug] import of mxnet newer than 1.6.0 after tvm is crashed

### ISSUE THREAD

**Issue by elvin-n** [apache/tvm#11452]
### Expected behavior

importing of mxnet and tvm should work together independently on order of their imports

### Actual behavior

```
>>> import tvm
>>> import mxnet
Segmentation fault (core dumped)
```
if import mxnet first and then tvm - everything works fine

### Environment
Crashes if tvm is imported first:
Ubuntu 21.10 cpython Python 3.9.12 mxnet 1.9.1
Ubuntu 21.10 Anaconda Python 3.8.5 mxnet 1.8.0.post0
Ubuntu 20.04 Anaconda 3.8.8 mxnet 1.8.0

Good in any order of importing:
Ubuntu 21.10 cpython Python 3.9.12 mxnet 1.6.0

### Steps to reproduce
call python and import tvm and mxnet

**Comment by masahi** [comment]
Probably related to https://github.com/apache/tvm/issues/9362. The same solution may work.
