### ISSUE TITLE
[merge bot] allow merge when an empty commit was pushed on top of an approved one

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11473]
it would be helpful if we also allow folks to retrigger the CI. we can't recognize force-pushes because GH garbage-collects the old pushes, but if ppl push an empty or merge commit we could check whether or not anything was changed and allow it to merge. this would let folks fix trivial CI problems without requiring re-approval.

cc @driazati

**Comment by driazati** [comment]
Merge bot is currently not in use
