### ISSUE TITLE
[Flaky Test] `tests/python/contrib/test_ethosu/test_codegen.py::test_mean[ifm_shape0-axis0-True-False-ethos-u65-256]`

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11527]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_mean[ifm_shape0-axis0-True-False-ethos-u65-256]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/3414/display/redirect

**Comment by driazati** [comment]
issue to still present (see #12956), but closing to consolidate on #12634
