### ISSUE TITLE
[Flaky Test] `tests/python/frontend/pytorch/test_forward.py::test_argsort`

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11568]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/pytorch/test_forward.py::test_argsort`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/3444/display/redirect

possibly of interest: https://github.com/apache/tvm/issues/4860

**Comment by driazati** [comment]
We haven't seen this lately and the test is enabled, cautiously closing this issue
