### ISSUE TITLE
[Flaky Test] `tests/python/unittest/test_custom_datatypes.py::test_myfloat`

### ISSUE THREAD

**Issue by FranckQC** [apache/tvm#11580]
These tests were found to be flaky (failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/unittest/test_custom_datatypes.py::test_myfloat`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/PR-11574/8/display/redirect

**Comment by Lunderberg** [comment]
Additional failure in PR#11798 , CI link https://ci.tlcpack.ai/job/tvm/job/PR-11798/1/display/redirect

**Comment by rafzi** [comment]
I also encountered this: https://ci.tlcpack.ai/job/tvm/job/PR-11877/1/display/redirect

The test passes locally.

**Comment by driazati** [comment]
this hasn't happened recently, closing this since it appears to be fixed
