### ISSUE TITLE
[Flaky Test] `tests/python/frontend/onnx/test_forward.py::test_qlinearmul[cuda]`

### ISSUE THREAD

**Issue by mbs-octoml** [apache/tvm#11603]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/onnx/test_forward.py::test_qlinearmul[cuda]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/PR-11481/9/display/redirect

**Comment by driazati** [comment]
We haven't seen this lately and the test is enabled, cautiously closing this issue
