### ISSUE TITLE
[ci][tlcpack] Encode workflow dependencies

### ISSUE THREAD

**Issue by driazati** [apache/tvm#11610]
Right now in [tlc-pack/ci](https://github.com/tlc-pack/ci/tree/main/.github/workflows) we have:
1. packer build
2. terraform plan
3. terraform apply
4. jenkins prepare
5. jenkins deploy

But really these are all dependent, but only 2 -> 3 is enforce but the current workflows.  We should make it so that any change runs through `1 -> 2 -> 3` at least (skipping packer if unchanged) and that running 4 runs 1 -> 2 -> 3 (again skipping unchanged workflows)

cc @Mousius @areusch @gigiblender

**Comment by areusch** [comment]
cc @hpanda-naut can you triage?
