### ISSUE TITLE
[Flaky Test] 

### ISSUE THREAD

**Issue by mbs-octoml** [apache/tvm#11660]
### Test(s)

python3 tests/scripts/ci.py i386 --tests tests/python/unittest/test_custom_datatypes.py::test_myfloat

### Jenkins Links

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11619/5/pipeline/344/

**Comment by masahi** [comment]
a dup with https://github.com/apache/tvm/issues/11580
