### ISSUE TITLE
[CI Image] support CSI-NN2 in ci_qemu

### ISSUE THREAD

**Issue by alter-xp** [apache/tvm#11688]
- [x] S0. Reason: [Introduce CSI-NN2 Compute Library into TVM to accelerate the inference performance of RISC-V CPU with Vector Extension](https://github.com/apache/tvm-rfcs/pull/75)

- [x] S1. Tag of nightly build: TAG: [20220713-060117-ca88c522f](https://hub.docker.com/layers/ci_qemu/tlcpackstaging/ci_qemu/20220713-060117-ca88c522f/images/sha256-2677d128446861d93412b7a9bb631eccb8878fc9801a546d459df2bcaf105002?context=explore)
- [x] S2. The nightly is built on TVM commit:  https://github.com/apache/tvm/pull/11689 https://github.com/apache/tvm/pull/11905 https://github.com/apache/tvm/pull/12230

the ci_riscv image does include the CSI-NN install script.

**Comment by alter-xp** [comment]
hi @areusch, the nightly rebuild has passed. So next we need to push the image to tlcpack, right?

**Comment by alter-xp** [comment]
@driazati  It seems to be the problem of environment variables. let me solve it.

**Comment by alter-xp** [comment]
@driazati It is the conflict between Xuantie QEMU and Zephyr QEMU. I have solved it by modifying the script in CSI-NN2 (merged), and it will not involve the content in TVM code. It seems that we need to wait for nightly rebuild before continuing.

**Comment by areusch** [comment]
@alter-xp we run these nightly, here's the [latest failure](https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdocker-image-run-tests/detail/docker-image-run-tests/169/pipeline). resolving the ARM toolchain seems maybe-related to this...what if instead of trying to fix the two together, we just create ci_riscv now? if you create Dockerfile.ci_riscv, i can help with getting that one built and added to various scripts.

**Comment by alter-xp** [comment]
thanks @areusch, i will create Dockerfile.ci_riscv. and should we need to create a RFC about this?

**Comment by areusch** [comment]
i think we're ok w/o RFC for this one as it's just moving around previously-RFC'd functionality. thanks!

**Comment by alter-xp** [comment]
hi @areusch, I created a [Dockerfile.ci_riscv (pr)](https://github.com/apache/tvm/pull/12230), which only retains the basic environment and riscv related content in Dockerfile.ci_qemu. Do we need to use CI to build ci_riscv image next?  I'm not familiar with this. So can you help me list the next process and what I need to do?

**Comment by areusch** [comment]
@alter-xp sorry--i've been a bit busy lately. looks like @driazati approved/merged that one, and i created https://github.com/tlc-pack/tlcpack/pull/131 to add that build to our nightly docker image rebuild/test. looks like that pipeline is green now so we should be able to get that image built today or tomorrow and then we can begin using it. i'll update this thread when it's ready.
