### ISSUE TITLE
[Bug] Tutorial icons are hard to read in docs

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11721]
On https://tvm.apache.org/docs/how_to/tune_with_autoscheduler/, the tutorial icons are not contrasted enough with the text.

See ![image](https://user-images.githubusercontent.com/532957/173696652-388784ee-377c-47ec-849a-4da1851da448.png) from Chrome 101.0.4951.64 (Official Build) (x86_64) on OS X.

cc @hpanda-naut

**Comment by hogepodge** [comment]
When I do a local build from head, the docs render correctly.
<img width="700" alt="Screen Shot 2022-06-14 at 3 35 27 PM" src="https://user-images.githubusercontent.com/367747/173701033-9c6921df-62b4-418d-9a00-37096aac2535.png">

**Comment by areusch** [comment]
@hogepodge did you rebuild with `tests/scripts/ci.py docs` or differently?

**Comment by hogepodge** [comment]
My docs script does:
```
bash -c "cd tvm/docs; TVM_TUTORIAL_EXEC_PATTERN=/vta/tutorials make html"
```

I can update if necessary to match CI.

**Comment by driazati** [comment]
this is fixed now
