### ISSUE TITLE
[Flaky Test] `tests/python/unittest/test_custom_datatypes.py::test_myfloat`

### ISSUE THREAD

**Issue by hpanda-naut** [apache/tvm#11739]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/unittest/test_custom_datatypes.py::test_myfloat`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/3541/display/redirect

cc @areusch @driazati

**Comment by masahi** [comment]
a dup of https://github.com/apache/tvm/issues/11580
