### ISSUE TITLE
[release] v0.9.0 Release Schedule

### ISSUE THREAD

**Issue by driazati** [apache/tvm#11736]
As discussed in https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md, we will be publishing a release of TVM on mid July. We will do a branch cut soon but accept cherry-picked changes for a couple weeks. See the [release steps](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation) for details as well as the [TVM release process docs](https://tvm.apache.org/docs/contribute/release_process.html).

The current schedule is:
* June 28 - branch cut
   * we will create a `v0.9` branch from `main` on this day
* July 7 - cherry-picking soft deadline
   * during this time any reasonable change can be merged, comment on this issue with the commit you would like added to the release branch
* July 11 - cherry-picking hard deadline
    * during this time only critical changes will be merged, comment on this issue with the commit you would like added to the release branch as well as the reasoning for adding it
* ~~July 12~~ July 14 - release vote opened
* ~~July 18~~ July 19 - release published

Keep in mind this schedule is tentative and may change as we progress through the process. We will also be collecting release notes in this thread as in the past (see #8976 for the v0.8.0 release planning thread), so please comment the changes since v0.8.0.

**Comment by driazati** [comment]
v0.9.0 has been cut at 97b3076c3532f73a9d9eeba26a3f329f8e0f803d in https://github.com/apache/tvm/tree/v0.9.0

**Comment by driazati** [comment]
cherry pick: #11969
reason: needed to get tests on the Python wheel in GitHub Actions passing

**Comment by areusch** [comment]
we should try and fix https://github.com/apache/tvm/issues/12022 before we release as well, i think

**Comment by Mousius** [comment]
@driazati / @areusch are we pushing the release schedule for #12022 ?

**Comment by driazati** [comment]
Yeah, along with some other things but #12022 is the only remaining item

**Comment by areusch** [comment]
just to update this issue, we're nearly done cutting the release and will post the release announcement shortly. we had a hiccup with our schedule here.

**Comment by driazati** [comment]
Finally posted announcement in https://discuss.tvm.apache.org/t/apace-tvm-v0-9-0-release/13291
