### ISSUE TITLE
[CI Image] Update Lint image

### ISSUE THREAD

**Issue by AndrewZhaoLuo** [apache/tvm#11733]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

- [x] S0. Reason: For example, a blocked PR or a feature issue:

Upgrading pylint allows use new features which might make linting a lot better, see https://github.com/apache/tvm/compare/main...AndrewZhaoLuo:aluo/upgrade-pylint?expand=1

- [x] S1. Tag of nightly build: TAG. Docker hub: https://hub.docker.com/layers/tlcpackstaging/ci_cpu/...

https://hub.docker.com/layers/ci_lint/tlcpackstaging/ci_lint/20220621-055909-9ff2a5e79/images/sha256-c59ebc1a897fca6e0d185038fbebfc49832ca7c6dbf9203d6fa692943eb518fc?context=explore

- [x] S2. The nightly is built on TVM commit: 9ff2a5e796b9cac0bdf05bfd600c50ade9728f1f. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/....
From https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/367/pipeline/58

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...

- [ ] S4. Retag TAG to VERSION:
```
docker pull tlcpackstaging/IMAGE_NAME:TAG
docker tag tlcpackstaging/IMAGE_NAME:TAG tlcpack/IMAGE_NAME:VERSION
docker push tlcpack/IMAGE_NAME:VERSION
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the IMAGE_NAME version on Jenkins

**Comment by leandron** [comment]
This seems to be done from a long time, given at the moment ci-lint is `20220810-060142-fae79bbc3`, so closing the issue.
