### ISSUE TITLE
[CI Image] Update ci_gpu

### ISSUE THREAD

**Issue by huajsj** [apache/tvm#11774]
[tlcpackstaging/ci_gpu:20220617-055916-1b8f3b54c]

- [ ] S0. [image generated by PR 11744 ad dnnl into ci/gpu](https://github.com/apache/tvm/pull/11744), blocked PR [Pipeline executor tutorial](https://github.com/apache/tvm/pull/11557)

- [ ] S1. Tag of nightly build: [tlcpackstaging/ci_gpu:20220617-055916-1b8f3b54c](https://hub.docker.com/layers/ci_gpu/tlcpackstaging/ci_gpu/20220617-055916-1b8f3b54c/images/sha256-bf47fb026181b8ac17e9ed733fc914044934a065b3ba06c215ceee0b3b28f42d?context=explore)

- [ ] S2. The nightly is built on TVM commit: TVM_COMMIT: 1b8f3b54c6da0bf25427a8bd9a049d87318a1e66. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11744/1/pipeline/49

- [ ] S3. Testing the nightly image on ci-docker-staging: TBC

- [ ] S4. Retag TAG to VERSION:
```
docker pull tlcpackstaging/ci_gpu:20220617-055916-1b8f3b54c
docker tag tlcpackstaging/ci_gpu:20220617-055916-1b8f3b54c tlcpack/ci_gpu:20220617-055916-1b8f3b54c
docker push tlcpack/ci_gpu:20220617-055916-1b8f3b54c
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the IMAGE_NAME version on Jenkins

**Comment by huajsj** [comment]
cc @masahi @areusch @driazati

**Comment by areusch** [comment]
working on this

**Comment by areusch** [comment]
@huajsj i think that CI run didn't validate properly. have to see the image validate before we can push it

**Comment by masahi** [comment]
I have a PR up for this https://github.com/apache/tvm/pull/11786.

**Comment by huajsj** [comment]
thanks @masahi @areusch.
