### ISSUE TITLE
[ci] ci_arm container build fails

### ISSUE THREAD

**Issue by areusch** [apache/tvm#11773]
ci_arm is [failing to build](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-11772/4/pipeline/).

Looks like the version of tensorflow-aarch64 has gone missing from the aarch64 pip repo: https://snapshots.linaro.org/ldcg/python-cache/tensorflow-aarch64/

cc @Mousius @driazati @gromero @leandron

**Comment by areusch** [comment]
cc @hpanda-naut

**Comment by driazati** [comment]
should we rehost the `.whl` ourselves? this isn't the first time it's been down

**Comment by areusch** [comment]
also cc @tom-gall

**Comment by tom-gall** [comment]
It would be better to use the official PyPi : https://pypi.org/project/tensorflow-aarch64/#description

I'll note that in the not too distant future (matter of weeks) you'll be able to pip install TensorFlow on aarch64 machines and it'll just work.

**Comment by lhutton1** [comment]
The reason for using `https://snapshots.linaro.org/ldcg/python-cache/tensorflow-aarch64/` was because it had made version `2.6.3` available, which I believe the official PyPi does not offer

**Comment by tom-gall** [comment]
We've managed to restore the 2.6.3 version - These are at : https://snapshots.linaro.org/ldcg/python/tensorflow-manylinux/43/tensorflow-aarch64/ 

Does this suffice ?

**Comment by leandron** [comment]
Hi. I’ll try to put together a patch to use the new location. Probably needs to be used in a slightly different way: downloaded manually and installed.

I’ll send a PR to test that soon. Thanks for the help!

**Comment by leandron** [comment]
This is now closed. Thanks @tom-gall for the help with making the packages available!
