### ISSUE TITLE
[ci] Execution failed for task ':app:checkDebugAarMetadata' on android build

### ISSUE THREAD

**Issue by hpanda-naut** [apache/tvm#11805]
### Branch/PR Failing

https://github.com/apache/tvm/pull/11683

### Jenkins Link

https://github.com/apache/tvm/runs/6941363212?check_suite_focus=true

cc @Mousius @areusch @driazati

**Comment by areusch** [comment]
i'm going to close this one as dl.google.com seems unlikely to frequently flake. we can leave it here for tracking purposes and re-open if we find more recurring flakes
