### ISSUE TITLE
[CMSIS-NN][ARM] ARM_MATH_ARGUMENT_ERROR due to not setting the context buffer in `arm_avgpool_s8`

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#11810]
Using TVM main to build keyword spotting model with CMSIS NN (same CMSIS version used in ci_qemu) would lead to error ARM_MATH_ARGUMENT_ERROR. Here are some details:

calling `arm_avgpool_s8` function would result in calling [this line](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c#L273) and here since the context buffer is null and `arm_avgpool_s8_get_buffer_size` returns non-zero, it results in ARM_MATH_ARGUMENT_ERROR error.

This is what the generated function looks like:
```
TVM_DLL int32_t tvmgen_default_cmsis_nn_main_9(int8_t* input_, int8_t* output_) {
  cmsis_nn_context context= {NULL,0};
  cmsis_nn_tile stride = {5,25};
  cmsis_nn_tile padding = {0,0};
  cmsis_nn_activation activation = {-128,127};
  cmsis_nn_pool_params pool_params = {stride, padding, activation};
  cmsis_nn_dims input_dims = {1,25,5,64};
  cmsis_nn_dims filter_dims = {1,25,5,1};
  cmsis_nn_dims output_dims = {1,1,1,64};
  arm_status status = arm_avgpool_s8(&context, &pool_params, &input_dims, input_, &filter_dims, &output_dims, output_);
  if (status != ARM_MATH_SUCCESS) {
    return -1;
  }
  return 0;
}
```

cc @Mousius @ashutosh-arm @areusch

**Comment by mehrdadh** [comment]
@grant-arm

**Comment by mehrdadh** [comment]
Here is a gist to reproduce this error:
https://gist.github.com/mehrdadh/2f3aa844e2df21e22e5ccf9708a56e0c#file-tvm_kws_cmsis-py

Note:
1. You don't see the error unless you use `west debug` to step by step go through the code. In the generated code `ARM_MATH_ARGUMENT_ERROR` would result in returning -1 and code execution just fails.
2. If you run this with older CMSIS version like (5.8.0 which we used before on ci_qemu) it will show wrong output. The reason is that previous CMSIS didn't check for if `context->buff` is not `NULL` and it would just overwrite some memory.

cc @ashutosh-arm

**Comment by ashutosh-arm** [comment]
Thanks @mehrdadh for putting together the script to reproduce this issue. I will get to this early next week.

**Comment by PhilippvK** [comment]
@mehrdadh  I would guess, that this is related to #11702 which was merged one month ago. You you please try again on the latest TVM commit?

**Comment by mehrdadh** [comment]
@PhilippvK thanks for reporting this! I checked today and the issue seems to be resolved!
I add some missing CMSIS NN source files to cmake: https://github.com/apache/tvm/pull/12642
