### ISSUE TITLE
[Flaky Test] tests/micro/zephyr/test_zephyr_aot_exec.py::test_aot_executor

### ISSUE THREAD

**Issue by nverke** [apache/tvm#11831]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking. You are always welcomed to post on the forum first :smile_cat:

These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). As per [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures, these failures will be disabled in a PR that references this issue until the test owners can fix the source of the flakiness.

### Test(s)

- `tests/micro/zephyr/test_zephyr_aot_exec.py::test_aot_executor[mps2_an521]`

### Jenkins Links

- https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3602/pipeline/374

cc @alanmacd

**Comment by alanmacd** [comment]
This test shouldn't be running on mps2_an521, will update it to skip.

**Comment by driazati** [comment]
PR is merged now!
