### ISSUE TITLE
[CI Problem] No space left on device

### ISSUE THREAD

**Issue by nverke** [apache/tvm#11840]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Branch/PR Failing

https://github.com/apache/tvm/commit/98fb955a5153e3d4f66fa3b9403e515da31c54b6

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3608/pipeline/

### Flakiness

No

**Comment by driazati** [comment]
See #11920
