### ISSUE TITLE
[Flaky Test] `tests/python/unittest/test_custom_datatypes.py::test_myfloat`

### ISSUE THREAD

**Issue by nverke** [apache/tvm#11861]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/unittest/test_custom_datatypes.py::test_myfloat`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/3612/display/redirect
  - https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3625/pipeline
  - https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3640/pipeline

cc @gussmith23 @jroesch @hypercubestart

**Comment by masahi** [comment]
A dup with https://github.com/apache/tvm/issues/11580, feel free to send a PR to disable this test.
