### ISSUE TITLE
[Bug] Quantize description is inconsistent with the actual implementation

### ISSUE THREAD

**Issue by sisleyli** [apache/tvm#11867]
There is the description of quantize in `/python/tvm/relay/qnn/op/qnn.py`

```python
def quantize(data, output_scale, output_zero_point, axis=-1, out_dtype="int8"):
    r"""Quantize op
    This operator takes float32 as input and produces quantized int8 or unit8 as output.
    The input tensor can be of any shape. The output shape is the same as input shape.
    Q_output = clamp((round(input_tensor/output_scale) + output_zero_point),
                     out_dtype::min,
                     out_dtype::max)
    Parameters
```

Here it seems that the implementation is `clamp((round(input_tensor/output_scale) + output_zero_point)` ,

but in `/src/relay/qnn/op/quantize.cc`:

```C++
  const int32_t min_val = GetQmin(out_dtype);
  const int32_t max_val = GetQmax(out_dtype);
  auto scale_data = Divide(input_tensor, expanded_output_scale);
  auto add_zero_point = Add(scale_data, Cast(expanded_output_zero_point, DataType::Float(32)));
  auto clamped_output = Clip(add_zero_point, min_val, max_val);
  auto rounded_clamped_output = Round(clamped_output);
  return Cast(rounded_clamped_output, out_dtype);
```

It seems that the actual implementation is `round(clamp((input_tensor/output_scale) + output_zero_point))` 

Now I'd like to know which implementation tvm wants to implement, round first or clip first?

### Expected behavior

Quantize description is consistent with the actual implementation

### Actual behavior

Quantize description is inconsistent with the actual implementation

**Comment by masahi** [comment]
I think the python description makes more sense to me. What do you think? Feel free to send a PR to fix the C++ implementation.

**Comment by masahi** [comment]
Actually, the order in the C++ implementation is done intentionally, see https://github.com/apache/tvm/pull/9558

cc @AndrewZhaoLuo

**Comment by sisleyli** [comment]
> 
@masahi 
Yeah, python description is also more compatible with my program. For the order you mentioned, please wait for me to confirm. If there is no problem, I am sure willing to send a PR.

**Comment by sisleyli** [comment]
> Actually, the order in the C++ implementation is done intentionally, see #9558
> 
> cc @AndrewZhaoLuo

> This fixes this by moving the clipping operation to operate on the floating point values before casting to integer.

My focus is that `round` should be executed before `scale_data` add `expanded_output_zero_point`, right? It seems that no conflict with #9558 , which move clip before cast to integer.

**Comment by masahi** [comment]
ah right, I was thinking about the order of round and clip, but I realized that it doesn't really matter.
