### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by normanzh** [apache/tvm#11900]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior
File tvm/python/tvm/script/parser.py:364

Bug: 
The Module has no attr func, it's should be len(node.func**s**) == 0, not len(node.func) == 0.

### Actual behavior

AttributeError: 'Module' object has no attribute 'func'

### Environment

Any environment details, such as: Operating System, TVM version, etc

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

**Comment by masahi** [comment]
Good catch, you are welcome to send a quick PR to fix it.

**Comment by gromero** [comment]
Since #12053 is merged I'm closing it.
