### ISSUE TITLE
[ci] Periodically trigger a repository scan on Jenkins

### ISSUE THREAD

**Issue by driazati** [apache/tvm#11914]
With just webhooks the code to delete old builds never runs and the head node will eventually run out of disk space. We should make a GitHub Actions job that uses the Jenkins API (either call an endpoint to trigger a scan directly or execute a groovy script to do the scan if that endpoint doesn't exist) that it set up to run weekly on a cron or something.

cc @Mousius @areusch @gigiblender

**Comment by areusch** [comment]
cc @hpanda-naut  can you triage?
