### ISSUE TITLE
Exercise TVM under minimal configuration in CI

### ISSUE THREAD

**Issue by hpanda-naut** [apache/tvm#11932]
We have seen a couple bugs due to microTVM being presumed-ON in config.cmake. Namely, you get python errors importing TVM right now when USE_MICRO is OFF. We should have a regression test that verifies basic functionality with everything (or nearly everything) OFF.

Context: apache/tvm#9617
And another micro-related issue of the same kind, which i don't have handy right now.

cc @gigiblender

**Comment by areusch** [comment]
@gigiblender
