### ISSUE TITLE
[Flaky Test] test_ethosu/test_networks.py::test_networks_with_usmp_and_cascader_with_striping

### ISSUE THREAD

**Issue by masahi** [apache/tvm#11941]
Saw it twice today:
https://ci.tlcpack.ai/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-11935/runs/7/nodes/358/steps/973/log/?start=0
https://ci.tlcpack.ai/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-11926/runs/3/nodes/358/steps/946/log/?start=0

cc @manupa-arm @d-smirnov

**Comment by manupa-arm** [comment]
I ll take a look!
