### ISSUE TITLE
[Flaky Test] `tests/python/frontend/onnx/test_forward.py::test_all_reduce_funcs[llvm]`

### ISSUE THREAD

**Issue by gigiblender** [apache/tvm#11964]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/onnx/test_forward.py::test_all_reduce_funcs[llvm]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/3695/display/redirect

Might be a similar reason for failure as in #8965.

**Comment by driazati** [comment]
This hasn't come up lately afaik, cautiously closing
