### ISSUE TITLE
[Bug] Mac m1 pro build fail.

### ISSUE THREAD

**Issue by DongqiShen** [apache/tvm#11997]
I try to build tvm on my m1 pro but got failed. I think I followed the tutorial, but still got wrong. The output as follows:

-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is Clang 14.0.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /opt/homebrew/opt/llvm@14/bin/clang++
-- Check for working CXX compiler: /opt/homebrew/opt/llvm@14/bin/clang++ - broken
CMake Error at /Users/dongqishen/.local/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/opt/homebrew/opt/llvm@14/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/dongqishen/Workspace/tvm/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/opt/homebrew/bin/gmake -f Makefile cmTC_d2688/fast && /opt/homebrew/bin/gmake  -f CMakeFiles/cmTC_d2688.dir/build.make CMakeFiles/cmTC_d2688.dir/build
    gmake[1]: Entering directory '/Users/dongqishen/Workspace/tvm/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_d2688.dir/testCXXCompiler.cxx.o
    /opt/homebrew/opt/llvm@14/bin/clang++   -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -MD -MT CMakeFiles/cmTC_d2688.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_d2688.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_d2688.dir/testCXXCompiler.cxx.o -c /Users/dongqishen/Workspace/tvm/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_d2688
    /Users/dongqishen/.local/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d2688.dir/link.txt --verbose=1
    /opt/homebrew/opt/llvm@14/bin/clang++  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/llvm@14/lib  CMakeFiles/cmTC_d2688.dir/testCXXCompiler.cxx.o -o cmTC_d2688
    ld: library not found for -lSystem
    clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_d2688.dir/build.make:100: cmTC_d2688] Error 1
    gmake[1]: Leaving directory '/Users/dongqishen/Workspace/tvm/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_d2688/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/dongqishen/Workspace/tvm/build/CMakeFiles/CMakeOutput.log".
See also "/Users/dongqishen/Workspace/tvm/build/CMakeFiles/CMakeError.log".

The tutorial said that "add -lc++abi in the LDFLAGS". I didn't know how to do it. Does anyone meet the problem? Thanks for your time.

**Comment by masahi** [comment]
This doesn't look like a TVM-specific problem. Many people are using TVM on M1 without any issues. Please make sure you can use cmake to compile a normal C++ program.
