### ISSUE TITLE
[Flaky Test] `tests/python/frontend/pytorch/test_forward.py::test_argsort`

### ISSUE THREAD

**Issue by shingjan** [apache/tvm#12012]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/pytorch/test_forward.py::test_argsort`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/PR-11994/1/display/redirect

**Comment by driazati** [comment]
This hasn't come up lately afaik, cautiously closing
