### ISSUE TITLE
[CI Image]  Updates to ci_cpu and ci_qemu to reflect CMSIS-NN SHA upgrade

### ISSUE THREAD

**Issue by ashutosh-arm** [apache/tvm#12089]
- [ ] S0. Reason: (https://github.com/apache/tvm/pull/12030)

- [ ] S1. Tag of nightly build: TAG. Docker hub: Don't see it corresponding to following commit in here: https://hub.docker.com/r/tlcpack/ci-cpu

- [ ] S2. The nightly is built on TVM commit: [5ad27ef](https://github.com/apache/tvm/commit/5ad27ef6506b5e50b82ee97f1a0a6aaa5fe0dbbf)

- [ ] S3. Testing the nightly image on ci-docker-staging: 

- [ ] S4. Retag TAG to VERSION:

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the ci_cpu and ci_qemu version on Jenkins

**Comment by ashutosh-arm** [comment]
@driazati I cannot see automatically generated docker image for this change in tlcpackaging on docker hub. I am assuming this has already been automated. Am I missing anything?

**Comment by driazati** [comment]
The CI build on 5ad27ef6506b5e50b82ee97f1a0a6aaa5fe0dbbf should have triggered a Docker image build but it looks like that code is broken, I'll put up a fix sometime soon. After that the tlcpackstaging images should be updated as soon as the build on `main` is done when `docker/*` changes are merged

**Comment by ashutosh-arm** [comment]
Thanks @driazati for quickly looking into this.

**Comment by ashutosh-arm** [comment]
@driazati It looks like https://github.com/apache/tvm/issues/12097 was closed. So, does it mean the issue was fixed and we can get updated docker images quicker?

**Comment by leandron** [comment]
Just checking whether this ticket can be closed, please update.

**Comment by driazati** [comment]
Closing since the images are currently on fae79bbc3e499f3b9f26c9a13743896f948b723d which should include the relevant PR here. Please re-open if this is not the case
