### ISSUE TITLE
[docs] Document the convention around reserving global names and specifying linkage in the IR

### ISSUE THREAD

**Issue by areusch** [apache/tvm#12098]
Raised as part of https://github.com/apache/tvm-rfcs/pull/84, we should document the convention around indicating that GlobalVar and function names are reserved (and consider if this should extend to Var as well). From the community meeting, @tqchen indicates:
>  right now there is an implicit convention: the `name_hint` is not final (it's just an internal-to-compiler concept) and there's a GlobalVar which enforces that there is external linkage type with a fixed name. e.g. if we are splitting the compilation flow, then there is an expectation that when calling into a symbol, the name won't change. another rule: if a function has attribute `kGlobalSymbol`, you cannot change it or even delete it.

adding this to backlog to document

cc @Hzfengsy @hpanda-naut @junrushao @kparzysz-quic

**Comment by tqchen** [comment]
Just to clarify, the main rule is : if a function has attribute kGlobalSymbol, you cannot change the name or delete the function. GlobalVar do not imply a fixed name or linkage.
