### ISSUE TITLE
[ci] CPU integration tests are bottleneck-ing CI

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12109]
The CI runtime has creeped up to around 2.5 hours from 1.8~ish. Looking at https://monitoring.tlcpack.ai/d/hB2FYR87k/build-status?orgId=1, this happened this week after #12030 merged. The second chart shows that the CPU integration steps are taking far longer than the others: 

![image](https://user-images.githubusercontent.com/9407960/179284795-4090b5f9-1dec-408b-aa46-f8981f5193bd.png)

We should increase the CPU integration test shards (probably from `6` to around `10`) to keep runtime down.

cc @Mousius @areusch

**Comment by areusch** [comment]
cc @hpanda-naut for triage

@mikepapadim would you like to take a look at this one?

**Comment by mikepapadim** [comment]
I am having a look into this.

**Comment by mikepapadim** [comment]
this should be done with #12316
