### ISSUE TITLE
[VOTE] Release Apache TVM v0.9.0.rc0

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12103]
Dear TVM community,

This is a call for vote to release Apache TVM version v0.9.0.  This is a major release with many new features and improvements. All users of Apache TVM v0.8 are advised to upgrade. Please see #12102 for any edits you would like to see included in the release notes.

Link to release notes: 
https://github.com/apache/tvm/releases/tag/v0.9.0.rc0

Link to release candidate: 
https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.9.0-rc0/

The vote will be open for at least 72 hours. Everyone is welcomed to vote. Please vote by replying to this thread explicitly.

+1 = approve
+0 = no opinion
-1 = disapprove (provide reason)

NOTE: this thread is being mirrored in dev@

**Comment by masahi** [comment]
+1

**Comment by jroesch** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by tqchen** [comment]
+1 , I checked

Signatures and hashes good
LICENSE, NOTICE
Signatures and hashes
No unexpected binary files
Code compiles and import in python
-----------------------
One minor note, would be great if everyone who voted can also reply the items being checked, it is a good habit to have more pairs of eyes doing spot check on thngs. :)

TQ

**Comment by driazati** [comment]
Thanks everyone! Following the schedule in #11736 the vote thread is closing today with the results in #12133.

**Comment by driazati** [comment]
This release and past releases have included the `rc0` in the top-level folder inside the source release tar. We've pushed a [new RC](https://dist.apache.org/repos/dist/dev/tvm/tvm-0.9.0-rc1/) with all the contents the same except the top level folder, which is named the same thing without the `rc0`. Since the contents are the same (you can verify by comparing the rc1 with rc0 by running `find . -type f -print0 | sort -z | xargs -0 sha512sum | sha512sum` inside the release folder), we are skipping the vote thread for this specific case. If anyone has any comments please let us know and we can push a patch release if necessary.

**Comment by areusch** [comment]
+1 to this as well, i will leave the previously-approved rc0 in the release dir for posterity.
