### ISSUE TITLE
[ci] Add retries to upload to S3

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12136]
Uploading artifacts sometimes fails, we should retry it up to 3 times with a short backoff. Example failure: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3840/pipeline/378

cc @Mousius @areusch

**Comment by areusch** [comment]
cc @hpanda-naut

**Comment by areusch** [comment]
@gigiblender want to take a look at this one?
