### ISSUE TITLE
[Docs]  Clicking on chapters in User Tutorial doesn't do anything

### ISSUE THREAD

**Issue by yurivict** [apache/tvm#12156]
Clicking on large squares [here](https://tvm.apache.org/docs/tutorial/index.html) doesn't have any effect.

Firefox-102.0.1

**Comment by blackkker** [comment]
+1

**Comment by driazati** [comment]
Thanks for reporting! Once https://github.com/tlc-pack/tlcpack-sphinx-addon/pull/8 is merged (that should fix this issue), we can update the version of `tlcpack-sphinx-addon` we use in tvm and this should be fixed on the live website
