### ISSUE TITLE
[RFC][Tracking Issue] Name mangling in IRModules

### ISSUE THREAD

**Issue by gigiblender** [apache/tvm#12181]
This issue is to track progress for `Name mangling in IRModules`

PR: #12066
RFC discussion: https://github.com/apache/tvm-rfcs/pull/84
Forum: https://discuss.tvm.apache.org/t/pre-rfc-name-mangling-in-irmodules/12944/7

**Comment by driazati** [comment]
Closing since the PR is merged, we can re-open if need be
