### ISSUE TITLE
[CI] We need to shard ci_qemu tests 

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#12180]
Working on this PR: https://github.com/apache/tvm/pull/11809
This will increase the workload on ci_qemu and it has timeout issue. So it's time to shard this image like others.

cc @Mousius @areusch @driazati

**Comment by areusch** [comment]
cc @gigiblender can you take a shot at this one? here are some PRs for inspiration:
- first you need to fix up the test script to support sharding similar to https://github.com/apache/tvm/pull/10413/files
- next you need to modify the Jenkinsfile to create 2 shards. there's not a PR that's done this from scratch yet, but there is an [example](https://github.com/apache/tvm/pull/11402/files#diff-e184a2c3547d7b16a189108dd1fcc13062a15ab459594635a1a3692bc598c8f2R7) of adding shards. it should be fairly straightforward once it's clear what to do here.

also cc @driazati
