### ISSUE TITLE
[ci] Build android_rpc fails in CI

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12191]
This has been failing intermittently but with increasing frequency lately:

https://github.com/apache/tvm/runs/7519810828?check_suite_focus=true

cc @Mousius @areusch @argrento

**Comment by cconvey** [comment]
Thanks for reporting this @driazati !

**Comment by argrento** [comment]
Well, need to investigate.

**Comment by areusch** [comment]
can we close this one now?
