### ISSUE TITLE
Develop a tool to keep track of skipped tests in CI

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#12235]
we had multiple instances where code changes resulted in skipping tests in the CI unintentionally. It would be great if we can have a tool which keeps track of the tests. Here are some instances:

- https://github.com/apache/tvm/pull/12223
- We had similar issue with hexagon tests which they were skipped because of a PR

cc @driazati @areusch

**Comment by driazati** [comment]
This is implemented in #12915
