### ISSUE TITLE
Executor Generation

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#123]
The current function generation is great for API functions with few input, but not so great for executor of multiple stages, where some argument(weight) can be preset. A executor interface might be better for these cases
```python
def Executor(object):
    def set_input(self, index, tensor):
          """Set tensor to i-th input"""
          pass
    def run(self):
          """Run computations"""
    def get_output(self, index):
          """Get output to index-th tensor"""
```

**Comment by driazati** [comment]
It has been a while since this PR was updated,  please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated,  please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated,  please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated, @someone please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated, @someone please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated, @someone please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated, @someone please leave a review or address the outstanding comments

**Comment by driazati** [comment]
It has been a while since this PR was updated, @someone please leave a review or address the outstanding comments
