### ISSUE TITLE
[Bug] import tvm before pytorch leads to core dump at the end

### ISSUE THREAD

**Issue by mikeseven** [apache/tvm#12326]
### Expected behavior

order of import should not matter

### Actual behavior

```python
import tvm
import torch
```

At the end, the application quits with
```python
free(): invalid pointer
Aborted (core dumped)
```

However, importing tvm **after** all other imports works
```python
import torch
import tvm
```
To reproduce, there is no need to even do anything with tvm in the code!

### Environment

TVM main branch, same error with latest tags too
- same error built with or without cuda
- same error built with `llvm-config --link-static` or without

Ubuntu 20.04, x86 
tested with clean conda environment with pytorch 1.11 and 1.12 + cudatoolkit

**Comment by masahi** [comment]
This was discussed in https://github.com/apache/tvm/issues/9362 and mitigation documented in https://github.com/apache/tvm/pull/9433.

**Comment by mikeseven** [comment]
yes I used this mitigation but it didn't work.
I sync'd today and rebuild and it now works....

**Comment by zky001** [comment]
yes I meet same bugs and haven't found true reason
