### ISSUE TITLE
[Bug][Relay] TVM generates input name that cannot be imported with the parser

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#12362]
I'm compiling an ONNX model which I realized the input name has this format `input:0`. When I import the model and run it, it works fine, however if I try to import the same Relay text with the parser it will result in error.

cc @gigiblender

**Comment by slyubomirsky** [comment]
Can you write a simple pass that will change ("sanitize") the variable names? I don't know if a colon is treated in any special way by the parser, but you could try replacing them with underscores. I thought the parser did some sanitization of its own and am surprised that this still happens.

**Comment by mehrdadh** [comment]
@slyubomirsky I added a cleanup step in the ONNX frontend to replace `:` with `_`.

**Comment by driazati** [comment]
This seems like it's fixed by #13046, if that's not the case we can re-open this issue
