### ISSUE TITLE
[Flaky Test] `tests/python/unittest/test_tvm_testing_features/TestFixtureCaching.py::test_uncached_count`

### ISSUE THREAD

**Issue by gigiblender** [apache/tvm#12451]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/unittest/test_tvm_testing_features/TestFixtureCaching.py::test_uncached_count`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4040/display/redirect

**Comment by driazati** [comment]
Fixed by #12376
