### ISSUE TITLE
[Flaky Test] `cython.py::tests.python.frontend.darknet.test_forward`

### ISSUE THREAD

**Issue by shingjan** [apache/tvm#12465]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `cython.py::tests.python.frontend.darknet.test_forward`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4062/display/redirect

### Preliminary Report

HTTP error 500 internal error on the url link

cc: @siju-samuel

**Comment by areusch** [comment]
Per @driazati, this can be fixed by following the instructions for [Network Resources](https://tvm.apache.org/docs/contribute/code_guide.html#network-resources) in test. want to take a crack at it?

**Comment by shingjan** [comment]
this should be fixed by https://github.com/apache/tvm/pull/12510
