### ISSUE TITLE
[Flaky Test] `tests/python/frontend/caffe/test_forward.py::test_forward_Alexnet`, `tests/python/frontend/caffe/test_forward.py::test_forward_Inceptionv1`

### ISSUE THREAD

**Issue by shingjan** [apache/tvm#12464]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/caffe/test_forward.py::test_forward_Alexnet`
  - `tests/python/frontend/caffe/test_forward.py::test_forward_Inceptionv1`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4073/display/redirect

### Possible cause

This flakiness seems to be introduced by fetching remote content from non-TVM urls.

cc: @fernchen

**Comment by areusch** [comment]
Per @driazati, this can be fixed by following the instructions for [Network Resources](https://tvm.apache.org/docs/contribute/code_guide.html#network-resources) in test. want to take a crack at it?

**Comment by shingjan** [comment]
This should be fixed by #12510
