### ISSUE TITLE
[Flaky Test] various tests in `tests/python/contrib/test_ethosu/test_codegen.py`

### ISSUE THREAD

**Issue by shingjan** [apache/tvm#12511]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-32]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_tflite_squeeze[ifm_shape2-None-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[1-0-1-0-ifm_shape3-ethos-u55-64]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[0.015-3-0.2-5-ifm_shape3-ethos-u55-128]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4084/display/redirect
  - https://ci.tlcpack.ai/job/tvm/job/main/4093/display/redirect
  - https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4105/pipeline
  - https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4109/pipeline

cc: @lhutton1 @ekalda

**Comment by lhutton1** [comment]
Thanks for reporting @shingjan, I hope to find some time to investigate soon

**Comment by shingjan** [comment]
Hi @areusch would that be possible that we keep this open until Luke can take a look? I believe David's PR only mitigate the issue instead of fixing it. Thanks!

**Comment by areusch** [comment]
oh whooops. that was not intentional!

**Comment by cconvey** [comment]
FYI there's a more recent CI failure that looks related.  Here's the filled-out flaky-test details, but I haven't created a new Issue yet:

These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_unary_elementwise[ifm_shape4-ABS-ethos-u55-32]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_tflite_slice[ifm_shape3-begin3-size3-ethos-u55-128]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4133/display/redirect

**Comment by cconvey** [comment]
Another CI failure: 
### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-32]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[1-0-1-0-ifm_shape3-ethos-u55-64]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_tflite_squeeze[ifm_shape2-None-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[0.015-3-0.2-5-ifm_shape3-ethos-u55-128]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4122/display/redirect

**Comment by cconvey** [comment]
Another CI failure: 
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[1-0-1-0-ifm_shape3-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_unary_elementwise[ifm_shape4-ABS-ethos-u55-128]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_relay_reshape_codegen[ifm_shape5-new_shape5-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-128]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_tflite_slice[ifm_shape3-begin3-size3-ethos-u55-256]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4131/display/redirect

**Comment by cconvey** [comment]
Another CI failure: 
### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-128]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_unary_elementwise[ifm_shape4-ABS-ethos-u55-128]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[1-0-1-0-ifm_shape3-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_tflite_slice[ifm_shape3-begin3-size3-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_relay_reshape_codegen[ifm_shape5-new_shape5-ethos-u55-256]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4132/display/redirect

**Comment by cconvey** [comment]
Another CI failure: 
### Tests(s)

  - `tests/python/contrib/test_ethosu/test_codegen.py::test_binary_add_with_non_4d_shapes[ifm_shape0-ifm2_shape0-ethos-u55-128]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_relay_reshape_codegen[ifm_shape5-new_shape5-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_unary_elementwise[ifm_shape4-ABS-ethos-u55-128]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_ethosu_identity_codegen[1-0-1-0-ifm_shape3-ethos-u55-256]`
  - `tests/python/contrib/test_ethosu/test_codegen.py::test_tflite_slice[ifm_shape3-begin3-size3-ethos-u55-256]`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm/job/main/4135/display/redirect

**Comment by cconvey** [comment]
Just FYI, another occurrence of this CI failure occurred _before_ the bugfix landed on `main`: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4137/pipeline
