### ISSUE TITLE
[CI Image] Remove Vela from ci_cpu

### ISSUE THREAD

**Issue by ekalda** [apache/tvm#12573]
- [x] S0. Reason: Stop downloading dependencies for features that have moved to `ci_cortexm` and to unblock https://github.com/apache/tvm/pull/12456

- [x] S1. Tag of nightly build: 20220824-060145-c15cc5ef6

- [x] S2. The nightly is built on TVM commit: c15cc5ef6

- [x] S3. Testing the nightly image on ci-docker-staging: All the `ci_cpu` tests are passing with that image: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdocker-image-run-tests/detail/docker-image-run-tests/201/pipeline/741/

- [ ] S4. Retag TAG to VERSION:
```
docker pull tlcpackstaging/IMAGE_NAME:TAG
docker tag tlcpackstaging/IMAGE_NAME:TAG tlcpack/IMAGE_NAME:VERSION
docker push tlcpack/IMAGE_NAME:VERSION
```

- [x] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [x] S6. Submit a PR updating the IMAGE_NAME version on Jenkins

**Comment by leandron** [comment]
This is being dealt with in the context of https://github.com/apache/tvm/pull/12738

**Comment by leandron** [comment]
Closed by https://github.com/apache/tvm/pull/12738
