### ISSUE TITLE
[VOTE] Commit Messages RFC

### ISSUE THREAD

**Issue by areusch** [apache/tvm#12583]
This is a formal vote thread to determine committer and PMC support for https://github.com/apache/tvm-rfcs/pull/88. Replying +1 here means you support the RFC and we should merge it. This vote thread is due to the fact that the RFC proposes a change in the way the community operates (namely the standards by which we commit code). This also signals the final comment period on that RFC, which will conclude with this vote. All are welcomed to vote here, though members of the PMC have binding votes which determine the outcome of the RFC.

We'll leave this vote thread open for a week, and make a decision then.

Thanks,
Andrew

Please vote:
+1 I support the RFC
0 I'm happy either way
-1 I do not support the RFC and it should not be merged.

@apache/tvm-committers

**Comment by leandron** [comment]
+1

Disclaimer: I’m a co-author of the original RFC

**Comment by tmoreau89** [comment]
+1 (binding)

Thierry

**Comment by csullivan** [comment]
+1

**Comment by tqchen** [comment]
+1

TQ

**Comment by driazati** [comment]
+1

**Comment by Hzfengsy** [comment]
+1

**Comment by junrushao** [comment]
+1 (binding)

**Comment by masahi** [comment]
+1

**Comment by AndrewZhaoLuo** [comment]
0

**Comment by manupak** [comment]
+1

**Comment by lhutton1** [comment]
+1

**Comment by mbaret** [comment]
+1

**Comment by kparzysz-quic** [comment]
0

**Comment by Lunderberg** [comment]
+1

**Comment by zxybazh** [comment]
0

**Comment by areusch** [comment]
The 7-day voting period has concluded. The votes are as follows:

+1:
Leandro
Thierry
Chris Sullivan
TQ
David
Siyuan
Junru
Masa
Manupa
Luke
Matthew Barrett
Eric Lunderberg

0:
Andrew Luo
Krzysztof
Xiyou

-1:
none

The vote has passed.

**Comment by tvm-archiver** [comment]
+1 (binding)

In which circumstances do we need to vote btw? I suppose it’s an approved
RFC and didn’t see objection.
