### ISSUE TITLE
[CI Problem] A problem occurred configuring root project 'android_rpc'.

### ISSUE THREAD

**Issue by cconvey** [apache/tvm#12599]
Possibly related: another `android_rpc` failure from several weeks ago: https://github.com/apache/tvm/issues/12191

### Branch/PR Failing

https://github.com/apache/tvm/commit/8174d082e8168db9ad63826c9d68aee8c76c7090

### Jenkins Link

https://github.com/apache/tvm/runs/7983481668?check_suite_focus=true

### Flakiness

No

**Comment by driazati** [comment]
closing since this hasn't happened in a while
