### ISSUE TITLE
[CI Problem] [docker] Pip package installation in cortexm image

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#12608]
Using any other docker image we can easily install extra packages by running a command: `sudo pip3 install XX`
and then it would be available in the python environment.

However, in Cortexm image installing the package with `sudo pip3 install` or `pip3 install --user` would end up in a different python env. My guess is because of this line that we have for cortexm and riscv images:

https://github.com/apache/tvm/blob/main/docker/Dockerfile.ci_cortexm#L37
https://github.com/apache/tvm/blob/main/docker/Dockerfile.ci_riscv#L37

cc @areusch

**Comment by areusch** [comment]
i was able to solve this by adding a dedicated venv group. i'll roll that into my venv PR

**Comment by mehrdadh** [comment]
I tested the hexagon docker image, the issue still exists. Perhaps the issue is related to user not having permission on python packages installation path
