### ISSUE TITLE
[CI Problem] failed docs push to https://github.com/apache/tvm-site.git 

### ISSUE THREAD

**Issue by cconvey** [apache/tvm#12600]
### Branch/PR Failing

https://github.com/apache/tvm/commit/5cef6bf559265e74b84504ed2e190f29f5c5bf33
https://github.com/apache/tvm/commit/13ebbfb37f8cec1da71d88fbcbecdd4ad4d24dcc

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4129/pipeline/
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4144/pipeline/

### Flakiness

Multiple commits (see above)

**Comment by driazati** [comment]
This usually happens since there is a merge race to update the docs between two commits. The best way to fix would be to check the hash in this file and:
* if it's newer: give up since the docs have already been built and pushed including this commit
* if it's older: force push the new changes

**Comment by cconvey** [comment]
Another occurrence: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4167/pipeline
