### ISSUE TITLE
[Flaky Test] segfault in `tests/python/contrib/test_ethosu/test_codegen.py::test_mean`

### ISSUE THREAD

**Issue by cconvey** [apache/tvm#12634]
### Branch/PR Failing

https://github.com/apache/tvm/commit/534412896e6d39ee4f830d63370d02e8e5f09050

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4188/pipeline

### Flakiness

We've been tracking other ethos-u flakiness in https://github.com/apache/tvm/issues/12511, but I'm not sure if this occurrence is actually related to ethos-u.

**Comment by ekalda** [comment]
An update on that issue of random codegen tests intermittently segfaulting in CI that has been causing problems for a while now - it happens during a call to Vela and Vela folks have tracked it down now and the fix will be available in their next release. So when we upgrade the Docker with the new version, it should go away and we can re-enable the tests.

**Comment by lhutton1** [comment]
closing this as the version of Vela was updated and the test was re-enabled
