### ISSUE TITLE
[VOTE] Establish TVM Unity Connection Technical Strategy

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#12651]
Dear community:

This is a formal vote on [TVM unity connection technical strategy](https://github.com/apache/tvm-rfcs/pull/91). We had great discussions and feedback in the [discuss thread](https://discuss.tvm.apache.org/t/establish-tvm-unity-connection-a-technical-strategy/13344) 

Vote:
+1
0 - I don't feel strongly about it, but don't object
-1 - because..

The VOTE will open for a week.

This thread is mirrored to dev@, please vote by replying to this thread

cc @Hzfengsy @junrushao

**Comment by YuchenJin** [comment]
+1

**Comment by tvm-archiver** [comment]
+1

**Comment by junrushao** [comment]
+1 (binding)

**Comment by Hzfengsy** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by yzh119** [comment]
+1

**Comment by csullivan** [comment]
+1

**Comment by sunggg** [comment]
+1

**Comment by masahi** [comment]
+1

**Comment by areusch** [comment]
-1 (binding veto)

I agree with @leandron that Establish TVM Unity Connection Technical Strategy RFC is heavily centered around Relax RFC. Additionally, while this RFC stops short of endorsing the Relax RFC as the future direction of TVM, it very [explicitly discusses](https://github.com/apache/tvm-rfcs/blob/d06a72546b8d169da354c5796ca250baca9970e4/rfcs/0091-establish-tvm-unity-connection.md#evolving-default-build) those aspirations. Therefore I do not agree that this RFC is separate from Relax RFC and therefore do not think a VOTE thread is appropriate at this time.

I want to be clear that I am not disagreeing with the technical direction here, but that I don't believe it is yet time to VOTE. I would happily change my vote should more consensus develop in the community.

**Comment by tqchen** [comment]
Thanks @areusch , the particular section that you described was explicitly listed as "future opportunities" and is not part of the RFC which may or may not be executed. As per stated in the text 

```
This section describes possible approaches to evolve the default build to leverage more of unity components. Note again that this is only a discussion of possible approach is not part of the RFC, but only to bring possible relevant context of future opportunities.
The detailed discussions about the exact approach shall happen in dedicated RFCs for each incremental change to the default build.
```

**Comment by zxybazh** [comment]
+1

**Comment by junrushao** [comment]
+1 (binding)

**Comment by LeshengJin** [comment]
+1

**Comment by cyx-6** [comment]
+1

**Comment by spectrometerHBH** [comment]
+1

**Comment by ganler** [comment]
+1

**Comment by comaniac** [comment]
+1

**Comment by ZihengJiang** [comment]
+1 (binding)

**Comment by shingjan** [comment]
+1

**Comment by mbaret** [comment]
+1

I'd love for us to have more clarity on the future of Relax and Relay, but I don't think vetoing this proposal is now progressing that goal any further. Instead, we're seeing substantial fracturing in the development community, with a number of branches and forks (including production repos) spinning up to support Relax-related efforts. This pulls mindshare and resources away from the main repo (CI/testing/fixes/documentation), ultimately to the detriment of anyone still working there.

**Comment by areusch** [comment]
0

Ultimately I'd prefer to get more clarity on this direction, but given we are getting that through the new `unity` branch, it makes sense to adopt this proposal as the "goal" given that progress on the unity branch will further illuminate the details.

**Comment by Mousius** [comment]
0

Does this vote serve any purpose given the `unity` work is continuing regardless of the outcome?

**Comment by csullivan** [comment]
+1

**Comment by lxiongh** [comment]
+1
