### ISSUE TITLE
[Bug] its fuzziness that  the num of outputs per node  > 1

### ISSUE THREAD

**Issue by zenyuhao** [apache/tvm#12672]
https://github.com/apache/tvm/blob/main/src/runtime/graph_executor/graph_executor.cc#L100

my model has 7 outputs of last node  named "reshap_op"
but  there is only one node-name in node map,
i think outputs_map should store out_tensor_index , should be  "reshape_nop:0" as tensorflow does

~~~

>>> c = m.get_function("default")(tvm.cpu(0))
reshape_nop:0
reshape_nop:1
reshape_nop:2
reshape_nop:3
reshape_nop:4
reshape_nop:5
reshape_nop:6

>>> c.get_function("get_output_index")("reshape_nop")
6

~~~

Please don’t hesitate to correct me if I’m wrong. Many thanks in advance.

**Comment by cery999** [comment]
I can support this feature. but I found some problem.
if there is one result in onnx ,the name should be output:0 or output? 
and can you support a case to reproduce it, so I can add it to ci?

**Comment by zenyuhao** [comment]
thanks for reply
In tensorflow graph, output of graph node is naming by `op_name:output_index`, so at least  there alwasy be 0 after outout.
im not sure that the same design in onnx, and i think the stable way to get output by output index is offical in tvm doc,
even though get_output_by_name is not stable in some situation, here is simple fix  which works well


```cpp
  for (size_t i = 0; i < outputs_.size(); i++) {
    const uint32_t nid = outputs_[i].node_id;
    std::string& name = nodes_[nid].name;
    std::stringstream ss;
    ss << name << ":" << i;
    output_map_[ss.str()] = i;
  }
```
