### ISSUE TITLE
[Tracking Issue] Commit Message Guideline

### ISSUE THREAD

**Issue by gromero** [apache/tvm#12690]
This issue is to track [RFC-0088](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0088-commit-message-guideline.md) progress.

Main author(s): @gromero @leandron

**Comment by gromero** [comment]
PR submitted for review (https://github.com/apache/tvm/pull/12689)

**Comment by leandron** [comment]
With https://github.com/apache/tvm/pull/12689 now merged, I'm also closing this one.
