### ISSUE TITLE
[Bug] import tvm error[correctly install]

### ISSUE THREAD

**Issue by wangzy0327** [apache/tvm#12709]
Expected behavior
What you were expecting

I have compiled tvm source files build the shared library from the C++ codes .

Setup for Python Package

![image](https://user-images.githubusercontent.com/22990858/188569916-8c7ff7b1-4956-46dd-8076-37bc0928cc6f.png)

Environment
OS version:
Ubuntu 18.04.6 LTS \n \l

TVM version:
TVM 0.9.0 commid-id : https://github.com/apache/tvm/commit/d361585965b95acfb35563b92a2011fe8059876c

Any environment details, such as: Operating System, TVM version, etc

Steps to reproduce

I want to use tvm with pytorch . So I use conda install pytorch 1.10.

I verify tvm environment but get Error.

![image](https://user-images.githubusercontent.com/22990858/188570649-cb811df7-dda2-4521-b742-2ac6aa5a71bd.png)

Preferably a minimal script to cause the issue to occur.

**Comment by masahi** [comment]
`pip install decorator`
