### ISSUE TITLE
[Bug] tvmc convert model Error

### ISSUE THREAD

**Issue by wangzy0327** [apache/tvm#12722]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

I want to convert onnx model to tvm input

### Actual behavior

![image](https://user-images.githubusercontent.com/22990858/188827148-d79fabdb-0072-4005-8b0e-ea80675ec0ff.png)

### Environment

OS :Ubuntu 18.04
TVM:0.9
onnx:1.12.0
protobuf:3.20.1

### Steps to reproduce

I use tvm follow the link

https://chinese.tvm.wiki/tutorial/tvmc_command_line_driver.html

**Comment by leandron** [comment]
Hi @wangzy0327. I'm not really sure on where that link you sent comes from. It seems a translation of an old version of TVM documentation, which isn't really expected to work nowadays. So I can't offer support based on that documentation.

I suggest you follow the guidance on the official documentation: https://tvm.apache.org/docs/tutorial/tvmc_command_line_driver.html

**Comment by wangzy0327** [comment]
> https://tvm.apache.org/docs/tutorial/tvmc_command_line_driver.html

I have tryied to follow the guidance on the official documentation but it also get error.
https://tvm.apache.org/docs/tutorial/tvmc_command_line_driver.html

onnx, onnxoprimizer is installed
![image](https://user-images.githubusercontent.com/22990858/189049693-8405e101-1bdd-4d9b-b0b2-fca7111c91a1.png)

![image](https://user-images.githubusercontent.com/22990858/189049760-246be34b-abc4-47f5-9b7f-bbed34acba69.png)

**Comment by masahi** [comment]
No actionable item from our side.
