### ISSUE TITLE
[ci] Re-enable GPU other build

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12739]
See #12644 for context

cc @Mousius @areusch @gigiblender

**Comment by masahi** [comment]
Can we close this now, after https://github.com/apache/tvm/pull/13366?

**Comment by driazati** [comment]
The build was broken before so the second round in that PR wasn't actually running with the new changes, https://github.com/apache/tvm/blob/main/ci/jenkins/templates/gpu_jenkinsfile.groovy.j2#L56-L57 still has them disabled so we can't close this yet

**Comment by areusch** [comment]
@mikepapadim has a few cycles to look at this
