### ISSUE TITLE
[VOTE] Issue Triage Workflow RFC

### ISSUE THREAD

**Issue by areusch** [apache/tvm#12743]
This is a formal vote thread to determine committer and PMC support for https://github.com/apache/tvm-rfcs/pull/93. Replying +1 here means you support the RFC and we should merge it. This vote thread is due to the fact that the RFC proposes a change in the way the community operates (namely the way we organize issues as a community). This also signals the final comment period on that RFC, which will conclude with this vote. All are welcomed to vote here, though members of the PMC have binding votes which determine the outcome of the RFC.

We'll leave this vote thread open for a week, and make a decision then.

Thanks,
Andrew

Please vote:
+1 I support the RFC
0 I'm happy either way
-1 I do not support the RFC and it should not be merged.

@apache/tvm-committers

**Comment by tkonolige** [comment]
+1

**Comment by driazati** [comment]
+1

**Comment by leandron** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by gromero** [comment]
+1

**Comment by masahi** [comment]
+1

**Comment by Mousius** [comment]
+1

**Comment by zxybazh** [comment]
+1

**Comment by tqchen** [comment]
+1

TQ

**Comment by areusch** [comment]
+1 (binding)

**Comment by areusch** [comment]
The vote period has concluded. The votes are as follows:

+1
Tristan
David
Leandro
Wuwei
Gustavo
Masa
Chris S.
Xiyou
TQ
Andrew

0:
none

-1:
none

The vote has passed, and the RFC is accepted. Thanks everyone!
