### ISSUE TITLE
[Bug] How to register op by c++.

### ISSUE THREAD

**Issue by loveppdog** [apache/tvm#12767]
I want to register support op by c++ to implement the following func like python code.

```
@tvm.ir.register_op_attr("nn.avg_pool2d","dnnl")
 def avg_pool2d_check(expr):
     attrs, args = expr.attrs, expr.args
     data_typ = args[0].checked_type
     rank = len(data_typ.shape)
     if rank < 3 or rank > 4 or data_typ.dtype != "float32":
              return False
     if attrs.layout != "NCHW":
            return False
return true
```

But I can't get expr in C++ by using PackedFunc (TVMArgs args, TVMRetValue* rv).
How to get expr from TVMArgs ?

**Comment by vinx13** [comment]
You can register typed packed func using `set_body_typed` so that you don't have to accept `TVMArgs`
