### ISSUE TITLE
[release] v0.10.0 Release Schedule

### ISSUE THREAD

**Issue by AndrewZhaoLuo** [apache/tvm#12832]
As discussed in https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md, releases will happen roughly every three months. I have been put in charge for this one. This thread is meant to discuss the release schedule. 

We will do a branch cut soon but accept cherry-picked changes for a couple weeks. 

See the [release steps](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0067-quarterly-releases.md#reference-level-explanation) for details as well as the [TVM release process docs](https://tvm.apache.org/docs/contribute/release_process.html).

The current schedule is:
- [x] September 20 - branch cut
   * we will create a `v0.10.0` branch from `main` on this day
   * Done: https://github.com/apache/tvm/tree/v0.10.0
   * Last commit: https://github.com/apache/tvm/commit/b051cad9f40671675d7101ac510b6f733cff0bc2
- [x] September 27 - cherry-picking soft deadline
   * during this time any reasonable change can be merged, comment on this issue with the commit you would like added to the release branch
- [x] September 30 - cherry-picking hard deadline
    * during this time only critical changes will be merged, comment on this issue with the commit you would like added to the release branch as well as the reasoning for adding it
- [x] ~~October 4~~ October 11- release vote opened (https://github.com/apache/tvm/issues/13026)
    - [x] Bump up TVM version on main: https://github.com/apache/tvm/pull/13036 
    - [x] https://github.com/apache/tvm/issues/13101
- [x] ~~October 11~~ October 17- release published

Keep in mind this schedule is tentative and may change as we progress through the process. 

A new issue will be made shortly before release vote detailing the release notes: https://github.com/apache/tvm/issues/12979

cc @driazati @areusch @leandron

**Comment by vinx13** [comment]
would be great to have https://github.com/apache/tvm/commit/7aef584c0f8fb3b516afde3fb5fac9c2d0969c0a cherry-picked

**Comment by areusch** [comment]
I'm hoping to land https://github.com/apache/tvm/pull/12880 shortly, will update this thread when it does so we can cherry-pick it.

**Comment by areusch** [comment]
#12880 is ready to cherry-pick

**Comment by areusch** [comment]
if it's not too late, could https://github.com/apache/tvm/pull/12856 get cherry-picked as well?

**Comment by zhyncs** [comment]
@Hzfengsy @YuchenJin Hi TVM genius, when will relax be merged to tvm main upstream?

**Comment by Hzfengsy** [comment]
@zhyncs Thanks for your interest. Relax is at the RFC stage (https://github.com/apache/tvm-rfcs/pull/89). And we will upstream it when the RFC passes.

**Comment by Johnson9009** [comment]
Does the release do more extra testing than the branch main?
In general, the release process contains two kinds of works, the first one is arrangement, like we have done here, e.g, release note, license confirmation, ..., the other one is testing, some company or organization may use the work "sign off", the full test suite will be confirmed to meet the release requirement.
My question is that do we have the extra "sign off" testing? 
@AndrewZhaoLuo, @driazati, @tqchen  Thanks.

**Comment by Johnson9009** [comment]
@driazati Understand, thanks.

**Comment by AndrewZhaoLuo** [comment]
Release done, thanks folks!
