### ISSUE TITLE
[Bug] target WebGPU cannot enable spirv support

### ISSUE THREAD

**Issue by yanghaku** [apache/tvm#12853]
When I compile the model with target ```' webgpu -keys=webgpu,gpu -max_num_threads=256 '; runtime = ' llvm --system-lib -mtriple=wasm32-emscripten -mattr=+bulk-memory '```, I get the error:  ```Check failed: target->kind->device_type == kDLVulkan (15 vs. 7) : SPIRVSupport can only be checked for vulkan device type```.

I saw the source code in [```src/target/spirv/spirv_support.cc L35```](https://github.com/apache/tvm/blob/d4e3207cca1bae532e6e616eca2e80191e45b437/src/target/spirv/spirv_support.cc#L35)

```c++
SPIRVSupport::SPIRVSupport(tvm::Target target) {
  ICHECK_EQ(target->kind->device_type, kDLVulkan)
      << "SPIRVSupport can only be checked for vulkan device type";

  if (target->GetAttr<Integer>("vulkan_api_version")) {
    vulkan_api_version = target->GetAttr<Integer>("vulkan_api_version").value().IntValue();
  }
......
```

Does the assert check not take into account the situation of the webgpu?

**Comment by yanghaku** [comment]
when I change the assert check to:
```c++
  ICHECK_EQ(target->kind->device_type == kDLVulkan || target->kind->device_type == kDLWebGPU, true)
      << "SPIRVSupport can only be checked for vulkan or WebGPU device type";
```

Compiling the model is successful.

**Comment by masahi** [comment]
Welcome to send a PR.
