### ISSUE TITLE
[Bug] Convert Model failed due to dynamic Split, but it's not 

### ISSUE THREAD

**Issue by MeJerry215** [apache/tvm#12885]
Convert Conformer Onnx Model Failed Due to Dynamic Split.
Below picture are the origin 
![image](https://user-images.githubusercontent.com/53092165/191945952-28716acb-de27-423a-a816-83f78f1b0a10.png)
When I using onnx frontend import this model , something error.
![image](https://user-images.githubusercontent.com/53092165/191946155-21fe398c-4fcc-4177-9e5b-696ad6a6c9b6.png)

Also I try to pdb
![image](https://user-images.githubusercontent.com/53092165/191946226-2bf9f48d-8242-4a36-8901-816fbccd4d19.png)
And the input[1] is a var, but the constant value in params.

(https://github.com/apache/tvm/blob/d80ce6b1ba5439dbe0437be6e37121844f87a113/python/tvm/relay/frontend/onnx.py#L1900)

why here doest not check the var name in the params?

### Expected behavior

convert split success.

### Actual behavior

convert split failed

### Steps to reproduce

onnx export graph with split

**Comment by shengxinhu** [comment]
you should set freeze_params = True

**Comment by masahi** [comment]
Please try `freeze_params = True` as suggested. Without a reproducible script, there is no actionable item from our side.
