### ISSUE TITLE
[Flaky Test] python-integration-contrib-test_ethosu-shard-5-ctypes failed on PR with unrelated changes

### ISSUE THREAD

**Issue by janetsc** [apache/tvm#12933]
I'm seeing a CI failure on python-integration-contrib-test_ethosu-shard-5-ctypes: tests/python/contrib/test_ethosu for Cortex-M5 on this PR:  https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-12918/2/pipeline.  

A previous run was successful, and the only thing I changed was specific to Hexagon.  

Full logs are here:  https://ci.tlcpack.ai/blue/rest/organizations/jenkins/pipelines/tvm/branches/PR-12918/runs/2/nodes/481/steps/1328/log/?start=0.

**Comment by driazati** [comment]
thanks for reporting! looks like we've seen this before (#12841) so I filed a PR to disable this test. Closing this issue for now to consolidate on #12841
