### ISSUE TITLE
[CI Problem] Mac and Windows builders failing with missing python package

### ISSUE THREAD

**Issue by joshherr-quic** [apache/tvm#12967]
### Branch/PR Failing

https://github.com/apache/tvm/pull/12931

### Jenkins Links

https://github.com/apache/tvm/actions/runs/3147975048/jobs/5118019253
https://github.com/apache/tvm/actions/runs/3147975048/jobs/5118019200

### Flakiness

Windows and Mac builders failing with error:
ImportError: Error importing plugin "tvm.testing.plugin": No module named 'synr'

**Comment by driazati** [comment]
The windows/mac builds use conda to install dependencies each time they run: https://github.com/apache/tvm/blob/main/conda/build-environment.yaml, you should be able to add `synr` somewhere there to get #12931 working

**Comment by joshherr-quic** [comment]
Added synr to conda/build-environent.yaml. CI builders completing now
