### ISSUE TITLE
[Bug] FQ2I Pass May Duplicates Operations

### ISSUE THREAD

**Issue by AndrewZhaoLuo** [apache/tvm#12977]
FQ2I can duplicate operations. More specifically, if an operation dominates the quantize in two QDQ regions, the operation can be duplicated.

### Expected behavior

See this [script](https://github.com/AndrewZhaoLuo/TVM-Sandbox/blob/main/quantization/issues_with_fq2i_pass.py#L93)  (use layers=1) where we want to convert the following fake quantized graph:

```
def @main(%input_var: Tensor[(1, 512, 512), float32] /* ty=Tensor[(1, 512, 512), float32] */) -> Tensor[(1, 512, 512), int8] {
  %0 = qnn.quantize(%input_var, 0.025f /* ty=float32 */, 1 /* ty=int32 */, out_dtype="int8") /* ty=Tensor[(1, 512, 512), int8] */;
  %1 = qnn.dequantize(%0, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), float32] */;
  %2 = mean(%1, axis=[-1], keepdims=True) /* ty=Tensor[(1, 512, 1), float32] */;
  %3 = subtract(%2, %1) /* ty=Tensor[(1, 512, 512), float32] */;
  %4 = sqrt(%3) /* ty=Tensor[(1, 512, 512), float32] */;
  %5 = qnn.quantize(%4, 0.025f /* ty=float32 */, 1 /* ty=int32 */, out_dtype="int8") /* ty=Tensor[(1, 512, 512), int8] */;
  %6 = qnn.dequantize(%5, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), float32] */;
  %7 = add(%6, %4) /* ty=Tensor[(1, 512, 512), float32] */;
  qnn.quantize(%7, 0.025f /* ty=float32 */, 1 /* ty=int32 */, out_dtype="int8") /* ty=Tensor[(1, 512, 512), int8] */
}
```
We expect a graph like:
```
def @main(%input_var: Tensor[(1, 512, 512), float32] /* ty=Tensor[(1, 512, 512), float32] */) -> Tensor[(1, 512, 512), int8] {
  %0 = qnn.quantize(%input_var, 0.025f /* ty=float32 */, 1 /* ty=int32 */, out_dtype="int8") /* ty=Tensor[(1, 512, 512), int8] */;
  %1 = cast(%0, dtype="int32") /* ty=Tensor[(1, 512, 512), int32] */;
  %2 = mean(%1, axis=[-1], keepdims=True) /* ty=Tensor[(1, 512, 1), int32] */;
  %3 = cast(%2, dtype="int8") /* ty=Tensor[(1, 512, 1), int8] */;
  %4 = qnn.mul(%3, %0, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */;
  %5 = qnn.sqrt(%4, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */;
  qnn.add(%4, %5, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */
}
```

### Actual behavior

We instead get:
```
def @main(%input_var: Tensor[(1, 512, 512), float32] /* ty=Tensor[(1, 512, 512), float32] */) -> Tensor[(1, 512, 512), int8] {
  %0 = qnn.quantize(%input_var, 0.025f /* ty=float32 */, 1 /* ty=int32 */, out_dtype="int8") /* ty=Tensor[(1, 512, 512), int8] */;
  %1 = cast(%0, dtype="int32") /* ty=Tensor[(1, 512, 512), int32] */;
  %2 = mean(%1, axis=[-1], keepdims=True) /* ty=Tensor[(1, 512, 1), int32] */;
  %3 = cast(%2, dtype="int8") /* ty=Tensor[(1, 512, 1), int8] */;
  %4 = qnn.subtract(%3, %0, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */;
  %5 = cast(%0, dtype="int32") /* ty=Tensor[(1, 512, 512), int32] */;
  %6 = mean(%5, axis=[-1], keepdims=True) /* ty=Tensor[(1, 512, 1), int32] */;
  %7 = cast(%6, dtype="int8") /* ty=Tensor[(1, 512, 1), int8] */;
  %8 = qnn.subtract(%7, %0, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */;
  %9 = qnn.sqrt(%4, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */;
  %10 = qnn.sqrt(%8, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */;
  qnn.add(%9, %10, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */, 0.025f /* ty=float32 */, 1 /* ty=int32 */) /* ty=Tensor[(1, 512, 512), int8] */
}
```

Note there are now 2 mean operations (which are otherwise identical).

### Environment

TVM Version Used: d4bf9ecf5524d265916ac7b860b0027f5eee5c49
Though it should still fail on the latest versions.

### Steps to reproduce

See the above script

### Explanation
The main issue is the graph uses `MixedModeMutator` which rewrites nodes in topological order. Internally, it memoizes rewritten nodes in the original (pre) graph with the original node with rewritten inputs (post graph). 

When a QDQ region is identified, the post graph is rewritten from a fake quantized to quantized form. 

What occurs is when there is a common subgraph in two QDQ regions, e.g.:

![image](https://user-images.githubusercontent.com/13855451/193699871-2e2320df-f3b0-4123-aebf-81589da644d7.png)

In this case, because the internal memo in `MixedModeMutator` is not updated after quantizing a subgraph region, the QDQ graph will reference nodes in the pre graph. The internal memo is only updated properly for `quantize` ops which mark the end of quantize regions.

As a result, the pre graph will have subgraphs which are quantized multiple times as the `quantize` ops which mark the boundaries are different and other nodes map back to the pre graph in the internal memo.

What would prevent this is properly updating the internal memo in `MixedModeMutator`. However, this has many challenges which I have identified:
- We need to memoize every node in the pre graph with the post graph
- To maintain proper typing, we need to insert many Q/DQs (as the post graph requires FP32 inputs usually)
   - This breaks the AffineType map stored.
- The QDQ mutator operates on the post graph, meaning to properly update the memo, we likely need to make sure all nodes in the pre graph are in the memo in a rewritten form (right now this is only done ).
- You need to give the QDQ mutator information about the memo in the `MixedModeMutator` to avoid extraneous ops.

It's probably possible, but is a lot of indirection.

### Proposed Solution
The sketch to this is relatively simple. This is basically a caching problem, if we see a subgraph we already have a quantized version of, we want to reuse the operations in that graph.

We want the internal memo of `MixedModeMutator` to map each node in the pre graph to a quantized version of that node if possible therefore. To do this, we can calculate which quantization regions each node in the graph belong to before hand. Then, we can mutate individual nodes using the registered FQ2I function for each node and memozie the results in `MixedModeMutator`.

There is a subtle difference between this and the current implementation. If we look at regions 1 and 2 in the image above, they could have different QParams. If the QParams are too different, then perhaps reusing the memoized result for region 1 does not make sense for region 2. The current implementation gets around this by just duplicating the region and redoing things with the proper QParams.

I think however this is a very rare edge case, and think using requantizes between memoized regions will be sufficient.

### Alternatives
CSE Pass should eliminate this but does not appear to.

**Comment by AndrewZhaoLuo** [comment]
cc @mbrookhart @masahi 

This is potentially an issue. Please be aware of it by manually verifying models. It does not appear CSE pass eliminates this.

**Comment by mbrookhart** [comment]
I don't know why CSE doesn't remove this, if we can fix the pass, I think that would be cleaner. That being said, the memoization is FQ2I probably isn't a bad idea.
