### ISSUE TITLE
Build TVM on MacOS failed

### ISSUE THREAD

**Issue by caifeiy** [apache/tvm#12987]
Only set USE_LLVM=ON

`[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/create_primfunc.cc.o
/Users/ycf/Desktop/code/tvm/src/te/autodiff/ad_simplify.cc:542:29: error: 'value' is unavailable: introduced in macOS 10.13
        return var_pair_opt.value().first;
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/optional:954:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
/Users/ycf/Desktop/code/tvm/src/te/autodiff/ad_simplify.cc:568:29: error: 'value' is unavailable: introduced in macOS 10.13
        return var_pair_opt.value().second;
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/optional:954:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
/Users/ycf/Desktop/code/tvm/src/te/autodiff/ad_simplify.cc:595:29: error: 'value' is unavailable: introduced in macOS 10.13
        return var_pair_opt.value().first;
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/optional:954:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
/Users/ycf/Desktop/code/tvm/src/te/autodiff/ad_simplify.cc:622:29: error: 'value' is unavailable: introduced in macOS 10.13
        return var_pair_opt.value().second;
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/optional:954:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
4 errors generated.
make[2]: *** [CMakeFiles/tvm_objs.dir/src/te/autodiff/ad_simplify.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/cross_thread_reduction.cc.o
make[1]: *** [CMakeFiles/tvm_objs.dir/all] Error 2
make: *** [all] Error 2`

[Environment]
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.3.0
Thread model: posix

Homebrew LLVM version 15.0.1
Optimized build.
Default target: arm64-apple-darwin21.3.0
Host CPU: apple-m1

Any help would be appreciated.

**Comment by masahi** [comment]
It compiles fine on my environment using clang 14. Maybe the older Apple clang doesn't have complete support for `std::optional`. If you google "error: 'value' is unavailable: introduced in macOS 10.13" you see many reports.

```
% clang --version
Homebrew clang version 14.0.6
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
% which clang
/opt/homebrew/opt/llvm/bin/clang
```
