### ISSUE TITLE
[Bug][MetaSchedule] Compute-At DataType Mismatch

### ISSUE THREAD

**Issue by zxybazh** [apache/tvm#12997]
I noticed a data type issue that can be triggered when applying compute-at, causing invalid expression in TIR script with incompatible datatype, thus failure in post processors and build.

To reproduce simple run this [script](https://gist.github.com/zxybazh/265b2996e736128eb78c29c94c7a35d3) would work. It can build successfully before schedule but fails with a data type mismatch error after a compute-at scheduling.

cc @Hzfengsy @junrushao1994

**Comment by masahi** [comment]
Does this issue still exist? Your test script doesn't work due to the MS API change.

**Comment by zxybazh** [comment]
Yes, the issue is still there, I changed the script (remove `TuneConfig` import) and it can work now.

**Comment by masahi** [comment]
The PR https://github.com/apache/tvm/pull/13327 works at `CreatePrimFunc` level and would change the generated TVMScript module. So we need to regenerate this TVMScript to verify that the PR fixes this issue.

**Comment by zxybazh** [comment]
Cannot reproduce, close for now.
