### ISSUE TITLE
[Docs] Compile tests error in `Installing TVM` chapters

### ISSUE THREAD

**Issue by liangzelang** [apache/tvm#13021]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Documentation Title & Type

Include the title of the document (e.g. "Getting Started with TVM"), and the type of documentation (e.g. user docs, developer docs, tutorials)

**Installing TVM -> Install from Source -> Enable C++ Tests**

### Additions/Changes Requested

If an RFC/discuss post exists, link it here.

Otherwise, specify what actions should be taken to provide additional clarity/readability/reproducibility to the document. Include code snippets from the previous documentation if applicable.

when I use `./tests/scripts/task_cpp_unittest.sh` command to compile C++ tests, but get errors below:
```
lzlang@YH-202006201754:~/code/tvm$ ./tests/scripts/task_cpp_unittest.sh
+ '[' 0 -gt 0 ']'
+ '[' -n '' ']'
+ BUILD_DIR=build
+ source tests/scripts/setup-pytest-env.sh
++ set +u
++ [[ ! -z '' ]]
++ export 'PYTEST_ADDOPTS=-s -vv '
++ PYTEST_ADDOPTS='-s -vv '
++ set -ux
+++ pwd
++ export TVM_PATH=/home/lzlang/code/tvm
++ TVM_PATH=/home/lzlang/code/tvm
++ export PYTHONPATH=/home/lzlang/code/tvm/python
++ PYTHONPATH=/home/lzlang/code/tvm/python
++ export TVM_PYTEST_RESULT_DIR=/home/lzlang/code/tvm/build/pytest-results
++ TVM_PYTEST_RESULT_DIR=/home/lzlang/code/tvm/build/pytest-results
++ mkdir -p /home/lzlang/code/tvm/build/pytest-results
++ pytest_errors=()
++ trap cleanup 0
+ export LD_LIBRARY_PATH=lib:
+ LD_LIBRARY_PATH=lib:
++ pwd
+ export VTA_HW_PATH=/home/lzlang/code/tvm/3rdparty/vta-hw
+ VTA_HW_PATH=/home/lzlang/code/tvm/3rdparty/vta-hw
+ export TVM_BIND_THREADS=0
+ TVM_BIND_THREADS=0
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ python3 tests/scripts/task_build.py --sccache-bucket tvm-sccache-prod --cmake-target cpptest --build-dir build
[tests/scripts/task_build.py:63 INFO] Not using sccache, reason: 'sccache' executable not found
[ci/scripts/cmd_utils.py:56 INFO] + cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "tests/scripts/task_build.py", line 79, in <module>
    sh.run("cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..", cwd=build_dir)
  File "/home/lzlang/code/tvm/ci/scripts/cmd_utils.py", line 66, in run
    return subprocess.run(cmd, **defaults)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..' returned non-zero exit status 1.
+ cleanup
+ set +x
```

command `make cpptest` works well.

### Triage

Please refer to the list of label tags linked above to find the relevant tags and add them here in a bullet format (example below).

* needs-triage

**Comment by vinx13** [comment]
please refer to the cmake error output
```
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```
