### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by venkatesha2411** [apache/tvm#13057]
Facing problem with compiling the model.

from tvm.driver import tvmc

#basic config
target = "llvm -mcpu=znver2"
device = "cpu"
do_tuning = True

#load the model
model = tvmc.load('model-small.onnx')

#apply autotuning to improve performance
if do_tuning:
  log_file = "logs.json"
  tvmc.tune(model, target = "llvm", tuning_records = log_file, enable_autoscheduler = True)
else:
  log_file = None

#Compile
package = tvmc.compile(model, target= "llvm", tuning_records = log_file)

Error:
 File "/workspace/tvm/src/tir/ir/data_layout.cc", line 424
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (GetStoreRule(&n->index_backward_rule, &n->shape_backward_rule, n->dst_layout, n->src_layout)) is false:

**Comment by masahi** [comment]
Can you upload your `model-small.onnx`?

**Comment by ganler** [comment]
@masahi The log seems identical to https://github.com/apache/tvm/issues/10528

**Comment by venkatesha2411** [comment]
The mode can be found with the link below: https://drive.google.com/file/d/1B2CpRCBIKe3Z948eollr0dD5eP57hAjy/view?usp=sharing

**Comment by ganler** [comment]
@venkatesha2411 Thanks! Would you like to turn on the link share? Thanks!

**Comment by venkatesha2411** [comment]
> 

Can you please check now? I have changed the access rights

**Comment by BlueBlueSloth** [comment]
> Can you please check now? I have changed the access rights

Thanks, it now works well.

**Comment by venkatesha2411** [comment]
On observation, the squeeze layers are not compatible with TVM, and is there any alternative solution for the same?

**Comment by ganler** [comment]
It seems this model is not valid? 

For ONNXRuntime, it says: 

```
sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invali
d model. In Node, ("Pad_4", Pad, "", -1) : ("486": tensor(float),) -> ("487": tensor(float),) , Error Node (Pad_4) ha
s input size 1 not in range [min=2, max=3].
```

For TVM, it shows a warning:

```
UserWarning: Node (Pad_4) has input
 size 1 not in range [min=2, max=3].
```
