### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fxrhhx** [apache/tvm#13060]
- AttributeError: <class 'tvm.ir.type.TupleType'> has no attribute shape

- so how to support  SequenceEmpty op  which belongs to onnx ? 
- this is my implement, but has error : - AttributeError: <class 'tvm.ir.type.TupleType'> has no attribute shape

- class **SequenceEmpty**(OnnxOpConverter):

    """Operator converter for sequence construction op."""

    @classmethod
    def _impl_v11(cls, inputs, attr, params):
        # Construct a tuple from input tensors.
        return _expr.Tuple([])

**Comment by masahi** [comment]
Please post such question to the discuss forum.
