### ISSUE TITLE
[Relay] relay.Var allows special characters like `:` while chose are not allowed in the compiler

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#13063]
In the current TVM, relay.Var would accept variable names like `input:0` while in the compiler `:` is a special character and we are sanitizing these name before passing it to the compiler.

The solution could be adding check in the relay.Var itself. This would result in adding sanitization in different places like frontends.

cc @AndrewZhaoLuo @slyubomirsky @areusch

**Comment by AndrewZhaoLuo** [comment]
I say just put the sanitation in relay.Var, make it automatic and call it a day B).

**Comment by mehrdadh** [comment]
@AndrewZhaoLuo no, I have a follow up draft PR which should fix this as you suggested
https://github.com/apache/tvm/pull/13086
