### ISSUE TITLE
[ci] `apps/` aren't run in CI

### ISSUE THREAD

**Issue by driazati** [apache/tvm#13105]
Currently the examples in https://github.com/apache/tvm/tree/main/apps are not continuously tested. Some are broken and have been for a while (e.g. `bundle_deploy`) while others are commonly used but untested (`howto_deploy`). We should add a CI job for these (probably as a separate parallel step) that runs the apps with reasonable configurations for CI to keep runtime down.

cc @Mousius @areusch @gigiblender

**Comment by oleggolev** [comment]
Was this ever addressed? I'm trying to figure out how to run `bundle_deploy` but am unsuccessful. Seems like it's even more broken now.
