### ISSUE TITLE
[Bug] Infer_types: The Relay type checker is unable to show the following types match.

### ISSUE THREAD

**Issue by vccheng2001** [apache/tvm#13143]
### Expected behavior

Trying to run TVM on ONNX model but erroring out.

### Actual behavior

```
.....
%744 = take(%743, meta[relay.Constant][208], axis=1);
%745 = shape_of(%744, dtype="int64");
%746 = take(%745, meta[relay.Constant][209], axis=0);
%747 = equal(%746, meta[relay.Constant][210]);
%748 = take(%747, 0i64);
if (%748) {
  squeeze(%744, axis=[1])
} else {
  copy(%744)
}
```
**ERROR**: tensor type `Tensor[(?, 1), int64]` has 2 dimensions, while `Tensor[(?), int64]` has 1 dimensions
The Relay type checker is unable to show the following types match.
In particular `Tensor[(?), int64]` does not match `Tensor[(?, 1), int64]`

### Version
Linux, TVM version: tvm-0.10.dev787+ge03e6d37f-cp38-cp38-linux_x86_64.whl 

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by ganler** [comment]
@vccheng2001 Would you like to attach the ONNX model? Thanks!

**Comment by masahi** [comment]
Feel free to reopen with a reproducible script.
