### ISSUE TITLE
Build apps/andoird_rpc error

### ISSUE THREAD

**Issue by Nullptr65535** [apache/tvm#13152]
### Actual behavior
after executing gradle clean build --stacktrace:

> Task :app:buildJni FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
......
Caused by: java.io.IOException: Cannot run program "ndk-build" (in directory "/home/tvm/tvm/apps/android_rpc/app"): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
2: Task failed with an exception.
\-----------
\* What went wrong:
java.lang.StackOverflowError (no error message)
\* Exception is:
java.lang.StackOverflowError
......

### Environment
windows10 wsl, ubuntu 20.04
TVM version: latest(0.10)

### Steps to reproduce

Follow the steps in ''https://tvm.apache.org/docs/install/from_source.html#install-from-source'' , build libtvm.so and libtvm_runtime.so successfully.
Follow the steps in android_rpc/README.md, I have installed gradle and tvm4j. Ndk for wsl linux is downloaded from https://developer.android.google.cn/ndk/downloads/, besides that, I also installed ndk on windows by android studio.
I have already set ANDROID_HOME and set sdk.dir in file local.properties.

**Comment by masahi** [comment]
android_rpc is tested on CI, please check your installation of ndk. Please post a usage question to the discuss forum.

**Comment by Nullptr65535** [comment]
I have posted a question on forum but got no answer, btw, what is CI?Thanks

**Comment by HandsomeSword** [comment]
> I have posted a question on forum but got no answer, btw, what is CI?Thanks

Hi!How did you solve this problem? I also encountered the same problem.
