### ISSUE TITLE
[Bug] about caffe frontend

### ISSUE THREAD

**Issue by honghuichao** [apache/tvm#13157]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

What you were expecting

### Actual behavior

What actually happened

### Environment

Any environment details, such as: Operating System, TVM version, etc

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

some bugs in this code:
'''''

  def op_fuse(self):
        """fuse bn and scale"""
        new_layers = []
        temp_layers = {}
        changed_layers = {}

        for index, pl in enumerate(self.predict_layer):
            op_type = pl.type
            if op_type == "Input":
                new_layers.append(pl)
                continue
            elif op_type == "BatchNorm":
                if (index != len(self.predict_layer) - 1) and (
                    self.predict_layer[index + 1].type == "Scale"
                ):
                    temp_layers["bn"] = pl
                    continue
                else:
                    new_layers.append(pl)
                    temp_layers.clear()
            elif op_type == "Scale":
                if self.predict_layer[index - 1].type == "BatchNorm":
                    temp_layers["scale"] = pl
                else:
                    new_layers.append(pl)
                    temp_layers.clear()
            else:
                temp_layers.clear()

            if len(temp_layers) == 2:
                layer = self.fuse_op(temp_layers)
                new_layers.append(layer)
                changed_layers[temp_layers["scale"].name] = temp_layers["bn"].name

            for idx, plt in enumerate(pl.bottom):
                if plt in changed_layers:
                    pl.bottom[idx] = changed_layers[plt]

            if op_type not in ["BatchNorm", "Scale"]:
                new_layers.append(pl)

'''

            for idx, plt in enumerate(pl.bottom):
                if plt in changed_layers:
                    pl.bottom[idx] = changed_layers[plt]

in caffe layer name can be different with output(top). in this code，if  name is not equal to output  , key error happend.  we cannot  set pl.bottom[idx] into  changed_layers[plt].

**Comment by honghuichao** [comment]
@fernand

**Comment by masahi** [comment]
The caffe frontend is not maintained. So unless you can send the solution to the problem yourself, we cannot address this issue.
