### ISSUE TITLE
[Flaky Test] HexagonThreadManagerTest.thread_order_signal_wait is flaky on simulator

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#13169]
This test seems to have inconsistent results based on different timings. This PR shows an example:

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-13161/4/tests/

cc @janetsc @adstraw

**Comment by janetsc** [comment]
Addressed the root cause and re-enabled the test in https://github.com/apache/tvm/pull/13174
