### ISSUE TITLE
[Bug] VTA FSIM MacOS incompatibility

### ISSUE THREAD

**Issue by gussmith23** [apache/tvm#13173]
@vcanumalla is attempting to build FSIM on MacOS and running into issues:

- FSIM source includes `malloc.h`, which isn't present (at least not by default) on MacOS. Removing the import doesn't break the code, so it doesn't seem necessary.
- the `memalign` function is not present on MacOS. @vcanumalla was experimenting with replacing it with `posix_memalign`.

Are there instructions for building on MacOS specifically?

**Comment by xhmelon** [comment]
Hi @vegaluisjose @vinx13 @masahi, please close this issue as it has been resolved.
