### ISSUE TITLE
[BYOC][DNNL] Check failed: (pf != nullptr) is false: no such function in module: tvmgen_default_dnnl_main_0

### ISSUE THREAD

**Issue by yuwenjun1988** [apache/tvm#13210]
Expected behavior
No Crash

Actual behavior
Crash Stack

Traceback (most recent call last):
  File "/mnt/e/tvm_mlir_learn-main/test/dnnl_test.py", line 190, in <module>
    run_and_verify_func(get_graph(relay.nn.relu), run_module=True)
  File "/mnt/e/tvm_mlir_learn-main/test/dnnl_test.py", line 173, in run_and_verify_func
    run_and_verify(
  File "/mnt/e/tvm_mlir_learn-main/test/dnnl_test.py", line 143, in run_and_verify
    func = relay.create_executor(
  File "/mnt/e/code/tvm/python/tvm/relay/backend/interpreter.py", line 171, in evaluate
    return self._make_executor()
  File "/mnt/e/code/tvm/python/tvm/relay/build_module.py", line 520, in _make_executor
    gmodule = _graph_executor.GraphModule(mod["default"](self.device))
  File "/mnt/e/code/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  5: TVMFuncCall
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::GraphExecutorFactory::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  3: tvm::runtime::GraphExecutorFactory::ExecutorCreate(std::vector<DLDevice, std::allocator<DLDevice> > const&)
  2: tvm::runtime::GraphExecutor::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::Module, std::vector<DLDevice, std::allocator<DLDevice> > const&, tvm::runtime::PackedFunc)
  1: tvm::runtime::GraphExecutor::SetupOpExecs()
  0: tvm::runtime::GraphExecutor::CreateTVMOp(tvm::runtime::TVMOpParam const&, std::vector<DLTensor, std::allocator<DLTensor> > const&)
  File "/mnt/e/code/tvm/src/runtime/graph_executor/graph_executor.cc", line 563
TVMError:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html

Environment
Ubuntu 18.04 TVM 0.11.dev0
Any environment details, such as: Operating System, TVM version, etc

Steps to reproduce

run tvm/tests/python/contrib/test_dnnl.py

**Comment by masahi** [comment]
Closing assuming this is not an issue of TVM.
