### ISSUE TITLE
[Flaky Test] Failing Caffe tests due to broken URL

### ISSUE THREAD

**Issue by lhutton1** [apache/tvm#13227]
A couple of Caffe tests are failing locally:
```
tests/python/frontend/caffe/test_forward.py::test_forward_Alexnet
tests/python/frontend/caffe/test_forward.py::test_forward_Inceptionv1
```

The failure seems to be caused by a broken URL (http://dl.caffe.berkeleyvision.org/) used to retrieve the models. 

I'm assuming this isn't an issue in upstream yet due to some form of cache being used?

**Comment by lhutton1** [comment]
Tried suggestion [here](https://github.com/BVLC/caffe/issues/6864#issuecomment-1293370779), but the updated model seems to cause the test to segfault

**Comment by masahi** [comment]
Let's just disable them. Caffe frontend is not maintained.

**Comment by driazati** [comment]
The URLs are caught in CI and sent to a more reliable version in S3: https://github.com/apache/tvm/blob/main/tests/scripts/request_hook/request_hook.py#L28

We could use that in the test so it passes locally or just disable it (if it's not maintained at all I'm in favor of disabling)

**Comment by lhutton1** [comment]
Looks like the link is back up, happy to close #13228 since this is not an issue upstream. Out of curiosity is there any plan to deprecate the Caffe frontend since it is no longer maintained?
