### ISSUE TITLE
[Bug] Deploy the Pretrained Model on Android，if generated model so file size is large，rpc upload failed，how to solve this problem.

### ISSUE THREAD

**Issue by yuwenjun1988** [apache/tvm#13225]
Expected behavior
No Crash

Actual behavior
Crash Stack
python3 arm_cpu_imagenet_bench.py --model p20pro --rpc-key android
--------------------------------------------------
Network Name         Mean Inference Time (std dev)
--------------------------------------------------
dense is not optimized for arm cpu.
dense is not optimized for arm cpu.
dense is not optimized for arm cpu.
pool is not optimized for arm cpu.
pool is not optimized for arm cpu.
pool is not optimized for arm cpu.
pool is not optimized for arm cpu.
pool is not optimized for arm cpu.
dense is not optimized for arm cpu.
dense is not optimized for arm cpu.
dense is not optimized for arm cpu.
Traceback (most recent call last):
  File "/mnt/e/code/tvm/apps/benchmark/arm_cpu_imagenet_bench.py", line 121, in <module>
    evaluate_network(network, target, target_host, args.repeat)
  File "/mnt/e/code/tvm/apps/benchmark/arm_cpu_imagenet_bench.py", line 58, in evaluate_network
    remote.upload(tmp.relpath(filename))
  File "/mnt/e/code/tvm/python/tvm/rpc/client.py", line 115, in upload
    self._remote_funcs["upload"](target, blob)
  File "/mnt/e/code/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/mnt/e/code/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError:
---------------------------------------------------------------
An error occurred during the execution of TVM.

Environment
Ubuntu 18.04 TVM 0.11.dev0
Any environment details, such as: Operating System, TVM version, etc

Steps to reproduce
 python3 arm_cpu_imagenet_bench.py --model p20pro --rpc-key android

**Comment by zuowanbushiwo** [comment]
@yuwenjun1988  Do you know how to fix it now? i have the same problem。

**Comment by yuwenjun1988** [comment]
No

**Comment by yuwenjun1988** [comment]
you can use cpp_rpc,it not shutdown
