### ISSUE TITLE
[Bug] Registering device to RPC tracker failed 

### ISSUE THREAD

**Issue by Priyadrasta-2111CS10** [apache/tvm#13237]
### Expected behavior
The output should be something like this.The picture shown below is showing the result while the RPC tracker is set on Raspberry PI and the RPC server is set on local host which in fact should be opposite.

![image](https://user-images.githubusercontent.com/92008353/199019051-7cbd64c2-6d5f-4ff4-94a8-e192b5bdca2a.png)

### Actual behavior
The RPC tracker couldn't track down the connected Raspberry PI as shown below.

![image](https://user-images.githubusercontent.com/92008353/199018414-c27ac580-2213-4794-ae29-9df0c3135c84.png)

### Environment

**Operating System for host :** Linux 22.04 LTS
**Operating System for target :** Raspbian 64 bit OS

### Steps to reproduce

1. Start the RPC tracker on the host system by the command `python -m tvm.exec.rpc_tracker --host=0.0.0.0 --port=9190`

2. Start the RPC server in the target devices  by the command : `python -m tvm.exec.rpc_server --tracker=[HOST_IP]:9190 --key=[KEY] `.In the case of HOST_IP and KEY use your host system IP address and key for target device.

3.Track the connected devices to the current RPC tracker on your host device : `python -m tvm.exec.query_rpc_tracker --host=0.0.0.0 --port=9190`

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* core:rpc

**Comment by xox9943** [comment]
This problem is also encountered on Windows. It got stuck when I bind it
`2022-11-22 13:09:02.854 INFO bind to 127.0.0.1:9190
`

**Comment by Priyadrasta-2111CS10** [comment]
I have fixed the issue. In Ubuntu 22.04 LTS ,the firewall was by default set. So we have to disable it so that the linux host can connect to RPi.In my case the command `sudo ufw disable`  fixed the issue.
