### ISSUE TITLE
[Docs][Bug] Image missing for UMA tutorial

### ISSUE THREAD

**Issue by StrongerXi** [apache/tvm#13304]
The image in [this section](https://tvm.apache.org/docs/tutorial/uma.html#vanilla) of the UMA tutorial is missing.

Root cause seems to be that it's [missing](https://github.com/apache/tvm-site/tree/main/images/tutorial) in the corresponding resource url.

**Comment by qzylalala** [comment]
URL: https://raw.githubusercontent.com/apache/tvm-site/main/images/tutorial/uma_vanilla_block_diagram.png 
But still not found

**Comment by lhutton1** [comment]
Closing as this should be fixed by #13624, the docs may take a bit of time to bring in the change. Feel free to reopen if the problem persists.
