### ISSUE TITLE
[Bug] [BYOC] After partitioning through BYOC, the constant memory of the operator in the model is out of order

### ISSUE THREAD

**Issue by yuwenjun1988** [apache/tvm#13412]
After partitioning through BYOC, the constant memory in the operator in the model is out of order
![image](https://user-images.githubusercontent.com/115987013/202334428-1b5d82c5-2217-4d67-8e75-7390429b5078.png)

**Comment by masahi** [comment]
I don't think this is a problem. Actually I'm not sure if these numbers represent some ordering. Feel free to reopen if this is causing you a real problem.
