### ISSUE TITLE
collect2: fatal error: cannot find ‘ld’

### ISSUE THREAD

**Issue by Xrigok** [apache/tvm#13415]
![image](https://user-images.githubusercontent.com/31384900/202408328-1e1e48be-caad-4a76-ae19-a39d568f2e63.png)
This problem occurred when I was building TVM. It compiled successfully before, but now it fails to recompile again.

**Comment by driazati** [comment]
This seems like a problem with your host system, are you able to compile and link a simple c program to an executable? Your `PATH` environment variable may be changed to not have `ld` in it anymore either.

If you're just looking to get started right away you could use the TVM Docker images instead: https://tvm.apache.org/docs/install/docker.html

**Comment by Xrigok** [comment]
I can compile the .c file directly with gcc to generate the .so file

**Comment by masahi** [comment]
Please make sure `ld` is available in your PATH. This is not reproducible.
