### ISSUE TITLE
[Bug] ‘NotImplementedError’ error

### ISSUE THREAD

**Issue by jakariamd** [apache/tvm#13447]
Hi, I am having the following error while trying to compile a PyTorch model. 

NotImplementedError: The following operators are not implemented: ['aten::conv2d', 'prim::unchecked_cast', 'aten::dim', 'aten::format', 'aten::warn', 'aten::__is__']

Here is my model: 
Net(
  (conv1): Conv2d(1, 5, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(5, 10, kernel_size=(3, 3), stride=(1, 1))
  (dropout1): Dropout(p=0.25, inplace=False)
  (dropout2): Dropout(p=0.5, inplace=False)
  (fc1): Linear(in_features=1440, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)

NB: I applied Activation Mean Rank Pruner on this model.

**Comment by masahi** [comment]
Please use `torch.jit.trace(...)`. Those ops you listed suggest you are using `torch.jit.script(...)`.
