### ISSUE TITLE
[CI Problem] cross-compilations are broken

### ISSUE THREAD

**Issue by hellokeey** [apache/tvm#13482]
cross-compile for aarch64：build errors occurred
cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_VERSION=1 \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu \
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
    -DMACHINE_NAME=aarch64-linux-gnu

**make runtime -j4**

errors when final link with ld. 

/home/sea/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: host_standalone_crt/libmicrotvm_rpc_common.a(framing.o): Relocations in generic ELF (EM: 62)
host_standalone_crt/libmicrotvm_rpc_common.a: error adding symbols: File in wrong format
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/tvm_runtime.dir/build.make:168：libtvm_runtime.so] error 1
make[2]: *** [CMakeFiles/Makefile2:255：CMakeFiles/tvm_runtime.dir/all] error 2
make[1]: *** [CMakeFiles/Makefile2:346：CMakeFiles/runtime.dir/rule] error 2
make: *** [Makefile:282：runtime] error 2

**Comment by masahi** [comment]
Please post a general usage problem to the forum.

**Comment by supersat** [comment]
@masahi this seems like an issue with PR #13073, which seems to be breaking a lot of things (#13393, #13486)

cc: @mehrdadh

**Comment by areusch** [comment]
i think this is specified well enough: cross-compile for aarch64

we are also seeing this problem internally
