### ISSUE TITLE
[microTVM] Change apps/microtvm/zephyr_cmsisnn to a microTVM tutorial

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#13501]
In the current state of TVM, Zephyr microtvm project API supports CMSIS-NN and ARM FVP. We could change this directory to a tutorial and use microtvm transport layer with AOT Executor.

cc @Mousius @alanmacd @gromero @leandron

**Comment by gromero** [comment]
I have no objections to that.

**Comment by Mousius** [comment]
The demo intentionally didn't use the Project API so as to demonstrate how to integrate TVM into an existing project rather than generating it in TVM. I think it's valuable to keep it as is so people can use it as a reference for how to use TVM without generating the entire project?

**Comment by mehrdadh** [comment]
@Mousius @gromero I agree, it makes sense to keep this for the standalone deployment story. I think this has the potential to be more generic and not just specific to use CMSIS. We could change this to be a standalone deployment of microTVM with Zephyr.
