### ISSUE TITLE
compile error for gcc 7 and 8

### ISSUE THREAD

**Issue by frankxyy** [apache/tvm#13531]
When I build tvm from source, this error occurs:

g++: error: unrecognized command line option ‘-fuse-ld=lld’; did you mean ‘-fuse-ld=bfd’?

**Comment by masahi** [comment]
Probably you need to install lld. Building from source on linux is tested on CI.

**Comment by frankxyy** [comment]
![image](https://user-images.githubusercontent.com/6971044/206406923-f25a81b4-ccbe-4b7b-8b9e-0d94130f9ebf.png)

@masahi no linux？

**Comment by Mousius** [comment]
Hi @frankxyy,

Our build system will try to find the best linker it can:
https://github.com/apache/tvm/blob/main/cmake/utils/Linker.cmake

On your system that seems to be `lld`, but the `g++` compiler can't seem to find it, to stop this behaviour you can add:
```
-DUSE_ALTERNATIVE_LINKER=OFF
```
to your `cmake` command, or add this to your `config.cmake`:
```
set(USE_ALTERNATIVE_LINKER OFF)
```

**Comment by frankxyy** [comment]
@Mousius got it, thank you!
