### ISSUE TITLE
[错误] TVMC reports: bound.cc:119: not in feed graph consumer =

### ISSUE THREAD

**Issue by Ninesheng9** [apache/tvm#13555]
### Expected behavior

When I used tvmc to convert PaddlePaddle models to C code, although some models can generate final files I need, the following prompts will appear:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/74167626/205804921-074e7431-ef9f-4af1-8b14-4e0dd0cb4b27.png">

I don't know the exactly reason.

### Environment
apache-tvm                    0.10.0
paddlepaddle                  2.3.2
Python                             3.9.12

### Steps to reproduce

My code:
tvmc compile --target=cmsis-nn,c \
    --target-c-mcpu=cortex-m55 \
    --runtime=crt \
    --executor=aot \
    --executor-aot-interface-api=c \
    --executor-aot-unpacked-api=1 \
    --pass-config tir.usmp.enable=1 \
    --pass-config tir.usmp.algorithm=hill_climb \
    --pass-config tir.disable_storage_rewrite=1 \
    --pass-config tir.disable_vectorize=1 fastscnn_cityscapes_1024x1024_160k/model.pdmodel \
    --output-format=mlf \
    --model-format=paddle \
    --module-name=fastscnn_cityscapes_1024x1024_160k \
    --input-shapes "x:[1,3,1024,1024]" \
    --output=fastscnn_cityscapes_1024x1024_160k.tar

You can find the model at: https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/configs/fastscnn

**Comment by masahi** [comment]
This is not a problem.

**Comment by masahi** [comment]
We should remove these lines 
https://github.com/apache/tvm/blob/cf15375e20cd1fb2e201e47afda169732ef88eea/src/te/schedule/bound.cc#L118-L120

Feel free to send a PR.
