### ISSUE TITLE
[Bug] [Frontend] [PyTorch] NotImplementedError: The following operators are not implemented: ['aten::conv2d', 'aten::format', 'aten::__is__', 'aten::dim', 'prim::unchecked_cast']

### ISSUE THREAD

**Issue by shingjan** [apache/tvm#13636]
This is from latest resnet18 on pytorch 

cc: @masahi 

cc @yelite

**Comment by masahi** [comment]
They only appear if you use `jit.script`, which we don't support.

**Comment by shingjan** [comment]
@masahi Thats right. I think the most recent resnet18 in pytorch is failing jit.trace and torchdynamo is falling back to `jit.script` which caused this error.

**Comment by zyc-bit** [comment]
My recent work involves these aspects, and I'm looking forward to your response.
So, if the model includes a 'conv2d' operation, does that mean we cannot use a model obtained through 'torch.jit.script' as input for Relay? Instead, we can only use 'torch.jit.trace'? Does this limitation seem too restrictive? What should we do if the model contains control flow that 'trace' cannot handle?
@shingjan @masahi

**Comment by engineer1109** [comment]
Me too.
So how to get the model?
torch.jit.trace?
