### ISSUE TITLE
[Bug] AttributeError: module 'tvm.meta_schedule' has no attribute 'TuneConfig' when running the colab notebook

### ISSUE THREAD

**Issue by digital-nomad-cheng** [apache/tvm#13657]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

I was trying to run the colab example for the mlc.ai course

### Actual behavior

https://colab.research.google.com/github/mlc-ai/notebooks/blob/main/5_Automatic_Program_Optimization.ipynb#scrollTo=bnweYKKyw9M0

the notebook report AttributeError: module 'tvm.meta_schedule' has no attribute 'TuneConfig'
when running the following section
```
from tvm import meta_schedule as ms

sch_tuned = ms.tune_tir(
    mod=MyModule,
    target="llvm --num-cores=1",
    config=ms.TuneConfig(
      max_trials_global=64,
      num_trials_per_iter=64,
    ),
    space=ms.space_generator.ScheduleFn(stochastic_schedule_mm),
    work_dir="./tune_tmp",
    task_name="main"
)
```

### Environment
colab jupyter notebook

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by masahi** [comment]
The notebook needs to be updated for the new API.
