### ISSUE TITLE
[Bug] Fail to convert standard huggingface BERT model

### ISSUE THREAD

**Issue by JamesTheZ** [apache/tvm#13664]
The latest TVM fail to convert the standard huggingface BERT model.
The script to replay directly:

``` python
from transformers import BertTokenizer, BertConfig, BertModel
import tvm
from tvm import relay
import torch


class AutoModelAMP(BertModel):
    def __init__(self, *args, **keyargs):
        with torch.cuda.amp.autocast():
            super().__init__(*args, **keyargs)

    def forward(self, *args, **keyargs):
        with torch.cuda.amp.autocast():
            return super().forward(*args, **keyargs)


config = BertConfig.from_pretrained("bert-large-uncased")
config.return_dict = False
config.torchscript = True
model = AutoModelAMP(config).cuda().eval()

batch = 1
seq_len = 128
input = torch.zeros([batch, seq_len], dtype=torch.int).long()
inputs = {
    "input_ids": input.cuda(),
    "attention_mask": input.cuda(),
    "token_type_ids": input.cuda(),
}
input_list = []
for k, v in inputs.items():
    input_list.append(v)

shape_list = []
for k, v in inputs.items():
    shape_list.append((k, v.shape))

traced_model = torch.jit.trace(
    model.cuda(), input_list, strict=False).cuda().eval()
mod, params = relay.frontend.from_pytorch(traced_model, shape_list)
```
Error log:
```
Traceback (most recent call last):
  File "tvm_bug.py", line 40, in <module>
    mod, params = relay.frontend.from_pytorch(traced_model, shape_list)
  File "/home/workspace/release/tvm/python/tvm/relay/frontend/pytorch.py", line 4653, in from_pytorch
    outputs = converter.convert_operators(_get_operator_nodes(graph.nodes()), outputs, ret_name)
  File "/home/workspace/release/tvm/python/tvm/relay/frontend/pytorch.py", line 4026, in convert_operators
    relay_out = relay_op(
  File "/home/workspace/release/tvm/python/tvm/relay/frontend/pytorch.py", line 1704, in linear
    mm_out = self.matmul(
  File "/home/workspace/release/tvm/python/tvm/relay/frontend/pytorch.py", line 1932, in matmul
    out = _op.reshape(out, [*a_shape[:-1], b_shape[-1]])
  File "/home/workspace/release/tvm/python/tvm/relay/op/transform.py", line 325, in reshape
    tempshape.append(int(shape))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Any'
```
The `a_shape` and `b_shape` at `tvm/python/tvm/relay/frontend/pytorch.py:1932` are `(?, 128, 1024)` and `(1024, 1024)`.
It looks like the reshape of the output of matmul does not support dynamic shape properly.

#### Env:
TVM commit: e2680142ef8d301ae5dfc10b89594fd388219a7e
huggingface transformers version: 4.25.1
torch: 1.12.0+cu113

**Comment by masahi** [comment]
It looks like amp is adding some dynamism, do you know why?

The following modified script that removed amp autocast works:

```
from transformers import BertTokenizer, BertConfig, BertModel
import tvm
from tvm import relay
import torch


class AutoModelAMP(BertModel):
    def __init__(self, *args, **keyargs):
        super().__init__(*args, **keyargs)

    def forward(self, *args, **keyargs):
        return super().forward(*args, **keyargs)


config = BertConfig.from_pretrained("bert-large-uncased")
config.return_dict = False
config.torchscript = True
model = AutoModelAMP(config).eval()

batch = 1
seq_len = 128
input = torch.zeros([batch, seq_len], dtype=torch.int).long()
inputs = {
    "input_ids": input,
    "attention_mask": input,
    "token_type_ids": input,
}
input_list = []
for k, v in inputs.items():
    input_list.append(v)

shape_list = []
for k, v in inputs.items():
    shape_list.append((k, v.shape))

traced_model = torch.jit.trace(
    model, input_list, strict=False).eval()
mod, params = relay.frontend.from_pytorch(traced_model, shape_list)

```

**Comment by JamesTheZ** [comment]
> It looks like amp is adding some dynamism, do you know why?
> 
> The following modified script that removed amp autocast works:
> 
> ```
> from transformers import BertTokenizer, BertConfig, BertModel
> import tvm
> from tvm import relay
> import torch
> 
> 
> class AutoModelAMP(BertModel):
>     def __init__(self, *args, **keyargs):
>         super().__init__(*args, **keyargs)
> 
>     def forward(self, *args, **keyargs):
>         return super().forward(*args, **keyargs)
> 
> 
> config = BertConfig.from_pretrained("bert-large-uncased")
> config.return_dict = False
> config.torchscript = True
> model = AutoModelAMP(config).eval()
> 
> batch = 1
> seq_len = 128
> input = torch.zeros([batch, seq_len], dtype=torch.int).long()
> inputs = {
>     "input_ids": input,
>     "attention_mask": input,
>     "token_type_ids": input,
> }
> input_list = []
> for k, v in inputs.items():
>     input_list.append(v)
> 
> shape_list = []
> for k, v in inputs.items():
>     shape_list.append((k, v.shape))
> 
> traced_model = torch.jit.trace(
>     model, input_list, strict=False).eval()
> mod, params = relay.frontend.from_pytorch(traced_model, shape_list)
> ```

Using the above script without autocast still results in the same error to me. The environment by executing `python -c 'import torch, tvm, transformers; print(f"torch version: {torch.__version__}, tvm version: {tvm.__version__}, transformers version: {transformers.__version__}");'` is:
```
torch version: 1.12.0+cu113, tvm version: 0.11.dev0, transformers version: 4.25.1
```

**Comment by JamesTheZ** [comment]
By the way, does TVM support converting dynamic-shaped models currently?

**Comment by masahi** [comment]
Mine is

```
torch version: 1.13.0+cpu, tvm version: 0.11.dev0, transformers version: 4.24.0
```

but Huggingface BERT should be supported regardless of the PT or `transformers` versions. I have the script https://github.com/masahi/torchscript-to-tvm/blob/master/transformers/bert_clean.py working for a long time. 

> By the way, does TVM support converting dynamic-shaped models currently?

Some frontends (ONNX, maybe TF too) support dynamic input shape. The PT frontend doesn't support dynamic input shape, but it supports dynamic-shape output (MaskRCNN etc).

**Comment by JamesTheZ** [comment]
> 

How can the Nimble functions be evaluated if the dynamic shape is not fully supported for torch frontends? Are there benchmarks for Nimble?

**Comment by JamesTheZ** [comment]
@masahi What is the tvm commit id you are using? I have tried to rebuild TVM and use the same software version as you, but the problem remains.

**Comment by masahi** [comment]
You can try the latest main, 520f2c594. But again, the specific version doesn't matter, HF has always been supported.

I don't know what is "Nimble functions".

**Comment by JamesTheZ** [comment]
Thanks for the reply. Nimble functions are: https://discuss.tvm.apache.org/t/codegen-of-nimble/9489/6 @masahi

**Comment by JamesTheZ** [comment]
I downgrade python from 3.8 to 3.7, and the conversion succeeds. It might be a PyTorch trace problem on python 3.8.

FYI. @masahi

**Comment by Healthcliff-Ding** [comment]
I encountered similar problem with yours @JamesTheZ , even though I didn't use any extra features like AMP etc. 

My bug occurs when I use tvm 0.15dev + Python 3.8 + PyTorch 2.01, but when I follow your experience, downgrade my Python to 3.7.12, tvm from_pytorch worked.

Thanks for your experience. But I wonder if there is some way to inform the developer to make accommodation on newer version of TorchScript, because Python 3.7 isn't supported by PyTorch now. It has lasted for almost ONE YEAR, and PyTorch stable has gone to 2.1.

Wish TVM a brighter future!
