### ISSUE TITLE
[Bug] [TVMScript] T.power or T.pow?

### ISSUE THREAD

**Issue by lightzhan-intellif** [apache/tvm#13674]
Hi all,
When I use TVMScript, I find a problem about the roundtripability of the intrinsic `tir.pow`. Currently, we use `T.power` to express that we want to call the intrinsic `tir.pow`, but when we print the script, it becomes "T.pow" which can not be parsed by the parser any more.

So, for the roundtripability of the intrinsic `tir.pow`, which name should we use?

(For the printer, it will use the intrinsic name `pow` to print, so if we use `T.power`, it maybe means that we need to change the intrinsic name.)

cc @junrushao

**Comment by junrushao** [comment]
Thanks for bringing this up! The naming inconsistency is definitely an issue we should fix. Ideally, if the intrinsic name is `pow`, we should probably stick with `pow` everywhere. Would you mind sending a fix?

**Comment by lightzhan-intellif** [comment]
Of course not.
