### ISSUE TITLE
[Bug] Process ‘tvm.exec.popen_worker’ still exists when I didn’t run any tvm task.

### ISSUE THREAD

**Issue by hexiaoyupku** [apache/tvm#13778]
Hi everyone,

We found that sometimes the process ‘tvm.exec.popen_worker’ still exists when I didn’t run any tvm task. It takes up around 20% of the CPU. What’s the reason? And how to avoid that?

**Comment by masahi** [comment]
Let's continue in https://discuss.tvm.apache.org/t/process-tvm-exec-popen-worker-still-exists-when-i-didnt-run-any-tvm-task-why-and-how-to-fix-it/14197. I think this can happen if tuning or something else that uses the RPC server doesn't shutdown properly for whatever reason.
