### ISSUE TITLE
[Bug] time evaluator on 3090

### ISSUE THREAD

**Issue by hulihan-start** [apache/tvm#13782]
I want to evaluator the time cost of tvm, and use the code from https://tvm.apache.org/docs/how_to/optimize_operators/opt_conv_cuda.html?highlight=convolution

But I found in my RTX 3090, the time cost is just 5.750624 ms, 10x faster than the results reported by the link.

I download tvm from github yesterday and I don't know if there are some errors occured in github project or what codes should I change in my env.

Thanks!

**Comment by junrushao** [comment]
Well, I don't think the number generated in the tutorial is realistically meaningful, because it is run on a slower CI machine that is not necessarily a 3090 GPU. Please feel free to reopen the issue if further explanation/action is needed :-)
