### ISSUE TITLE
[CI Problem] TOPI tests on ci_cpu fail

### ISSUE THREAD

**Issue by neildhickey** [apache/tvm#13805]
### PR Failing
https://github.com/apache/tvm/pull/13724 caused an issue when running TOPI tests on ci_cpu.

```
tvm.topi.transform:test_strided_set segfaults when run on ci_cpu.

test_topi_transform.py Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Fatal Python error: Segmentation faultSegmentation faultSegmentation faultSegmentation faultSegmentation fault

Segmentation fault
```

https://github.com/apache/tvm/pull/13804 tries to resolve this by making the test require a gpu, but there could be a better solution.

* needs-triage
* tir:transform

**Comment by masahi** [comment]
https://github.com/apache/tvm/pull/13804
