### ISSUE TITLE
Use of Instruction instead of LLVM intrinsic in Tensorize schedule

### ISSUE THREAD

**Issue by Darshvino** [apache/tvm#13850]
Hi TVM team,

I am writing a custom operator in TVM and adding a Tensorize schedule for its execution. I See that we can use the LLVM intrinsics(for example:` llvm.aarch64.neon.uaddlp`, `llvm.aarch64.neon.addp`) through **tvm.tir.call_llvm_pure_intrin()** call. I just wanted to know if we can use directly the instruction instead of Intrinsic(for example: %3 = `mul <8 x i16> %1, %0` for `vmulq_u16`).

Look forward to your reply.

Thanks

**Comment by vinx13** [comment]
In this case you don't need to tensorize. If you tile the loop (using factor=8 as indicated by the instruction size) and vectorize it, llvm mul will be generated

**Comment by Darshvino** [comment]
Hi @vinx13,

Thanks a lot for your reply.

Actually, I am trying to write this operation: **((w_ * x_) & mask_value) >> shift_value** in a Tensorize schedule everything using intrinsics just to make sure that it’s fully optimized. And when I am trying to use the LLVM intrinsics(llvm.aarch64.neon equivalent) for the multiplication, there are no llvm.aarch64.neon equivalent for the type of multiplication which I am using. And just to give you an info: I need an equivalent for this: vmulq_u16: [Intrinsics – Arm Developer](https://developer.arm.com/architectures/instruction-sets/intrinsics/#q=vmulq_u16) not sure how I can implement it with LLVM intrinsics.

So that is the reason I got thought to directly use the instruction in the Tensorize schedule. [Compiler Explorer](https://godbolt.org/z/h43cPMfTK)

**Comment by vinx13** [comment]
Tensorization approach is also feasible. You can write a tensor intrin implementing the above formula and mixing ordinary * and llvm intrinsics. You will need to write a vectorized loop of multiply and check the generated llvm code is expected. 

Alternatively you can implement micro kernel in asm or llvm byte code see https://github.com/apache/tvm/issues/1276.

**Comment by masahi** [comment]
Let's continue in https://discuss.tvm.apache.org/t/use-of-instruction-instead-of-llvm-intrinsic-in-tensorize-schedule-13850/14252
