### ISSUE TITLE
TVM v0.11.0 Release Candidate Notes

### ISSUE THREAD

**Issue by leandron** [apache/tvm#13899]
# Introduction

The TVM community has worked since the v0.10.0 release to deliver the following new exciting improvements!

* Metaschedule
    * Tuning API improvements and anchor-block tuning

* TVMSCript metaprogramming
    * Lots of progress wiht TVMScript, with the introduction of a core parser, AST, Evaluator, Source and diagnostics

And many other general improvements to microTVM, code quality, CI, frontends, and more! Please visit the full listing of commits for a complete view: https://github.com/apache/tvm/compare/v0.10.0...v0.11.0.

## RFCs

These RFCs have been merged in [apache/tvm-rfcs](https://github.com/apache/tvm-rfcs) since the last release.

  * [CodeGenAArch64 backend with Scalable Vector Extension (SVE) #94](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0094-aarch64-backend-with-sve.md) https://github.com/apache/tvm-rfcs/commit/04b9909d6f8b63524091f12ff5eb964ad490c7b8

## What's Changed

Note that this list is not comprehensive of all PRs and discussions since v0.10. Please visit the full listing of commits for a complete view: https://github.com/apache/tvm/compare/v0.10.0...v0.11.0.

### Adreno
  * https://github.com/apache/tvm/pull/13573
  * https://github.com/apache/tvm/pull/13393
  * https://github.com/apache/tvm/pull/13153
  * https://github.com/apache/tvm/pull/13100
  * https://github.com/apache/tvm/pull/13117
  * https://github.com/apache/tvm/pull/13253
  * https://github.com/apache/tvm/pull/12833

### AoT
  * https://github.com/apache/tvm/pull/13250
  * https://github.com/apache/tvm/pull/13095
  * https://github.com/apache/tvm/pull/13046

### Arith
  * https://github.com/apache/tvm/pull/13041
  * https://github.com/apache/tvm/pull/12972

### arm
  * https://github.com/apache/tvm/pull/13417

### AutoTVM
  * https://github.com/apache/tvm/pull/12545

### Build
  * https://github.com/apache/tvm/pull/12839

### CI
  * https://github.com/apache/tvm/pull/13570
  * https://github.com/apache/tvm/pull/13300
  * https://github.com/apache/tvm/pull/13283
  * https://github.com/apache/tvm/pull/13335
  * https://github.com/apache/tvm/pull/13368
  * https://github.com/apache/tvm/pull/12915
  * https://github.com/apache/tvm/pull/13142
  * https://github.com/apache/tvm/pull/13058
  * https://github.com/apache/tvm/pull/12983
  * https://github.com/apache/tvm/pull/13590
  * https://github.com/apache/tvm/pull/13572
  * https://github.com/apache/tvm/pull/13505

### CL
  * https://github.com/apache/tvm/pull/13488

### CMSIS-NN
  * https://github.com/apache/tvm/pull/12950
  * https://github.com/apache/tvm/pull/13484

### DNNL
  * https://github.com/apache/tvm/pull/12787

### Docker
  * https://github.com/apache/tvm/pull/13342

### Docs
  * https://github.com/apache/tvm/pull/13188

### Ethos-N
  * https://github.com/apache/tvm/pull/13159
  * https://github.com/apache/tvm/pull/13022
  * https://github.com/apache/tvm/pull/13092
  * https://github.com/apache/tvm/pull/12970
  * https://github.com/apache/tvm/pull/12887

### Frontend
  * https://github.com/apache/tvm/pull/12042

### Hexagon
  * https://github.com/apache/tvm/pull/13256
  * https://github.com/apache/tvm/pull/13352
  * https://github.com/apache/tvm/pull/13381
  * https://github.com/apache/tvm/pull/13271
  * https://github.com/apache/tvm/pull/13233
  * https://github.com/apache/tvm/pull/13180
  * https://github.com/apache/tvm/pull/13110
  * https://github.com/apache/tvm/pull/13161
  * https://github.com/apache/tvm/pull/12971
  * https://github.com/apache/tvm/pull/13162
  * https://github.com/apache/tvm/pull/13135
  * https://github.com/apache/tvm/pull/13107
  * https://github.com/apache/tvm/pull/13005
  * https://github.com/apache/tvm/pull/13037
  * https://github.com/apache/tvm/pull/12981
  * https://github.com/apache/tvm/pull/12954
  * https://github.com/apache/tvm/pull/12911
  * https://github.com/apache/tvm/pull/12854
  * https://github.com/apache/tvm/pull/12669
  * https://github.com/apache/tvm/pull/13336
  * https://github.com/apache/tvm/pull/13197
  * https://github.com/apache/tvm/pull/13538
  * https://github.com/apache/tvm/pull/13416
  * https://github.com/apache/tvm/pull/13072
  * https://github.com/apache/tvm/pull/13181
  * https://github.com/apache/tvm/pull/13111
  * https://github.com/apache/tvm/pull/12398
  * https://github.com/apache/tvm/pull/13028
  * https://github.com/apache/tvm/pull/12947
  * https://github.com/apache/tvm/pull/12826
  * https://github.com/apache/tvm/pull/12820
  * https://github.com/apache/tvm/pull/12141
  * https://github.com/apache/tvm/pull/13557
  * https://github.com/apache/tvm/pull/12999
  * https://github.com/apache/tvm/pull/12919
  * https://github.com/apache/tvm/pull/12918

### LLVM
  * https://github.com/apache/tvm/pull/12877
  * https://github.com/apache/tvm/pull/13515

### MetaSchedule
  * https://github.com/apache/tvm/pull/13535
  * https://github.com/apache/tvm/pull/13459
  * https://github.com/apache/tvm/pull/13421
  * https://github.com/apache/tvm/pull/13384
  * https://github.com/apache/tvm/pull/13334
  * https://github.com/apache/tvm/pull/12948
  * https://github.com/apache/tvm/pull/13329
  * https://github.com/apache/tvm/pull/13195
  * https://github.com/apache/tvm/pull/13255
  * https://github.com/apache/tvm/pull/13206
  * https://github.com/apache/tvm/pull/13091
  * https://github.com/apache/tvm/pull/13050
  * https://github.com/apache/tvm/pull/12991
  * https://github.com/apache/tvm/pull/12895
  * https://github.com/apache/tvm/pull/12936
  * https://github.com/apache/tvm/pull/12914
  * https://github.com/apache/tvm/pull/13561
  * https://github.com/apache/tvm/pull/13453
  * https://github.com/apache/tvm/pull/13399
  * https://github.com/apache/tvm/pull/13383
  * https://github.com/apache/tvm/pull/13246
  * https://github.com/apache/tvm/pull/13052
  * https://github.com/apache/tvm/pull/13006
  * https://github.com/apache/tvm/pull/12866

### microNPU
  * https://github.com/apache/tvm/pull/13394
  * https://github.com/apache/tvm/pull/13281

### microTVM
  * https://github.com/apache/tvm/pull/13242
  * https://github.com/apache/tvm/pull/13051
  * https://github.com/apache/tvm/pull/12969
  * https://github.com/apache/tvm/pull/12818
  * https://github.com/apache/tvm/pull/12856
  * https://github.com/apache/tvm/pull/12495
  * https://github.com/apache/tvm/pull/12789
  * https://github.com/apache/tvm/pull/13518
  * https://github.com/apache/tvm/pull/13377
  * https://github.com/apache/tvm/pull/13324

### Misc
  * https://github.com/apache/tvm/pull/13522
  * https://github.com/apache/tvm/pull/13578
  * https://github.com/apache/tvm/pull/13339
  * https://github.com/apache/tvm/pull/13536
  * https://github.com/apache/tvm/pull/13121
  * https://github.com/apache/tvm/pull/12980
  * https://github.com/apache/tvm/pull/13001
  * https://github.com/apache/tvm/pull/13285
  * https://github.com/apache/tvm/pull/12880
  * https://github.com/apache/tvm/pull/11358

### ONNX
  * https://github.com/apache/tvm/pull/13119
  * https://github.com/apache/tvm/pull/13322

### OpenCL
  * https://github.com/apache/tvm/pull/13362
  * https://github.com/apache/tvm/pull/13563
  * https://github.com/apache/tvm/pull/13408

### Relay
  * https://github.com/apache/tvm/pull/13597
  * https://github.com/apache/tvm/pull/13343
  * https://github.com/apache/tvm/pull/13275
  * https://github.com/apache/tvm/pull/13236
  * https://github.com/apache/tvm/pull/13182
  * https://github.com/apache/tvm/pull/12886
  * https://github.com/apache/tvm/pull/13213
  * https://github.com/apache/tvm/pull/13080
  * https://github.com/apache/tvm/pull/13361

### roofline
  * https://github.com/apache/tvm/pull/13003
  * https://github.com/apache/tvm/pull/13419

### RPC
  * https://github.com/apache/tvm/pull/13420

### Runtime
  * https://github.com/apache/tvm/pull/13426
  * https://github.com/apache/tvm/pull/13177

### Target
  * https://github.com/apache/tvm/pull/12455
  * https://github.com/apache/tvm/pull/12454
  * https://github.com/apache/tvm/pull/12509

### TIR
  * https://github.com/apache/tvm/pull/13579
  * https://github.com/apache/tvm/pull/13299
  * https://github.com/apache/tvm/pull/13327
  * https://github.com/apache/tvm/pull/10940
  * https://github.com/apache/tvm/pull/13358
  * https://github.com/apache/tvm/pull/13301
  * https://github.com/apache/tvm/pull/13338
  * https://github.com/apache/tvm/pull/13194
  * https://github.com/apache/tvm/pull/13085
  * https://github.com/apache/tvm/pull/13069
  * https://github.com/apache/tvm/pull/13049
  * https://github.com/apache/tvm/pull/12794
  * https://github.com/apache/tvm/pull/12757
  * https://github.com/apache/tvm/pull/13565
  * https://github.com/apache/tvm/pull/13292
  * https://github.com/apache/tvm/pull/12949
  * https://github.com/apache/tvm/pull/12937
  * https://github.com/apache/tvm/pull/13510
  * https://github.com/apache/tvm/pull/13349
  * https://github.com/apache/tvm/pull/13217
  * https://github.com/apache/tvm/pull/13130
  * https://github.com/apache/tvm/pull/13326
  * https://github.com/apache/tvm/pull/13024
  * https://github.com/apache/tvm/pull/13033
  * https://github.com/apache/tvm/pull/13023
  * https://github.com/apache/tvm/pull/13129
  * https://github.com/apache/tvm/pull/13192
  * https://github.com/apache/tvm/pull/12939
  * https://github.com/apache/tvm/pull/12920
  * https://github.com/apache/tvm/pull/12863
  * https://github.com/apache/tvm/pull/12974
  * https://github.com/apache/tvm/pull/12916
  * https://github.com/apache/tvm/pull/13560
  * https://github.com/apache/tvm/pull/13345
  * https://github.com/apache/tvm/pull/12891
  * https://github.com/apache/tvm/pull/12766

### TOPI
  * https://github.com/apache/tvm/pull/12913
  * https://github.com/apache/tvm/pull/12864
  * https://github.com/apache/tvm/pull/13423
  * https://github.com/apache/tvm/pull/12865
  * https://github.com/apache/tvm/pull/13282
  * https://github.com/apache/tvm/pull/12499

### Torch
  * https://github.com/apache/tvm/pull/12318
  * https://github.com/apache/tvm/pull/12871

### TVMC
  * https://github.com/apache/tvm/pull/13309

### TVMScript
  * https://github.com/apache/tvm/pull/13438
  * https://github.com/apache/tvm/pull/12496
  * https://github.com/apache/tvm/pull/13190
  * https://github.com/apache/tvm/pull/13176
  * https://github.com/apache/tvm/pull/13088
  * https://github.com/apache/tvm/pull/12978
  * https://github.com/apache/tvm/pull/12900
  * https://github.com/apache/tvm/pull/12890

**Comment by echuraev** [comment]
@leandron probably we could include this patch https://github.com/apache/tvm/pull/13434? It is a good addition to OpenCL wrapper functionality (https://github.com/apache/tvm/pull/13362).

**Comment by leandron** [comment]
> @leandron probably we could include this patch #13434? It is a good addition to OpenCL wrapper functionality (#13362).

Given this release is already quite late (bringing changes from around December 2022), I will suggest that we start a new release process very soon in the next couple weeks or so, so I'd suggest we keep `v0.11.0` as is, and your PR #13434 will be brought in for the next release.

If that was a serious bug, then I'd be in favour of bringing it now, but it seems like an improvement to detect OpenCL version. Does that make sense to wait until the next release?

**Comment by echuraev** [comment]
Thank you for your reply! Yes, in this case it can be included to the next release. I just thought that if next release is not planned for a sooner time than then it might be useful to have this patch together with OpenCL wrapper. Because if user has unsupported OpenCL version and OpenCL wrapper will load this OpenCL library in runtime, then it might be some issues with incompatible OpenCL version in TVM. But if the next release process will be started soon, then I'm ok with that.

**Comment by leandron** [comment]
v0.11.0 is released, so closing this issue.
