### ISSUE TITLE
[Bug & fix] gen_requirements issue with latest setup tools

### ISSUE THREAD

**Issue by mikeseven** [apache/tvm#13911]
latest setup tools crash when doing `make cython`
The issue is in gen_requirements.py:
`    ("numpy", "<=1.23.*"),`

must be changed to:
 `   ("numpy", "<=1.23"),
`

**Comment by lhutton1** [comment]
Thanks for reporting @mikeseven, I pushed #13912 to fix this using your suggestion.

**Comment by mikeseven** [comment]
all good, thanks for super speedy fix ;-)
