### ISSUE TITLE
[CI Problem] Merge to `main` branch is not blocked on Github Actions

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#13952]
Looking at [this file](https://github.com/apache/tvm/blob/main/.asf.yaml#L57-L71), it seems that we only block merge on Jenkins flows. This issue has caused problem before where the committer missed Github Action builds and accidentally merged a PR.
Since we are using more Github Action flows, we should block merging based on those actions.

cc @driazati @gigiblender

**Comment by infdahai** [comment]
maybe just add  `tvm-ci/pr-head` in the end?  https://github.com/apache/tvm/commit/7bc90ef6f327bbfb12d09a2d7b7b11ec0ec233a5
