### ISSUE TITLE
[Bug] v0.11.0 issue with python/tvm/micro/build.py:106: MicroTVMTemplateProjectNotFoundError

### ISSUE THREAD

**Issue by leandron** [apache/tvm#14119]
While testing `v0.11.0` branch, there is an issue making many tests to fail, to do with `python/tvm/micro/build.py:106: MicroTVMTemplateProjectNotFoundError`.

```
tvm.micro.build.MicroTVMTemplateProjectNotFoundError
Stacktrace
interface_api = 'packed', use_unpacked_api = True
test_runner = AOTTestRunner(makefile='default', prologue='', epilogue='', includes=[], parameters={}, pass_config={})
    @parametrize_aot_options
    def test_add_with_params(interface_api, use_unpacked_api, test_runner):
        """Tests compilation of add with parameters"""
        input_x = relay.var("x", shape=(1, 10))
        input_y = relay.var("y", shape=(1, 10))
        input_z = relay.add(input_x, input_y)
        func = relay.Function([input_x, input_y], input_z)
    
        input_x_data = np.ones((1, 10)).astype("float32")
        input_y_data = np.random.uniform(size=(1, 10)).astype("float32")
    
        params = {"x": input_x_data}
        inputs = {"y": input_y_data}
        output_list = generate_ref_data(func, inputs, params)
    
        compile_and_run(
            AOTTestModel(
                module=IRModule.from_expr(func),
                inputs=inputs,
                outputs=output_list,
                params=params,
            ),
            test_runner,
            interface_api,
>           use_unpacked_api,
        )
tests/python/relay/aot/test_crt_aot.py:123: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python/tvm/testing/aot.py:895: in compile_and_run
    verbose=verbose,
python/tvm/testing/aot.py:834: in run_and_check
    run_and_check_body(os.path.join(tmpdir.path, "test"))
python/tvm/testing/aot.py:725: in run_and_check_body
    tvm.micro.copy_crt_config_header("crt", include_path)
python/tvm/micro/build.py:122: in copy_crt_config_header
    crt_config_path = Path(get_microtvm_template_projects(platform)) / "crt_config" / "crt_config.h"
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
platform = 'crt'
    def get_microtvm_template_projects(platform: str) -> str:
        """Find microTVM template project directory for specific platform.
    
        Parameters
        ----------
        platform : str
            Platform type which should be defined in MicroTVMTemplateProject.
    
        Returns
        -------
        str :
            Path to template project directory for platform.
        """
        if platform not in MicroTVMTemplateProject.list():
            raise ValueError(f"platform {platform} is not supported.")
    
        microtvm_template_projects = None
        for path in libinfo.find_lib_path():
            template_path = os.path.join(os.path.dirname(path), "microtvm_template_projects")
            if os.path.isdir(template_path):
                microtvm_template_projects = template_path
                break
        else:
>           raise MicroTVMTemplateProjectNotFoundError()
E           tvm.micro.build.MicroTVMTemplateProjectNotFoundError
python/tvm/micro/build.py:106: MicroTVMTemplateProjectNotFoundError
```

I'm wondering if @areusch @mehrdadh can you help troubleshoot this? It is not present in the current `main`, so I assume it was fixed, but I couldn't track it down when searching for closed/merged PRs. Any idea?

For visibility I'm tagging the Release Schedule #13586

**Comment by areusch** [comment]
i can't reproduce this locally, but i notice that the release branch CI is merging `main` back in so I wonder if there is a collision there? could you say more about how you're invoking this? we did recently change the way the CRT is built in `main`.

From https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-cpu/detail/v0.11.0/2/pipeline:
![image](https://user-images.githubusercontent.com/532957/221258371-2572d5b4-3f20-4f5a-9daf-e6dd63733af3.png)

It seems to be merging origin/main, specifically [this commit](https://github.com/apache/tvm/commit/5562d906f91c702be09392d282f5b4462a78f9fa). And I think that brings in https://github.com/apache/tvm/pull/13812/files, which requires jenkinsfile changes that aren't present in the v0.11.0 branch.

So I think this is likely a problem with our release branch CI, not an actual bug. I think we should rerun the release branch tests without merging, and then declare victory. I'm trialling a fix to the Jenkinsfile [here](https://github.com/apache/tvm/tree/areusch/fix-branch-release-ci) that hopefully will allow us to bypass the merge on non-main branches.

**Comment by leandron** [comment]
OK, so I'll validate that the tests failing here are not failing with your trial run. If they pass, then I'll push the Release Candidate and we can, for now, declare that as an issue with CI.

**Comment by leandron** [comment]
Closed via https://github.com/apache/tvm/pull/14121
