### ISSUE TITLE
[VOTE] Release Apache TVM v0.11.0.rc0

### ISSUE THREAD

**Issue by leandron** [apache/tvm#14129]
Dear TVM community,

This is a call for vote to release Apache TVM version v0.11.0.  https://github.com/apache/tvm/issues/13899 for any edits you would like to see included in the release notes.

Link to release notes:
https://github.com/apache/tvm/issues/13899

Link to release candidate:
https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.11.0-rc0/

Link to github pre-release page:
https://github.com/apache/tvm/releases/tag/v0.11.0.rc0

Everyone is welcomed to vote. Please vote by replying to this thread explicitly.

+1 = approve
+0 = no opinion
-1 = disapprove (provide reason)

NOTE: this thread is being mirrored in dev@

Vote will close Mar. 1st at 23:59PM GMT.

**Comment by tqchen** [comment]
I checked
+1 , I checked


Signatures and hashes good
LICENSE, NOTICE
Signatures and hashes
No unexpected binary files
Code compiles and import in python

**Comment by junrushao** [comment]
+1

**Comment by echuraev** [comment]
+1

**Comment by areusch** [comment]
+1

**Comment by Hzfengsy** [comment]
+1

**Comment by lhutton1** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by leandron** [comment]
Thanks for all who voted, I'll summarise the results and publish a `[RESULT]` ticket.
