### ISSUE TITLE
[Flaky Test] `tests/python/frontend/paddlepaddle/test_forward.py::test_forward_take_along_axis`

### ISSUE THREAD

**Issue by WhatGhost** [apache/tvm#14173]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/frontend/paddlepaddle/test_forward.py::test_forward_take_along_axis`

### Jenkins Links

  - https://ci.tlcpack.ai/job/tvm-gpu/job/PR-14170/1/display/redirect

this test failed and the log show "AttributeError: module 'paddle' has no attribute 'take_along_axis'"
the take_alone_axis api was added since paddle2.3 ane i pass this test on my own env using paddle2.3.2.
how can i fix this error and pass the ci.
thanks

**Comment by WhatGhost** [comment]
#14170

**Comment by jiangjiajun** [comment]
The ci image is still in paddlepaddle v2.1.3, we need to upgrade its version.

@masahi Could you help to update the docker image, I have send a pull request https://github.com/apache/tvm/pull/14206

**Comment by masahi** [comment]
@jiangjiajun Sorry I was on vacation until today. Has anyone did the actual CI update since #14206? Otherwise I'll do it tomorrow.

**Comment by masahi** [comment]
The new CPU and GPU images are being tested in https://github.com/apache/tvm/commits/ci-docker-staging

**Comment by masahi** [comment]
The CI images have been updated, please try again.
