### ISSUE TITLE
[Docs] `v0.11.dev0` still appears in the docs

### ISSUE THREAD

**Issue by leandron** [apache/tvm#14208]
I've noticed that we still have `v0.11.dev0` being shown in the documentation page at https://tvm.apache.org/docs/.

@areusch @driazati do you know how to make that to be updated to `v0.12.dev0`, which would be where we are now?

**Comment by driazati** [comment]
It looks like https://tvm.apache.org/docs/contribute/release_process.html#update-tvm-version-on-main still needs to happen (i'm seeing some `v0.11.0`s around e.g. in `conda/recipe/meta.yaml`)
