### ISSUE TITLE
[Bug] Handling Scopes in Structural Equal

### ISSUE THREAD

**Issue by psrivas2** [apache/tvm#14240]
How is scoping handled in `assert_structural_equal`?

Take an example of following two IRModules
```python
    # a relax function object created separately
    @R.function
    def foo(y: R.Object):
        return y

    @I.ir_module
    class Foo:
        @R.function
        def main(x: R.Object):
            return foo(x)

    @I.ir_module
    class Bar:
        @R.function
        def main(x: R.Object):
            @R.function
            def bar(y: R.Object):
                return y
            return bar(x)

    tvm.ir.assert_structural_equal(Foo, Bar, map_free_vars=True) # succeeds
``` 

If we compare the two IRModules `Foo` and `Bar`, structural equal check would pass as expected since their ASTs are identical (shown below). The `main` function in both defines a local func `inner func` and returns `inner_func(x)`. 
```python
@I.ir_module
class Module:
    @R.function
    def main(x: R.Tensor((16,), dtype="float32")) -> R.Tensor((16,), dtype="float32"):
        @R.function
        def inner_func(y: R.Tensor((16,), dtype="float32")) -> R.Tensor((16,), dtype="float32"):
            return y
        gv1: R.Tensor((16,), dtype="float32") = inner_func(x)
        return gv1
```

However, if we add another function `some_func` to both the modules `Foo` and `Bar` that is identical to `main`, the modules would fail structural equal test. See below:
```python
    # a relax function object created separately
    @R.function
    def foo(y: R.Object):
        return y

    @I.ir_module
    class Foo:
        @R.function
        def main(x: R.Object):
            return foo(x)
        @R.function
        def some_func(x: R.Object):
            return foo(x)

    @I.ir_module
    class Bar:
        @R.function
        def main(x: R.Object):
            @R.function
            def bar0(y: R.Object):
                return y
            return bar0(x)
        @R.function
        def some_func(x: R.Object):
            @R.function
            def bar1(y: R.Object):
                return y
            return bar1(x)

    tvm.ir.assert_structural_equal(Foo, Bar, map_free_vars=True)  # fails
```

This failure is unexpected, as `inner_func` is local to functions `main` and `some` is both the IRModules. So as long as `tvm.ir.assert_structural_equal(Foo["main"], Bar["main"])` and `tvm.ir.assert_structural_equal(Foo["some_func"], Bar["some_func"])` succeed, the module structural equality should pass. 

The root cause seems to be how we handle scoping in structural equality. When we compare `main` functions, `foo` gets mapped to `bar0` and then later when we compare `some_func`, comparing `foo` and `bar1` fails as `foo` is already mapped to `bar0`.

**Comment by slyubomirsky** [comment]
Are we certain that the var in the function `foo` is being copied/recreated? Maybe reusing the var object (pointer and all) is throwing off the free var mapping somehow.

This version works, namely:
```python
@I.ir_module
class Foo:
    @R.function
    def main(x: R.Object):
        @R.function
        def foo(y: R.Object):
            return y
        return foo(x)

    @R.function
    def some_func(x: R.Object):
        @R.function
        def foo(y: R.Object):
            return y
        return foo(x)
```

**Comment by psrivas2** [comment]
> Are we certain that the var in the function foo is being copied/recreated?

We are certain that the var is **not** being copied :), but that should not be an issue since AST nodes are immutable and reuse should be ok, no?

**Comment by slyubomirsky** [comment]
In Relay, we didn't permit vars to be reused in multiple binding sites or across multiple functions. That assumption may be used in the structural equality check. We should probably adopt a similar policy in Relax, too.

**Comment by psrivas2** [comment]
Interesting choice. Does that also hold for vars used in shape expressions or attributes?

The following module passes well formed check even though var `m` is used in shape expression across functions.
```python
bb = relax.BlockBuilder()
m = tir.Var("m", dtype="int64")
x = relax.Var("x", R.Tensor((m,), "float32"))
y = relax.Var("y", R.Tensor((m,), "float32"))

with bb.function("main", [x]):
    with bb.dataflow():
        gv = bb.emit_output(relax.op.add(x, x))
    bb.emit_func_output(gv)
with bb.function("foo", [y]):
    with bb.dataflow():
        gv = bb.emit_output(relax.op.multiply(y, y))
    bb.emit_func_output(gv)
mod = bb.get()
```

**Comment by slyubomirsky** [comment]
It's nice that it works out but I think it might not be a good idea to reuse vars across scopes. If we can guarantee that that will work, then we don't need the restriction. That would take some digging in the implementation of the structural equality checker

**Comment by psrivas2** [comment]
> It's nice that it works out but I think it might not be a good idea to reuse vars across scopes.

oh this will fail parser roundtrip structural equality check in a similar way to the original example. My concern is that it is entirely possible that a transformation pass introduces this (for example while copying over attributes or shape expressions) and leave the IR in this state which then fails structural equality check as it does not handle scopes.

**Comment by slyubomirsky** [comment]
Those passes shouldn't do it and I think we should try to catch it in the well-formedness check.

**Comment by psrivas2** [comment]
> Those passes shouldn't do it and I think we should try to catch it in the well-formedness check.

Would this only be to pass structural equality checks or would such a module actually miscompile?

**Comment by tqchen** [comment]
Var reuse issue did come up a few times and I agree that we should catch it in well-formness. 

Since having single define site of var does come handy (think it as some form of SSA), we can for example use map<var, info> without worrying about scoping.

We did also encounter similar issues in gradient passes. Utils like CopyWithNewVars helps to deal with some of the pas cases

**Comment by psrivas2** [comment]
Ah makes sense. Thanks for the explanation @slyubomirsky and @tqchen !
Closing this issue as this is intended behavior.
