### ISSUE TITLE
[Bug] NotImplementedError when converting pytorch module

### ISSUE THREAD

**Issue by 0x00-pl** [apache/tvm#14268]
File "/home/pl/github/test_torch/pytorch_rendering/graph_to_tvm.py", line 7, in graph_to_tvm
    mod, params = relay.frontend.from_pytorch(scripted_model, shape_list)
  File "/home/pl/github/test_torch/venv/lib/python3.8/site-packages/tvm/relay/frontend/pytorch.py", line 4517, in from_pytorch
    converter.report_missing_conversion(op_names)
  File "/home/pl/github/test_torch/venv/lib/python3.8/site-packages/tvm/relay/frontend/pytorch.py", line 3722, in report_missing_conversion
    raise NotImplementedError(msg)
NotImplementedError: The following operators are not implemented: ['prims::broadcast_in_dim', 'prims::mul', 'prims::squeeze', 'prims::split_dim', 'aten::slice_scatter', 'prims::pow', 'prims::sum', 'prims::cat', 'prims::amax', 'prims::ne', 'prims::exp', 'prims::view_of', 'prims::convert_element_type', 'prims::add', 'prims::collapse_view', 'prims::where', 'prims::sub', 'prims::div', 'prims::transpose', 'prims::log', 'prims::tanh', 'prims::copy_to', 'aten::as_strided', 'prims::neg', 'prims::var', 'prims::rsqrt', 'aten::alias']
python-BaseException

**Comment by masahi** [comment]
You are probably using `torch.jit.script`. Please use tracing instead.

**Comment by 0x00-pl** [comment]
https://tvm.apache.org/docs/how_to/compile_models/from_pytorch.html#load-a-pretrained-pytorch-model

I followed this instruction. From a GraphModule construct into ScriptModule.

    tracer = Tracer()
    graph = tracer.trace(my_model)
    graph_model = GraphModule(tracer.root, graph)
    scripted_model = torch.jit.trace(graph_model, example_inputs).eval()
