### ISSUE TITLE
[Bug][Contrib][CUTLASS] matmul+bias template

### ISSUE THREAD

**Issue by spectrometerHBH** [apache/tvm#14335]
https://github.com/apache/tvm/blob/unity/python/tvm/contrib/cutlass/build.py#L778
https://github.com/apache/tvm/blob/unity/python/tvm/contrib/cutlass/gemm_operation.py#L372

Note here that if bias has 2 dims, `ldc` will be N.
If the bias is of shape (1, N), I suppose the `ldc` should still be 0?

It seems unlikely for the bias to be of shape (M, N), but the residual.

https://github.com/apache/tvm/blob/unity/tests/python/relax/test_codegen_cutlass.py#L398
It looks to me that only 1D bias cases are tested.

**Comment by spectrometerHBH** [comment]
cc @masahi @yelite

**Comment by masahi** [comment]
yeah [gemm_operation.py#L372](https://github.com/apache/tvm/blob/unity/python/tvm/contrib/cutlass/gemm_operation.py#L372) was added last week to distinguish bias vs residual add case. Indeed I was assuming that bias for matmul is always passed as a 1D tensor. 

I'll fix this in the next PR.
