### ISSUE TITLE
 module 'tvm.relay.op.strategy' has no attribute 'conv3d_winograd_without_weight_transform_strategy'

### ISSUE THREAD

**Issue by shaunakjoshi12** [apache/tvm#14392]
Hi I am executing a function called
 * *reg.register_strategy(
    "nn.contrib_conv3d_winograd_without_weight_transform",
    strategy.conv3d_winograd_without_weight_transform_strategy,
* *

and from https://github.com/apache/tvm/blob/main/python/tvm/relay/op/nn/_nn.py#L462 it throws the above error written in the subject.

**Comment by masahi** [comment]
It's defined in https://github.com/apache/tvm/blob/e5ae4347ddf492a9e017dd1dba47df364a27a197/python/tvm/relay/op/strategy/generic.py#L617

**Comment by shaunakjoshi12** [comment]
Yes it is I see however the it fails execution in _nn.py itself. Sorry but I still can't understand any explanation for this
