### ISSUE TITLE
[CI Problem] how to set log output level ?

### ISSUE THREAD

**Issue by wangzy0327** [apache/tvm#14573]
how to control the output level of log ?
If I want to print only higher output level instead of LOG INFO , what can I do to set the log level config?
below the code
```
const std::vector<std::string> fwd_algo_names{"CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_GEMM",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_DIRECT",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_FFT",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD",
                                                "CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED"};

  auto best_algo = perf_results[0].algo;
  LOG(INFO) << "\tCUDNN Found " << returned_algo_count << " fwd algorithms, choosing "
            << fwd_algo_names[best_algo];
  for (int i = 0; i < returned_algo_count; ++i) {
    LOG(INFO) << "\t\t" << i << ") " << fwd_algo_names[perf_results[i].algo]
              << " - time: " << perf_results[i].time << " ms"
              << ", Memory: " << perf_results[i].memory;
  }
```

**Comment by masahi** [comment]
You cannot turn off `LOG(INFO)`. We can replace `LOG` with `DLOG` to control verbosity if you want.

**Comment by wangzy0327** [comment]
> You cannot turn off `LOG(INFO)`. We can replace `LOG` with `DLOG` to control verbosity if you want.

@masahi How to use ```DLOG``` to control verbosity ? Can you provide case study?

**Comment by masahi** [comment]
See 

https://github.com/apache/tvm/blob/7bc41ecca26204112f266d146371d0e867ec1240/include/tvm/runtime/logging.h#L617-L621

https://github.com/apache/tvm/blob/7bc41ecca26204112f266d146371d0e867ec1240/include/tvm/runtime/logging.h#L460-L469

**Comment by wangzy0327** [comment]
@masahi I set ```TVM_LOG_DEBUG=-1``` ,but the DLOG(WARNING) still output the result refer [VLOG](https://github.com/apache/tvm/blob/main/docs/dev/how_to/debugging_tvm.rst)
