### ISSUE TITLE
[Docs] when will unity comes to main?

### ISSUE THREAD

**Issue by lucasjinreal** [apache/tvm#14763]
Recently mlc-llm draw a lot attentions but people who want try build themself will clone the main, but it was wrong, just wondering any time schedualings on  when will unity comes to main?

**Comment by tqchen** [comment]
Thank you for asking and interest in TVM Unity. 

Please checkout https://discuss.tvm.apache.org/t/establish-tvm-unity-branch/14244 on some of the notes and feel free to followup there. We love to support our broader community members.
