### ISSUE TITLE
[Bug] Error reported when set(USE_DNNL C_SRC)

### ISSUE THREAD

**Issue by qzylalala** [apache/tvm#14803]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

I have built oneDNN following this link https://oneapi-src.github.io/oneDNN/dev_guide_build.html.
And I modify the config.cmake `set(USE_DNNL C_SRC)`.
It should work fine.

### Actual behavior

I got error reported. And it seems the problem is the version of oneDNN?
```C++
/home/qzylalala/work_space/tvm/src/relay/backend/contrib/dnnl/query_layout.cc:137:17: error: ‘const struct dnnl::memory::desc’ has no member named ‘data’; did you mean ‘data_’?
   dim_chars[md->data.ndims] = '\0';
                 ^~~~
                 data_
/home/qzylalala/work_space/tvm/src/relay/backend/contrib/dnnl/query_layout.cc: In function ‘std::__cxx11::string tvm::relay::contrib::get_optimal_layout_for_conv(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)’:
/home/qzylalala/work_space/tvm/src/relay/backend/contrib/dnnl/query_layout.cc:257:47: error: ‘desc’ is not a member of ‘dnnl::convolution_forward’
   auto conv_desc = dnnl::convolution_forward::desc(
                                               ^~~~
/home/qzylalala/work_space/tvm/src/relay/backend/contrib/dnnl/query_layout.cc: In function ‘std::__cxx11::string tvm::relay::contrib::get_optimal_layout_for_conv_transpose(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)’:
/home/qzylalala/work_space/tvm/src/relay/backend/contrib/dnnl/query_layout.cc:346:51: error: ‘desc’ is not a member of ‘dnnl::deconvolution_forward’
   auto deconv_desc = dnnl::deconvolution_forward::desc(
```

### Environment

Operating System: Ubuntu1804
TVM version: Latest
LLVM: 17.0
OneDNN: 3.1.0

### Steps to reproduce

```bash
# build oneDNN
git clone https://github.com/oneapi-src/oneDNN.git
mkdir -p build
cd build
cmake ..
make -j16
cmake --build . --target install

# build tvm
git clone --recursive https://github.com/apache/tvm tvm
mkdir build
cp cmake/config.cmake build
# modify config.cmake 
cmake ..
make -j16
```

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by masahi** [comment]
C_SRC is not maintained. Please use the json one.
