### ISSUE TITLE
[Bug] Wrong lowered TIR with symbolic input buffer

### ISSUE THREAD

**Issue by MasterJH5574** [apache/tvm#14834]
@wrongtest-intellif Hello, I noticed an abnormal issue after #14021 being merged.

https://gist.github.com/MasterJH5574/64e9dca54cc08cd0131126efd55cfac7

In the gist above, the original TIR function is one that takes a symbolic var and creates a buffer whose shape depends on the symbolic variable. The lowered TIR function with this PR is abnormally complicated. I’m not sure if it is a semantically correct one, but obviously the lowered TIR is way too complicated and involves much more redundant computation. This is what we need to fix.

Would you please help take a look and fix the issue? Thanks in ahead!

**Comment by tqchen** [comment]
@wrongtest-intellif would be great to visit this, since it seems to impact most of dyn shape schedules

**Comment by wrongtest-intellif** [comment]
Do we have one more workloads to verify the fix?

**Comment by MasterJH5574** [comment]
Fixed in #14866
