### ISSUE TITLE
[Bug] Install project. 

### ISSUE THREAD

**Issue by xioaxin** [apache/tvm#14860]
### Expected behavior
I follow the install document and happen these following errors, how can I do to solve problem?
### Actual behavior
/usr/local/llvm/bin/ld.lld: 1:ELF▒4t▒@▒@8: not found
/usr/local/llvm/bin/ld.lld: 2: Syntax error: word unexpected (expecting ")")
collect2: error: ld returned 2 exit status
xterm-256colormake[2]: *** [CMakeFiles/tvm_runtime.dir/build.make:195: libtvm_runtime.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:983: CMakeFiles/tvm_runtime.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/llvm/bin/ld.lld: 1:ELF▒4t▒@▒@8: not found
/usr/local/llvm/bin/ld.lld: 2: Syntax error: word unexpected (expecting ")")
collect2: error: ld returned 2 exit status
make[2]: *** [CMakeFiles/tvm.dir/build.make:1469: libtvm.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:956: CMakeFiles/tvm.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
### Environment
Ubuntu:20.04 (wsl)
LLVM: 10.0.0
Cmake: 3.25.2

**Comment by masahi** [comment]
General questions should be posted to https://discuss.tvm.apache.org/
