### ISSUE TITLE
[Tracking Issue][Unity][WebGPU] Supporting fp16 in WebGPU backend

### ISSUE THREAD

**Issue by jzm-intel** [apache/tvm#14905]
### This issue is to track progress for FP16 in WebGPU Backend
- [x] P1. Support FP16 dtype in WGSL codegen (#14904)

### Triage

* backend: webgpu

cc @quic-sanirudh

**Comment by tqchen** [comment]
This is now landed

**Comment by tqchen** [comment]
Try out https://github.com/mlc-ai/web-llm/tree/main#get-started with `RedPajama-INCITE-Chat-3B-v1-q4f16_0`
