### ISSUE TITLE
[Docs] a misspelling in "User Tutorial>Making your Hardware Accelerator TVM-ready with UMA" 

### ISSUE THREAD

**Issue by SStarver** [apache/tvm#14992]
UMA is a nice project for AI compilers, wish to see more tutorials committed.

### Documentation Title & Type
Path: Docs>User Tutorial>Making your Hardware Accelerator TVM-ready with UMA
Title: Making your Hardware Accelerator TVM-ready with UMA
Type:  User Tutorial

### Additions/Changes Requested
  There seems to be a misspelling in "User Tutorial>Making your Hardware Accelerator TVM-ready with UMA" 
  "revist"  better corrected to be "revisit".

![image](https://github.com/apache/tvm/assets/108868933/222d4ab9-a8ee-431b-83ff-3467c7552b52)

**Comment by Hzfengsy** [comment]
Feel free to send a PR to fix it :)

**Comment by cchung100m** [comment]
Hi @SStarver @Hzfengsy 

I think we can close this issue if you agreed. :grinning:

**Comment by Hzfengsy** [comment]
Thanks for your fixes. Let's close it as completed

**Comment by SStarver** [comment]
> Feel free to send a PR to fix it :)
 Happy to do so next time.
