### ISSUE TITLE
[Docs] You should update your copyright year from 2020

### ISSUE THREAD

**Issue by SamuelMarks** [apache/tvm#15043]
I usually check the bottom of websites to see if the project(s) represented are still maintained. (then I check GitHub and other sources)

You ARE maintained but 3 years out as per the website 📃 
https://tvm.apache.org

Time to update that©️ !

**Comment by cchung100m** [comment]
Hi @SamuelMarks 

Thanks for the feedback and I will handle it soon.

**Comment by cchung100m** [comment]
Hi @yzh119 @SamuelMarks 

Maybe we can close this issue now.
