### ISSUE TITLE
[Bug] Get"Did you forget to bind?" Error , when I build stable-diffusion-model-v1.5  with relax.build

### ISSUE THREAD

**Issue by felixslu** [apache/tvm#15108]
### Expected behavior

relax.build is OK!

### Actual behavior

Get"Did you forget to bind?" Error , when I build stable-diffusion-model-v1.5  with relax.build.

### Environment

https://github.com/mlc-ai/web-stable-diffusion
Under repo above,I try to auto-tunning it with  cuda target, but failed!

https://github.com/mlc-ai/web-stable-diffusion/issues/39

### Steps to reproduce

python build.py

### Triage

* needs-triage

**Comment by masahi** [comment]
Please use https://github.com/mlc-ai/web-stable-diffusion/issues/39
