### ISSUE TITLE
[Bug] Use asymmetric operations will cause inconsistent 

### ISSUE THREAD

**Issue by cxx122** [apache/tvm#15209]
relate to https://github.com/apache/tvm/issues/15196#issue-1784616103
I tried it on the latest version of tvm and converted the te program to TVMScript, but the schedule I got was still obtained by autoscheduler. The results show that these schedules still lead to inconsistencies. I am not sure whether the schedule of the meta-schedule is the same as the schedule of the autoscheduler, and further attempts are needed.

If the metaschedule test is necessary, is there an exact process that can be provided, TIA.

### TVMScript
```
# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func
    def main(A: T.Buffer((64, 64), "float32"), B: T.Buffer((64,), "float32")):
        T.func_attr({"from_legacy_te_schedule": T.bool(True), "global_symbol": "main", "tir.noalias": T.bool(True)})
        for i in range(64):
            B[i] = T.float32(0)
            for k in range(64):
                A_1 = T.Buffer((4096,), data=A.data)
                B[i] = B[i] - A_1[i * 64 + k]
```

### After Schedule

```
# from tvm.script import ir as I
# from tvm.script import tir as T

@I.ir_module
class Module:
    @T.prim_func
    def main(A: T.Buffer((64, 64), "float32"), B: T.Buffer((64,), "float32")):
        T.func_attr({"from_legacy_te_schedule": T.bool(True), "global_symbol": "main", "tir.noalias": T.bool(True)})
        B_rf = T.allocate([64], "float32", "global")
        B_rf_1 = T.Buffer((64,), data=B_rf)
        for i in T.parallel(64):
            B_rf_1[i] = T.float32(0)
            for k_outer in range(64):
                A_1 = T.Buffer((4096,), data=A.data)
                B_rf_1[i] = B_rf_1[i] - A_1[i * 64 + k_outer]
        for ax0 in T.parallel(64):
            B[ax0] = T.float32(0)
            B[ax0] = B[ax0] - B_rf_1[ax0]
```

### Environment

Operating System: Ubuntu 18.04
TVM version: v0.13.dev0

### Triage

* tune:auto_scheduler
* tir:schedule 
* tir:transform

**Comment by tqchen** [comment]
In this particular case, TVMScript is better. For this particular case, we do require the comm_reducer to be communicative and the system won't check the case
