### ISSUE TITLE
[Bug] [Unity] segfault on MergeCompositeFunctions with pytorch hub resnet18

### ISSUE THREAD

**Issue by slai-nick** [apache/tvm#15227]
### Expected behavior

No segfault happening during `MergeCompositeFunctions` pass. 

### Actual behavior

A segfault occurs, I didn't get any stack trace info unfortunately:
```shell
!!!!!!! TVM encountered a Segfault !!!!!!!
Stack trace:

zsh: segmentation fault  python bug.py
```

### Environment

- MacOS Ventura (13.3.1) with M1 chip (also tested on windows + docker, using an image based on cli_minimal)
- TVM unity branch, pulled as of today

### Steps to reproduce

I encountered this issue using pytorch resnet18 from the hub imported via `from_fx`:

```python
import numpy as np
from torch import hub, fx

from tvm.relax.frontend.torch import from_fx
from tvm.relax import transform
from tvm.relax.dpl import is_op, wildcard


model = hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=False).eval()
traced_model = fx.symbolic_trace(model)
input_info = [((1, 3, 224, 224), "float")]
ir_mod = from_fx(traced_model, input_info)

patterns = [
        ("foo.matmul", is_op("relax.matmul")(wildcard(), wildcard())),
]
ir_mod = transform.FuseOpsByPattern(patterns)(ir_mod)
# segfault with the following line:
ir_mod = transform.MergeCompositeFunctions()(ir_mod)
```

### Triage

* relax:transform

cc @quic-sanirudh

**Comment by masahi** [comment]
I don't get a segfault using the latest commit as of today.

**Comment by slai-nick** [comment]
I also don't get the segfault anymore after updating (as of today).
