### ISSUE TITLE
[FRONTEND][PYTORCH] Relay pytorch frontend does not support aten:scaled_dot_product_attention

### ISSUE THREAD

**Issue by rebel-shshin** [apache/tvm#15361]
Hi, I just wondering that is there any plan to support scaled_dot_product_attention OP which is included in pytorch2.0?

cc @shingjan @yelite

**Comment by mshr-h** [comment]
I'll try to work on it.

**Comment by mshr-h** [comment]
@rebel-shshin 
The initial implementation is done. #16143 
But haven't tested with the actual model.
Can you provide the script for CLIP model conversion if possible? https://github.com/apache/tvm/issues/15663#issue-1879827100

**Comment by rebel-shshin** [comment]
Hi, @mshr-h. Thanks for the update. I test the CLIP model using [HF stable diffusion](https://huggingface.co/runwayml/stable-diffusion-v1-5), and confirmed the patch working.
