### ISSUE TITLE
[Bug] TVM doesn't buid with cython 3.0.0 (latest)

### ISSUE THREAD

**Issue by mikeseven** [apache/tvm#15397]
### Expected behavior

```make cython``` should not crash

### Actual behavior

crash

### Environment

mac or linux, python 3.10, cython latest

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

### Triage

* needs-triage
* build

**Comment by lhutton1** [comment]
Hi @mikeseven, please see https://github.com/apache/tvm/pull/15346 which proposes a fix

**Comment by mikeseven** [comment]
Thanks @lhutton1. I hope we can lend the fix in main branch and benefit from cython 3 improvements cleanly rather than hacking tvm.

**Comment by tqchen** [comment]
I think it can be closed by #15346
