### ISSUE TITLE
[Tracking Issue] Transformers support 

### ISSUE THREAD

**Issue by manjeetbhati** [apache/tvm#15516]
I tried compiling llama model using examples on apache-tvm.org and got many errors, I have weights file (.pth) and checkpoint file (.chk), is transformers library already integrated into TVM? if yes where can I find the examples? couldn't find it on apache-tvm.org docs.

### This issue is to track progress for Transformers support in TVM
-

### Triage

* needs-triage

**Comment by tqchen** [comment]
please checkout https://github.com/mlc-ai/mlc-llm

**Comment by manjeetbhati** [comment]
thanks,

I see it's supports below devices

iPhone, iPad;
Android phones;
Apple Silicon and x86 MacBooks;
**AMD, Intel and NVIDIA GPUs via Vulkan on Windows and Linux;**
NVIDIA GPUs via CUDA on Windows and Linux;
WebGPU on browsers (through companion project [WebLLM](https://github.com/mlc-ai/web-llm/tree/main)).

it says **AMD, Intel and NVIDIA GPUs via Vulkan on Windows and Linux;** would it work on Xeon CPUs?

**Comment by tqchen** [comment]
atm it focuses on GPU support, but the same flow should also be resuable for CPU, although there is no effort atm
