### ISSUE TITLE
[VOTE] Clarify Community Strategy Decision Process

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#15521]
Hi Community:

This is a formal procedural voting thread about the proposal to clarify the community strategy 
decision process. The main intent here is for the community to collectively choose how we 
would like to make strategic decisions in the TVM community.

This is a procedural decision on how we would make strategic decisions. The ASF process enables 
the community to have a collective conversation that gains clarity of everyone’s view and then 
comes to a resolution together. The vote for procedural issues takes a majority binding.

We have had many related conversations over the past year. We know that there are different 
opinions on how we should operate as a community. We also know what process roughly looks like
under each category of opinions. This vote is for accepting a version that aims to provide a clear and 
concise process for strategy decisions (see text below). I pick this one as this seems to be what 
most prefer in the discussions (of course, the community should decide whether accepting it).

I would encourage everyone to take a look at the RFC and discussion thread[1][2] so you are aware 
of all the views before casting your vote

------------
[1] https://github.com/apache/tvm-rfcs/pull/102
[2] https://discuss.tvm.apache.org/t/process-rfc-clarify-community-strategy-decision-process/15463/10

------------
## Summary

Machine Learning Compilation (MLC) is an emerging field in fast development.
With the tremendous help from the whole community, it’s exciting to see that TVM 
delivers significant needs from and to developers and thus has become widely popular 
in both academia and industry. As the community pushes for different goals that help each other, 
naturally, there are strategy decision points about overall directions and new modules adoptions.
These decisions are not fine-grained code-level changes but are important for a
community to be viable in the long term. The process of bringing those changes is less 
clarified to the community, and hurdles can be high. We have made attempts in the past to 
bring more verbose processes, but this has proven to be less successful. One observation 
is that it is hard for broader volunteer developers and community members to follow complicated
processes. Additionally, different members can have different interpretations of how to do things, 
leading to stagnation and lack of participation from volunteer members. We are in a different world 
now in the case of ML/AI ecosystem, and it is critical for the community to be able to make 
collective decisions together and empower the community. Following the practices of existing 
ASF projects (e.g. hadoop), we propose to use a simple process for strategic decisions.

## Proposal: Strategy Decision Process

We propose the following clarification of the strategy decision process: It takes lazy 2/3 majority 
(at least 3 votes and twice as many +1 votes as -1 votes) of binding decisions to make the following 
strategic decisions in the TVM community:

- Adoption of a guidance-level community strategy to enable new directions or overall project evolution.
- Establishment of a new module in the project.
- Adoption of a new codebase: When the codebase for an existing, released product is to be replaced 
   with an alternative codebase.If such a vote fails to gain approval, the existing code base will continue. 
   This also covers the creation of new sub-projects within the project.

All these decisions are made after community conversations that get captured as part of the summary.

----------------

This vote will be open for at least one week, please vote:

+1 If you support we adopt the above process 
-0 
-1 because...

**Comment by Hzfengsy** [comment]
+1. After reviewing all the comments from the related threads and wearing the community hat, I think this is the proper process

**Comment by sunggg** [comment]
+1 Fully support this proposal.

**Comment by csullivan** [comment]
+1

**Comment by comaniac** [comment]
+1

**Comment by jwfromm** [comment]
+1

**Comment by yongwww** [comment]
+1

**Comment by vinx13** [comment]
+1. I’m supportive after reviewing the community discussions and wearing the hat as a PMC member

**Comment by junrushao** [comment]
+1 Carefully reading all the response from all the community, I'm even more convinced that it is the right operational guideline for us to pursue as a whole community, because to any strategic decision, it helps incorporate the voice of both sides and sets a clear guideline to pass.

**Comment by psrivas2** [comment]
+1

**Comment by LeshengJin** [comment]
+1

**Comment by farshidsp** [comment]
+1

**Comment by MasterJH5574** [comment]
+1

**Comment by cyx-6** [comment]
+1

**Comment by spectrometerHBH** [comment]
+1

**Comment by zhiics** [comment]
+1

**Comment by FrozenGene** [comment]
+1

**Comment by ZihengJiang** [comment]
+1

**Comment by quic-sanirudh** [comment]
+1

**Comment by mbaret** [comment]
+1

**Comment by leandron** [comment]
-0

I think the text could be improved, but not standing in the way.

In summary, it is time we agree to disagree in some aspects and move forward as a community.

**Comment by Lunderberg** [comment]
+1

**Comment by yzh119** [comment]
+1 
I have no problem w/ the decision process, it's important to figure out a way to reach a consensus on strategic decisions in TVM community and 2/3 majority looks reasonable to me.

**Comment by xqdan** [comment]
+1

**Comment by jikechao** [comment]
+1

**Comment by zxybazh** [comment]
+1

**Comment by hsaputra** [comment]
+1

I support this proposal.
As the community grows, we will have different interests and focus areas. Great to have strategy of decision making to get us moving as healthy community!

**Comment by merrymercy** [comment]
+1 I support this

**Comment by tqchen** [comment]
thanks everyone who voted, link to the result thread https://github.com/apache/tvm/issues/15618
