### ISSUE TITLE
CUDA_ARCHITECTURES Problem

### ISSUE THREAD

**Issue by wslong36** [apache/tvm#15606]
Hi Community:
when I star to cmake .. in tvm/build, I got this error:

CMake Error in CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "tvm_runtime_objs".

CMake Error in CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "tvm".

CMake Error in CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "tvm_runtime".

**Comment by masahi** [comment]
Maybe you don't have CUDA installed correctly. Please use https://discuss.tvm.apache.org/ for such question.

**Comment by wslong36** [comment]
> CUDA_ARCHITECTURES
But, nvcc -V is right, torch.cuda.is_available() is True
I'm confused.
