### ISSUE TITLE
[Flaky Test] `tests/python/unittest/test_autotvm_droplet_tuner.py::test_multi_filter`

### ISSUE THREAD

**Issue by ashutosh-arm** [apache/tvm#15611]
These tests were found to be flaky (intermittently failing on `main` or failed in a PR with unrelated changes). See [the docs](https://github.com/apache/tvm/blob/main/docs/contribute/ci.rst#handling-flaky-failures) for details.

### Tests(s)

  - `tests/python/unittest/test_autotvm_droplet_tuner.py::test_multi_filter`

This test has been failing locally with latest build of ci_cpu docker image.

cc @lhutton1 @Liam-Sturge @leandron

**Comment by lhutton1** [comment]
Thanks for reporting @ashutosh-arm, curious if this is still an issue?

**Comment by ashutosh-arm** [comment]
It has not recurred in the last two weeks. I am happy to close it and the corresponding issue.
