### ISSUE TITLE
[FRONTEND][TENSORFLOW] Support separable_conv2d and depthwise_conv2d

### ISSUE THREAD

**Issue by olesalscheider** [apache/tvm#1563]
It would be nice if the Tensorflow frontend would support separable_conv2d and depthwise_conv2d.

In Tensorflow, these operations are composed of the convolution itself and a space_to_batch operation (that handles the dilation rate): https://github.com/tensorflow/tensorflow/blob/62cf06bfa94af4c97cdd8ca5c4faab49accc7a12/tensorflow/python/ops/nn_impl.py#L550

So either the Tensorflow frontend should get support for space_to_batch, or the pattern of tensorflow operations should be replaced by a single tvm operation for a convolution with dilation. But until now, the frontend does not allow to match a pattern but only single operations.

**Comment by srkreddy1238** [comment]
@olesalscheider  Thanks for raising this issue.

We do support depthwise as a special case of group convolution to an extent.
Let me analyse the feasibility to support separable convolution and get back on this.

**Comment by sdll** [comment]
This seems like a stale issue.
