### ISSUE TITLE
[Bug] [Unity] Error with 'munmap_chunk(): invalid pointer' when importing 'torch' after importing 'tvm'

### ISSUE THREAD

**Issue by Thrsu** [apache/tvm#15669]
I encountered an error when importing the 'torch' library in Python after importing 'tvm' previously. The error message displayed was "Error in `python': munmap_chunk(): invalid pointer: 0x00007f0c685b53f0". However, importing only 'tvm' without importing 'torch' beforehand or importing 'tvm' after importing 'torch' does not trigger the error.

### Actual behavior

```
*** Error in `python': munmap_chunk(): invalid pointer: 0x00007f0c685b53f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7f0d11a467f5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7f0d11a536e8]
/usr/lib/x86_64-linux-gnu/libLLVM-8.so.1(+0x161dc4c)[0x7f0cfb469c4c]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a008)[0x7f0d11a09008]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a055)[0x7f0d11a09055]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0x7f0d119ef847]
python(+0x1c24db)[0x55a5a61814db]
======= Memory map: ========
55a5a5fbf000-55a5a601a000 r--p 00000000 fd:00 177515246                  /workplace/software/miniconda3/envs/torch_gpu/bin/python3.7
55a5a601a000-55a5a61af000 r-xp 0005b000 fd:00 177515246                  /workplace/software/miniconda3/envs/torch_gpu/bin/python3.7
55a5a61af000-55a5a624d000 r--p 001f0000 fd:00 177515246                  /workplace/software/miniconda3/envs/torch_gpu/bin/python3.7
55a5a624e000-55a5a6251000 r--p 0028e000 fd:00 177515246                  /workplace/software/miniconda3/envs/torch_gpu/bin/python3.7
55a5a6251000-55a5a62ba000 rw-p 00291000 fd:00 177515246                  /workplace/software/miniconda3/envs/torch_gpu/bin/python3.7
...
Aborted (core dumped)
```

### Environment

- TVM version: v0.14.dev0-595-gfa0d35b
- Python version: Python 3.7.10
- torch version: 1.7.0

### Steps to reproduce

```python
import tvm
import torch
```

### Triage

* needs-triage

cc @quic-sanirudh

**Comment by lhutton1** [comment]
Hi @Thrsu perhaps you can try the suggestion here: https://github.com/apache/tvm/issues/9362#issuecomment-955263494

**Comment by Thrsu** [comment]
> Hi @Thrsu perhaps you can try the suggestion here: [#9362 (comment)](https://github.com/apache/tvm/issues/9362#issuecomment-955263494)

Thank you for your prompt response!
