### ISSUE TITLE
[CI Problem] ci_gpu fails to build due to missing oneflow version

### ISSUE THREAD

**Issue by ashutosh-arm** [apache/tvm#15754]
ERROR: No matching distribution found for oneflow==0.7.0+cpu

The error might be new as the [last gpu docker build](https://hub.docker.com/r/tlcpack/ci-gpu/tags) is 4 months old. When I checked the [command line](https://github.com/apache/tvm/blob/67df20faeeffaf3c145698783f6cd157b8cdbd9c/docker/install/ubuntu_install_oneflow.sh#L25) that is used to install oneflow dependency, the source https://release.oneflow.info/ seems to be unreachable. What should be the way out?

### Branch/PR Failing

https://github.com/apache/tvm/pull/15747

### Jenkins Link

https://ci.tlcpack.ai/blue/rest/organizations/jenkins/pipelines/tvm-docker/branches/PR-15747/runs/2/nodes/74/steps/240/log/?start=0

* needs-triage

**Comment by leandron** [comment]
cc @hhhfccz @BBuf for visibility.

**Comment by lhutton1** [comment]
fixed by https://github.com/apache/tvm/pull/15836
