### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hlacikd** [apache/tvm#15770]
### Actual behavior

When feeding data via *module.set_input* , inference time is **4fps**, without it it reaches over **100fps**!

Example
```
target = tvm.target.mali(model="rk3588")
loaded_lib = tvm.runtime.load_module("lpr_model_0910_autotvm.tar")
dev = tvm.device(str(target), 0)
module = graph_executor.GraphModule(lib["default"](dev))
```
this gives over 100fps :
```
import time

tic = time.time()
for i in range(100):
    module.run()
fps = 100 / (time.time() - tic)
print(f"FPS: {fps:.2f}")
```

adding set_input, slowes it down to 4.67fps!

```
import time

tic = time.time()
for i in range(100):
    module.set_input(input_name, tvm.nd.array(img_data))
    module.run()
fps = 100 / (time.time() - tic)
print(f"FPS: {fps:.2f}")
```

img_data is just normalized image
```
import cv2

def load_image(image_path="./lp.jpg"):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (94, 24))
    return image

img_data = load_image().astype(np.float32)
img_data /= 255.0
img_data = img_data.transpose((2, 0, 1))
img_data = img_data[np.newaxis, :]
```

how can i make it faster? is really feeding mali gpu taking so long?
this makes model run faster (~30fps on cpu itself)

### OpenCL
root@notebook-68c585ffc-c2fx4:/app/notebook# clinfo
arm_release_ver: g13p0-01eac0, rk_so_ver: 3
Number of platforms                               1
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 3.0 v1.g13p0-01eac0.a8b6f0c7e1f83c654c60d1775112dbe4
  Platform Profile                                FULL_PROFILE

### ApacheTVM

apache-tvm-src-v0.13.0.tar.gz
--

[apache-tvm-src-v0.13.0.tar.gz](https://www.apache.org/dyn/closer.lua/tvm/tvm-v0.13.0/apache-tvm-src-v0.13.0.tar.gz)

### OS
Welcome to Armbian 23.8.1 Jammy with Linux 5.10.160-legacy-rk35xx

### HW
Radxa Rock 5B (RK3588]

**I am open to help with testing of this issue as i have plenty of these boards**

**Comment by masahi** [comment]
```
import time

tic = time.time()
for i in range(100):
    module.run()
fps = 100 / (time.time() - tic)
print(f"FPS: {fps:.2f}")
```

This code is not correctly measuring the elapsed time. `.run()` is asynchronous, so it hasn't been finished when it returns.
