### ISSUE TITLE
[Bug] [VTA] Running Example/Test for VTA

### ISSUE THREAD

**Issue by smtalds** [apache/tvm#15787]
I am new for tvm/vta. I fallowed intstalling guide for tvm and vta. I am using ethernet switch for pynq and my local machine. I can start rpc_server. But i can not run any example , tutorial or test. I always get different error. One of them for vta_get_started.py : 
![image](https://github.com/apache/tvm/assets/59387657/98968b9c-25d7-4e5c-8f0e-aae3f8134a98)
 or matrix_multiply.py
![image](https://github.com/apache/tvm/assets/59387657/d6ee1afb-7165-459d-9dec-d75624f1386a)
or deploy_detection.py 
![image](https://github.com/apache/tvm/assets/59387657/3a6809f3-2d84-422c-b8d3-a9b8106bc862)

I cant found any solution. What is the main problem ?

**Comment by smtalds-knt** [comment]
You have to re-built for vta on FPGA. 

Resource : https://discuss.tvm.apache.org/t/vta-recursion-error/7271/26?u

**Comment by smtalds** [comment]
You have to rebuild FPGA two times. 
Resource : https://discuss.tvm.apache.org/t/vta-recursion-error/7271/26?u
