### ISSUE TITLE
[Bug] Unable to build TVM with LLVM 12.0.0

### ISSUE THREAD

**Issue by Railcalibur** [apache/tvm#16013]
I am attempting to rebuild TVM from scratch with LLVM 12.0.0, which was download from pre-build. This used to work, but now I'm getting a make error, as shown below. 

Actually, I found llvm supports `VendorSignatures` from version 12.0.1. Therefore, when using LLVM 12.0.0, it may result in compilation errors.

https://github.com/apache/tvm/blob/main/src/target/llvm/llvm_module.cc#L500
```cpp
TVM_REGISTER_GLOBAL("target.llvm_get_system_x86_vendor").set_body_typed([]() -> String {
#if TVM_LLVM_VERSION >= 120
#if defined(__i386__) || defined(_M_IX86) || defined(__x86_64__) || defined(_M_X64)
  using namespace llvm::sys::detail::x86;
  const auto x86_sign = getVendorSignature();
  if (x86_sign == VendorSignatures::GENUINE_INTEL)
    return "intel";
  else if (x86_sign == VendorSignatures::AUTHENTIC_AMD)
    return "amd";
  else if (x86_sign == VendorSignatures::UNKNOWN)
    return "unknown";
#endif
#endif
  return "unimplemented";
});
```

### Expected behavior

TVM successfully compiles

### Actual behavior

I get the following error:

```shell
tvm/src/target/llvm/llvm_module.cc: In lambda function:
tvm/src/target/llvm/llvm_module.cc:502:38: error: 'x86' is not a namespace-name
  502 |   using namespace llvm::sys::detail::x86;
      |                                      ^~~
tvm/src/target/llvm/llvm_module.cc:503:25: error: 'getVendorSignature' was not declared in this scope
  503 |   const auto x86_sign = getVendorSignature();
      |                         ^~~~~~~~~~~~~~~~~~
tvm/src/target/llvm/llvm_module.cc:504:19: error: 'VendorSignatures' has not been declared
  504 |   if (x86_sign == VendorSignatures::GENUINE_INTEL)
      |                   ^~~~~~~~~~~~~~~~
tvm/src/target/llvm/llvm_module.cc:506:24: error: 'VendorSignatures' has not been declared
  506 |   else if (x86_sign == VendorSignatures::AUTHENTIC_AMD)
      |                        ^~~~~~~~~~~~~~~~
tvm/src/target/llvm/llvm_module.cc:508:24: error: 'VendorSignatures' has not been declared
  508 |   else if (x86_sign == VendorSignatures::UNKNOWN)
      |                        ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/tvm_objs.dir/build.make:8812: CMakeFiles/tvm_objs.dir/src/target/llvm/llvm_module.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/tvm_objs.dir/all] Error 2
```

### Environment

docker: nvcr.io/nvidia/cuda:11.6.0-cudnn8-devel-ubuntu20.04

llvm: 12.0.0 download from https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.0

tvm commit: 57597f62b44

### Steps to reproduce

Follow the installation guide provided in the official documentation.

### Triage

* needs-triage

https://github.com/apache/tvm/blob/main/src/target/llvm/llvm_module.cc#L500
```cpp
#if TVM_LLVM_VERSION >= 120
```

**Comment by chowwil** [comment]
@Railcalibur did you find a solution to this? I don't get this error on my older clones, but I get it on newer clones of the repo. Would the fix just be upgrading llvm?

**Comment by chowwil** [comment]
<img width="1227" alt="Screenshot 2023-11-06 at 1 56 17 PM" src="https://github.com/apache/tvm/assets/31594431/0bb7398a-0243-4d5e-965b-5a6092a3147c">

Looks like the change was from 4 weeks ago. My intel macbook gets the same error.

**Comment by HLearning** [comment]
#if TVM_LLVM_VERSION >= 121  
????????????????????????????????????????????????
