### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by niteshbaghel95** [apache/tvm#16060]
[ERROR] Directory name=/home/root/drpai_tvm/preprocess:This Object files do not support the Dynamic allocation function.
[ERROR] Failed to read Address Map List /home/root/drpai_tvm/preprocess/pp_addrmap_intm.txt
[ERROR] Failed to run Pre-processing Runtime Load().

getting this when running my custom app based on yolov3-tiny

**Comment by masahi** [comment]
Nothing we can do here.
