### ISSUE TITLE
[Bug] train cost model free invalid pointer

### ISSUE THREAD

**Issue by ningpengtao-coder** [apache/tvm#16103]
----------------------------------------------------------------------
------------------------------  [ Train cost model ]
----------------------------------------------------------------------
free(): invalid pointer

**Comment by masahi** [comment]
See `If you are a PyTorch user..` under

https://tvm.apache.org/docs/install/from_source.html#build-the-shared-library

**Comment by creaiter** [comment]
I applied the setting set(USE_LLVM "/path/to/llvm-config --link-static") and set(HIDE_PRIVATE_SYMBOLS ON).
But I'm still in the same error while using auto_scheduler.

- Error:
```
----------------------------------------------------------------------
------------------------------  [ Train cost model ]
----------------------------------------------------------------------
free(): invalid pointer
Aborted (core dumped)
```

- Trials:
1. The error occurs when using TVM (unity branch) built with the above configuration.
2. However, in main branch, "Train cost model" works without the configuration.

Do you have any idea for this?
