### ISSUE TITLE
[Bug] Android build faild for Llama-2-7b-chat-hf 

### ISSUE THREAD

**Issue by sunzj** [apache/tvm#16275]
Follow the steps in https://llm.mlc.ai/docs/deploy/android.html

After clone Llama-2-7b-chat-hf, run
` python3 -m mlc_llm.build   --target android  --max-seq-len 768  --model ./dist/models/Llama-2-7b-chat-hf   --quantization q4f16_1`

Get the followng error:

tvm._ffi.base.TVMError: Traceback (most recent call last):
  4: operator()
        at /home/josephsun/llm/tvm-unity/src/driver/driver_api.cc:527
  3: tvm::TIRToRuntime(tvm::runtime::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target const&)
        at /home/josephsun/llm/tvm-unity/src/driver/driver_api.cc:488
  2: tvm::SplitMixedModule(tvm::IRModule, tvm::Target const&, tvm::Target const&)
        at /home/josephsun/llm/tvm-unity/src/driver/driver_api.cc:415
  1: tvm::ApplyPasses(tvm::IRModule, tvm::transform::Sequential)
        at /home/josephsun/llm/tvm-unity/src/driver/driver_api.cc:286
  0: operator()
        at /home/josephsun/llm/tvm-unity/src/tir/analysis/verify_memory.cc:205
  Did you forget to bind?
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
  File "/home/josephsun/llm/tvm-unity/src/tir/analysis/verify_memory.cc", line 205
RuntimeError: Memory verification failed with the following errors:
"# from tvm.script import tir as T"

@T.prim_func
def encode1(A: T.Buffer((12288, 4096), "float16"), w_gathered: T.Buffer((12288, 512), "uint32"), scale: T.Buffer((12288, 128), "float16")):
    T.func_attr({"target": T.target({"host": {"keys": ["cpu"], "kind": "llvm", "tag": ""}, "keys": ["opencl", "gpu"], "kind": "opencl", "max_function_args": 128, "max_num_threads": 256, "max_shared_memory_per_block": 16384, "max_threads_per_block": 256, "tag": "", "texture_spatial_limit": 16384, "thread_warp_size": 1}), "tir.is_scheduled": T.bool(True), "tir.noalias": T.bool(True)})
    max_abs_value = T.allocate([1572864], "float16", "global")
    max_abs_value_1 = T.Buffer((1572864,), "float16", data=max_abs_value)
    A_1 = T.Buffer((50331648,), "float16", data=A.data)
    for i, j, k in T.grid(12288, 128, 32):
        cse_var_1: T.int32 = i * 128 + j
        if k == 0:
            max_abs_value_1[cse_var_1] = T.float16(-65504)
        max_abs_value_1[cse_var_1] = T.max(max_abs_value_1[cse_var_1], T.fabs(A_1[i * 4096 + j * 32 + k]))
    scale_1 = T.Buffer((1572864,), "float16", data=scale.data)
    for i, j in T.grid(12288, 128):
        cse_var_2: T.int32 = i * 128 + j
        scale_1[cse_var_2] = T.max(max_abs_value_1[cse_var_2], T.float16(0.0001)) * T.float16(0.14285714285714285)
    for i, j, k in T.grid(12288, 512, 8):
        cse_var_3: T.int32 = i * 512 + j
        w_gathered_1 = T.Buffer((6291456,), "uint32", data=w_gathered.data)
        if k == 0:
            w_gathered_1[cse_var_3] = T.uint32(0)
        w_gathered_1[cse_var_3] = T.bitwise_or(w_gathered_1[cse_var_3], T.shift_left(T.Cast("uint32", T.min(T.max(T.round(A_1[i * 4096 + j * 8 + k] / scale_1[i * 128 + j // 4] + T.float16(7)), T.float16(0)), T.float16(14))), T.Cast("uint32", k) * T.uint32(4)))

### Environment
mlc-llm:  commit 36c0d61065680cf2735245b6fdceef19fbfb1604
tvm-unity: commit 3f8bc0af7221117331e31ea71f1f15c433a30789
Ubuntu 20.04

**Comment by sunzj** [comment]
the issue cause by : tvm-unity: commit 1c35c392648e4336fc5e00ab91abb37af997cd59
After revert it, that issue disappear.

**Comment by llllwwwjj** [comment]
> the issue cause by : tvm-unity: commit [1c35c39](https://github.com/apache/tvm/commit/1c35c392648e4336fc5e00ab91abb37af997cd59) After revert it, that issue disappear. @yongwww
> 
> after invertigation, it casue by: [1c35c39#r135690043](https://github.com/apache/tvm/commit/1c35c392648e4336fc5e00ab91abb37af997cd59#r135690043)

你好，我遇到相同问题了，请问是tvm-unity 代码回退到1c35c39 提交节点之前吗，期待您的恢复；
ps:当前i提交: f5f048bbd71513f087799f987019e3931f68a6d9

**Comment by sunzj** [comment]
> > the issue cause by : tvm-unity: commit [1c35c39](https://github.com/apache/tvm/commit/1c35c392648e4336fc5e00ab91abb37af997cd59) After revert it, that issue disappear. @yongwww
> > after invertigation, it casue by: [1c35c39#r135690043](https://github.com/apache/tvm/commit/1c35c392648e4336fc5e00ab91abb37af997cd59#r135690043)
> 
> 你好，我遇到相同问题了，请问是tvm-unity 代码回退到1c35c39 提交节点之前吗，期待您的恢复； ps:当前i提交: f5f048bbd71513f087799f987019e3931f68a6d9

使用mlc_llm.build 方式来编译的版本太老了，当前你拿到最新的代码应该是没有问题了。参考一下文档：https://llm.mlc.ai/docs/compilation/compile_models.html#
