### ISSUE TITLE
[VOTE] Transition Main to Unity 

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#16368]
Hi Community:

Over the last year, we have witnessed a great number of innovations with the arrival of foundational models, including stable diffusion models for image generation, whisper for voice recognition, GPT, and open LLMs.

As of now, the unity is being developed as a branch for GenAI support. Because of the level of new features being brought in, as well as the ML/AI landscape shift we are experiencing. As of now, the unity branch includes all the main features, with additional modules to support genAI-related needs. The community held quite a few conversations about our general GenAI strategy. Most of the community agrees that it is important to bring unity support officially in a timely manner.  As of now we also start to see the majority of new development activities shift to the unity branch, making it the de-facto main.

TVM unity is a major change in terms of the set of approaches to reflect the trends in AI/ML ecosystem. We have also developed the system in a way that involves continuous communication with the community for over a year with various applications that are already being used in LLM use cases.

After discussions with the community members, this post proposes to take the path that most favor:  change the current codebase main branch to the unity branch, ensuring the main modules are incorporated (ensure git merge of latest main into unity). 

This is a formal voting thread; The vote will be open for at least one week, please vote:

+1 if you support the transition
+0 
-1 because

**Comment by tqchen** [comment]
Please also see the following thread for background discussions and context
https://discuss.tvm.apache.org/t/discuss-tvm-core-strategy-for-emerging-needs/15751

**Comment by junrushao** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by csullivan** [comment]
+1

**Comment by yongwww** [comment]
+1

**Comment by sunggg** [comment]
+1 (binding)

**Comment by yelite** [comment]
+1

**Comment by zhiics** [comment]
+1

**Comment by merrymercy** [comment]
+1

**Comment by jinhongyii** [comment]
+1

**Comment by Hzfengsy** [comment]
+1

**Comment by ZihengJiang** [comment]
+1

**Comment by Johnson9009** [comment]
+1

**Comment by xqdan** [comment]
+1

**Comment by vincentccc** [comment]
+1

**Comment by Tao-begd** [comment]
+1

**Comment by SunCrazy** [comment]
+1

**Comment by weity** [comment]
+1

**Comment by Aharrypotter** [comment]
+1

**Comment by Karbit** [comment]
+1

**Comment by jikechao** [comment]
+1

**Comment by comaniac** [comment]
+1

**Comment by MasterJH5574** [comment]
+1

**Comment by zxybazh** [comment]
+1

**Comment by sequoiar** [comment]
+1

**Comment by cgerum** [comment]
+1

**Comment by masahi** [comment]
+1

**Comment by LeshengJin** [comment]
+1

**Comment by YuchenJin** [comment]
+1 (binding)

**Comment by cyx-6** [comment]
+1

**Comment by psrivas2** [comment]
+1

**Comment by Archermmt** [comment]
+1

**Comment by yzh119** [comment]
+1

**Comment by shifeiwen** [comment]
+1

**Comment by yzhliu** [comment]
+1

**Comment by jwfromm** [comment]
+1

**Comment by spectrometerHBH** [comment]
+1

**Comment by leandron** [comment]
-1 (binding)

It has been raised before that [some tests are disabled in the `unity` branch](https://github.com/apache/tvm/blob/a2a1b534024e677a9407bec8d09d99f2237b2b0b/ci/jenkins/generated/gpu_jenkinsfile.groovy#L57-L60), so it would be good to double check that as this proposal is actioned by its proponents, we guarantee that all current `main` tests are passing on the proposed merged branch. It shouldn't be an onus of contributors working on `main` to re-enable their tests.

The linked source has a note that the test workaround shouldn't be moved into the target branch but the current vote statement isn't covering for this "disabled tests" item. If that's already planned, please let me know and I'll change the vote.

**Comment by tqchen** [comment]
see latest note in https://discuss.tvm.apache.org/t/discuss-tvm-core-strategy-for-emerging-needs/15751/27 @Hzfengsy have take steps to ensure all main tests pass in unity. The the intention is to work with @Hzfengsy on enabling a smooth transition and main tests enabled

**Comment by gogo800** [comment]
+1

**Comment by brainternet** [comment]
+1, be faster will be better, can't wait for any seconds

**Comment by brainternet** [comment]
I have working on unity branch for a couple of months ^_^

**Comment by tqchen** [comment]
note: leandron edited vote to +1, posting in new thread since GH issue mirror may not record edit to dev@

**Comment by tqchen** [comment]
Thanks everyone who voted, the results are published in https://github.com/apache/tvm/issues/16434

The vote is now passed. I will work with @Hzfengsy and others to start working on the transition
