### ISSUE TITLE
[Bug] InternalError: Check failed: (!axes.defined() || static_cast(axes.size()) == ndim) is false: Dimension mismatch: axes has 4 elements, but data.ndim = 5

### ISSUE THREAD

**Issue by wangweiwei1188** [apache/tvm#16496]
### Expected behavior
tvm.error.InternalError: Traceback (most recent call last):
  File "/tvm/src/relay/op/tensor/transform.cc", line 463
InternalError: Check failed: (!axes.defined() || static_cast<int>(axes.size()) == ndim) is false: Dimension mismatch: axes has 4 elements, but data.ndim = 5

### Environment
 the newest tvm version, and llama7b module

###Command
python -m tvm.driver.tvmc  compile  --target "cuda"  --output llama_7b_gpu.tar ./llama-hf-7b-onnx/model.onnx

**Comment by Hzfengsy** [comment]
Native TVM does not support LLM for now, please track [MLC-LLM](https://github.com/mlc-ai/mlc-llm), an application for LLM based on TVM stack

**Comment by wangweiwei1188** [comment]
> Native TVM does not support LLM for now, please track [MLC-LLM](https://github.com/mlc-ai/mlc-llm), an application for LLM based on TVM stack
ok , very thanks.
