### ISSUE TITLE
[CI Problem] unity/pr-head does not automatically rebase against main before CI run

### ISSUE THREAD

**Issue by lhutton1** [apache/tvm#16657]
unity/pr-head started failing due to a concurrent merge of both https://github.com/apache/tvm/pull/16612 and https://github.com/apache/tvm/pull/16563. This issue was fixed in https://github.com/apache/tvm/pull/16649, however, PR's that haven't been rebased on the latest main are still failing.

Other CI runs e.g. cpu/pr-head, gpu/pr-head, etc automatically rebase the PR before a CI run. This ensures the PR's are tested against the latest main, rather than a previous head of main. unity/pr-head doesn't seem to do this which can result in PR's failing even after triggering a rerun of CI:
- https://discuss.tvm.apache.org/t/is-there-an-anomaly-in-ci-unity-pr-head/16446/3
- https://github.com/apache/tvm/pull/16652#issuecomment-1970170247

The behaviour of unity/pr-head should be consistent with cpu/pr-head, gpu/pr-head, etc. Taking a look at the jenkinsfiles, it seems unity/pr-head is missing a call to `merge_with_main()`([link](https://github.com/apache/tvm/blob/997adcaaead1714b108fc7401197113fbb80ca54/ci/jenkins/templates/utils/Prepare.groovy.j2#L47)) when a PR branch is detected.

_Originally posted [here](https://github.com/apache/tvm/pull/16612#issuecomment-1966648171), creating an issue for better visibility._

**Comment by yongwww** [comment]
Tried to add the merge_with_main in unity #16661

**Comment by lhutton1** [comment]
Closing since https://github.com/apache/tvm/pull/16661 was merged
