### ISSUE TITLE
[CI Problem] Windows Conda Build Does Not Support C++20 Features

### ISSUE THREAD

**Issue by zxybazh** [apache/tvm#16720]
The windows conda build would fail because it doesn't support c++20 feature such as designated initializer.

### Branch/PR Failing

https://github.com/apache/tvm/pull/16717/commits/a5bbfcc9dd068e9a069f3dce3e06535a85bca66e

### Jenkins Link

[Provide a link to the specific run that has failed.
](https://github.com/apache/tvm/actions/runs/8285739038/job/22674133153)

### Flakiness

Reproduces in the same PR for different commits.

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by tqchen** [comment]
Can we first update to make it cxx17 compatible?

**Comment by vinx13** [comment]
we are still using c++17, the error is because c++20 is not enabled

**Comment by zxybazh** [comment]
Original PR #16717 has been updated to make it c++17 compatible and passed the CI. This issue is created to mark that c++20 features may cause windoes CI to fail during conda build.

**Comment by zxybazh** [comment]
Won't fix for now. Please feel free to reopen if this reproduces.
