### ISSUE TITLE
[CI Problem] Missing AWS Key for S3 file cache storage

### ISSUE THREAD

**Issue by leandron** [apache/tvm#17019]
I noticed this while running https://github.com/apache/tvm/actions/runs/9188515282.

@tqchen any idea who has access to AWS and can fix this?

This is the error I see:
```
+ aws s3 cp downloaded_file s3://tvm-ci-resources/2024-05-22/resnet50-v2-7.onnx
upload failed: ./downloaded_file to s3://tvm-ci-resources/2024-05-22/resnet50-v2-7.onnx An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.
```

Related to #17017 and #17018.

**Comment by leandron** [comment]
This also blocks https://github.com/apache/tvm/pull/17020

**Comment by yongwww** [comment]
this issue should be fixed now.
