### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangsheng115** [apache/tvm#17090]
I  run  command:
mlc_chat convert_weight  ..................

An error  happened, this is  error message:
TVMError: Op(relax.nn.rms_norm) requires the input gamma, beta, etc., to have size same as the lengths of the data on the given axes. However, there exists [T.int64(2304)] and [T.int64(4096)] that are unequal

platform:   macOs Sonoma 14.5
   
How to  avoid this problem?

**Comment by Hzfengsy** [comment]
If you'd like to ask about mlc-llm, please open the issue at https://github.com/mlc-ai/mlc-llm but not TVM repo.

BTW, `mlc_chat` is the old interface that has been deprecated by the latest mlc-llm, please check your version too.
