### ISSUE TITLE
fatal error: string_view: No such file or directory

### ISSUE THREAD

**Issue by yizhihenpidehou** [apache/tvm#17209]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior
I want to build from tvm source code, but when I conduct: make -j4, some errors raise.

### Actual behavior

<img width="823" alt="image" src="https://github.com/user-attachments/assets/42c5020c-7252-46d9-b385-d23dd7fed0a3">

error message:
/opt/SparseMatrixAnalysis/tvm/include/tvm/runtime/container/string.h:40:23: fatal error: string_view: No such file or directory

### Environment

linux-ubuntu x86_64, gcc (GCC) 8.1.0

### Triage

Please refer to the list of label tags [here](https://github.com/apache/tvm/wiki/Issue-Triage-Labels) to find the relevant tags and add them below in a bullet format (example below).

* needs-triage

**Comment by Cookiee235** [comment]
@yizhihenpidehou You should update the GCC version. `std::string_view` is a C++17 feature and GCC 8 did not support it.

**Comment by yizhihenpidehou** [comment]
> @yizhihenpidehou You should update the GCC version. `std::string_view` is a C++17 feature and GCC 8 did not support it.

Thanks! I upgrade the GCC to 10.2 which seem to support c++17, but I still got the similar error.
<img width="792" alt="image" src="https://github.com/user-attachments/assets/ebf2855e-7b06-492c-90f2-6ce88c43d7be">

**Comment by Lunderberg** [comment]
When you upgraded the GCC version, are you now compiling with the stdlib implementation provided by the new GCC version?  This may require re-running cmake, if the old stdlib implementation is saved in `CMakeCache.txt`.

**Comment by yizhihenpidehou** [comment]
> When you upgraded the GCC version, are you now compiling with the stdlib implementation provided by the new GCC version? This may require re-running cmake, if the old stdlib implementation is saved in `CMakeCache.txt`.

I do not find 'stdlib' thing in  CMakeCache.txt, and my gcc version is shown below, my operate system is ubuntu16.0.4
<img width="508" alt="image" src="https://github.com/user-attachments/assets/8af26668-3ca0-4048-a59e-10dc412f8e18">
<img width="493" alt="image" src="https://github.com/user-attachments/assets/8422f3be-e739-489f-a779-8c9ae2dadda6">

**Comment by Lunderberg** [comment]
Can you show the output from the following commands?

* `make VERBOSE=1`: Show the full command used to compile the `analyzer.cc` file
* `which g++`: Where the `g++` executable is located.
* `echo | g++ -xc++ -E -v -`: Print out the defaults used by g++.  You'll want to look at the lines after `#include <...> search starts here` to see if it is looking for the new stdlib implementation.
* `ldconfig --print-cache | grep libstdc`: Whether the linker is configured to find the new stdlib implementation.
* `echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH`: Whether the `LD_LIBRARY_PATH` is used to override the settings from `ldconfig`.


It's possible that the newer version of g++ is still using the stdlib headers provided by the system's default version of g++, and these should help in determining if that's the case.

**Comment by yizhihenpidehou** [comment]
1.
root@ubuntu:/opt/SparseMatrixAnalysis/tvm# make VERBOSE=1
Re-run cmake no build system arguments
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Linux
-- Build with RPC support...
-- Build with Graph Executor support...
-- Build with profiler...
-- Build with AOT Executor support...
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Build Alloc alignment set to 64
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/opt/SparseMatrixAnalysis/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=4330c110550242571da017a1b15ae0b765723ae8
-- Found TVM_GIT_COMMIT_TIME=2024-07-28 10:02:22 +0530
-- Could NOT find LIBBACKTRACE (missing: LIBBACKTRACE_STATIC_LIBRARY LIBBACKTRACE_INCLUDE_DIR) 
-- Building libbacktrace from 3rdparty/libbacktrace
-- Building with TVM Map...
-- Build with thread support...
-- Added "-fuse-ld=lld" to linker flags 
-- Build without FlashInfer
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/SparseMatrixAnalysis/tvm/build
make[1]: Entering directory '/opt/SparseMatrixAnalysis/tvm/build'
/opt/cmake-3.18.0/bin/cmake -P /opt/SparseMatrixAnalysis/tvm/build/CMakeFiles/VerifyGlobs.cmake
/opt/cmake-3.18.0/bin/cmake -S/opt/SparseMatrixAnalysis/tvm -B/opt/SparseMatrixAnalysis/tvm/build --check-build-system CMakeFiles/Makefile.cmake 0
/opt/cmake-3.18.0/bin/cmake -E cmake_progress_start /opt/SparseMatrixAnalysis/tvm/build/CMakeFiles /opt/SparseMatrixAnalysis/tvm/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[2]: Entering directory '/opt/SparseMatrixAnalysis/tvm/build'
make  -f CMakeFiles/project_libbacktrace.dir/build.make CMakeFiles/project_libbacktrace.dir/depend
make[3]: Entering directory '/opt/SparseMatrixAnalysis/tvm/build'
cd /opt/SparseMatrixAnalysis/tvm/build && /opt/cmake-3.18.0/bin/cmake -E cmake_depends "Unix Makefiles" /opt/SparseMatrixAnalysis/tvm /opt/SparseMatrixAnalysis/tvm /opt/SparseMatrixAnalysis/tvm/build /opt/SparseMatrixAnalysis/tvm/build /opt/SparseMatrixAnalysis/tvm/build/CMakeFiles/project_libbacktrace.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/opt/SparseMatrixAnalysis/tvm/build'
make  -f CMakeFiles/project_libbacktrace.dir/build.make CMakeFiles/project_libbacktrace.dir/build
make[3]: Entering directory '/opt/SparseMatrixAnalysis/tvm/build'
make[3]: Nothing to be done for 'CMakeFiles/project_libbacktrace.dir/build'.
make[3]: Leaving directory '/opt/SparseMatrixAnalysis/tvm/build'
[  1%] Built target project_libbacktrace
make  -f CMakeFiles/tvm_runtime_objs.dir/build.make CMakeFiles/tvm_runtime_objs.dir/depend
make[3]: Entering directory '/opt/SparseMatrixAnalysis/tvm/build'
cd /opt/SparseMatrixAnalysis/tvm/build && /opt/cmake-3.18.0/bin/cmake -E cmake_depends "Unix Makefiles" /opt/SparseMatrixAnalysis/tvm /opt/SparseMatrixAnalysis/tvm /opt/SparseMatrixAnalysis/tvm/build /opt/SparseMatrixAnalysis/tvm/build /opt/SparseMatrixAnalysis/tvm/build/CMakeFiles/tvm_runtime_objs.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/opt/SparseMatrixAnalysis/tvm/build'
make  -f CMakeFiles/tvm_runtime_objs.dir/build.make CMakeFiles/tvm_runtime_objs.dir/build
make[3]: Entering directory '/opt/SparseMatrixAnalysis/tvm/build'
[  1%] Building CXX object CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o
/usr/bin/c++ -DDMLC_USE_FOPEN64=0 -DDMLC_USE_LOGGING_LIBRARY="<tvm/runtime/logging.h>" -DNDEBUG -DNDEBUG=1 -DTVM_INDEX_DEFAULT_I64=1 -DTVM_KALLOC_ALIGNMENT=64 -DTVM_THREADPOOL_USE_OPENMP=0 -DTVM_USE_LIBBACKTRACE=1 -DUSE_FALLBACK_STL_MAP=0 -I/opt/SparseMatrixAnalysis/tvm/include -I/opt/SparseMatrixAnalysis/tvm/build/libbacktrace/include -I/opt/SparseMatrixAnalysis/tvm/3rdparty/libcrc/include -isystem /opt/SparseMatrixAnalysis/tvm/3rdparty/dlpack/include -isystem /opt/SparseMatrixAnalysis/tvm/3rdparty/dmlc-core/include -isystem /opt/SparseMatrixAnalysis/tvm/3rdparty/rang/include -isystem /opt/SparseMatrixAnalysis/tvm/3rdparty/compiler-rt -isystem /opt/SparseMatrixAnalysis/tvm/3rdparty/picojson -std=c++17 -O2 -Wall -fPIC  -o CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o -c /opt/SparseMatrixAnalysis/tvm/src/runtime/c_runtime_api.cc
In file included from /opt/SparseMatrixAnalysis/tvm/include/tvm/runtime/ndarray.h:30:0,
                 from /opt/SparseMatrixAnalysis/tvm/include/tvm/runtime/device_api.h:28,
                 from /opt/SparseMatrixAnalysis/tvm/src/runtime/c_runtime_api.cc:27:
/opt/SparseMatrixAnalysis/tvm/include/tvm/runtime/container/string.h:40:23: fatal error: string_view: No such file or directory
compilation terminated.
CMakeFiles/tvm_runtime_objs.dir/build.make:94: recipe for target 'CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o' failed
make[3]: *** [CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o] Error 1
make[3]: Leaving directory '/opt/SparseMatrixAnalysis/tvm/build'
CMakeFiles/Makefile2:135: recipe for target 'CMakeFiles/tvm_runtime_objs.dir/all' failed
make[2]: *** [CMakeFiles/tvm_runtime_objs.dir/all] Error 2
make[2]: Leaving directory '/opt/SparseMatrixAnalysis/tvm/build'
Makefile:148: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/SparseMatrixAnalysis/tvm/build'
Makefile:87: recipe for target '/opt/SparseMatrixAnalysis/tvm/build/all' failed
make: *** [/opt/SparseMatrixAnalysis/tvm/build/all] Error 2


2. /usr/local/bin/g++
3. sing built-in specs.
COLLECT_GCC=g++
Target: x86_64-pc-linux-gnu
Configured with: ../configure --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --enable-gnu-indirect-function --with-tune=generic --disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (GCC) 
COLLECT_GCC_OPTIONS='-std=c++17' '-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/cc1plus -E -quiet -v -imultiarch x86_64-linux-gnu -D_GNU_SOURCE - -mtune=generic -march=x86-64 -std=c++17
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0
 /usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-pc-linux-gnu
 /usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/backward
 /usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include
 /usr/local/include
 /usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/:/usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/:/usr/local/libexec/gcc/x86_64-pc-linux-gnu/:/usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/:/usr/local/lib/gcc/x86_64-pc-linux-gnu/
LIBRARY_PATH=/usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/:/usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/:/lib/x86_64-linux-gnu/:/lib/../lib64/:/usr/lib/x86_64-linux-gnu/:/usr/local/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-std=c++17' '-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'


4.libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6


5. > echo LD_LIBRARY_PATH=$LD_LIBRARY_PAT
LD_LIBRARY_PATH=
The LD_LIBRARY_PATH display nothing in the cmd

**Comment by Lunderberg** [comment]
Everything looks reasonable for the g++ configuration.

It looks like cmake is calling the `/usr/bin/c++` executable, which is usually a symlink to a specific compiler version.  Can you run `realpath /usr/bin/c++` to see which compiler it ends up running?

**Comment by yizhihenpidehou** [comment]
> Everything looks reasonable for the g++ configuration.
> 
> It looks like cmake is calling the `/usr/bin/c++` executable, which is usually a symlink to a specific compiler version. Can you run `realpath /usr/bin/c++` to see which compiler it ends up running?

Thanks !!!
I see /usr/bin/g++-5, now could to tell me how to relink c++ to g++-10.2.0

**Comment by Lunderberg** [comment]
Should be doable with `update-alternatives` ([SO link](https://askubuntu.com/a/26518)).

**Comment by yizhihenpidehou** [comment]
> Should be doable with `update-alternatives` ([SO link](https://askubuntu.com/a/26518)).

Thanks for your help!!! Now I can successfully compile and install tvm on my machine👍👍👍
