### ISSUE TITLE
build failed. cannot find -lxml2

### ISSUE THREAD

**Issue by weizhenhuan** [apache/tvm#17329]
when I build tvm from source with cuda version, I encounter the following problem. I have installed libxml2 with conda, but the problem still exists. I also try installing libxml2 from source from [website](xmlsoft.org/sources/old/), and adding corresponding lib dir to LD_LIBRARY_PATH, it cannot solve the problem.

[  1%] Built target project_libbacktrace
[  1%] Built target tvm_libinfo_objs
[ 10%] Built target tvm_runtime_objs
[ 10%] Built target tvm_runtime
[100%] Built target tvm_objs
[100%] Linking CXX shared library libtvm_allvisible.so
[100%] Linking CXX shared library libtvm.so
/usr/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tvm.dir/build.make:2231: libtvm.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:177: CMakeFiles/tvm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/tvm_allvisible.dir/build.make:2231: libtvm_allvisible.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: CMakeFiles/tvm_allvisible.dir/all] Error 2

**Comment by wsty1234** [comment]
I have met the same problem. How to solve this ?  Thank you so much

**Comment by Zoeeeeey** [comment]
I have met the same problem. How to solve this ? Thank you so much TxT

**Comment by actinks** [comment]
I solved it by:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/lib/x86_64-linux-gnu/libxml2.so`
