### ISSUE TITLE
[Bug] How to use auto_scheduler to generate SVE code

### ISSUE THREAD

**Issue by yohuna77777** [apache/tvm#17456]
Hello, I am currently using auto_scheduler to automatically tune a naive gemm operator. However, after the tuning is completed, I checked the corresponding assembly code and found that the registers related to the SVE instruction set were not used, but the NEON instruction set was used(The target is set to: "llvm -mtriple=aarch64-gnu-linux -mattr=+sve"). Does auto_scheduler not support the generation of SVE code? Looking forward to your reply!

**Comment by yohuna77777** [comment]
Resolved.

**Comment by yohuna77777** [comment]
In fact, I wrote a naive gemm, and after setting the target, the compiled code still did not use the sve instruction set. What's going on? The code is as follows:
`
import tvm
import tvm.testing
from tvm import te
from tvm.script import tir as TIR
import re
import os
import ctypes
import pytest

from tvm.target.codegen import llvm_version_major


target = "llvm -mtriple=aarch64-linux-gnu -mattr=+sve"

#m = te.var("m")
#A = te.placeholder(m, dtype="float32", name="A")
#B = te.placeholder(m, dtype="float32", name="B")
#C = te.compute((m), lambda i: A[i] * B[i], name="C")
M = 1024
N = 1024
K = 1024
A = te.placeholder((M, K), name="A", dtype="float32")
B = te.placeholder((K, N), name="B", dtype="float32")

k = te.reduce_axis((0, K), name="k")
C = te.compute(
        (M, N),
        lambda i, j: te.sum(A[i, k] * B[k, j], axis=k),
        name="C",
        attrs={"layout_free_placeholders": [B]},  # enable automatic layout transform for tensor B
)
s = te.create_schedule([C.op])


f = tvm.build(s, [A, B, C], target)

# Verify we see SVE load instructions and mul instructions using z registers
assembly = f.get_source("asm")
print(assembly)
`

**Comment by cbalint13** [comment]
Hi @yohuna77777 ,

* If you pre-define the length (=1024 in this case) of arrays so there will be no SVE "dynamism" involved.
* But can try tune your pre-defined kernel against real target to see if a better SVE kernel will be proposed or not.

I updated your script [tvm-17456.py.gz](https://github.com/user-attachments/files/17966884/tvm-17456.py.gz) for dynamic scenario and here is the output:

```
$ ./tvm-17456.py | grep ld1
	ld1b	{ z0.b }, p0/z, [x3, x11]
	ld1b	{ z1.b }, p0/z, [x5, x11]
	ld1w	{ z2.s }, p1/z, [x14, #1, mul vl]
	ld1w	{ z3.s }, p1/z, [x15, #1, mul vl]
```

Also you can look at more [tvm testcase examples](https://github.com/apache/tvm/blob/main/tests/python/codegen/test_target_codegen_aarch64.py) where explicit ```T.vscale()``` kernels are constructed if this is the goal. 
Or simply try tune your kernel agaisnt real arm64+sve target to see if the best performing kernel will have SVE included.
