### ISSUE TITLE
[Docs] Converting PyTorch to Relax

### ISSUE THREAD

**Issue by yoon5862** [apache/tvm#17500]
Hello,
 
I am currently working on converting a PyTorch model using TVM Relax.
I have some question regarding how iteration in PyTorch dynamo handled within TVM Relax.

There is no examples and document about it.
I think Relax IR given like LLVM IR.

Thank you!

**Comment by Hzfengsy** [comment]
Here is the doc about importing pytorch model into Relax.
https://tvm.apache.org/docs/how_to/tutorials/e2e_opt_model.html

**Comment by yoon5862** [comment]
Thank you for relay!
I will read document carefully.
