### ISSUE TITLE
[RFC] Imperfect Loop Split Condition Handling

### ISSUE THREAD

**Issue by liwchang** [apache/tvm#1979]
Though tvm has predicates information, there seems no proper loop transformation utilizing that info to generate efficient loop structure when conditions happen.

An example. 
A simple 1D vector add (c = a+b), with a tail condition, say a length as 255.
```
c.split(x, 64, xo, xi).
The condition will be inserted within inner-most.
for(xo[0:4])
   for(xi[0:64])  // some schedule is supposed here, but blocked by the condition.
     if(likely(condition))
       c = a+b
```
Then, if a user applies a non-scalar transformation on xi, like vectorize, unroll, any other custom one,
it will be blocked.

There are several typical solutions. 
1) one is splitting out tail out.
It will look like this.
```
for(xo[0:4])
  if(likely(another condition))
    for(xi[0:64]) // some schedule can be applied now
        c = a+b
  else
     for(xi[0:64])
       if(likely(condition))
           c = a+b
```
or like this, if you have a better analysis 
```
for(xo[0:3])
    for(xi[0:64]) // some schedule can be applied now
        c = a+b
for(xi[0:64])
    if(likely(condition))
         c = a+b
  
```
2) another is only doing predicated load/store
It will look like this
```
for(xo[0:4])
    for(xi[0:64]) // some schedule can be applied now
        c' = a+b
    for(xi[0:64])
       if(likely(condition))
           c = c'
```

In CPU-like machine, this is important.
It is still useful for GPU.
Though tvm source-to-source to CUDA, and nvcc can handle it,
you might still need this later for dropping nvcc dependency.

There might be two potential locations for doing this.
One is before or when you first construct Stmt.
The other is doing Stmt mutation after the original Stmt is constructed.

**Comment by liwchang** [comment]
I agree that without first two working (efficiently) in tvm, padding seems the only way. 
That's my current workaround for this issue. 
I only call it a workaround instead of a solution. 

If the padding is really "auto" (internal in tvm), it will be nice.
But the current case seems requiring users' effort at a high-level.  
The key issue is that the padding size might be highly associated with split/tile sizes, 
which are parameters of low-level transformation. 
That seems slightly contradicting the design of decoupling high-level/low-level IR.

-L

**Comment by tqchen** [comment]
I agree that manual padding is a workaround, automatic padding is more desirable in most cases. The first two approaches are great, but also have their limitations(if you are targeting ASIC which don't have scalar unit)

As for the cases of decoupling of IRs, or compute/schedule. In many cases, such de-coupling is indeed imperfect (when considering padding, layout or wino-grad algorithm), and we are taking a pragmatic approach in solving this problem and allow the high level to be aware of low-level things when they can, but also embraces a slight coupled declaration if that brings performance gains

**Comment by tqchen** [comment]
I agree (b) (c) are reasonable choices. Actually, by automatic padding, I do mean (c). Shifting the loop range have quite a lot of problems, especially in reduction, which makes it undesirable. 

Making things ASIC compatible is an explicit choice we make, and that may not be a bad one, given the extensive use of tensorization even in modern GPUs and future CPUs. 

I agree that it is important to make low-level IR better(which in turn makes everything better). It is also important to acknowledge the limitations of the low-level approach and keep co-design in mind, that is why tvm contains both high-level and low-level IR and co-design them together.

Contributions are welcomed :)

**Comment by xqdan** [comment]
Two more things added here,
1) ASIC may have instructions for tail, so both have and not have should be considered.
2) users may only use low level IR to develop operators, and integrate ops to other frameworks such TF, in this case, we can not do padding on graph level.

**Comment by liwchang** [comment]
@xqdan Great points. I had similar thoughts.

I think introducing tailcondtion as a schedule option of split/tile might be a generic-enough solution, so user or autotuner can select among them based on their needs for a specific arch.
(b) and (c) should be two reasonable ones.
(a) can still be the default, so we don't break existing ones.
(b) should be a direct, simple extension on top of the current semantics (a), so some cases can gain performance benefit.
(c) should be also a good one, but might take more time to introduce, since it involves more transformation. We can gradually add it.

All of these are still orthogonal to tvm's future high-level IR. So co-design can still have its own value.

-L
