### ISSUE TITLE
[FRONTEND] Tensorflow Op: Conv2DBackpropInput

### ISSUE THREAD

**Issue by simpzan** [apache/tvm#2368]
the following errors occurred when I was trying to import tensorflow models with [this script](https://github.com/dmlc/tvm/blob/master/tutorials/nnvm/from_tensorflow.py).
Any plans to support these 2 operators? Thanks!

```
NotImplementedError: The following operators are not implemented: set([u'Slice', u'Conv2DBackpropInput'])
```

**Comment by srkreddy1238** [comment]
@simpzan thanks for reporting this.
```Slice``` should be a straight forward implementation. ```Conv2DBackpropInput``` required effort.
You are welcome to contribute a part or all of it if interested.

**Comment by bravomikekilo** [comment]
I would like to implement slice, may I get this part? @tqchen

**Comment by srkreddy1238** [comment]
@bravomikekilo you are most welcome to contribute :+1:

**Comment by srkreddy1238** [comment]
@bravomikekilo  sorry about my communication above. #2285 is WIP PR for Slice.

**Comment by optima2005** [comment]
PR #4300 is for Op 'Conv2DBackpropInput', which is the graph node name of 'conv2d_transpose' Op in tensorflow.
