### ISSUE TITLE
[Relay][RFC] Mutual Recursion

### ISSUE THREAD

**Issue by slyubomirsky** [apache/tvm#2603]
Mutual recursion is a construct available in many functional programming languages that allows two functions to be defined together such that each can make recursive calls to the other. For example (using OCaml):

```
let rec even x = if (x = 0) then true else odd (x - 1)
and odd x = if (x = 1) then true else even (x - 1)
```

~In Relay, mutual recursion is currently only possible for global functions~ (it should be but apparently doesn't work); it is not otherwise possible for locally defined functions since to define local functions `f` and `g`, both must be in separate `let` bindings and thus only the later function could reference the former. It may be useful to allow multiple mutually referential definitions in Relay down the line. This would require modifying the current AST let binding node or adding a new AST node for simultaneous bindings, though the type-checking rule for it would be fairly simple.

cc @ehsanmok

**Comment by jroesch** [comment]
@abergeron requires this feature for Myia.

@slyubomirsky check out this example, I wrote up a small function to do so in Python. 

https://gist.github.com/jroesch/4f6a601cbc86170025011d9d34a708dc

**Comment by slyubomirsky** [comment]
Thanks for the example. @MarisaKirisame and I will start implementing mutual recursion this week.

**Comment by slyubomirsky** [comment]
What sort of syntax should there be to indicate mutual recursion? I presume that mutual recursion should always work for globals.
