### ISSUE TITLE
[DOCS] Document  Fusion Algorithm

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#3109]
The new generic fusion algorithm is great and it would be even better if we can document the process so that others can easily come in and understand what is going on. 

This is an issue calling for help in contributing such document to developer docs. There are already some inline comments that document the algorithm, but some formal examples and figures might help to make it even better

**Comment by tqchen** [comment]
@masahi would you be interested in this?

**Comment by masahi** [comment]
alright, I'll give it a try

**Comment by masahi** [comment]
I don't think I'll ever work on this, moreover a new fusion implementation based pattern matching is being discussed. I'd like to close this.
