### ISSUE TITLE
Cast from float16 to uint8 was not supported by CUDA

### ISSUE THREAD

**Issue by kice** [apache/tvm#3879]
Example code

```python
expr_text = """v0.0.3
fn(%data: Tensor[(1, 1, 1, 1), uint8]) -> Tensor[(1, 1, 1, 1), uint8] {
  %0 = cast(%data, dtype="float16");
  cast(%0, dtype="uint8")
}
"""

func = relay.parser.fromtext(expr_text)

with relay.build_config(opt_level=3):
    graph, lib, params = relay.build(func, target='cuda')
```

Output:
```
my_kernel.cu(4): error: more than one conversion function from "half" to "unsigned char" applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
```

After looking into cuda_fp16.h, found that no direct conversion from fp16 to uint8/int8.

Suggest to warn the user who want to this conversion, or conver it to uint16/int16 and then to uint8/int8 internally.

You may close this issue after reading.

P.S. I am sorry that I open too many small PRs and issues in short period of time. xD

**Comment by kice** [comment]
I also found that `relay.clip` does not support fp16 operation for cuda

**Comment by tqchen** [comment]
Would be great if you can send a PR to add an error when user performs such conversion

**Comment by kice** [comment]
```
void CodeGenCUDA::VisitExpr_(const Cast* op, std::ostream& os) { 
  bool fromHalf =
      op->value.type().is_float() && op->value.type().bits() == 16 && op->value.type().lanes() == 1;
  bool toint8 = (op->type.is_int() || op->type.is_uint()) && op->type.bits() == 8 && op->type.lanes() == 1;
  if (fromHalf && toint8) {
    std::stringstream value_16;
    std::stringstream value_int8;
    this->PrintExpr(op->value, value_16);
    auto inter_type = op->type.is_int() ? Int(16) : UInt(16);
    value_int8 << CastFromTo(value_16.str(), op->value.type(), inter_type);
    os << CastFromTo(value_int8.str(), inter_type, op->type);
  } else {
    CodeGenC::VisitExpr_(op, os);
  }
}
```
Just for the record

**Comment by kice** [comment]
Also I found before CUDA 10.2, there is no support for absolute value APIs for half-precision.

**Comment by tqchen** [comment]
close for now due to inactive status, i believe there were a few recent improvement by @wpan11nv that might be relevant, feel free to open new forum thread or issue if there are more things to be addressed

**Comment by kice** [comment]
If you take a look here
```
auto inter_type = op->type.is_int() ? Int(16) : UInt(16);
    value_int8 << CastFromTo(value_16.str(), op->value.type(), inter_type);
    os << CastFromTo(value_int8.str(), inter_type, op->type);
```

We need to convert to `uint16` and then cast to `uint8`. No direct conversion from `fp16` to `uint8`.

ref: https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____HALF__MISC.html#group__CUDA__MATH____HALF__MISC

**Comment by tqchen** [comment]
cc @wpan11nv @Hzfengsy

**Comment by wpan11nv** [comment]
Looks like there is a choice on rounding mode. If rounding mode is not important, then a fix in CUDA code  is fine.

**Comment by tqchen** [comment]
I think we can pick a rounding mode and add a support. Most rounding mode from fp -> int are round down

**Comment by kice** [comment]
Although rounding is important, but here is a legitimate type conversion but no compiler support or native support on our target device.

I will suggest we implement type converter or add a cast function to TVM Type class. And then we can add global flags to control type conversion, like which rounding mode we should use as default.
But the drawback is we need to write codes for all target device and different compilers.

**Comment by tqchen** [comment]
Let us try an impl that support round down behavior, which is typical in float to int conversion

**Comment by hgt312** [comment]
What is the current status of this issue? Does some one working on it?

**Comment by tqchen** [comment]
@hgt312 feel free to take over, right now this issue has not been addressed
