### ISSUE TITLE
[Relay]Inconsistent behavior of ExprFunctor/ExprVisitor/ExprMutator between python and C++

### ISSUE THREAD

**Issue by GuoliangLiCN** [apache/tvm#3908]
I found inconsistent behavior of ExprFunctor/ExprVisitor/ExprMutator between python and C++
Is it intended?

In C++, only ExprMutator has an internal map for memoization.
Lines 227-229 in include/tvm/relay/expr_functor.h
>  protected:
>   /*! \brief Internal map used for memoization. */
>   std::unordered_map<Expr, Expr, NodeHash, NodeEqual> memo_;

In python, it's implemented in ExprFunction and is inherited by ExprVisitor/ExprMutator.
Lines 26-40 in python/tvm/relay/expr_functor.py
> class ExprFunctor:
>     """
>     An abstract visitor defined over Expr.
>     Defines the default dispatch over expressions, and
>     implements memoization.
>     """
>     def __init__(self):
>         self.memo_map = {}
> 
>     # pylint: disable=no-else-return
>     def visit(self, expr):
>         """Apply the visitor to an expression."""
>         if expr in self.memo_map:
>             return self.memo_map[expr]

**Comment by tqchen** [comment]
cc @jroesch this seems to be something we need to unify the terminology and behavior for

**Comment by MarisaKirisame** [comment]
I dont think it is intended. we should have the python one adhere to the C++ one.
