### ISSUE TITLE
[VTA] Tutorial on how to deploy and execute model on device without RPC

### ISSUE THREAD

**Issue by tmoreau89** [apache/tvm#4272]
This is a follow up to forum post: https://discuss.tvm.ai/t/solved-pynq-vta-run-model-locally-on-pynq-z1-instead-of-via-rpc/4336/11

The idea is to complement the existing VTA tutorials to having one that shows how to run a model directly on the device without relying on RPC.

Assigning to @flip1995

**Comment by flip1995** [comment]
@tmoreau89 I have time to write up this documentation now. Should I start a new page in the documentation or just append this to a previous document? Can you post a quick link where to put this documentation in either case?

Sorry for the delay. I forgot about this and just discovered it in my saved issues again.

**Comment by tmoreau89** [comment]
@flip1995 if you could start a new page of the doc (see: https://github.com/apache/incubator-tvm/tree/master/docs/vta), and from your private fork issue a PR. When it's ready please assign the PR to be reviewed by me. Thank you!

**Comment by thilinikb** [comment]
@tmoreau89 @flip1995 Could you please point me to this document if it is available?

**Comment by flip1995** [comment]
Oh damn, I totally forgot about it. Basically you have to add those two lines to your python script, that runs your model on the PYNQ:

```python
dll_path = "/home/xilinx/tvm/build/libvta.so"
ctypes.CDLL(dll_path, ctypes.RTLD_GLOBAL)
```

before the `graph_runtime.create(..)` command. 

I hope this still works. I haven't used TVM/VTA for a long time now.

**Comment by flip1995** [comment]
Or to be more precise, you have to load your model like this:

```python
import ctypes

import tvm
from tvm.contrib import graph_runtime as runtime

libvta_path = "/home/xilinx/tvm/build/libvta.so"
ctypes.CDLL(libvta_path, ctypes.RTLD_GLOBAL)

# load compiled model
with open("graph.json", "r") as graph_file:
    graph = graph_file.read()
with open("params.params", "rb") as params_file:
    params = bytearray(params_file.read())
lib = tvm.module.load("./lib.tar")

ctx = tvm.ext_dev(0)

module = runtime.create(graph, lib, ctx)
module.load_params(params)
```

After that `module.run(**<input-dict>)` should work

**Comment by Joetibz** [comment]
hello guys I am equally new to tvm, and I am trying to run inference on the zynq board without rpc but I keep getting the error stated below, I have not even gotten to making the changes as discussed on this forum, can I get some guidance?
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory

**Comment by flip1995** [comment]
I haven't worked with TVM in ages. But this is probably unrelated to this issue. Either this lib is not installed on the device or you should try to run the same commands with root privileges. The latter usually solved things like this on the PYNQ for me.

**Comment by Joetibz** [comment]
Hello yes thank you so much for your feedback I am aware it has been a
minute since you worked on TVM, but please bear with me I need this for my
studies, I am also trying to run the prediction of a cat from the FPGA
directly, and I saw your modifications you made to have that working, in
the case of the picture model to run on the board are there any other
modifications i should add?

**Comment by flip1995** [comment]
I'm not aware of any other modifications. However, when I used TVM it was even pre-Apache time. So a lot has happened since then. So take all of the suggestions here with a grain of salt.

**Comment by Joetibz** [comment]
w. but any


import ctypes
import tvmfrom tvm.contrib import graph_runtime as runtime
libvta_path = "/home/xilinx/tvm/build/libvta.so"ctypes.CDLL(libvta_path,
ctypes.RTLD_GLOBAL)
# load compiled modelwith open("graph.json", "r") as graph_file:
    graph = graph_file.read()with open("params.params", "rb") as params_file:
    params = bytearray(params_file.read())lib = tvm.module.load("./lib.tar")
ctx = tvm.ext_dev(0)
module = runtime.create(graph, lib, ctx)module.load_params(params)

okay so if i run my own python script like this i should be able to
run tvm on the board with rpc and yes i am aware TVM has long improved
from then till now but i am open to any contributions you might
suggest about running tvm on the fpga board directlyKrones
***@***.***> wrote:

I'm not aware of any other modifications. However, when I used TVM it was

**Comment by Joetibz** [comment]
okay so if i run my own python script like this i should be able to
run tvm on the board with rpc and yes i am aware TVM has long improved
from then till no

import ctypes

import tvm
from tvm.contrib import graph_runtime as runtime

libvta_path = "/home/xilinx/tvm/build/libvta.so"
ctypes.CDLL(libvta_path, ctypes.RTLD_GLOBAL)

# load compiled model
with open("graph.json", "r") as graph_file:
    graph = graph_file.read()
with open("params.params", "rb") as params_file:
    params = bytearray(params_file.read())
lib = tvm.module.load("./lib.tar")

ctx = tvm.ext_dev(0)

module = runtime.create(graph, lib, ctx)
module.load_params(params)
okay so if i run my own python script like this i should be able to run tvm
on the board with rpc and yes i am aware TVM has long improved from then
till now but i am open to any contributions you might suggest about running
tvm on the fpga board
