### ISSUE TITLE
[Relay][Feature] CoreML MLModel PipelineClassifier support

### ISSUE THREAD

**Issue by Rphaet0n** [apache/tvm#4288]
Now Core ML (>= 2.0) models created using Create ML framework for image classification have [PipelineClassifier ](https://apple.github.io/coremltools/coremlspecification/sections/Model.html#pipelineclassifier) type, which is not supported by current version of Relay.
Are there any plans to implements this feature?

I think it would be really cool because Create ML tool allows to achieve good results in ML and it is much more easy to use than for example tensorflow/keras.

**Comment by masahi** [comment]
I don't know anyone actively working on core ml improvement. So there is no actionable item here.
