### ISSUE TITLE
Improve tflite testing for quantized conv2d.

### ISSUE THREAD

**Issue by u99127** [apache/tvm#4823]
@anijain2305 , @inadob 

While we have tests for qnn.conv2d at the relay level, the recent issue with padding highlighted by the pull request #4807 has highlighted the need for better unit tests for quantized conv2d in the tflite frontend. One of the reasons that we hit this issue in the tflite frontend is that the relay unit tests for qnn.conv2d considered an implicit padding while the tflite frontend lowers the padding in quantized conv2d into a separate relay operation. Thus we need to have a unit test for qnn.conv2d for the tflite frontend. 

Further it's probably worth a separate audit to make sure we have adequate tests for qnn ops in the tflite frontend for those operators that are not added.

**Comment by anijain2305** [comment]
Thanks @u99127 for raising this. I will work in coming weeks to get the unit coverage better.

@FrozenGene might also be interested in this.

**Comment by tqchen** [comment]
@anijain2305 please check if we can close this issue

**Comment by anijain2305** [comment]
Yes, we can close this. More tests have been added over past few months, including unit test for quantized conv2d.
Ping @u99127 to have a final say.
