### ISSUE TITLE
[VTA][Chisel] deploy classification not working when timer() is used

### ISSUE THREAD

**Issue by pasqoc** [apache/tvm#5003]
The deploy_classification.py tutorial does not work when used with Chisel based targets such as TSIM and DE10NANO, suggesting this is a runtime related issue coupled with the Chisel based implementation.

The test runs successfully when replacing the timer() call on line 255 with a direct call to the inference model m.run(), suggesting that the problem maybe due to bad state or re-initialization across subsequent runs commanded by the timer() module which by default makes 12 runs.

**Comment by tqchen** [comment]
Please comment about the state of the issue. Whether there are actionable items, or should it be closed

**Comment by pasqoc** [comment]
The issue is still open, as far as I know a fix has not been made.

**Comment by tqchen** [comment]
cc @liangfu @vegaluisjose @tmoreau89

**Comment by liangfu** [comment]
I think this is actually a hardware issue in Chisel implementation of VTA. An incorrect result takes place when we run multiple cycles of inference, due to buffer is contaminated in the first cycle.

**Comment by tqchen** [comment]
@liangfu can you comment the state of the issue? is it possible to fix? or shall we simply close it due to the inability to take further actions
