### ISSUE TITLE
Remote Cross Compilation CUDA Runtime Independent Target

### ISSUE THREAD

**Issue by JonathanMace** [apache/tvm#5420]
I'm training a resnet18_v2 model for CUDA using the RPC runner.  I run an RPC server on a remote machine that has a GPU, and I run the training program locally on a machine that has no GPUs.

`extract_from_program` fails because internally a GPU is required.  Specifically, in `/python/tvm/relay/op/strategy/cuda.py`, the code checks for local GPU properties in three places:
```
if nvcc.have_tensorcore(tvm.gpu(0).compute_version):
```
This check fails when there is no local GPU.  It's also logically inconsistent for remote GPUs even if the local GPU exists.

**Comment by tqchen** [comment]
This is something that we could improve as part of the target system https://discuss.tvm.ai/t/target-and-attributes/6013 they should be part of the target attributes instead of the runtime attribute. 

Leave it open for tracking the issue.

**Comment by tqchen** [comment]
@zxybazh please confirm if this is fixed by recent target change

**Comment by zxybazh** [comment]
I think it's been fixed in [this PR]( https://github.com/apache/tvm/pull/7063).

**Comment by tqchen** [comment]
Awesome, thanks @zxybazh for confirming
