### ISSUE TITLE
[CI] Fix gluoncv tutorial under mxnet-mkl 

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#5458]
This is an error message generated by the mxnet-mkl image in the current master. The error was due to the operator `amp_multicast` is not implmented in the mxnet frontend(likely due to a mkl specialization).

http://ci.tvm.ai:8080/job/temp-ci-docker-staging/job/ci-stage2/6/execution/node/309/log/?consoleFull

Please see if we are interested in quick a fix, since we have docker upgrades depending on it. In the meanwhile, I will revert the docker image to mxnet for now until the next upgrade.

**Comment by tqchen** [comment]
cc @icemelon9 @shoubhik @anijain2305

**Comment by anijain2305** [comment]
@icemelon9 Do you know about this operator?

**Comment by icemelon9** [comment]
It's weird that I cannot reproduce the error in my local environment with mxnet-mkl 1.6.0 and gluoncv.

**Comment by tqchen** [comment]
@icemelon9 could it due to that mxnet optionally enabled amp on the platform that support these ops?

**Comment by icemelon9** [comment]
@tqchen Yes, that might be possible. I'll check it on a GPU instance.

**Comment by eric-haibin-lin** [comment]
I cannot reproduce the error either on Ubuntu GPU instance
```
from mxnet.contrib.quantization import quantize_model_mkldnn
  ImportError: cannot import name 'quantize_model_mkldnn'
```
for both mxnet==1.6.0 and mxnet-mkl==1.6.0
