### ISSUE TITLE
[OpenCL] `directly 4 8 bit int in integer` causes compiling error

### ISSUE THREAD

**Issue by westion717** [apache/tvm#5464]
Hi, I find if use `directly 4 8 bit int in integer ` as following link, it will cause compiling error (when the member of int is referred as .s0, .s1 later) in my opencl compiler provided by my vendor. I am wondering whether the paradigm is legal in the specific opencl spec version or it should be fixed to use `char4` instead.

https://github.com/apache/incubator-tvm/blob/952def53da51e6cf17c5dbf50b92e193622ca695/src/target/source/codegen_opencl.cc#L125

**Comment by tqchen** [comment]
cc @kazum @masahi

**Comment by kazum** [comment]
It looks wrong and should be fixed, I think.

**Comment by kazum** [comment]
@westion717 Can you share your program to reproduce this problem?

**Comment by tqchen** [comment]
@westion717 please follow up

**Comment by areusch** [comment]
closing this issue since there is no reproduction and it is over 2 years old.
