### ISSUE TITLE
[RELAY][PASS] Handle Op Attribute for LRN in ConvertLayout

### ISSUE THREAD

**Issue by mikeseven** [apache/tvm#5529]
While converting layout from TensorFlow, from NHWC to NCHW, I noticed LRN axis was not converted from using axis=3 to axis=1. 

Looking at the code, I don't find where ConvertLayout pass would handle attributes of operators. So, potentially, I wonder if this bug on LRN may be even more widespread to other nodes?

**Comment by tqchen** [comment]
cc @yzhliu @anijain2305 can you look into the issue?

**Comment by yzhliu** [comment]
The attributes are handled in registered python code, e.g., https://github.com/apache/incubator-tvm/blob/master/topi/python/topi/x86/conv2d_alter_op.py 
I don't see such registry for LRN, did I miss anything @anijain2305 ?

**Comment by anijain2305** [comment]
Yes, we dont have a registry for LRN. Not sure this is a bug. This seems like a missing feature. ConvertLayout will put LayoutTransforms before and after LRN.

**Comment by tqchen** [comment]
I see, if the result is generated corrected, then it should be missing feature case.

**Comment by mikeseven** [comment]
thanks @tqchen and @anijain2305
