### ISSUE TITLE
[TEST][FLAKY] tests/python/contrib/test_cudnn.py

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#5667]
https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-5665/1/pipeline
https://ci.tvm.ai/blue/organizations/jenkins/tvm/detail/PR-5663/2/pipeline

**Comment by tqchen** [comment]
cc @wpan11nv

**Comment by mbrookhart** [comment]
I can reproduce this consistently on my desktop system with Cuda 10.0 and Cudnn 7.6.5.
