### ISSUE TITLE
NotImplementedError: The following operators are not implemented: {'GatherTree'} 

### ISSUE THREAD

**Issue by yjiangling** [apache/tvm#5810]
Hi,
    When I compile a tensorflow pb model with TVM, it gives the following error message:

NotImplementedError: The following operators are not implemented: {'GatherTree'} 

Is it caused by dunamic RNN network? The op "TensorArray" is not support yet? How can I solve it? As the examples given in the projects are image processing models, most of them are CNN networks. But when we deal with speech recognition task, the dynamcin RNN networks are universally used, especially in the decoder step, the decode results are stored in the TensorArray.

Anyone could U please give me some help? Thanks a lot!

**Comment by masahi** [comment]
TF TensorArray should be already supported, but there is no tree data structure in TVM. There is no actionable item, so closing.
