### ISSUE TITLE
[TFLite] TFLite FP16 Post Quantization Support

### ISSUE THREAD

**Issue by FrozenGene** [apache/tvm#5823]
TensorFlow Lite now supports converting weights to 16-bit floating point values during model conversion from TensorFlow to TensorFlow Lite's flat buffer format. This results in a 2x reduction in model size. 

However, this will insert new `dequantize` for ops (like `conv2d`) used for `dequantize` fp16 weight to fp32.  Like this:
![image](https://user-images.githubusercontent.com/7287321/84767184-925abf80-b004-11ea-8894-8c94119fc25e.png)

TVM doesn't support this behavior. List the things we mainly should to do:

- Support float16 type inside tflite parser
- Extend `dequantize` to support fp16 to fp32 

Related issue:https://github.com/apache/incubator-tvm/issues/5774#

**Comment by onkar-sima-ai** [comment]
Is this issue still open?

**Comment by FrozenGene** [comment]
> @FrozenGene Is this issue still open?

I think #7093 is enough and could close it now.
