### ISSUE TITLE
[GOLANG]Can not import the compiled binary package gotvm.a in Golang with version > 1.12

### ISSUE THREAD

**Issue by xijiz** [apache/tvm#6178]
Hi,
  I am using TVM Golang API for neural model inference. However, I can not import the compiled binary package `gotvm.a` in my code. The environment information as follows:

- Golang 1.14.6
- Ubuntu 18.04/amd64

**Comment by srkreddy1238** [comment]
Thanks for notifying this issue. I will  try to spend some time to upgrade golang version.
You are most welcome to contribute, if you are already progressing with upgrade.

**Comment by tqchen** [comment]
ping @srkreddy1238
