### ISSUE TITLE
[Frontend][PyTorch] NotImplementedError: The following operators are not implemented: ['aten::is_floating_point', 'aten::true_divide']

### ISSUE THREAD

**Issue by cloud-mxd** [apache/tvm#6239]
I'm using file /python/tvm/relay/frontend/pytorch.py to convert pytorch model, but raise error like this:
![image](https://user-images.githubusercontent.com/68592047/89726825-a1348000-da51-11ea-8368-124062d4aa52.png)

pytorch == 1.6.0 and tvm is latest

**Comment by cloud-mxd** [comment]
@masahi

**Comment by TylerADavis** [comment]
It seems that true_divide is supported as of #6472, but `is_floating_point` is definitely missing. I'm currently looking at adding support for `is_floating_point`, and I hope to have something before the week is done.
