### ISSUE TITLE
[DISCUSS][RFC] Apache TVM Graduation

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#6299]
Dear Community:

The TVM project has been an Apache incubator project for nearly 1.5 years now. In the past one and half year, the community grew healthily under the Apache way:

- The community now has 16 PPMC members, 31 committers, from a diverse list of organizations. The list is actively growing every month.
- ~ 150 PRs merged each month.
- vibrate technical discussion and exciting new features.

The community has produced two high-quality apache releases. We think that the community is mature enough to push for graduation as it is, and will continue to work on high-quality releases concurrently.

For reference, we also put together a [maturity evaluation doc](https://docs.google.com/document/d/18nyAH-fcptVezAxPQe6H3FeTKPRkujOp1tc1YRSPLok/edit?usp=sharing) under the Apache maturity model.

Please share your thoughts!

NOTE: this thread is mirrored to dev@

**Comment by markusweimer** [comment]
+1

TVM has been implementing many of the best practices of the ASF since before it entered incubation. The project is ready :)

**Comment by ZihengJiang** [comment]
+1
Looking forward to this!

**Comment by bgchun** [comment]
+1

I'm really excited about the progress that the TVM community has made! The project is definitely ready for graduation.

**Comment by junrushao1994** [comment]
+1

TVM not only follows the Apache guideline with great practices, but also delivers the greatest features for users continuously. Glad to see the rapid development and accomplishment of TVM and the community! Hope to see it graduate smoothly!

**Comment by hsaputra** [comment]
The community also have done several successful releases. 
All the discussions and decisions have been done in the open and Apache way.
I agree that the project is ready for graduation as TLP in ASF.

**Comment by tnachen** [comment]
+1 as well, I don't see any problems for TVM to graduate,

**Comment by yidawang** [comment]
+1 TVM follows the Apache guideline well and has substantial impact in both academia and industry. It sets a great example for a successful Apache project.

**Comment by sscdotopen** [comment]
+1 from me as well!

**Comment by vinx13** [comment]
+1, this is very exciting

**Comment by siju-samuel** [comment]
+1
TVM community progress is very good and its ready for graduation. Looking forward to this.

**Comment by tvm-archiver** [comment]
+1 Apache TVM graduation will be a huge milestone. It’s already been a very vibrant community.

**Comment by tom-gall** [comment]
+1, definitely think the project is ready. Well done everyone!

**Comment by MarisaKirisame** [comment]
+1
what does graduation imply? how will it change tvm?

**Comment by tqchen** [comment]
@MarisaKirisame graduation means the project will official land as a top-level project of ASF. From a technical point of view, nothing will change, and we will continue to make better deep learning compiler together with the community.

**Comment by comaniac** [comment]
+1
Exciting to become an Apache project contributor :D

**Comment by jroesch** [comment]
+1 exciting times, agree with what everyone else has already said!

**Comment by yzhliu** [comment]
+1. feel great to be part of the team.

**Comment by zhiics** [comment]
+1
Looking forward to the continued success after graduation.

**Comment by icemelon9** [comment]
+1
TVM community gets good traction. super excited to be part of the community.

**Comment by srkreddy1238** [comment]
+1, feeling very happy and great to be part of TVM.

**Comment by tvm-archiver** [comment]
Hi,

Apart from being a great project, TVM has an active and growing community.
It has a good understanding of the Apache Way [1] which is most important.

I think that TVM is ready for graduation. As the last step, we should
update the podling status file before starting a vote for graduation at
general@incubator [2][3].

I am +1 for graduation!

[1] https://www.apache.org/theapacheway/
[2]
https://incubator.apache.org/guides/graduation.html#checking_the_status_file
[3] http://incubator.apache.org/projects/tvm.html

Kind Regards,
Furkan KAMACI

**Comment by tqchen** [comment]
Thanks Furkan. I have updated the status file.

**Comment by tqchen** [comment]
We also need a VP who handles the PMC's reporting to the board, I self nominate to serve that role for the community.

**Comment by tqchen** [comment]
Thanks everyone for great discussions, here is the formal voting thread:
- https://github.com/apache/incubator-tvm/issues/6299
- https://lists.apache.org/thread.html/rd5b8eefe49af09a2d0913758a5e5737b3fdb9072bc0becf4a2b2c7ee%40%3Cdev.tvm.apache.org%3E

**Comment by hsaputra** [comment]
Thanks, Tianqi. I think the community would love to have you the VP for the TVM as TLP.
