### ISSUE TITLE
[VOTE] Apache TVM Graduation

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#6332]
Dear Community:

Thanks  to everyone who participated in the discussion about graduation[1]. This is a formal voting thread for Apache TVM’s graduation.

If this vote passes, the next step would be to submit the resolution below
to the Incubator PMC, who would vote on sending it on to the Apache Board.

Vote:
[ ] +1 - Recommend graduation of Apache TVM as a TLP
[ ]  0 - I don't feel strongly about it, but don't object
[ ] -1 - Do not recommend graduation of Apache TVM because...

The VOTE will open for at least 72 hours.

This thread is mirrored to dev@, please vote by replying to this thread

------------------
The TVM project has been an Apache incubator project for nearly 1.5 year now. In the past one and half year, the community grew healthily under the Apache way. Some highlights include:

- A successful developer conference that we are continuing to host this year
- Great community growth, as of now, the community contains 16 PPMC members, 31 committers, from a diverse list of organizations. We are actively growing the list monthly.
- Active contributions: ~ 150 PRs merged each month.

The community has produced two formal apache releases. While we could also wait until more releases. We feel that the community is mature enough that we can push for graduation as it is, and continue to push for high quality releases concurrently.

For reference, we also put together a maturity evaluation doc[2] under the Apache maturity model.

Some additional note about the resolution below: the current PPMC will be transitioned to the PMC. We have invited all the mentors in the current PPMC who like to stay involved.

-----------------

Establish the Apache TVM Project

WHEREAS, the Board of Directors deems it to be in the best interests of
the Foundation and consistent with the Foundation's purpose to establish
a Project Management Committee charged with the creation and maintenance
of open-source software, for distribution at no charge to the public,
related to compilation of machine learning models to run on a wide range of hardware platforms...

NOW, THEREFORE, BE IT RESOLVED, that a Project Management Committee
(PMC), to be known as the "Apache TVM Project", be and hereby is
established pursuant to Bylaws of the Foundation; and be it further

RESOLVED, that the Apache TVM Project be and hereby is responsible for the
creation and maintenance of software related to compilation of machine learning models to run on a wide range of hardware platforms; and be it further

RESOLVED, that the office of "Vice President, Apache TVM" be and
hereby is created, the person holding such office to serve at the
direction of the Board of Directors as the chair of the Apache TVM
Project, and to have primary responsibility for management of the
projects within the scope of responsibility of the Apache TVM
Project; and be it further

RESOLVED, that the persons listed immediately below be and hereby are
appointed to serve as the initial members of the Apache TVM Project:

 * Tianqi Chen <tqchen@apache.org>
 * Timothy Chen <tnachen@apache.org>
 * Zhi Chen <zhic@apache.org>
 * Byung-Gon Chun <bgchun@apache.org>
 * Ziheng Jiang <ziheng@apache.org>
 * Furkan Kamaci <kamaci@apache.org> 
 * YiZhi Liu <liuyizhi@apache.org>   
 * Masahiro Masuda <masahi@apache.org>
 * Thierry Moreau <moreau@apache.org>
 * Jared Roesch <jroesch@apache.org>
 * Henry Saputra <hsaputra@apache.org>
 * Haichen Shen <haichen@apache.org>
 * Markus Weimer <weimer@apache.org>
 * Eddie Yan <eqy@apache.org>
 * Lianmin Zheng <lmzheng@apache.org>

NOW, THEREFORE, BE IT FURTHER RESOLVED, that Tianqi Chen be appointed to
the office of Vice President, Apache TVM, to serve in accordance
with and subject to the direction of the Board of Directors and the
Bylaws of the Foundation until death, resignation, retirement, removal
or disqualification, or until a successor is appointed; and be it
further

RESOLVED, that the Apache TVM Project be and hereby is tasked with
the migration and rationalization of the Apache Incubator TVM
podling; and be it further

RESOLVED, that all responsibilities pertaining to the Apache Incubator
TVM  podling encumbered upon the Apache Incubator PMC are hereafter
Discharged.

- [1] https://lists.apache.org/thread.html/r91b8f469c6a54769869bb2435b7334a28bcff885ae078ab5612dae00%40%3Cdev.tvm.apache.org%3E
- [2] https://docs.google.com/document/d/18nyAH-fcptVezAxPQe6H3FeTKPRkujOp1tc1YRSPLok/edit?usp=sharing

**Comment by tvm-archiver** [comment]
+1 (binding)

TVM is ready to graduate.

Markus

**Comment by junrushao1994** [comment]
+1 (non-binding)

Super excited!!

**Comment by ZihengJiang** [comment]
+1 (binding)

**Comment by tmoreau89** [comment]
+1 (binding)

**Comment by hsaputra** [comment]
+1 (binding)

**Comment by electriclilies** [comment]
+1 (non-binding)

**Comment by jroesch** [comment]
+1 (binding)

**Comment by icemelon9** [comment]
+1 (binding)

**Comment by zhiics** [comment]
+1 (binding)

**Comment by comaniac** [comment]
+1 (non-binding)

**Comment by masahi** [comment]
+1 (binding)

**Comment by kazum** [comment]
+1 (non-binding)

**Comment by vinx13** [comment]
+1 (non-binding)

**Comment by cchung100m** [comment]
+1 (non-binding)

**Comment by siju-samuel** [comment]
+1 (non-binding)

**Comment by bgchun** [comment]
+1 (binding)

**Comment by tnachen** [comment]
+1 binding

**Comment by jcf94** [comment]
+1 (non-binding)

**Comment by srkreddy1238** [comment]
+1 (binding)

**Comment by kamaci** [comment]
Apart from being a great project, TVM has an active and growing community. It has a good understanding of the Apache Way [1] which is most important. I think that TVM is ready for graduation. 

I am +1 for graduation!

[1] https://www.apache.org/theapacheway/

**Comment by tqchen** [comment]
Thanks everyone. The results are:

+1
Markus
Junru
ziheng
Thierry
Henry
Lily
Jared
Haichen
Masa
Morita
Wuwei
Siju
Gon
Timothy
Chenfan 
Siva 
Furkan

+0 None
-1 None

The vote has passed. We will now proceed with a followup vote in IPMC.
