### ISSUE TITLE
[Torch] Support aten::lstm

### ISSUE THREAD

**Issue by masahi** [apache/tvm#6474]
It seems the commonly used [`torch.nn.LSTM`](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html) module generates `aten::lstm` op, which we currently don't support. It is reported in https://discuss.tvm.apache.org/t/import-rnn-t-pytorch-model-into-tvm/7874 and it is likely we'll get more requests for this op in the future.

The corresponding PyTorch implementation is here https://github.com/pytorch/pytorch/blob/70c8daf43946b53af6493d058899ef952d27d339/aten/src/ATen/native/RNN.cpp#L1396

**Comment by jroesch** [comment]
I believe the MXNet frontend lowers LSTM to Relay directly.

**Comment by zhangzhen507** [comment]
But, the pre-trained rnn-t model  https://zenodo.org/record/3662521 is a pytorch model. Can you support the torch.nn.LSTM by aten::lstm in TVM ?

**Comment by masahi** [comment]
yes, `torch.nn.LSTM` is translated to `aten::lstm` in Torchscript.

**Comment by zhangzhen507** [comment]
> yes, `torch.nn.LSTM` is translated to `aten::lstm` in Torchscript.

Hi, do you have a plan when you will support the aten::lstm in tvm/relay/frontend/pytorch.py ?

**Comment by masahi** [comment]
No from my end. I'm not expert on LSTM and don't have time for this.

**Comment by masahi** [comment]
https://github.com/apache/tvm/pull/8447
