### ISSUE TITLE
[TOPI] High dimension matrix multiplication not supported 

### ISSUE THREAD

**Issue by wjliu1998** [apache/tvm#6476]
When run the code 
`input_tensor_placeholder = te.placeholder((224,224,3), name="input_tensor_placeholder")
m_tensor_placeholder = te.placeholder((3,3), name="m_tensor_placeholder")
mid_result = topi.matmul(input_tensor_placeholder, m_tensor_placeholder)`
error will occur:
`TVMError: Check failed: ndim() == indices.size() (3 vs. 2) : Tensor dimension mismatch in readndim = 3, indices.size=2`
It seems that in `topi.matmul`, the dimension of two tensors will be the same， which is different from the `torch.matmul`.

Is there any other way to execute high dimension matrix multiplication? Or is it just a missing feature?

**Comment by masahi** [comment]
It is not supported yet, let's continue at https://github.com/apache/tvm/issues/8412
