### ISSUE TITLE
[RUST][FFI] Pass uint as int in PackedFunc

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#6540]
per PackedFunc FFI convention, we should always pass integer as i64 when they appear as argument of a PackedFunc to simplify the calling.  We might need to update the rust FFI to reflect it. 

Related 
- https://github.com/apache/incubator-tvm/issues/6528

cc @ehsanmok

**Comment by tqchen** [comment]
cc @jroesch @mwillsey

**Comment by intheworld** [comment]
I see the following code in PackedFunc. 
impl_pod_value!(Int, i64, [i8, i16, i32, i64, isize]);
impl_pod_value!(UInt, i64, [u8, u16, u32, u64, usize]);

Inner type is i64. in #6528 , I think the problem is the inconsistence between rust Context and TVMContext.

**Comment by tqchen** [comment]
ping @jroesch
