### ISSUE TITLE
[Rust] Stabilization Tracking Issue for 0.8

### ISSUE THREAD

**Issue by jroesch** [apache/tvm#6604]
The goal of this issue is tracking requisite changes needed to stabilize the compiler APIs in Rust.

- [ ] Refactor NDArray with type parameter? 
- [ ] Ensure sufficient documentation examples. 

More to come.

**Comment by jroesch** [comment]
See #5889

**Comment by jroesch** [comment]
See #6089

**Comment by masahi** [comment]
v0.8 was already released.
