### ISSUE TITLE
[IR] Make IRModule non-nullable

### ISSUE THREAD

**Issue by jroesch** [apache/tvm#6617]
After my recent diagnostic refactors it would be great to make modules non-nullable as they have a valid "empty" value, and there is no reason to use null ptrs here. 

cc @ANSHUMAN87 @Hzfengsy @junrushao

**Comment by ANSHUMAN87** [comment]
Yes, I also agree IRModule should be non-nullable. Would love to have some thoughts from @junrushao1994 too!

Please bear with me, I am just trying to get a clear picture here.
As per our last effort(#5654), the IRModule has now empty constructor with empty values. It can not have null ptrs. But there are cases which needs optional input for IRModule which carry null ptrs.

So what is our line of action here ?

**Comment by junrushao1994** [comment]
Thanks @ANSHUMAN87 for reminding me of the PR #5654! It means that by default we won’t create null IRModules any more. The only thing left to do is that we search the code base, and find whether there are intentionally created null IRModules.

**Comment by ANSHUMAN87** [comment]
Sorry for such late response!
I have cross checked entire base code as per suggestion from @junrushao1994 , however could not find any candidate.
Please correct me if i am mistaken.
@jroesch : In case you have any specific case in mind, please let us know. Thanks!
