### ISSUE TITLE
Cuda NMS argsorts with invalid entries

### ISSUE THREAD

**Issue by ghost** [apache/tvm#6629]
I believe the following two lines should have `valid_count=valid_count`, as in [the default implementation](https://github.com/apache/incubator-tvm/blob/21002cd094c34716b1e07a63ed76f53dadd60e23/python/tvm/topi/vision/nms.py#L558). I believe the `data` array is zeroed at initialization for cuda, so the issue only manifests if nms is run more than once, with the first run containing more valid boxes than the second run.

https://github.com/apache/incubator-tvm/blob/21002cd094c34716b1e07a63ed76f53dadd60e23/python/tvm/topi/cuda/nms.py#L488

https://github.com/apache/incubator-tvm/blob/21002cd094c34716b1e07a63ed76f53dadd60e23/python/tvm/topi/cuda/nms.py#L492

**Comment by zhiics** [comment]
cc @Laurawly

**Comment by Laurawly** [comment]
@alec-anyvision Thanks for pointing this issue out. The changes made were explained in PR #5339. So in the original implementation, `get_valid_count` will rearrange the invalid boxes to the end of the array while in the updated implementation, this movement is done by `argsort` to improve the performance. `argsort` doesn't make changes to `valid_count`, I'm not sure why running `nms` multiple times will manifest the number of valid boxes. Could you elaborate more?

**Comment by masahi** [comment]
This code is no longer used.
