### ISSUE TITLE
Race Condition in Cuda SSD Multibox

### ISSUE THREAD

**Issue by ghost** [apache/tvm#6631]
I may be missing something about the IR, but there seems to be a race condition in the following line. There is no guarantee that `temp_valid_count[tid * num_anchors + k - 1]` will be computed before `tid == 0` reaches this point. However, in practice this seems very unlikely. https://github.com/apache/incubator-tvm/blob/21002cd094c34716b1e07a63ed76f53dadd60e23/python/tvm/topi/cuda/ssd/multibox.py#L234

**Comment by tqchen** [comment]
cc @Laurawly

**Comment by Laurawly** [comment]
@alec-anyvision Thanks for catching this! I'd reimplement the `valid_count` computation using atomic operations similarly as what's done in `nms.py`.
