### ISSUE TITLE
[TEST][FLAKY] frontend/pytorch/test_forward.py::test_forward_nms 

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#6689]
https://ci.tlcpack.ai/job/tvm/job/main/19/execution/node/380/log/

Could due to too close ties, perhaps we should construct nms test-cases differently that have no clear ties

**Comment by tqchen** [comment]
cc @masahi @Laurawly

**Comment by masahi** [comment]
cc @yongwww

**Comment by yongwww** [comment]
@masahi @tqchen I failed to reproduce it on my environment. The flaky issue was introduced due to the accumulation of tiny difference of computations, especially for a large number of input boxes. I will send a pr to loosen the tolerance.

**Comment by masahi** [comment]
@yongwww maybe setting rng manual seed via `torch.manual_seed(...)` help.

**Comment by masahi** [comment]
Still has this problem 

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7824/1/pipeline

**Comment by denise-k** [comment]
Hi folks, is this still active?

**Comment by masahi** [comment]
I was able to reproduce the error after 30 runs, it is fixed in https://github.com/apache/tvm/pull/9140
