### ISSUE TITLE
[FRONTEND][MXNET 2.0] Support three missing operators: _npi_subtract_scalar, _npi_stack, _npi_advanced_indexing_multiple

### ISSUE THREAD

**Issue by sxjscience** [apache/tvm#6721]
Recently, TVM has supported the incoming MXNet 2.0 frontend via a series of PRs: https://github.com/apache/incubator-tvm/pull/6054, https://github.com/apache/incubator-tvm/pull/6699. This enables the new GluonNLP 1.0, which has upgraded from MXNet 1.x to MXNet 2.0 to convert to TVM graph (as added in https://github.com/dmlc/gluon-nlp/pull/1390). However, I noticed that there are three missing operators when I profile against the [BART model](https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/models/bart.py).

- _npi_subtract_scalar
- _npi_stack
- _npi_advanced_indexing_multiple

The first two operators are pretty straightforward to support while the `_npi_advanced_indexing_multiple` is more complicated and is triggered when we call `a[idx1, idx2]`. The MXNet-side implementation of `_npi_advanced_indexing_multiple` is here: https://github.com/apache/incubator-mxnet/blob/6bbd53107aa16fc41e8d462cf5dc46fb70d592df/src/operator/numpy/np_indexing_op.cc#L479-L491

Since I do not have the bandwidth in supporting this operator. Help is really appreciated.

**Comment by sxjscience** [comment]
Also cc @yzhliu

**Comment by sxjscience** [comment]
To provide more context on the `_npi_advanced_indexing_multiple` usage in GluonNLP, it's used here: https://github.com/dmlc/gluon-nlp/blob/149270a7b357e2a34972e6a596fbeea2bbd6869e/src/gluonnlp/models/bart.py#L277

**Comment by junrushao1994** [comment]
Hey Xingjian, thanks for bringing this up! It is certainly more than welcome for future contribution. Shall we put up a list of MXNet operators to be supported and consolidate them into a single thread instead? If there is no actionable item, shall we close this issue? Thanks!

**Comment by sxjscience** [comment]
I think we can create a thread about that. Do you think that we should create a new one?

**Comment by junrushao1994** [comment]
Yeah we can have a consolidated "[Frontend][MXNet] Importer Missing Operators" thread and mark it as "help wanted". What do you think?

**Comment by sxjscience** [comment]
Sounds good to me. Should I change the title of this issue so we may reuse that? (Or create a new one?)

**Comment by junrushao1994** [comment]
What about creating a new one, categorizing operators like #1799 does

**Comment by sxjscience** [comment]
Move to https://github.com/apache/tvm/issues/7186
