### ISSUE TITLE
[Rust][Relay] nn.dense: is `units` a required parameter?

### ISSUE THREAD

**Issue by gussmith23** [apache/tvm#6836]
When parsing the following Relay expression:
```
#[version = "0.0.5"]
def @main(%data: Tensor[(16, 32), float32], %weights: Tensor[(64, 32), float32]) -> Tensor[(16, 64), float32] {
  nn.dense(%data, %weights)/* ty=Tensor[(16, 64), float32] */
}
```
I get:
```
thread 'language::from_relay::tests::dense' panicked at 'AttributeError: relay.attrs.DenseAttrs: Cannot find required field 'units' during initialization.If the key is defined check that its type matches the declared type.
```

Adding `units=64` fixes the problem. However, the docs indicate that `units` is optional...at least in the Python frontend. Maybe `units` isn't optional in the text format?

(this is a new error -- I used to get the error detailed in #6470 when parsing nn.dense)

**Comment by masahi** [comment]
Let's continue at https://github.com/apache/tvm/issues/7003
