### ISSUE TITLE
[MaskRCNN][AnnotateTarget]: Fails while reconciling shapes of concatenate inputs

### ISSUE THREAD

**Issue by ashutoshparkhi** [apache/tvm#6943]
Hello,

Here is the error:
_in particular dimension 0 conflicts 1 does not match 0; unable to unify: `Tensor[(1, ?, ?), float32]` and `Tensor[(0, 300, 300), float32]_

Attached file is capable of producing the error. It calls PyToch frontend followed by AnnotateTarget. It is a modified version of TVM's tutorial about MaskRCNN.

Thanks,
Ashutosh
[partition_maskrcnn.py.txt](https://github.com/apache/incubator-tvm/files/5572718/partition_maskrcnn.py.txt)

**Comment by junrushao1994** [comment]
Thanks for reporting. We use the discussion forum (https://discuss.tvm.apache.org/) for general usage issues. Please open a thread in the forum. Thanks!
