### ISSUE TITLE
strncpy in TVMAPISetLastError needs to make sure that the copied string is less then the size of the destination 

### ISSUE THREAD

**Issue by tom-gall** [apache/tvm#6960]
When building the micro tvm runtime with Zephyr

Including boilerplate (Zephyr base): /lkft/tgall/zephyrproject/zephyr/cmake/app/boilerplate.cmake
In file included from /home/tgall/zephyr-sdk-0.11.3/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/string.h:180,
                 from /home/tgall/tvm/tvm/src/runtime/crt/common/crt_runtime_api.c:27:
/home/tgall/tvm/tvm/src/runtime/crt/common/crt_runtime_api.c: In function 'TVMAPISetLastError':
/home/tgall/tvm/tvm/src/runtime/crt/common/crt_runtime_api.c:41:44: error: '__builtin_strncpy' specified bound 1024 equals destination size [-Werror=stringop-truncation]
   41 | void TVMAPISetLastError(const char* msg) { strncpy(g_last_error, msg, sizeof(g_last_error)); }
      |                                            ^~~~~~~
cc1: all warnings being treated as errors

**Comment by tom-gall** [comment]
@areusch - minor bug

**Comment by tqchen** [comment]
cc @areusch can you follow up on this?

**Comment by tom-gall** [comment]
Looks like a fix for this has already landed from a different PR.

**Comment by tqchen** [comment]
Thanks @tom-gall for the timely update :)
