### ISSUE TITLE
[TEST][FLAKY] tests/python/topi/python/test_topi_argwhere

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7041]
https://ci.tlcpack.ai/job/tvm/job/main/275/execution/node/458/log/

Should due to the problem of a tie, need to construct the testcases carefully. For example try to construct from a shuffle of arange

**Comment by tqchen** [comment]
cc @zhiics

**Comment by zhiics** [comment]
I see. I think the problem is caused by cuda sort. It is flaky. That's why we wanted to use thrust. Let's skip cuda for this test for now. I thought removing the annotation would skip it, but it would be still in the enabled list on the GPU CI.

**Comment by zhiics** [comment]
close by #7042
