### ISSUE TITLE
is-there-a-horizontal-fusion-demo

### ISSUE THREAD

**Issue by zhxfl** [apache/tvm#7047]
https://discuss.tvm.apache.org/t/is-there-a-horizontal-fusion-demo/8598

**Comment by zhxfl** [comment]
It is very import for small network when the num of block is small than the num of sm

**Comment by zhxfl** [comment]
paper :  https://arxiv.org/pdf/2007.01277.pdf

**Comment by zhiics** [comment]
Thanks. Let's just use the discuss thread to keep the discussion.
