### ISSUE TITLE
c++ run slower than python?

### ISSUE THREAD

**Issue by Coder-nlper** [apache/tvm#7052]
I use the following example, and modify it to load my model.
https://github.com/apache/tvm/blob/main/apps/howto_deploy/cpp_deploy.cc
I count the inference time of python and C++.

c++ code:
  clock_t startTime, endTime;
  startTime=clock();
  for (int i = 0; i < 36; ++i) {
      static_cast<int*>(x->data)[i] = array[i];
  }
  // set the right input
  set_input("input_ids", x);
  // run the code
  run();
  // get the output
  get_output(0, y);

  for (int i = 0; i < 36; ++i) {
      cout << static_cast<float*>(y->data)[i] << " ";
  }
 endTime = clock();
 cout<<(double)(endTime - startTime)/CLOCKS_PER_SEC<<endl;

python code:
   start = time()
   m.set_input("input_ids", x)
   m.run()
   tvm_output= m.get_output(0)
   predictions = np.squeeze(tvm_output.asnumpy())
   end = time()
   print("cost {}".format(end - start))

the result:
python cost : 0.00779s
c++ cost: 0.033162s

c++ is much slower than python, I can not figure out why????

my platform info:
cpu:   Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
os:   Linux x-np 5.4.0-56-generic #62~18.04.1-Ubuntu x86_64
tvm:   0.8
llvm:   6.0
gcc:   7.5.0

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.apache.org/. In your partcular case, the time cost of printing(in c++) might be related. Under the hood both APIs uses the same runtime and generated code
