### ISSUE TITLE
Error running YOLOv3-tiny example

### ISSUE THREAD

**Issue by fprotopapa** [apache/tvm#7061]
I'm trying to run the YOLOv3-tiny example (tvm/vta/tutorials/frontend/legacy/deploy_detection.py) 
with applied changes from #7058. 
Scripts launched from tvm base directory terminates with the error message below. 

**System**

Running under Ubuntu 18.04.5 LTS and Docker images created with Dockerfile.ci_cpu. 
Version: 0.8.dev0

**Error message**

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (7) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x65) [0x7f1f51478b75]
  [bt] (6) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0x6496c2) [0x7f1f508f56c2]
  [bt] (5) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const+0x1b7) [0x7f1f508f4f77]
  [bt] (4) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0xfd19cf) [0x7f1f5127d9cf]
  [bt] (3) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0xfd0c25) [0x7f1f5127cc25]
  [bt] (2) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::TypeInferencer::Infer(tvm::GlobalVar, tvm::relay::Function)+0x67) [0x7f1f5127c1d7]
  [bt] (1) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::TypeSolver::Solve()+0xd39) [0x7f1f51120599]
  [bt] (0) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0xe70732) [0x7f1f5111c732]
  [bt] (8) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0x6496c2) [0x7f1f508f56c2]
  [bt] (7) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const+0x1b7) [0x7f1f508f4f77]
  [bt] (6) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0xfd19cf) [0x7f1f5127d9cf]
  [bt] (5) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0xfd0c25) [0x7f1f5127cc25]
  [bt] (4) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::TypeInferencer::Infer(tvm::GlobalVar, tvm::relay::Function)+0x67) [0x7f1f5127c1d7]
  [bt] (3) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::TypeSolver::Solve()+0x36d) [0x7f1f5111fbcd]
  [bt] (2) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<bool (tvm::runtime::Array<tvm::Type, void> const&, int, tvm::Attrs const&, tvm::TypeReporter const&)>::AssignTypedLambda<bool (*)(tvm::runtime::Array<tvm::Type, void> const&, int, tvm::Attrs const&, tvm::TypeReporter const&)>(bool (*)(tvm::runtime::Array<tvm::Type, void> const&, int, tvm::Attrs const&, tvm::TypeReporter const&))::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x7d7) [0x7f1f50d8d0e7]
  [bt] (1) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(tvm::relay::ReshapeRel(tvm::runtime::Array<tvm::Type, void> const&, int, tvm::Attrs const&, tvm::TypeReporter const&)+0x709) [0x7f1f5104f759]
  [bt] (0) /workspace/.local/lib/python3.6/site-packages/tvm-0.8.dev238+gdc7220447-py3.6-linux-x86_64.egg/tvm/libtvm.so(+0xd75d12) [0x7f1f51021d12]
  File "/workspace/tvm/src/relay/analysis/type_solver.cc", line 621
TVMError: 
---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: false == false: [16:00:03] /workspace/tvm/src/relay/op/tensor/transform.cc:632: 
---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: oshape_sum == data_shape_sum (172380 vs. 173056) : Input tensor shape and reshaped shape are not compatible
---------------------------------------------------------------

TVM/VTA is new to me, help is really appreciated.

**Comment by tqchen** [comment]
Please open a new thread on https://discuss.tvm.apache.org/
