### ISSUE TITLE
tvm c++ compil error

### ISSUE THREAD

**Issue by xingha** [apache/tvm#7066]
compiled tvm_mobilefacenet

root@3301baaa7ede:build# make
Scanning dependencies of target tvm_mobilefacenet
[ 33%] Building CXX object CMakeFiles/tvm_mobilefacenet.dir/tvm_runtime_pack.cc.o
[ 66%] Building CXX object CMakeFiles/tvm_mobilefacenet.dir/main.cpp.o
[100%] Linking CXX executable ../tvm_mobilefacenet
CMakeFiles/tvm_mobilefacenet.dir/tvm_runtime_pack.cc.o: In function `TVMModFree':
tvm_runtime_pack.cc:(.text+0x2441): undefined reference to `TVMObjectFree'
collect2: error: ld returned 1 exit status
CMakeFiles/tvm_mobilefacenet.dir/build.make:170: recipe for target '../tvm_mobilefacenet' failed
make[2]: *** [../tvm_mobilefacenet] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tvm_mobilefacenet.dir/all' failed
make[1]: *** [CMakeFiles/tvm_mobilefacenet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dimitraka** [comment]
How did you solved this issue?

I'm getting an error "recipe for target 'container_test' failed"  while  "Linking CXX executable container_test"

**Comment by xingha** [comment]
i add tvm library into target_link_libraries(tvm_mobilefacenet  ${OpenCV_LIBS} -ldl -lpthread tvm), it's run.
