### ISSUE TITLE
tvm_mobilefacenet running error

### ISSUE THREAD

**Issue by xingha** [apache/tvm#7077]
terminate called after throwing an instance of 'dmlc::Error'
  what():  [03:14:35] /data/workspace/tvm/include/../src/runtime/registry.cc:78: Check failed: override: Global PackedFunc __tvm_set_device is already registered
Stack trace:
  [bt] (0) ../tvm_mobilefacenet(dmlc::LogMessageFatal::~LogMessageFatal()+0x4a) [0x560d8f3e25f2]
  [bt] (1) ../tvm_mobilefacenet(tvm::runtime::Registry::Register(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x1ef) [0x560d8f3d025d]
  [bt] (2) ../tvm_mobilefacenet(+0x2d404) [0x560d8f3e0404]
  [bt] (3) ../tvm_mobilefacenet(+0x2e071) [0x560d8f3e1071]
  [bt] (4) ../tvm_mobilefacenet(+0x7f64d) [0x560d8f43264d]
  [bt] (5) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f556611a150]
  [bt] (6) ../tvm_mobilefacenet(+0x16b6a) [0x560d8f3c9b6a]

Aborted (core dumped)

**Comment by junrushao1994** [comment]
Thanks for reporting. We use the discussion forum (https://discuss.tvm.apache.org/) for general usage issues. Please open a thread in the forum. Thanks!
