### ISSUE TITLE
Addition of Unsupported Operators to Relay

### ISSUE THREAD

**Issue by jay-karan** [apache/tvm#7103]
Hi, I am new to this space. I am looking forward to contribute after a deep view.

1. How do I analyze the operators of a particular framework (say onnx, tensorflow) are being supported in Relay? Is there any helper function to list?

2. How do I add a unsupported operator in Relay? Any code example showcasing addition of new operators is highly appreciated.

Tried [this](https://tvm.apache.org/docs/dev/relay_add_op.html)

**Comment by zhiics** [comment]
Thanks for your interests in TVM. Please create a thread at the discuss forum (https://discuss.tvm.apache.org/) and ask above questions there since they are not issues. Thanks.
