### ISSUE TITLE
Segmentation fault with ACL integration on onnx inception v1

### ISSUE THREAD

**Issue by dlexplorer** [apache/tvm#7104]
The [ONNX inception v1 ](https://github.com/onnx/models/tree/master/vision/classification/inception_and_googlenet/inception_v1) been compiled with ACL integration crashes on the Android
The crash happens during the call of "default" packed func form module:
```
DLContext ctx{kDLCPU, 0};
tvm::runtime::Module mod_factory = tvm::runtime::Module::LoadFromFile(input_model);
// is crashed during execution of this func:
tvm::runtime::Module gmod = mod_factory.GetFunction("default")(ctx);
```

The same network been compiled through llvm works fine

I tried also [onnx mobilenet v2](https://github.com/onnx/models/tree/master/vision/classification/mobilenet/model) and it works fine either through pure llvm approach or through ACL integration.

**Comment by zhiics** [comment]
@mbaret @manupa-arm

**Comment by Leo-arm** [comment]
@d-smirnov

**Comment by d-smirnov** [comment]
Could you double-check that you have compiled the model properly, and it runs OK without ACL runtime, please?

**Comment by tqchen** [comment]
Let us move the discussion to https://discuss.tvm.apache.org/ once we confirmed the problem that is actionable, we can move back to issues

**Comment by dlexplorer** [comment]
I double checked it and still confirm that loading inception v1 been compiled with ACL crashes on device and the version been compiled with pure llvm approach works well

this is how I compiled network
```
import argparse
import sys
import onnx
import tvm
from tvm import relay
from tvm.contrib import ndk

parser = argparse.ArgumentParser(description=
    "Converts and compiles ONNX model")
required = parser.add_argument_group('required arguments')
required.add_argument('-m', '--input_model', required=True, type=str, help="path to ONNX model")
args = parser.parse_args()

onnx_model = onnx.load(args.input_model)
mod, params = relay.frontend.from_onnx(onnx_model)

target = "llvm -model=snapdragon835 -mtriple=arm-linux-android -mattr=+neon"
target_host = "llvm -mtriple=aarch64-linux-android-g++"

with tvm.transform.PassContext(opt_level=3):
    lib = relay.build(mod, target=target, target_host=target_host, params=params)

print(args.input_model + ".so")
lib.export_library(args.input_model + ".so", ndk.create_shared)
~
```

**Comment by u99127** [comment]
What does the code for the version that "works" with native llvm look like ? Is the only difference the ACL partitioning ? Can I suggest trying out a tflite file or a model that is already known to work ? 

BTW we are currently making this work with ACL 20.11 but all our testing has been on GNU/Linux with AArch64 file systems so  it might make sense to try and reduce the differences as much as possible first. 

regards
Ramana
