### ISSUE TITLE
Potential bug for SearchSpace length 

### ISSUE THREAD

**Issue by roger-zhao** [apache/tvm#7155]
https://github.com/apache/tvm/blob/08a69d4f92742c8c526d6a7c2a5805d00f5dc725/python/tvm/autotvm/task/space.py#L839

here, when _length is None, then initiate it to current search space length, it's almost good most of times, however if user/developer get __len__ of search space when space is empty, then a unreasonable _length 1 will be produced( the result of empty list for np.prod is 1), so it's better for adding an extra condition such as " len(self.space_map.values()) != 0" . :)

**Comment by comaniac** [comment]
Thanks for the proposal. Could you send a PR?

**Comment by roger-zhao** [comment]
@comaniac No problem!

**Comment by junrushao1994** [comment]
Closed via #7175
