### ISSUE TITLE
Can we create a standalone executable?

### ISSUE THREAD

**Issue by monkbai** [apache/tvm#7171]
Can we somehow create a standalone executable like glow and nnfusion?

[https://github.com/pytorch/glow](https://github.com/pytorch/glow)
[https://github.com/microsoft/nnfusion](https://github.com/microsoft/nnfusion)

**Comment by comaniac** [comment]
Thanks for your interests in TVM. Please create a thread at the discuss forum (https://discuss.tvm.apache.org/) and ask above questions there since they are not issues. Thanks.
