### ISSUE TITLE
CPU core number setting

### ISSUE THREAD

**Issue by justingyym** [apache/tvm#7178]
At present, I use TVM CPU for model inference.When TVM infers, it is calculated on the first three CPUs.When I start the two instances, both of them operate on the first three CPUs. c++ :sched_setaffinity  doesn't work.

1、How to specify the number of CPU cores in TVM for calculation。
2、How to specify specific CPUs for calculation
Thanks

目前我使用TVM的CPU进行模型推理，在TVM推理时候，均在前3个CPU上进行计算，当我启两个实例的时候，两个实例也都在前三个CPU进行运算（尝试使用c++ :sched_setaffinity 函数设置进程的CPU粘性，但是无法对TVM中的模型推理部分起作用）
1、请问tvm中如何指定CPU核心数进行计算？
2、如何指定特定几个CPU核心进行计算？
谢谢

**Comment by junrushao1994** [comment]
Thanks for your interests in TVM. Please create a thread at the discuss forum (https://discuss.tvm.apache.org/) and ask general usability issues. Thanks!
