### ISSUE TITLE
[Auto Scheduler] Add custom build func support

### ISSUE THREAD

**Issue by leowang1225** [apache/tvm#7179]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :)

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

For bug reports, to help the developer act on the issues, please include a description of your environment, preferably a minimum script to reproduce the problem.

For feature proposals, list clear, small actionable items so we can track the progress of the change.

**Comment by junrushao1994** [comment]
Thanks for your interests in TVM. Please create a thread at the discuss forum (https://discuss.tvm.apache.org/) and ask general usability issues. Thanks!

BTW, I agree with a custom build func is a good feature to have, and your contribution is definitely more than welcome. To workaround your issue temporarily, you might be interested in hacking those lines: https://github.com/apache/tvm/blob/main/python/tvm/auto_scheduler/measure.py#L627-L630
