### ISSUE TITLE
unsupported operators from tensorflow model garden models

### ISSUE THREAD

**Issue by aaltonenzhang** [apache/tvm#7196]
I'm checking tensorflow models from tensorflow models garden at https://github.com/tensorflow/models/tree/master/community.
For community models, there are types and operators which tvm doesn't supported. Most of them are quantize related, and some are not. I really hope these operators could be supported officially and I can check if these models work well.
The details are listed below.

> 

model name | result
-- | --
inceptionv3_int8 | Op type not registered 'QuantizedConcatV2'
inceptionv4_int8 | Op type not registered 'QuantizedConcatV2'
mobilenetv1_int8 | The  following operators are not implemented: {'QuantizeV2', 'Dequantize',  'QuantizedAvgPool',  'QuantizedDepthwiseConv2DWithBiasAndReluAndRequantize',  'QuantizedConv2DWithBiasAndReluAndRequantize',  'QuantizedConv2DWithBiasAndRequantize'}
resnet101_int8 | The  following operators are not implemented: {'Dequantize',  'QuantizedConv2DWithBiasAndRequantize', 'QuantizeV2',  'QuantizedConv2DWithBiasAndReluAndRequantize', 'QuantizedMaxPool',  'QuantizedConv2DWithBiasSignedSumAndReluAndRequantize',  'QuantizedConv2DWithBiasSumAndReluAndRequantize'}
resnet50_int8 | The  following operators are not implemented: {'Dequantize', 'QuantizeV2',  'QuantizedConv2DWithBiasSumAndReluAndRequantize',  'QuantizedConv2DWithBiasAndReluAndRequantize',  'QuantizedConv2DWithBiasSignedSumAndReluAndRequantize',  'QuantizedConv2DWithBiasAndRequantize'}
resnet50_v1_5_bfloat16 | data type 'bfloat16' not understood
resnet50v1_5_int8 | The  following operators are not implemented:  {'QuantizedConv2DWithBiasAndReluAndRequantize',  'QuantizedConv2DWithBiasSumAndReluAndRequantize', 'QuantizedMaxPool',  'QuantizedConv2DWithBiasSignedSumAndReluAndRequantize', 'Dequantize',  'QuantizeV2', 'QuantizedConv2DWithBiasAndRequantize'}
ssdmobilenet_fp32 | The following operators are not implemented: {'CombinedNonMaxSuppression'}
ssdmobilenet_int8 | The  following operators are not implemented:  {'QuantizedDepthwiseConv2DWithBiasAndReluAndRequantize',  'CombinedNonMaxSuppression', 'Dequantize',  'QuantizedConv2DWithBiasAndRequantize', 'QuantizeV2',  'QuantizedConv2DWithBiasAndReluAndRequantize'}
ssd_resnet34_fp32_1200x1200 | The following operators are not implemented: {'CombinedNonMaxSuppression'}
ssd_resnet34_int8_bs1 | The  following operators are not implemented:  {'QuantizedConv2DWithBiasSignedSumAndReluAndRequantize',  'QuantizedConv2DWithBiasAndRequantize', 'QuantizedMaxPool',  'QuantizeV2', 'QuantizedConv2DWithBiasAndReluAndRequantize',  'QuantizedConv2DWithBiasSumAndReluAndRequantize', 'Dequantize'}
ssd_resnet34_int8_1200x1200 | The  following operators are not implemented: {'QuantizeV2',  'QuantizedConv2DWithBiasSignedSumAndReluAndRequantize',  'QuantizedConv2DWithBiasSumAndReluAndRequantize',  'CombinedNonMaxSuppression',  'QuantizedConv2DWithBiasAndReluAndRequantize',  'QuantizedConv2DWithBiasAndRequantize', 'Dequantize',  'QuantizedMaxPool'}
wide_deep_fp32 | RuntimeError: Unsupported dtype: int64
wide_deep_int8 | The  following operators are not implemented: {'QuantizedMatMulWithBias',  'Requantize', 'QuantizedMatMulWithBiasAndReluAndRequantize',  'Dequantize', 'QuantizeV2'}

**Comment by insop** [comment]
@aaltonenzhang 
Nit, it seems the embedded url (https://github.com/tensorflow/models/tree/master/community) in the above post is not the actual url shown, i.e. if you click the link you will go to different site. And I see the similar in https://github.com/apache/tvm/issues/7198

**Comment by aaltonenzhang** [comment]
@insop  It seems that there are something wrong when you click the url, but you can copy and paste it to your browser. And for the issue #7198, it's also created by me, but they are different problems. Please help me to check them, thank you!

**Comment by aaltonenzhang** [comment]
@insop reedited the url link for both of the two issues.
