### ISSUE TITLE
mesg: ttyname failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by rhzhang1995** [apache/tvm#7204]
When I was using Alveo U50 to configure TVM, I entered command “./tvm/docker/build.sh demo_vitis_ai bash”, and finally 2“mesg: ttyname failed: Inappropriate ioctl for device” appeared. Is TVM incompatible with Alveo U50？Thank you！

**Comment by junrushao1994** [comment]
It is not an error actually. In our CI pipeline, we can see this message on the beginning of every stage...

**Comment by abuvaneswari** [comment]
I am considering buying Alveo U50 and following the VTA workflow. Can someone let me know if Alveo U50 is compatible with VTA? It is one of the supported PYNQ boards as you can see from the [PYNQ](http://www.pynq.io/board.html) site.

@rhzhang1995 , were you successful with your VTA workflow on Alveo U50?
