### ISSUE TITLE
[BUG] Get wrong measure time in graph debug runtime

### ISSUE THREAD

**Issue by jcf94** [apache/tvm#7207]
This bug was introduced in #6964 .
Currently, use graph debug runtime will get wrong time result.

Cause:
https://github.com/apache/tvm/blob/d05275298d9e630af6d8ff958753fd010759935c/src/runtime/graph/debug/graph_runtime_debug.cc#L150-L159
This function returns a time with second, but is expected to return microsecond.

cc @areusch

**Comment by junrushao1994** [comment]
I suppose the bug has been fixed by #7197, is that correct?

**Comment by areusch** [comment]
no, it was tangential to that PR, so this issue is open to track a follow-on to fix
