### ISSUE TITLE
build with MKL error:  ‘CBLAS_OFFSET’ does not name a type

### ISSUE THREAD

**Issue by TriLoo** [apache/tvm#7223]
I set `USE_MKL` to my mkl installed path in the `config.cmake` , however, I got below errors:
```
error: ‘CBLAS_OFFSET’ does not name a type
...
error: ‘MKLStringToOffset’ was not declared in this scope
...
error: ‘cblas_gemm_s8u8s32’ was not declared in this scope
```

I verified the `cmake/modules/contrib/BLAS.cmake` and the correct `mkl_rt` library was found.  The `mkl_cblas.h` exactly include the definitions of `CBLAS_OFFSET, cblas_gemm_s8u8s32`, but don't know why these errors happened.

g++ version -> 7.3.1
cmake version -> 3.16.6
thanks

**Comment by tqchen** [comment]
Thanks @TriLoo We checked locally but was not able to reproduce the error. If you still face the problem, please open a followup troubleshooting thread on https://discuss.tvm.apache.org/ Please also try to build from a clean clone

**Comment by jlquinn** [comment]
I ran into this trying to build within conda.  In my case, I was missing the mkl-include package, which wasn't listed in the conda dependencies.  Posting here in case someone else lands here searching for this issue.
