### ISSUE TITLE
Unable to launch tuning jobs on google colab

### ISSUE THREAD

**Issue by dandingol03** [apache/tvm#7238]
Hi
    I run the ` Auto-tuning a Convolutional Network for NVIDIA GPU` tutorial on google colab, and i met an error as below:

[Task 1/16] Current/Best: 0.00/ 0.00 GFLOPS | Progress: (0/2000) | 0.00 sProcess Process-6: Traceback (most recent call last): File “/usr/lib/python3.6/multiprocessing/process.py”, line 258, in _bootstrap self.run() File “/usr/lib/python3.6/multiprocessing/process.py”, line 93, in run self._target(*self._args, **self._kwargs) File “/usr/local/lib/python3.6/dist-packages/tvm-0.8.dev423+g93d79bafc-py3.6-linux-x86_64.egg/tvm/rpc/tracker.py”, line 362, in _tracker_server handler.run() File “/usr/local/lib/python3.6/dist-packages/tvm-0.8.dev423+g93d79bafc-py3.6-linux-x86_64.egg/tvm/rpc/tracker.py”, line 357, in run self._ioloop.start() File “/usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py”, line 132, in start self.asyncio_loop.run_forever() File “/usr/lib/python3.6/asyncio/base_events.py”, line 425, in run_forever raise RuntimeError(‘This event loop is already running’) RuntimeError: This event loop is already running

  Thanks in advance~

**Comment by tqchen** [comment]
Thsnks @dandingol03 for bringing this up. This may have things to do with colab restrictions(that the env is already implemented via an event loop). A separate process might be necessary to start the rpc server. Please open a new thread on https://discuss.tvm.apache.org/ for followup discussions.
