### ISSUE TITLE
[TEST] Skip TensorCore TOPI test when it is not available

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7277]
https://github.com/apache/tvm/pull/7146 Introduces a test on tensorcore for batchmatmul

Because tensorcore is only optionally supported in the topi testing stage, it would be great to skip it when it is not available.

**Comment by tqchen** [comment]
cc @jwfromm @jcf94 @Meteorix

**Comment by leandron** [comment]
(Posting here as I think it is related)

When running TVM tests on a CPU only machine, I'm getting an error when running `/test_topi_batch_matmul_tensorcore.py:test_batch_matmul`:
https://github.com/apache/tvm/blob/89e3688137b9d8dd0e431cbdadb84d42dae9eee3/tests/python/topi/python/test_topi_batch_matmul_tensorcore.py#L66-L71


The error I see is:
> Check failed: allow_missing == false: Device API gpu is not enabled.

The test is marker as `uses_gpu`.

I wonder whether we should move it to either `requires_gpu` or even `requires_tensorcore`?

**Comment by tqchen** [comment]
I think `requires_tensorcore` is the right macro cc @tkonolige

**Comment by tkonolige** [comment]
Yes, it should be `requires_tensorcore`.
