### ISSUE TITLE
LSTM&GRU support for uTVM

### ISSUE THREAD

**Issue by peter197321** [apache/tvm#7283]
Hello guys,

I'm curious if the uTVM can support audio models and especially LSTM or GRU operations in there for ARM-based bare-metal devices such CortexM7 alike? 
Is there any example for that ...

BR/Peter

**Comment by leandron** [comment]
Hi @peter197321 - it might worth raising this discussion on https://discuss.tvm.apache.org/ rather than as an issue.

**Comment by peter197321** [comment]
OK @leandron I will push it there :)
