### ISSUE TITLE
[BUG] tvmc runner: print_top sorts output causing sorted output to be stored.

### ISSUE THREAD

**Issue by SebastianBoblestETAS** [apache/tvm#7322]
The options print_top and outputs are currently incompatible, get_top_results should work on a copy of outputs.
Otherwise sorted outputs are stored in .npz

https://github.com/apache/tvm/blob/8524b28078928caf5c8ca82442ad0eab81dce838/python/tvm/driver/tvmc/runner.py#L127

**Comment by comaniac** [comment]
Thanks for pointing out. Would you send a PR to fix it?
Also cc @leandron
