### ISSUE TITLE
[Bug][Parser] Parser/tokenizer doesn't handle inf float

### ISSUE THREAD

**Issue by altanh** [apache/tvm#7339]
Running `AnnotateSpans` pass on a module which uses `inf` float literal (such as in the case of `clip(x, 0, np.inf)`) causes an error.

**Comment by jroesch** [comment]
I would be happy to mentor anyone who wants to pick this one up.

**Comment by masahi** [comment]
I'm interested in taking this up, @altanh can you post a repro script?

**Comment by masahi** [comment]
Printing `mod` shows that `inff` is a thing:

```
def @main(%x: Tensor[(3, 4), float32]) {
  clip(%x, a_min=0.5f, a_max=inff)
}
```
Do we want to special-case `inf` in the printer as well?

**Comment by altanh** [comment]
Not sure if Python should be the source of truth but `float("inf")` returns `inf` whereas `float("inff")` fails. Also numpy seems to have similar behavior (but they somehow avoid erroring by ignoring the rest of the input...):
```
>>> np.fromstring("inff, 1.0", dtype=float, sep=",")
array([inf])
```
