### ISSUE TITLE
test_frontends.py::test_load_model__pth munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by apivovarov** [apache/tvm#7471]
Quite often I see the following failure in CI builds
```
test_frontends.py::test_load_model__pth munmap_chunk(): invalid pointer
Fatal Python error: Aborted
```

Failed CI builds:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/579/pipeline

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7465/4/pipeline

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7465/3/pipeline

Related PRs: https://github.com/apache/tvm/pull/7366

@CircleSpin

**Comment by leandron** [comment]
I think this is being discussed on #7455 (maybe needs a better title)
