### ISSUE TITLE
[Relay][topi/nn] Ways to get layout of each operator.

### ISSUE THREAD

**Issue by xhuohai** [apache/tvm#7505]
I'm using TVM as front end, and need to know the layout of each operator in implement. Operators like conv2d have "data_layout", "kernel_layout" in it's attrs field, which I could use directly, but many operators like tvm.relay.nn.batch_norm/tvm.relay.nn.relu/tvm.topi.add etc. don't have the layout field in attrs. Is there a way to quickly get the layout for those operators?
Thanks very much.

**Comment by tqchen** [comment]
Thanks @xhuohai . right now there is no easy way to do so. We do have convert layout that transforms layout of an entire network. We generally use https://discuss.tvm.apache.org/ for this kind of topics, please open a new thread there for followup discussions :)
