### ISSUE TITLE
Error of compilation on main branch

### ISSUE THREAD

**Issue by haruband** [apache/tvm#7511]
I have encountered following compilation errors on the main branch. It's okay on the v0.7 branch.

> /workspace/include/tvm/support/logging.h:129:70: note: suggested alternative: 'clearerr'
       << ICHECK_INDENT << "Check failed: " << #x " " #op " " #y << *(_check_err.str) << ": "
                                                                      ^
/workspace/include/tvm/support/logging.h:140:25: note: in expansion of macro 'ICHECK_BINARY_OP'
 #define ICHECK_EQ(x, y) ICHECK_BINARY_OP(_EQ, ==, x, y)
                         ^~~~~~~~~~~~~~~~
/workspace/src/auto_scheduler/compute_dag.cc:863:5: note: in expansion of macro 'ICHECK_EQ'
     ICHECK_EQ(ori_iter_names.size(), 1);
     ^~~~~~~~~
/workspace/src/auto_scheduler/compute_dag.cc: In member function 'tvm::runtime::String tvm::auto_scheduler::ComputeDAG::PrintDAG(bool) const':
/workspace/include/tvm/support/logging.h:126:13: error: 'LogCheckError' is not a member of 'dmlc'
   if (dmlc::LogCheckError _check_err = dmlc::LogCheck##name(x, y)) \

So, i found the include/tvm/support/logging.h on the main branch is different with the v0.7 branch, and i couldn't find the LogCheckError in the tvm source directory.

Am i missing something?

**Comment by altanh** [comment]
Can you try updating your tvm git submodules?

**Comment by haruband** [comment]
It's working. Thank you very much!
