### ISSUE TITLE
[Profiling] Unify profiling into standardized formats/APIs

### ISSUE THREAD

**Issue by altanh** [apache/tvm#7523]
cc @tkonolige 

As we further improve our TVM profiling tools (such as #7472, #7495, #7500, etc.), it will be good to agree on some kind of standard format/approach to exposing the profiling data. The type and structure of profiled data may be quite different, so ideally the format should be flexible (perhaps JSON-style?).

This issue is intended for tracking these discussions related to profiling APIs, so we can work towards standardization.

**Comment by altanh** [comment]
cc @jroesch

**Comment by tkonolige** [comment]
This might be a good discussion to have on discuss.

**Comment by masahi** [comment]
Let's continue on discuss if this is still relevant.
