### ISSUE TITLE
DLTensor from float32 to float16 in cpp deploy

### ISSUE THREAD

**Issue by hzwangjl** [apache/tvm#7529]
I have relay.build_module.build the model to fp16, but during cpp deploy, need to convert image data to fp16. I tried the following method, but it didn't work. Is there any efficient method in TVM？ Thank you~
```
DLTensor *fp32_tensor;
DLTensor *fp16_tensor;
TVMArrayAlloc(shape, ndim, KDLFloat, 32, lanes, KDLCPU, 0,  &fp32_tensor);
TVMArrayAlloc(shape, ndim, KDLFloat, 16, lanes, KDLGPU, 0,  &fp32_tensor);
memcpy(fp32_tensor->data, data_cpu, size);
TVMArrayCopyFromTo(fp32_tensor, fp16_tensor);
```

**Comment by tqchen** [comment]
@hzwangjl an explicit converstion method would be necessary.  Normally there are intrinsics on the device that are able to do so. The community uses https://discuss.tvm.apache.org/ for this type of questions, let us follow up there

**Comment by jinfagang** [comment]
@jellywong88 Did u able to do it?
