### ISSUE TITLE
uTVM for Ethos-U

### ISSUE THREAD

**Issue by peter197321** [apache/tvm#7547]
Hello all,

I have a question and want to understand if TVM or its micro TVM support or is under consideration to have support for Ethos-U class devices?
Just for your reference: https://tvm.apache.org/2020/06/04/tinyml-how-tvm-is-taming-tiny

Thank you.

**Comment by comaniac** [comment]
Hi thanks for your interest. For feature discussions please post it to the discuss forum: https://discuss.tvm.apache.org/
