### ISSUE TITLE
Suggest to R CallFunc

### ISSUE THREAD

**Issue by sunjiweiswift** [apache/tvm#7560]
https://github.com/apache/tvm/blob/a1d43c15ac6382831370c6de141bf80888761e70/src/relay/backend/build_module.cc#L106-L115

If there are special requirements for returning, such as returning an Int.
template <typename... Args>
  int CallFunc(const std::string& name, Args... args) {
    auto pf = mod.GetFunction(name, false);
    pf(std::forward<Args>(args)...);
    return;
  }
CallFunc<int>(). It will only match R CallFunc.
solution:  https://github.com/sunjiweiswift/BeautifulCode/tree/master/Template

**Comment by tqchen** [comment]
Thanks @sunjiweiswift do you want to open a PR for this? Given this is not a bug and a code improvement instead I will mark it as closed for now. Thank you for your suggestion
