### ISSUE TITLE
CreateAtomicRMW error C2660 during Windows 10 build.

### ISSUE THREAD

**Issue by Luuk-** [apache/tvm#7576]
When trying to build TVM on Windows (with VS 15 2017 and from-source-built LLVM ~11.0.0~ 13.0.0), I encountered some errors in `TVM\tvm\src\target\llvm\codegen_amdgpu.cc` and `...\codegen_nvptx.cc`. 
Namely, I got `error C2660: 'llvm::IRBuilderBase::CreateAtomicRMW': function does not take 4 arguments` (twice in each file). When examing `CreateAtomicRMW()`, I notice that it's supposed to be passed a `MaybeAlign` parameter as well, which isn't in place here. When I add `llvm::MaybeAlign::MaybeAlign()` as a parameter to the in total 4 `CreateAtomicRMW()` calls, it compiles and seems to work.

My question now is, is this a TVM bug, or is it an issue on my side (perhaps a mismatch between TVM and LLVM version, or perhaps using a wrong compiler or not having support for the newest C++ version)?

If it's a bug, I propose to add `llvm::MaybeAlign::MaybeAlign()` (which defaults to undefined) to these 4 calls.

**Comment by masahi** [comment]
Yes please send a pr to fix build with llvm 11.

**Comment by tqchen** [comment]
Thanks @Luuk- , fixed by #7617
