### ISSUE TITLE
[CI][FLAKY] Qemu pipeline timeout

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7590]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/645/pipeline/44

**Comment by tqchen** [comment]
cc @areusch

**Comment by areusch** [comment]
https://ci.tlcpack.ai/job/tvm/job/PR-7653/8/console on `node.aladdin.cuda0` 

looks like it is stuck in xargs rm -f

in both cases:
`+ echo 'INFO: NODE_NAME=node.aladdin.cudabuild EXECUTOR_NUMBER=0'`

still waiting for more data, but potentially node.aladdin.cudabuild gets stuck finding *.pyc to remove.

**Comment by areusch** [comment]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7438/12/pipeline/
