### ISSUE TITLE
[arm cpu][auto scheduler] Auto scheduler @ arm cpu can not reproduce paper's performance

### ISSUE THREAD

**Issue by FrozenGene** [apache/tvm#7625]
currently, in the upstream version of auto scheduler on arm cpu can not reproduce [OSDI paper](https://www.usenix.org/conference/osdi20/presentation/zheng)'s performance. One issue we find is we call wrong compute for arm cpu (https://github.com/apache/tvm/blob/main/python/tvm/relay/op/strategy/arm_cpu.py#L156) and we don't enable winograd for arm cpu too. Open this issue to tracker this.

@jcf94

**Comment by jcf94** [comment]
#7635 Add a fix on arm strategy to choose the right `nwhc` conv2d implementation with layout rewrite support.
