### ISSUE TITLE
quantized pytorch model convert bug in upsample_nearest2d

### ISSUE THREAD

**Issue by eleflea** [apache/tvm#7645]
When I convert a QNN with `aten::upsample_nearest2d` op, I encountered a error with:

  _File "/home/eleflea/.local/lib/python3.7/site-packages/tvm-0.8.dev704+g3a0e3a5bb-py3.7-linux-x86_64.egg/tvm/relay/frontend/pytorch.py", line 1749, in upsample
    assert isinstance(inputs[-2], float)_

After some research I found that for some quantized op, tvm add qparams manually to help convert. But for `aten::upsample_nearest2d`, it seems to be missing.

So I add `aten::upsample_nearest2d` just above `aten::upsample_bilinear2d` at [here](https://github.com/apache/tvm/blob/e9e014b4685ea05885cb321f1e42d2d3f71a0407/python/tvm/relay/frontend/qnn_torch.py#L356). And it works.

**Comment by masahi** [comment]
Yes that sounds correct, can you send a PR?

**Comment by masahi** [comment]
Actually, for nearest we don't need to wrap upsample with dequantize/quantize, we can use the same compute as fp32, since resize nearest just copies values.
