### ISSUE TITLE
Amazon  triple containing

### ISSUE THREAD

**Issue by liushuangddu** [apache/tvm#7662]
Hi, I'm very glad to find you on this website. I'm a developer from China. Now I does working on Bluetooth Sigmesh . I plan to access the Amazon echo for my device , and then I recgnized before I need the BLE Mesh Credentials- A triple containing the OOB Type (Static only for now), OOB Data (pub key), and Device UUID.
But I has clicked entire website still connot find out the documentation for how to get my triple containing.
May I get some help form you , very appreciate.

**Comment by comaniac** [comment]
I'm not sure if this question is related to TVM. For issue discussions and question answering, please create a post at https://discuss.tvm.apache.org/. Also, please be more specific about what's your task and your current environment.
