### ISSUE TITLE
Build error: TypeError: Map is not registered via TVM_REGISTER_NODE_TYPE

### ISSUE THREAD

**Issue by majercakdavid** [apache/tvm#7697]
Hello, while building the ONNX model (originally Pytorch) in TVM I got the following error: 
`TypeError: Map is not registered via TVM_REGISTER_NODE_TYPE`

I have quite hard time understanding the reason because as far as I know there is no any "Map" node you can use in the PyTorch/ONNX, also if I use run `.graph` on the ONNX model the output does not contain any definition of the "Map"

**Comment by comaniac** [comment]
Hi this usually indicates that your TVM library is not up-to-date. You may check if you `git submodule update --resursive` and rebuild TVM after pulling the last commit.

In addition, for the question like this, please post it to the discuss forum: https://discuss.tvm.apache.org/

**Comment by majercakdavid** [comment]
@comaniac I have tried to update the local repository, build it through conda environment, create a new python environment (venv) and run setup.py install from the build folder but Im still getting the same error
