### ISSUE TITLE
[BUG] Compile failed due to redundant cast.

### ISSUE THREAD

**Issue by changkaiyan** [apache/tvm#7713]
When I compile tvm source code, an error occurs. I try to fix it by removing a reduntant 'MaybeAlign'.
In tvm/src/target/llvm/codegen_nvptx.cc and tvm/src/target/llvm/codegen_amdgpu.cc, please change llvm::MaybeAlign::MaybeAlign() to llvm::MaybeAlign()
---------------------------------
/mnt/d/tvm/src/target/llvm/codegen_nvptx.cc: In member function ‘virtual llvm::Value* tvm::codegen::CodeGenNVPTX::CreateIntrinsic(const tvm::tir::CallNode*)’:
/mnt/d/tvm/src/target/llvm/codegen_nvptx.cc:243:69: error: cannot call constructor ‘llvm::MaybeAlign::MaybeAlign’ directly [-fpermissive]
  243 |                                        llvm::MaybeAlign::MaybeAlign(),
      |                                                                     ^
/mnt/d/tvm/src/target/llvm/codegen_nvptx.cc:243:69: note: for a function-style cast, remove the redundant ‘::MaybeAlign ’
--------------------------------

**Comment by masahi** [comment]
What LLVM version are you using? The recent PR introduced this change https://github.com/apache/tvm/pull/7617

**Comment by masahi** [comment]
Fixed by https://github.com/apache/tvm/pull/7783
