### ISSUE TITLE
Minor bug in storage_access.cc

### ISSUE THREAD

**Issue by pratikfegade** [apache/tvm#7724]
Hi,

I have been playing around with TVM and it seems that the barrier insertion pass (implemented in `src/tir/storage_access.cc` and `src/tir/thread_storage_sync.cc`) does not handle the else case of an `IfThenElse` node correctly. Specifically, I think the body of the else case, when present, is not being visited in the code [here](https://github.com/apache/tvm/blob/main/src/tir/transforms/storage_access.cc#L177).

**Comment by tqchen** [comment]
thanks @pratikfegade, great catch can you craft a regression test case and send a patch ?

**Comment by tqchen** [comment]
cc @masahi it would be great if you can help follow up
