### ISSUE TITLE
do we have any check point to contine unfinished tuning jobs?

### ISSUE THREAD

**Issue by xiebaiyuan** [apache/tvm#7725]
do we have any check point to contine unfinished  tuning jobs?

sometimes i have to stop my jobs , 
but i did not find a way to contine my job,

i have to restart from 0

thanks

**Comment by tqchen** [comment]
Thanks @xiebaiyuan please open a new thread on https://discuss.tvm.apache.org/ We generally use the discuss forum for related questions
