### ISSUE TITLE
Use WASM model in browser

### ISSUE THREAD

**Issue by majercakdavid** [apache/tvm#7727]
Hello,
please is it possible and if how to use the WASM models in the browser on the client side? The problem is that the wasi runtime requires "fs" module to work, which is unavailable on the client-side.

**Comment by tqchen** [comment]
helloe @majercakdavid , yes it is possible via emscripten polyfill version of wasi. Please see https://github.com/apache/tvm/tree/main/web#run-wasm-remotely-through-websocket-rpc However things could be a bit outdated. We use discourse forum https://discuss.tvm.apache.org/ for this type of topic. Please open a follow thread there
