### ISSUE TITLE
CodeGenOpenCL : expect calling_conv equals CallingConv::kDeviceKernelLaunch

### ISSUE THREAD

**Issue by ctlinglingliu** [apache/tvm#7741]
when I Compile PyTorch Models  demo in https://tvm.apache.org/docs/tutorials/frontend/from_pytorch.html#sphx-glr-tutorials-frontend-from-pytorch-py
i set the configure below
target = "opencl"
target_host = "opencl"
ctx = tvm.gpu(0)
there occurs the error below:
An internal invariant violated during the execution of TVM
Check failed: calling_conv == CallingConv::kDeviceKernelLaunch ==false: CodeGenOpenCL:expect calling_conv equals CallingConv::kDeviceKernelLaunch

**Comment by tqchen** [comment]
Thanks @ctlinglingliu . please open a new thread on https://discuss.tvm.apache.org/ for followup Qs, you need to set target_host to be llvm
