### ISSUE TITLE
The asnumpy() function costs most of the time during infer, how to use numpy to compute directly ranther than use tvm NDarray()?

### ISSUE THREAD

**Issue by wxyhv** [apache/tvm#7762]
After I complete tune module, I build the tvm module,set_input() and run, then I use GraphModule.get_out() funtion to get TVM compute result,  the result is a class named "tvm.runtime.ndarray.NDArray". 
However, I need 'numpy.ndarray' to do the following operations,such as get data by index,numpy.expand_dims(),and so on. So I use the asnumpy() function to convert the data type, but the asnumpy() funtion costs a lot of time even surpass the TVM module run time! This make the whole inference time much big than "no TVM tuned DeepLearning model"
The following is part of my inference code, which indicate how the asnumpy enlarge the whole inference time!
`      

        # set input_data
        self.tuned_module.set_input("Input", data)
        # execute
        self.tuned_module.run()#12ms
        # get outputs
        result = self.tuned_module.get_output(0)
        print(type(result)) # <class 'tvm.runtime.ndarray.NDArray'>

        t1 = time.time()
        result = result.asnumpy()  # 
        t2 = time.time()
        print("asnumpy_time:", t2-t1) #255ms
        print(type(result)) # <class 'numpy.ndarray'>

        result = result[:, 0, :]
        result = numpy.expand_dims(result, 1)
`

If I don't use asnumpy,the error is:
`

    result = result[:, 0, :]

TypeError: 'NDArray' object is not subscriptable

`

Consequently, my questions are:
1. Why the TVM use "tvm.runtime.ndarray.NDArray" to compute data, rather than numpy library? The numpy library have many useful funtion to process data which can't find in "tvm.runtime.ndarray.NDArray".

2. How to use numpy to compute directly ranther than  tvm NDarray()?  This will save much time during the whole DeepLearning inference

3. How to get the TVM run (or compute) result in the memery address, to prevent  convert & copy result to NDarray again(the input data already convertd to NDarray by set_input())? 

Looking forward to your reply! @tqchen 
Thank you very much!

**Comment by VoVAllen** [comment]
You can try dlpack in tvm

**Comment by tqchen** [comment]
Thanks @wxyhv , can you open a new thread on https://discuss.tvm.apache.org/ about the question. The time of asnumpy could also due to the fact that previous computations are asynchronous, so the cost comes from the actual compute instead of the copy
