### ISSUE TITLE
How can I run TVM over RPC on Xilinx ultra96v2? 

### ISSUE THREAD

**Issue by TiejunChina** [apache/tvm#7798]
I tried to do this with this reference https://tvm.apache.org/docs/tutorials/get_started/cross_compilation_and_rpc.html, but failed. Not sure if currently TVM supports Xilinx ultra96v2.

**Comment by tqchen** [comment]
Thanks for asking the question, the community uses for trouble shooting , please bring a new discussion topic on https://discuss.tvm.apache.org/, where more people will be able to watch and answer the questions.
