### ISSUE TITLE
Could not use GraphExecutor to load optimized models tuned before GraphRuntime renamed into GraphExecutor

### ISSUE THREAD

**Issue by JC1DA** [apache/tvm#7822]
I have a .so module tuned a month ago. When I tried to run that model with the latest tvm. 
I noticed that tvm.contrib.graph_runtime was no longer supported. I have to use tvm.contrib.graph_executor instead.
(GraphRuntime was renamed as GraphExecutor from this commit https://github.com/apache/tvm/commit/9b43a646fc70f3d4a2d033c73380e0bae75f4586 )

But when I loaded the module using graph_executor, I got this error
#########################
tvm.runtime.load_module(model_path)

TVMError: Binary was created using GraphRuntimeFactory but a loader of that name is not registered. Available loaders are GraphExecutorFactory, VMExecutable, metadata. Perhaps you need to recompile with this runtime enabled.
#########################

Can we add the support to load old modules using GraphExecutor?
Thanks in advance.

**Comment by tqchen** [comment]
cc @areusch , we should perhaps add the loader registration of GraphRuntimeFactory back as an alias

**Comment by tqchen** [comment]
closed by https://github.com/apache/tvm/pull/7868
