### ISSUE TITLE
Undefined symbols when running task_cpp_unittest.sh on MacOS

### ISSUE THREAD

**Issue by CleverFat** [apache/tvm#7856]
When I added logging.cc to apps/bundle_deploy/bundle.cc, this error disappeared. 

Details as follow:
Undefined symbols for architecture x86_64:
  "tvm::runtime::detail::LogFatal::GetEntry()", referenced from:
      tvm::runtime::TVMPODValue_::operator tvm::runtime::Module() const in bundle-9339c6.o
      tvm::runtime::ArgTypeCode2Str(int) in bundle-9339c6.o
      tvm::runtime::detail::LogFatal::LogFatal(char const*, int) in bundle-9339c6.o
      tvm::runtime::GetCustomTypeName(unsigned char) in runtime-f5e2d1.o
      tvm::runtime::TVMRetValue::operator std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >() const in runtime-f5e2d1.o
      tvm::runtime::GetCustomTypeCode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in runtime-f5e2d1.o
      tvm::runtime::TVMPODValue_::operator int() const in runtime-f5e2d1.o
      ...
  "tvm::runtime::Backtrace()", referenced from:
      tvm::runtime::detail::LogFatal::Entry::Finalize() in bundle-9339c6.o
      tvm::runtime::detail::LogFatal::Entry::Finalize() in runtime-f5e2d1.o
      std::__1::__function::__func<TVMFuncCreateFromCFunc::$_1, std::__1::allocator<TVMFuncCreateFromCFunc::$_1>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) in runtime-f5e2d1.o
      std::__1::__function::__func<TVMFuncCreateFromCFunc::$_2, std::__1::allocator<TVMFuncCreateFromCFunc::$_2>, void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::operator()(tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&) in runtime-f5e2d1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tqchen** [comment]
Thanks @CleverFat for reporting the problem, do you mind open a new PR to add the include of logging.cc? Thank you!

cc @tkonolige @junrushao1994

**Comment by tqchen** [comment]
gentle ping
