### ISSUE TITLE
pynq z1 fails to make the VTA, caused by the libbacktrace

### ISSUE THREAD

**Issue by ChenNie99** [apache/tvm#7857]
Here is the error:

make[3]: Warning: File '../3rdparty/libbacktrace/posix.c' has modification time 9023918 s in the future
[  0%] Creating directories for 'project_libbacktrace'
[  8%] No download step for 'project_libbacktrace'
[  8%] No update step for 'project_libbacktrace'
[  8%] No checkout step for 'project_libbacktrace'
[  8%] No patch step for 'project_libbacktrace'
[  8%] Performing configure step for 'project_libbacktrace'
/bin/sh: 1: /home/xilinx/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: Permission denied
CMakeFiles/project_libbacktrace.dir/build.make:107: recipe for target 'libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure' failed
make[3]: *** [libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure] Error 126
CMakeFiles/Makefile2:319: recipe for target 'CMakeFiles/project_libbacktrace.dir/all' failed
make[2]: *** [CMakeFiles/project_libbacktrace.dir/all] Error 2
CMakeFiles/Makefile2:111: recipe for target 'CMakeFiles/runtime.dir/rule' failed
make[1]: *** [CMakeFiles/runtime.dir/rule] Error 2
Makefile:175: recipe for target 'runtime' failed
make: *** [runtime] Error 2

I'm not sure why it happens, but the error info indicates the 'libbacktrace' may be the problem.

**Comment by shihangfu** [comment]
Have you solved this problem？
I have a similar question.


[  0%] Creating directories for 'project_libbacktrace'
[  0%] No download step for 'project_libbacktrace'
[  0%] No checkout step for 'project_libbacktrace'
[  0%] No update step for 'project_libbacktrace'
[  1%] No patch step for 'project_libbacktrace'
[  1%] Performing configure step for 'project_libbacktrace'
/bin/sh: 1: /workspace/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: not found
CMakeFiles/project_libbacktrace.dir/build.make:107: recipe for target 'libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure' failed
make[2]: *** [libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure] Error 127
CMakeFiles/Makefile2:596: recipe for target 'CMakeFiles/project_libbacktrace.dir/all' failed
make[1]: *** [CMakeFiles/project_libbacktrace.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ChenNie99** [comment]
Yeah, I have already deployed the VTA on my pynq-z1. As for the problem, I'm not sure but you can try this command:

chmod +x /path/to/tvm/3rdparty/libbacktrace/configure

This may work, and I guess it's because the 'configure' file are not accessed due to its premission setting.

**Comment by tqchen** [comment]
Thanks for asking the question, the community uses for trouble shooting , please bring a new discussion topic on https://discuss.tvm.apache.org/, where more people will be able to watch and answer the questions.

You can disable libbacktrace through the cmake command

**Comment by chaoranli20** [comment]
> Have you solved this problem？ I have a similar question.
> 
> [ 0%] Creating directories for 'project_libbacktrace' [ 0%] No download step for 'project_libbacktrace' [ 0%] No checkout step for 'project_libbacktrace' [ 0%] No update step for 'project_libbacktrace' [ 1%] No patch step for 'project_libbacktrace' [ 1%] Performing configure step for 'project_libbacktrace' /bin/sh: 1: /workspace/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: not found CMakeFiles/project_libbacktrace.dir/build.make:107: recipe for target 'libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure' failed make[2]: *** [libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure] Error 127 CMakeFiles/Makefile2:596: recipe for target 'CMakeFiles/project_libbacktrace.dir/all' failed make[1]: *** [CMakeFiles/project_libbacktrace.dir/all] Error 2 Makefile:129: recipe for target 'all' failed make: *** [all] Error 2

Have you solved this problem？ I have a similar question and can not be solved by changing the premission setting.

**Comment by wolfworld6** [comment]
> Have you solved this problem？

Have you solved this problem？thx
