### ISSUE TITLE
[TEST][FLAKY]  test_vm_rpc

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7870]
https://ci.tlcpack.ai/job/tvm/job/main/852/execution/node/234/log/

cc @tkonolige

**Comment by tkonolige** [comment]
Maybe we just bump up the sleep timer?

**Comment by tqchen** [comment]
https://github.com/apache/tvm/pull/7889 could resolve the issue in a more fundamental way

**Comment by areusch** [comment]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-7838/26/pipeline/

**Comment by tqchen** [comment]
should be fixed by https://github.com/apache/tvm/pull/7889
