### ISSUE TITLE
[bug][tvmc]auto scheduler causes an CUDA error: initialization error

### ISSUE THREAD

**Issue by gquanma** [apache/tvm#7888]
tvm/python/tvm/driver/tvmc/autotuner.py：
![image](https://user-images.githubusercontent.com/17522766/115483908-4a3fa580-a284-11eb-9f17-451e3b8dd9bc.png)

an CUDA error: initialization error occurs due to multiple processes.

**Comment by Cjkkkk** [comment]
Do you have code to reproduce that error?

**Comment by gquanma** [comment]
> Do you have code to reproduce that error?

![image](https://user-images.githubusercontent.com/17522766/118251812-9fb15000-b4da-11eb-9ec8-74c621c69700.png)

The above code can reproduce that error.

**Comment by masahi** [comment]
I'll close since there is no actionable iteam.
