### ISSUE TITLE
[arm_cpu] bitserial conv2d TOPI schedule does not support post elementwise ops

### ISSUE THREAD

**Issue by bernhardklein** [apache/tvm#7909]
The **bitserial conv2d** nhwc operator is not working if the next operation is **elementwise**, for example if the next operation is a ReLU.
Corresponding [tvm discussion thread](https://discuss.tvm.apache.org/t/arm-bitserial-bug-cryptic-error-message/9757?u=bernhardklein)

@comaniac pointed out that in the [TOPI schedule](https://github.com/apache/tvm/blob/main/python/tvm/topi/arm_cpu/bitserial_conv2d.py#L350-L443) the corresponding decision seems missing. In contrast for the [bitserial dense TOPI schedule](https://github.com/apache/tvm/blob/main/python/tvm/topi/arm_cpu/bitserial_dense.py#L190) a check for elemwise tag is included and the example snippet works with it.

Attached files:
[python snippet to reproduce the error](https://github.com/apache/tvm/files/6356509/tvm-bitserial-operator-issue.txt)
[full error message](https://github.com/apache/tvm/files/6356503/error.txt)

**Comment by tqchen** [comment]
cc @jwfromm

**Comment by jwfromm** [comment]
fixed in #7929
