### ISSUE TITLE
libbacktrace does not inherit the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER values of the top level project

### ISSUE THREAD

**Issue by mherkazandjian** [apache/tvm#7916]
This issue is a followup of the discussion in the following thread:
https://discuss.tvm.apache.org/t/cross-compile-the-runtime-only-for-aarch64/9800

basically (just to minimize duplication of the forum discussion)
when cross compiling the runtime only on a x86 host, libbacktrace is causing a link-time issue

````bash
mkdir build 
cd build  
cp ../cmake/config.cmake .

 cmake ..
    -DCMAKE_SYSTEM_NAME=Linux
    -DCMAKE_SYSTEM_VERSION=1
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc-8
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g+±8
    -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
````

The cleanest current solution (i think) is to turn off using libbacktrace

**Comment by junrushao1994** [comment]
A related issue: #7705
