### ISSUE TITLE
TVM support for A100

### ISSUE THREAD

**Issue by zhiqi-0** [apache/tvm#7921]
Hi, does TVM support generating kernels (e.g., matmul) on A100 GPUs using TensorCore? I failed to generate matmul (tensorcore, fp16) kernel by using the script from https://tvm.apache.org/docs/tutorials/optimize/opt_matmul_auto_tensorcore.html

**Comment by tqchen** [comment]
Thanks for asking the question, the community uses for trouble shooting and discussions, please bring a new discussion topic on https://discuss.tvm.apache.org/, where more people will be able to watch and answer the questions.

The old tensor core support is indeed stale, but the community is working on adding new tensorization support via TensorIR
