### ISSUE TITLE
"CRT not found. Ensure you have built the standalone_crt target and try again"

### ISSUE THREAD

**Issue by wzelang** [apache/tvm#7930]
when I try "../tests/scripts/task_cpp_unittest.sh" for testing TVM. It turned out "CRT not found. Ensure you have built the standalone_crt target and try again".
I followed TVM INSTALL with link: https://zhuanlan.zhihu.com/p/83806067.

**Comment by wzelang** [comment]
when I try "../tests/scripts/task_cpp_unittest.sh" for testing TVM. It turned out "CRT not found. Ensure you have built the standalone_crt target and try again".
I followed TVM INSTALL with link: https://zhuanlan.zhihu.com/p/83806067.

**Comment by tqchen** [comment]
Please use https://discuss.tvm.apache.org/ to ask related questions
