### ISSUE TITLE
AlterOpLayout modifies input module inplace (and other issues)

### ISSUE THREAD

**Issue by masahi** [apache/tvm#7979]
https://discuss.tvm.apache.org/t/check-failed-axes-defined-static-cast-int-axes-size-ndim-dimension-mismatch/9887

This seems a recurring issue. A Relay pass shouldn't change the input mod inplace.

**Comment by masahi** [comment]
Other related issues
* https://github.com/apache/tvm/pull/8143
* https://discuss.tvm.apache.org/t/frontend-onnx-fail-to-compile-an-onnx-model-at-opt-level-3/9926

**Comment by electriclilies** [comment]
#6624 is an old issue that was worked around by #8143

**Comment by masahi** [comment]
One more bug fixed in https://github.com/apache/tvm/pull/8669

**Comment by masahi** [comment]
I'm not aware of other outstanding issues now.
