### ISSUE TITLE
[PyTorch] ImplementationError: The following operators are not implemented: ['aten::embedding_bag']

### ISSUE THREAD

**Issue by crazydemo** [apache/tvm#7986]
when I try to relay dlrm (pytorch model), I encounter the error:
ImplementationError: The following operators are not implemented: ['aten::embedding_bag']

pytorch=1.7.0, tvm is the latest

cc @yelite

**Comment by GoodNight-bye** [comment]
hello, have you finished importing the DLRM model，i have the same task

**Comment by crazydemo** [comment]
no i haven't



发自我的iPhone


------------------ Original ------------------
From: GoodNight-bye ***@***.***&gt;
Date: Mon,Jun 21,2021 4:26 PM
To: apache/tvm ***@***.***&gt;
Cc: Ivy Zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/tvm] ImplementationError: The following operators are not implemented: ['aten::embedding_bag'] (#7986)

**Comment by crazydemo** [comment]
是的



发自我的iPhone


------------------ Original ------------------
From: GoodNight-bye ***@***.***&gt;
Date: Mon,Jun 21,2021 4:30 PM
To: apache/tvm ***@***.***&gt;
Cc: Ivy Zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/tvm] ImplementationError: The following operators are not implemented: ['aten::embedding_bag'] (#7986)

**Comment by GoodNight-bye** [comment]
我这边是把网络拆分了，embedding的部分不放在NPU上执行，但是后面有个index算子的问题

**Comment by GoodNight-bye** [comment]
embedding_bag is supported in relay/frontend/onnx.py, you can refer to this file.

**Comment by GoodNight-bye** [comment]
I have done the job, DLRM is already running on our NPU. If you have any question, you can contact me.

**Comment by TaoCheng-CS** [comment]
> I have done the job, DLRM is already running on our NPU. If you have any question, you can contact me.
您好， 我目前也遇到这个算子不支持的问题， 能给个联系方式吗？感谢！

**Comment by GoodNight-bye** [comment]
> > I have done the job, DLRM is already running on our NPU. If you have any question, you can contact me.
> > 您好， 我目前也遇到这个算子不支持的问题， 能给个联系方式吗？感谢！

aten::embedding_bag relay层直接参考onnx的实现，算子侧的话需要实现对应的take算子

**Comment by zgplvyou** [comment]
> embedding_bag is supported in relay/frontend/onnx.py, you can refer to this file.

Hi, I`m also relay from onnx dlrm model, in this file(onnx.py), the implementation of embedding_bag use a reshape op(        indices = _op.reshape(indices, indices_shape)), however, if the indices_shape is [3, -1],  the size of indices is [13, ], the indices can not be reshape to the size[3, ?],how to do it!
