### ISSUE TITLE
[VOTE] Adopt the New RFC Process

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7991]
Dear Community:

This is a formal vote to adopt the new RFC process after being discussed in the community for a while. Please see the proposed process here https://github.com/apache/tvm-rfcs

This is a formal voting thread for the community to adopt the new RFC process.

Please vote

Vote:
 +1
 0 - I don't feel strongly about it, but don't object
-1 - because..

The VOTE will open for a week.

This thread is mirrored to dev@, please vote by replying to this thread

**Comment by hogepodge** [comment]
+1

**Comment by mbrookhart** [comment]
+1

**Comment by Lunderberg** [comment]
+1

One small question: Under "Tracking Issue", the tracking issue is closed "when the RFC is either completed or abandoned."  Is "abandoned" the same as "postponed" in this context, or is there a distinction between them?

**Comment by junrushao1994** [comment]
+1

Agree with @Lunderberg on the tracking issue

**Comment by comaniac** [comment]
+1

**Comment by hogepodge** [comment]
@Lunderberg @junrushao1994 good catch, would changing "abandoned" to "postponed" resolve the ambiguity sufficiently?

**Comment by junrushao1994** [comment]
Thanks @hogepodge! Yeah that sounds better to me

**Comment by electriclilies** [comment]
+1 Thanks @hogepodge for your hard work on this!

**Comment by tkonolige** [comment]
+1

**Comment by Lunderberg** [comment]
> @Lunderberg @junrushao1994 good catch, would changing "abandoned" to "postponed" resolve the ambiguity sufficiently?

Thank you!  That resolves my question.

**Comment by jwfromm** [comment]
+1

**Comment by icemelon9** [comment]
+1

**Comment by zackcquic** [comment]
+1

**Comment by zxybazh** [comment]
+1

**Comment by tvm-archiver** [comment]
+1

Thierry

**Comment by areusch** [comment]
+1

**Comment by leandron** [comment]
+1

**Comment by YuchenJin** [comment]
+1

**Comment by tvm-archiver** [comment]
+1

- Ziheng

**Comment by tvm-archiver** [comment]
Hi,

+1

Kind Regards,
Furkan KAMACI

**Comment by liangfu** [comment]
+1

**Comment by jcf94** [comment]
+1

**Comment by tqchen** [comment]
Thanks everyone for participating so far, this vote is extended for another week in case there are more participations

**Comment by altanh** [comment]
+1

**Comment by tqchen** [comment]
Thanks everyone for participating, the results are:

+1
Chris, Matt, Lunderberg, Tristan, Lily, Josh, haichen, Zach, Xiyou, Thierry, Andrew, leandro, Yuchen, ziheng, Furkan, liangfu, chenfan, altan

+0 None

-0 None

The vote has passed
