### ISSUE TITLE
[VM]How to deploy Mask-RCNN with C++

### ISSUE THREAD

**Issue by beautyGril100** [apache/tvm#8001]
I compiled the Mask-RCNN(pytorch version) model with relay VM, and generated maskrcnn-code.ro and maskrcnn-lib.so. How can I use C + + for deployment? Is there an example to show how to do it?

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.apache.org/ since community uses the forum for general types of discussions. 

https://tvm.apache.org/docs/deploy/index.html might be relevant
