### ISSUE TITLE
build tvm CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/tvm_objs.dir/all' failed

### ISSUE THREAD

**Issue by zyh3826** [apache/tvm#8033]
I set these configs at build/config.cmake:

> set(USE_CUDA ON)
set(USE_GRAPH_EXECUTOR ON)
set(USE_PROFILER ON)
set(USE_RELAY_DEBUG ON)
set(USE_LLVM ON)

I use this cmd to build:

> cd build
cmake ..
make -j4

but there are some error:

> In file included from /root/tvm/src/arith/../tir/transforms/ir_utils.h:27:0,
                 from /root/tvm/src/arith/int_constraints.cc:36:
/root/tvm/include/tvm/runtime/device_api.h: In function 'const char* tvm::runtime::DeviceName(int)':
/root/tvm/include/tvm/runtime/device_api.h:234:10: error: 'kDLGPU' was not declared in this scope
     case kDLGPU:
          ^~~~~~
/root/tvm/include/tvm/runtime/device_api.h:234:10: note: suggested alternative: 'kDLCPU'
     case kDLGPU:
          ^~~~~~
          kDLCPU
/root/tvm/include/tvm/runtime/device_api.h:236:10: error: 'kDLCPUPinned' was not declared in this scope
     case kDLCPUPinned:
          ^~~~~~~~~~~~
/root/tvm/include/tvm/runtime/device_api.h:236:10: note: suggested alternative: 'kDLCPU'
     case kDLCPUPinned:
          ^~~~~~~~~~~~
          kDLCPU
In file included from /root/tvm/src/runtime/c_runtime_api.cc:27:0:
/root/tvm/include/tvm/runtime/device_api.h: In function 'const char* tvm::runtime::DeviceName(int)':
/root/tvm/include/tvm/runtime/device_api.h:234:10: error: 'kDLGPU' was not declared in this scope
     case kDLGPU:
          ^~~~~~
/root/tvm/include/tvm/runtime/device_api.h:234:10: note: suggested alternative: 'kDLCPU'
     case kDLGPU:
          ^~~~~~
          kDLCPU
/root/tvm/include/tvm/runtime/device_api.h:236:10: error: 'kDLCPUPinned' was not declared in this scope
     case kDLCPUPinned:
          ^~~~~~~~~~~~
/root/tvm/include/tvm/runtime/device_api.h:236:10: note: suggested alternative: 'kDLCPU'
     case kDLCPUPinned:
          ^~~~~~~~~~~~
          kDLCPU
CMakeFiles/tvm_runtime_objs.dir/build.make:75: recipe for target 'CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o' failed
make[2]: *** [CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o] Error 1
CMakeFiles/Makefile2:282: recipe for target 'CMakeFiles/tvm_runtime_objs.dir/all' failed
make[1]: *** [CMakeFiles/tvm_runtime_objs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/ir_mutator_with_analyzer.cc.o
CMakeFiles/tvm_objs.dir/build.make:140: recipe for target 'CMakeFiles/tvm_objs.dir/src/arith/int_constraints.cc.o' failed
make[2]: *** [CMakeFiles/tvm_objs.dir/src/arith/int_constraints.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/tvm_objs.dir/all' failed
make[1]: *** [CMakeFiles/tvm_objs.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

does anyone can help me, thanks a lot

**Comment by zyh3826** [comment]
in build/CMakeFiles/CMakeError.log, there are also some error msgs:

> Determining if the pthread_create exist failed with the following output:
Change Dir: /root/tvm/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/gmake" "cmTC_c5039/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_c5039.dir/build.make CMakeFiles/cmTC_c5039.dir/build
gmake[1]: Entering directory '/root/tvm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c5039.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_c5039.dir/CheckSymbolExists.c.o   -c /root/tvm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_c5039
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c5039.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     -rdynamic CMakeFiles/cmTC_c5039.dir/CheckSymbolExists.c.o  -o cmTC_c5039
CMakeFiles/cmTC_c5039.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c5039.dir/build.make:86: recipe for target 'cmTC_c5039' failed
gmake[1]: *** [cmTC_c5039] Error 1
gmake[1]: Leaving directory '/root/tvm/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_c5039/fast' failed
gmake: *** [cmTC_c5039/fast] Error 2
File /root/tvm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>
int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/tvm/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/gmake" "cmTC_ff4ce/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_ff4ce.dir/build.make CMakeFiles/cmTC_ff4ce.dir/build
gmake[1]: Entering directory '/root/tvm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ff4ce.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_ff4ce.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_ff4ce
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ff4ce.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_ff4ce.dir/CheckFunctionExists.c.o  -o cmTC_ff4ce -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ff4ce.dir/build.make:86: recipe for target 'cmTC_ff4ce' failed
gmake[1]: *** [cmTC_ff4ce] Error 1
gmake[1]: Leaving directory '/root/tvm/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_ff4ce/fast' failed
gmake: *** [cmTC_ff4ce/fast] Error 2

**Comment by zyh3826** [comment]
I also find libpthead.so in /lib
![image](https://user-images.githubusercontent.com/31238754/118086309-5556a300-b3f6-11eb-95c6-20dc8a79223e.png)

but there are no *pthreads*

**Comment by zyh3826** [comment]
after cmake .., the log in the terminal are:

> -- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build with RPC support...
-- Build with Graph Executor support...
-- Build with profiler...
-- VTA build with VTA_HW_PATH=/root/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2
-- Found CUDA_CUDA_LIBRARY=/usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs/libcuda.so
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda-10.2/lib64/libcudart.so
-- Found CUDA_NVRTC_LIBRARY=/usr/local/cuda-10.2/lib64/libnvrtc.so
-- Found CUDA_CUDNN_INCLUDE_DIRS=/usr/local/cuda-10.2/include
-- Found CUDA_CUDNN_LIBRARY=/usr/local/cuda-10.2/lib64/libcudnn.so
-- Found CUDA_CUBLAS_LIBRARY=CUDA_CUBLAS_LIBRARY-NOTFOUND
-- Found CUDA_CUBLASLT_LIBRARY=CUDA_CUBLASLT_LIBRARY-NOTFOUND
-- Build with CUDA support
-- Build with cuDNN support
-- Link with dynamic LLVM library
-- Found LLVM_INCLUDE_DIRS=/usr/lib/llvm-6.0/include
-- Found LLVM_DEFINITIONS=-D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LLVM_LIBS=LLVM
-- Found TVM_LLVM_VERSION=60
-- Build with LLVM 6.0.0
-- Set TVM_LLVM_VERSION=60
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Not a git repo
-- Performing Test SUPPORT_CXX14
-- Performing Test SUPPORT_CXX14 - Success
-- Autoset: USE_LIBBACKTRACE=ON in Linux
-- Building with libbacktrace...
-- Building Relay in debug mode...
-- Building with TVM Map...
-- Build with thread support...
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Configuring done
-- Generating done
-- Build files have been written to: /root/tvm/build
I find it print Configuring done and Generating done, no any errors, except Looking for pthread_create in pthreads - not found and Looking for pthread_create - not found, I search many other issues, also find the same, I guess this is normal?

**Comment by tkonolige** [comment]
Update your submodule

`git submodule update`

**Comment by zyh3826** [comment]
Thanks for your rely, I followed your advice, and I also find that my tvm floder missing some files, and now it worded, install successed@tkonolige
