### ISSUE TITLE
Auto-tuning a Convolutional Network for ARM CPU (tutorial error, bug reports)

### ISSUE THREAD

**Issue by cbswj** [apache/tvm#8067]
tutorial link : https://tvm.apache.org/docs/tutorials/autotvm/tune_relay_arm.html#sphx-glr-tutorials-autotvm-tune-relay-arm-py
XGB API link : https://tvm.apache.org/docs/api/python/autotvm.html#tvm.autotvm.tuner.XGBtuner

I tried autoTVM tutorial and there is a problem.

Frist, I connected Raspberry Pi and the host server with an rpc session and proceeded with autoTVM.

There was a problem with tuning on autoTVM.
![image](https://user-images.githubusercontent.com/48883649/118622332-2aa78880-b802-11eb-93b8-eb19d1b5e9d8.png)

As in the tutorial example, creating xgbtuner causes problems.

I looked up tvm-API to solve the problem and found this sentence.
‘For cross-device or cross-operator tuning, you can use ‘curve’ only.’
![image](https://user-images.githubusercontent.com/48883649/118615694-f335dd80-b7fb-11eb-824a-384c029597a3.png)

However, the tutorial creates an xgbtuner that does not have a curve option.
![image](https://user-images.githubusercontent.com/48883649/118615977-3c862d00-b7fc-11eb-980e-f4313800c25b.png)

In addition, the tutorial doesn't even have code to create xgbtuner with curve options.
![image](https://user-images.githubusercontent.com/48883649/118616364-9686f280-b7fc-11eb-8785-07bcc6d3015a.png)

Although it is an autoTVM tutorial for ARM CPU using RPC session, it seems strange that there is no curve option when creating xgbtuner.

So I made all the feature_type options available by xgbtuner and experimented.
Of the 3 options knob, itervar, and curve, only knob option does not fail and works well!
![image](https://user-images.githubusercontent.com/48883649/118923194-24d2b400-b976-11eb-8d7a-b7fb2e8afb0b.png)
![image](https://user-images.githubusercontent.com/48883649/118617190-5aa05d00-b7fd-11eb-8e14-cee761d33f24.png)

It is a problem when using RPC session to connect Raspberry Pi and GPU server to proceed autoTVM.

Question
The API says to use the curve option when using xgb, but in reality, it is strange that the knob option, not the curve option, works!

**Comment by leandron** [comment]
@cbswj thanks for the detailed reporting on this issue. Can you send a PR with your fix for the tutorial?

**Comment by cbswj** [comment]
> @cbswj thanks for the detailed reporting on this issue. Can you send a PR with your fix for the tutorial?

I modified the issue content. Could you take a look again and leave a comment?

**Comment by cbswj** [comment]
@leandron 
I modified the issue content.
https://github.com/apache/tvm/pull/8103
