### ISSUE TITLE
AttributeError: Module has no function 'tvm.contrib.vta.init' while running test_benchmark_topi_conv2d.py 

### ISSUE THREAD

**Issue by torontotong** [apache/tvm#8080]
Hello, 

I am trying to make TVM up running with VTA on my own Stratix 10 FPGA board. 
After changed some configuration I could start the test script as show below, howver the program stopped with error, if trace the error all the wat to the bottom, it seems the failure was caused by **_AttributeError: Module has no function 'tvm.contrib.vta.init'_**.
Does anyone can point out where coould wrong or what module Imight missed?

Thanks in adavance! 

Tong
******************************************************************************************************************************************
$ python vta/tests/python/integration/test_benchmark_topi_conv2d.py 
Conv2DWorkload(batch=1, height=56, width=56, in_filter=64, out_filter=64, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=1, wstride=1)
CPU CONV2D TEST PASSED: Time cost = 0.0152826 sec/op, 15.129 GOPS
Conv2DWorkload(batch=1, height=56, width=56, in_filter=64, out_filter=128, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=2, wstride=2)
CPU CONV2D TEST PASSED: Time cost = 0.00870865 sec/op, 13.2748 GOPS
Conv2DWorkload(batch=1, height=56, width=56, in_filter=64, out_filter=128, hkernel=1, wkernel=1, hpad=0, wpad=0, hstride=2, wstride=2)
CPU CONV2D TEST PASSED: Time cost = 0.00139053 sec/op, 9.23755 GOPS
Conv2DWorkload(batch=1, height=28, width=28, in_filter=128, out_filter=128, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=1, wstride=1)
CPU CONV2D TEST PASSED: Time cost = 0.0157609 sec/op, 14.6699 GOPS
Conv2DWorkload(batch=1, height=28, width=28, in_filter=128, out_filter=256, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=2, wstride=2)
CPU CONV2D TEST PASSED: Time cost = 0.0087689 sec/op, 13.1836 GOPS
Conv2DWorkload(batch=1, height=28, width=28, in_filter=128, out_filter=256, hkernel=1, wkernel=1, hpad=0, wpad=0, hstride=2, wstride=2)
CPU CONV2D TEST PASSED: Time cost = 0.00122179 sec/op, 10.5133 GOPS
Conv2DWorkload(batch=1, height=14, width=14, in_filter=256, out_filter=256, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=1, wstride=1)
CPU CONV2D TEST PASSED: Time cost = 0.0137043 sec/op, 16.8714 GOPS
Conv2DWorkload(batch=1, height=14, width=14, in_filter=256, out_filter=512, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=2, wstride=2)
CPU CONV2D TEST PASSED: Time cost = 0.0112738 sec/op, 10.2544 GOPS
Conv2DWorkload(batch=1, height=14, width=14, in_filter=256, out_filter=512, hkernel=1, wkernel=1, hpad=0, wpad=0, hstride=2, wstride=2)
CPU CONV2D TEST PASSED: Time cost = 0.00133913 sec/op, 9.59209 GOPS
Conv2DWorkload(batch=1, height=7, width=7, in_filter=512, out_filter=512, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=1, wstride=1)
CPU CONV2D TEST PASSED: Time cost = 0.0164792 sec/op, 14.0305 GOPS
Traceback (most recent call last):
  File "vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 311, in <module>
    test_conv2d(device="vta")
  File "vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 306, in test_conv2d
    vta.testing.run(_run)
  File "/media/tliu/ECE699/tvm-repo/tvm/vta/python/vta/testing/utils.py", line 74, in run
    run_func(env, remote)
  File "vta/tests/python/integration/test_benchmark_topi_conv2d.py", line 297, in _run
    program_fpga(remote, bitstream=None)
  File "/media/tliu/ECE699/tvm-repo/tvm/vta/python/vta/rpc_client.py", line 64, in program_fpga
    fprogram = remote.get_function("tvm.contrib.vta.init")
  File "/media/tliu/ECE699/tvm-repo/tvm/python/tvm/rpc/client.py", line 73, in get_function
    return self._sess.get_function(name)
  File "/media/tliu/ECE699/tvm-repo/tvm/python/tvm/runtime/module.py", line 91, in get_function
    raise AttributeError("Module has no function '%s'" % name)
AttributeError: Module has no function 'tvm.contrib.vta.init'

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.apache.org/ as we use the forum for related discussions. In this particular case, please confirm the vta on the remote rpc setver is properly build with the VTA FPGA option set to ON
