### ISSUE TITLE
[device] set tvm.cpu(1), error occurred when run

### ISSUE THREAD

**Issue by beautyGril100** [apache/tvm#8100]
I have two physical CPUs. Each CPU has 32 cores. When I set tvm.cpu (0), the program can run normally. When I set tvm.cpu (1), the program will run with an error. Why? The error is as follows：
![cpu_1_error](https://user-images.githubusercontent.com/45866946/119077198-6fac0480-ba26-11eb-97d4-9fe08ef91172.JPG)

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.apache.org/ as we use the forum for related discussions. For CPU devices, we should always use cpu(0), and the OS should be able to pin threads to two of your CPUs
