### ISSUE TITLE
Run slower than original pytorch?

### ISSUE THREAD

**Issue by ZhuYuJin** [apache/tvm#8104]
My mac use the following process:
https://ark.intel.com/content/www/us/en/ark/products/134906/intel-core-i7-8750h-processor-9m-cache-up-to-4-10-ghz.html

Run the official demo. It seems TVM(cost 28ms) run slower than pytorch(cost 22ms), and much slower than onnxruntime(cost 7ms).

I also find a blog that has the same situation with me...
https://zhuanlan.zhihu.com/p/88369758

![image](https://user-images.githubusercontent.com/5879410/119104127-7b132600-ba4e-11eb-812a-4e1c887fd747.png)

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.apache.org/, this likely have things to do with the tuning being involved. https://github.com/tlc-pack/tlcbench also contains some more benchmark scripts that might be relevant
