### ISSUE TITLE
docker ci_cpu image build is failing

### ISSUE THREAD

**Issue by mherkazandjian** [apache/tvm#8173]
Hi,

It seems that building the docker ci_cpu image build is failing.
I tested reproducing this (i think bug) in a vanilla environment OS too, so 
i think you should be able to reproduce it with the following procedure:

````bash
   # clone tvm repository
   git clone --recursive https://github.com/apache/tvm.git

   # build the docker ci_cpu image
   cd docker && ./build.sh ci_cpu
```` 
the build fails when building at stage `` RUN bash /install/ubuntu_install_tflite.sh``
![image](https://user-images.githubusercontent.com/3264637/120411321-e44f3f00-c354-11eb-83cd-1b5754052c14.png)

particularly the following error should show up:

![image](https://user-images.githubusercontent.com/3264637/120411461-25dfea00-c355-11eb-94ff-e17ed8904403.png)

ps: how is the tag version here https://github.com/apache/tvm/blob/main/docker/Dockerfile.ci_cpu#L19 related to the 
``ci_cpu`` tag in the jenkins file https://github.com/apache/tvm/blob/main/Jenkinsfile#L49 ? where are these version tracked?

**Comment by areusch** [comment]
cc @tkonolige (who may not reply til next week) for possible insight on the error. 

I think the tag version commented in `Dockerfile.ci_cpu` is out of date. The version used in CI is documented in `Jenkinsfile`, but we don't currently document the revision from which each version is built.

**Comment by mherkazandjian** [comment]
@areusch @tkonolige 
maybe it is a good idea to have building the docker container in some kind of a CI too (as a separate pipeline or as a separate stage in the main CI pipeline?)

**Comment by leandron** [comment]
> @areusch @tkonolige
> maybe it is a good idea to have building the docker container in some kind of a CI too (as a separate pipeline or as a separate stage in the main CI pipeline?)

@mherkazandjian Yes, I'm working on this, aiming to have a specific pipeline to update the docker images we use and publish them in a staging area.

**Comment by areusch** [comment]
@mherkazandjian @leandron agreed this would be much more optimal!

**Comment by mherkazandjian** [comment]
Great. If you need help testing please let me know, i'll be happy to give it a test drive. 
btw, may you confirm that the ci_cpu is broken? or it is something that has to do with my environment, although i tested on a vanilla machine.

**Comment by mherkazandjian** [comment]
@areusch please checkout the following PR #8239 

the tensorflow issue during building the ci_cpu seems to have been fixed, i am not sure why, probably some tensorflow dependency has been updated.

technically the PR  #8239 fixes is issue (not for the original reason though)

**Comment by mherkazandjian** [comment]
this issue is not relevant anymore, the ci_cpu build is succeeding
https://github.com/apache/tvm/issues/8173
