### ISSUE TITLE
Support conv2d transpose operator with groups > 1

### ISSUE THREAD

**Issue by YuhengHuang42** [apache/tvm#8182]
Currently TVM doesn't support Conv2d transpose with groups > 1. When turning Pytorch model to Relay there will be an error.

Detail discussion could be seen at: https://discuss.tvm.apache.org/t/pytorch-error-when-turning-a-simple-pytorch-model-to-relay/10158

P.S. It may be better if TVM can show some warnings saying that a specific parameter for an op is unsupported, rather than  just gives some kind of error?

**Comment by Lyken17** [comment]
happened to be here. It was surprising the issue was not solved after so long time. For anyone who also had this trouble, you may refer following code to support `group` parameter in transposed convolution

```python
    out_c = simplify(out_c)
    out_channels = simplify(out_c * groups)

    out_h = simplify(in_h - filter_h + 1)
    out_w = simplify(in_w - filter_w + 1)
    dc = te.reduce_axis((0, in_c // groups), name="dc")
    dh = te.reduce_axis((0, filter_h), name="dh")
    dw = te.reduce_axis((0, filter_w), name="dw")
    
    # data: batch, in_channels, out_h, out_w
    # weight: out_channels // G, in_channels, out_h, out_w
    return te.compute(
        (batch, out_channels, out_h, out_w),
        lambda b, c, h, w: te.sum(
            data_pad[
                b, 
                c // (out_channels // groups) * (in_channels // groups) + dc, 
                h + dh, 
                w + dw
            ].astype(out_dtype)
            * kernel_transform[
                c % (out_channels // groups), 
                c // (out_channels // groups) * (in_channels // groups) + dc, 
                dh, 
                dw
            ].astype(out_dtype),
            axis=[dc, dh, dw],
        ),
        tag="conv2d_transpose_nchw",
    )
```

**Comment by tqchen** [comment]
Thanks @Lyken17 , do you mind to send a PR to resolve the case?

**Comment by Lyken17** [comment]
@tqchen Sure, I can craft a PR.
