### ISSUE TITLE
[Topi] Allow relay.nn.dense support arbitrary number dimensions

### ISSUE THREAD

**Issue by AndrewZhaoLuo** [apache/tvm#8412]
Right now the schedule assumes two dimensions for the input tensor though the documentation suggests otherwise:
https://tvm.apache.org/docs/api/python/relay/nn.html#tvm.relay.nn.dense

Alternatively we can just adjust the documentation to stipulate relay.nn.dense has an input tensor of only two dimensions. However, other frameworks allow their dense layers to be arbitrary number dimensions. E.g. https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear

For forum discussion see: https://discuss.tvm.apache.org/t/relay-nn-does-relay-nn-dense-supports-multi-dimensional-input/10343/5

**Comment by masahi** [comment]
I think a good way to add N-D input support to `topi.dense` is to do `topi.reshape` on the input before doing dense compute, and inside dense schedules we do `compute_inline(...)` on the reshape stage. This way, we can reuse existing schedules that are hardcoded for 2D input at no performance overhead (modulo some indexing math from reshaping). See my PR https://github.com/apache/tvm/pull/9207 that does something similar.

**Comment by comaniac** [comment]
I agree with @masahi that adding `topi.reshape` is a more general solution. The reason is we have more than one backends and we need to make sure all backend implementations have the same semantic/spec. For example, previously I encountered the issue (#7730) that CuBLAS batch_matmul implementation doesn't supports implicit broadcasting, which results in errors when lowering batch_matmul to CuBLAS.

If we allow arbitrary dimension in `relay.nn.dense`, which means implicitly reshaping actually, we need to make sure all supported implementations follow this semantic. Considering Relay graph should be as general as possible to be compatible with arbitrary backends, simplify the operator semantic and make extra behaviors as explicit as possible seems more developer friendly.

**Comment by masahi** [comment]
Another workaround that allows dense + activation without supporting N-D dense is to swap the order of reshape and activations. So right now we are doing `dense -> reshape -> activations` but we can do `dense -> activations -> reshape`. We need to reshape the bias but that's compile time op. We are still left with annoying "naked" reshape at the end, but this might be a quicker solution for demonstrating cutlass byoc.

**Comment by comaniac** [comment]
Thanks for the analysis and I deeply agree with it as we (with @icemelon) are also experiencing the same issue. Making the pattern like `dense -> activations` is definitely more straightforward, and reshaping `bias` is basically a free lunch. We may start with this solution to unblock CUTLASS, and we could still support N-D dense/batch_matmul in parallel.

**Comment by masahi** [comment]
I found something interesting wrt the reshape swapping approach. If there are back-to-back `dense` op, currently we end up with something like
```
  %2367 = fn (%p06: Tensor[(1024, 1024), float16], %p16: Tensor[(4096, 1024), float16], Primitive=1, hash="c13735290dc46bbc") -> Tensor[(1024, 4096), float16] {
    nn.dense(%p06, %p16, units=None, out_dtype="float16") /* ty=Tensor[(1024, 4096), float16] */
  };
  %2368 = %2367(%2366, meta[relay.Constant][430] /* ty=Tensor[(4096, 1024), float16] */) /* ty=Tensor[(1024, 4096), float16] */;
  %2369 = fn (%p05: Tensor[(1024, 4096), float16], %p15: Tensor[(4096), float16], %p24: float16, Primitive=1, hash="ab37ab7bd1a05f99") -> Tensor[(1024, 4096), float16] {
    %13 = reshape(%p05, newshape=[8, 128, 4096]) /* ty=Tensor[(8, 128, 4096), float16] */;
    %14 = add(%13, %p15) /* ty=Tensor[(8, 128, 4096), float16] */;
    %15 = multiply(%14, %p24) /* ty=Tensor[(8, 128, 4096), float16] */;
    %16 = cast(%15, dtype="float32") /* ty=Tensor[(8, 128, 4096), float32] */;
    %17 = erf(%16) /* ty=Tensor[(8, 128, 4096), float32] */;
    %18 = multiply(%17, 0.5f /* ty=float32 */) /* ty=Tensor[(8, 128, 4096), float32] */;
    %19 = cast(%14, dtype="float32") /* ty=Tensor[(8, 128, 4096), float32] */;
    %20 = add(0.5f /* ty=float32 */, %18) /* ty=Tensor[(8, 128, 4096), float32] */;
    %21 = multiply(%19, %20) /* ty=Tensor[(8, 128, 4096), float32] */;
    %22 = reshape(%21, newshape=[-1, 4096]) /* ty=Tensor[(1024, 4096), float32] */;
    cast(%22, dtype="float16") /* ty=Tensor[(1024, 4096), float16] */
  };
  %2370 = %2369(%2368, meta[relay.Constant][431] /* ty=Tensor[(4096), float16] */, meta[relay.Constant][432] /* ty=float16 */) /* ty=Tensor[(1024, 4096), float16] */;
  %2371 = fn (%p04: Tensor[(1024, 4096), float16], %p14: Tensor[(1024, 4096), float16], Primitive=1, hash="adf706330ace9ece") -> Tensor[(1024, 1024), float16] {
    nn.dense(%p04, %p14, units=None, out_dtype="float16") /* ty=Tensor[(1024, 1024), float16] */
  };
```
Note that there are two `reshape`s in the middle, one for 2D -> 3D and another for 3D-2D. If we swap activation with reshape, two reshapes become back-to-back and hence they cancel each other.
