### ISSUE TITLE
TVM Docker build issues on Rust SGX SDK

### ISSUE THREAD

**Issue by AlexYaoRuihao** [apache/tvm#8444]
Hi, I was working on building TVM based on Rust SGX SDK right before #4976 with commit hash 93dff448b06a8fd6e133326cf8c32bb623817fc3. I was trying to run the docker version following instructions below. 
![image](https://user-images.githubusercontent.com/34175393/125169032-01560980-e16e-11eb-9b39-44cb1de62767.png)
When I try to run the command `make -j4` after cmake, I got the following errors.
![image](https://user-images.githubusercontent.com/34175393/125169222-cdc7af00-e16e-11eb-9f7a-dc771d2f1ec1.png)
Does anyone know how to fix this? Any response is appreciated!

**Comment by vinx13** [comment]
try `git submodule update`, there are some updates to `dlpack` and `DLContext` has been renamed to `DLDevice`
