### ISSUE TITLE
automatically terminate when I use breakpoints to debug

### ISSUE THREAD

**Issue by zhaiyi000** [apache/tvm#8545]
The program can be executed normally, but it will automatically terminate when I use breakpoints to debug. There is no prompt when using vscode. When using pycharm, it prompts "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

Environment: MacBook Pro
System: macOS 11.4
Server: ubuntu 18 docker
use ssh to connect server

I call the function `aa = IRModule()`, this function calls the `__init__` function of `IRModule`, then calls `__init_handle_by_constructor__` inside `__init__`, and after entering `__init_handle_by_constructor__`, I click "step over" and the program terminates.

<img width="1707" alt="截屏2021-07-24 下午6 53 20" src="https://user-images.githubusercontent.com/61309244/126866395-6ee54927-4576-4102-9814-02052df6ea2f.png">
<img width="1707" alt="截屏2021-07-24 下午6 53 32" src="https://user-images.githubusercontent.com/61309244/126866402-435d948b-e87f-47a3-b413-2913482e5162.png">
<img width="1707" alt="截屏2021-07-24 下午6 53 39" src="https://user-images.githubusercontent.com/61309244/126866406-537ba992-a633-4315-b333-eeec85573def.png">
<img width="1707" alt="截屏2021-07-24 下午6 53 49" src="https://user-images.githubusercontent.com/61309244/126866407-e0486861-e8c1-4d27-9ef4-829ab7d68a20.png">
<img width="1707" alt="截屏2021-07-24 下午6 54 44" src="https://user-images.githubusercontent.com/61309244/126866408-90cab3d0-0d22-4d4e-98bc-890d2051f717.png">

**Comment by zhaiyi000** [comment]
I'm sorry I don't have any more details, and at the end yet I don't know what the problem is. And I gave up debugging by breakpoints in these files

**Comment by areusch** [comment]
ok, thanks for following up!

**Comment by zhaiyi000** [comment]
@areusch No, my computer is MacBook Pro (15-inch, 2017), 2.8 GHz quad-core Intel Core i7
