### ISSUE TITLE
[CI] Does anyone feel that out CI is becoming slower and slower?

### ISSUE THREAD

**Issue by jcf94** [apache/tvm#8552]
The recent PRs trend to spend more time on passing the CI, looks like mainly cost by waiting for the machine resources.

**Comment by tqchen** [comment]
Thanks @jcf94 . There was an outage during the weekend which is being worked on, we now recovered some of the GPU nodes and will work to recover all of them.

**Comment by tqchen** [comment]
The CI nodes are recovered. There are more ongoing effort to reduce the CI running time.

Let us move to more concrete threads for improving the CI test times
