### ISSUE TITLE
[TESTS] Hardcode target and device when getting tvm output

### ISSUE THREAD

**Issue by CaptainDuke** [apache/tvm#8565]
https://github.com/apache/tvm/blob/344553223494d136d5eb1cd315e2c000879b06ec/tests/python/frontend/onnx/test_forward.py#L81-L84

I comment the code but test case [test_gemm](https://github.com/apache/tvm/blob/a492db89d9d7ddfc773baec0e8ee0ee09a9487c5/tests/python/frontend/onnx/test_forward.py#L5323) failed. It seems onnx_runtime and tvm differ on the precision.

**Comment by masahi** [comment]
cc @mbrookhart @jwfromm I remember we found this problem before and fixed it then...

**Comment by electriclilies** [comment]
Yeah, @mbrookhart and I definitely removed it (or tried to)..

**Comment by mbrookhart** [comment]
:/ I don't see the removal of the hard-coded target in the PR we did. https://github.com/apache/tvm/pull/7438/files

But I could have sworn it was in there. Perhaps we messed up a rebase?

**Comment by masahi** [comment]
Looks like it was fixed in https://github.com/apache/tvm/pull/8621
