### ISSUE TITLE
error:libLLVMMCJIT.a: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by fengzhao860814** [apache/tvm#8572]
cp cmake/config.cmake build
set(USE_LLVM ON)
cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_VERSION=1 \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_CXX_COMPILER=$CXX \
    -DMACHINE_NAME=aarch64-linux-android \
    -DCMAKE_HOST=aarch64-linux-android 
    
make -j32   
Cross compilation failed:
libLLVMMCJIT.a: error adding symbols: File in wrong format
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/tvm.dir/build.make:1031: recipe for target 'libtvm.so' failed
make[2]: *** [libtvm.so] Error 1
CMakeFiles/Makefile2:634: recipe for target 'CMakeFiles/tvm.dir/all' failed
make[1]: *** [CMakeFiles/tvm.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tqchen** [comment]
Thanks for asking the question, please open a new thread on https://discuss.tvm.apache.org/ for related build trouble shooting. You  only likely need to build tvm runtime instead of libtvm on android.
