### ISSUE TITLE
CI sporadically fails with "unstable" status

### ISSUE THREAD

**Issue by areusch** [apache/tvm#8593]
Seen twice now, once yesterday and once today:

* https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8525/15/pipeline/390/
* https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8567/2/pipeline

Tests contains the same stack trace:
```
ImportError while importing test module '/workspace/tests/python/frontend/onnx/test_forward.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/python/frontend/onnx/test_forward.py:23: in <module>
    import torch
E   ModuleNotFoundError: No module named 'torch'
```

Suspect this is from a stale pytest JUnit report, since ONNX tests are not run by tests/scripts/task_python_frontend_cpu.sh. Hopeful fix incoming.

**Comment by driazati** [comment]
we use a different workspace for every build now so this should be fixed
