### ISSUE TITLE
[TEST] TF broadcast tests taking 25+ mins on CI runs

### ISSUE THREAD

**Issue by denise-k** [apache/tvm#8609]
# Context

CI is taking a while (see #8552 and [build#1384](https://ci.tlcpack.ai/job/tvm/job/main/1384/testReport/)), and I am tracking short-term fixes to alleviate this.

# Summary of the issue

The following test cases are located in `tests/python/frontend/tensorflow/test_forward.py`

`test_forward_broadcast_args`  [takes over 15 minutes](https://ci.tlcpack.ai/job/tvm/job/main/1384/testReport/cython.tests.python.frontend.tensorflow/test_forward/Integration_Test___frontend__GPU___test_forward_broadcast_args/) to run 3 cases.

The parameters passed into `_test_broadcast_args` do not seem to be minimal:
```
    _test_broadcast_args((4, 1, 32, 32), [4, 8, 32, 32])
    _test_broadcast_args((6, 32, 32, 1), [6, 32, 32, 16])
    _test_broadcast_args((32, 32, 16), [6, 32, 32, 16])
```

`test_forward_broadcast_to` [takes over 10 minutes](https://ci.tlcpack.ai/job/tvm/job/main/1384/testReport/cython.tests.python.frontend.tensorflow/test_forward/Integration_Test___frontend__GPU___test_forward_broadcast_to/) to run 3 cases.

The parameters passed into `_test_broadcast_to` do not seem to be minimal:
```
    _test_broadcast_to((4, 1, 32, 32), [4, 8, 32, 32])
    _test_broadcast_to((6, 32, 32, 1), [6, 32, 32, 16])
    _test_broadcast_to_from_tensor((1))
```

# Suggested actions

* Consider using smaller input shapes for these tests.

**Comment by Lunderberg** [comment]
Closing based on completion of https://github.com/octoml/tvm-roadmap/issues/5
