### ISSUE TITLE
Link librvm_runtime.so get Error.

### ISSUE THREAD

**Issue by laiou** [apache/tvm#8629]
I wanted to link tvm lib to my repo , using tvm 0.6 lib. after use target_link_libraries to link libtvm_runtime.so ,but get a ld error is showing :
undefined reference to `tvm::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DLDataType, DLContext, int)'
collect2: error: ld returned 1 exit status

How can i  fix this error , thanks!

**Comment by tqchen** [comment]
please check if the problem still exists in the latest main, based on my reading it should be fixed by the TVM_DLL prefix
