### ISSUE TITLE
[microTVM] move function prototypes from lib0.c to an include file

### ISSUE THREAD

**Issue by areusch** [apache/tvm#8640]
Now that we have `--interface=` target string flag, it's possible to wind up in a bad situation with two different styles of function prototypes:

lib0.c:
```
TVM_DLL int32_t tvmgen_default_fused_multiply_add(TVMValue* args, int* type_code, int num_args, TVMValue* out_value, int* out_type_code);
```

lib1.c:
```
TVM_DLL int32_t tvmgen_default_fused_multiply_add(void* arg0, void* arg1, void* arg2) {
```

target string used: `"c -keys=cpu -link-params=1 -model=host -runtime=c -system-lib=1 -unpacked-api=1"`

the action item here is to move the prototype from lib0.c into a header file which is included by both files.

cc @Mousius @alanmacd @gromero @guberti @mehrdadh

**Comment by guberti** [comment]
This issue exists on https://github.com/guberti/tvm/commit/61a0a392af5dd20d44f6974f975335a8d4da859d.

**Comment by Mousius** [comment]
I think this has always been the case, at least with AOT? `--system-lib=1` also generates normal packed function prototypes without `resource_handle`:
```
TVM_DLL int32_t tvmgen_default_fused_layout_transform(TVMValue* args, int* type_code, int num_args, TVMValue* out_value, int* out_type_code);
```

Whereas the actual operators have `resource_handle`:
```
TVM_DLL int32_t tvmgen_default_fused_layout_transform(void* args, void* arg_type_ids, int32_t num_args, void* out_ret_value, void* out_ret_tcode, void* resource_handle) {
```

This applies whenever you use `-system-lib=1`. I'm unsure if the correct solution is moving the prototypes to another header or just providing the correct prototypes in the metadata module, it doesn't seem necessary to expose this outside of the `.c` files?
