### ISSUE TITLE
[RFC][Tracking Issue] CMSIS-NN Integration

### ISSUE THREAD

**Issue by ashutosh-arm** [apache/tvm#8646]
1. Graph partitioner for CMSIS-NN target #8653 
2. Code generation using existing BYOC #8833 
2a. tvmc support to generate code for #8833 
3. Moved TIR generator to C++ #8951
4. Use of CMSIS-NN data structures while supporting Convolution #9331
4a. Buffer sizes based on arch extensions #9338
5. Support for Depthwise Convolution #9409 
6. Support for Fully connected #9531 
7. Support for Max Pooling #9531 
8. Support for Avg Pooling #9531 
9. Support for elementwise add and multiply #9167 and #9163 
10. Move TIR and C codegen to target hooks #9397

**Comment by areusch** [comment]
https://github.com/apache/tvm-rfcs/pull/15

**Comment by Mousius** [comment]
All of this seems to have landed, huzzah! Thanks to @ashutosh-arm for coordinating this effort :smile_cat:
