### ISSUE TITLE
confusing error: CUDA_ERROR_INVALID_PTX

### ISSUE THREAD

**Issue by techshoww** [apache/tvm#8649]
I have two computer. 
Computer A has  two 24G memory nvidia gpu (RTX 6000).
Computer B only has a 2000M memory nvidia gpu (MX330).
The two computer all use same cuda-9.0 , same tvm version, same gcc version,  same system ubuntu18.04 and same code.

There are two scene,
scene 1,
I export a tvm model on  computer A.  
Then i run the model on computer B.
TVM report error "Check failed: ret == 0 (-1 vs. 0) : CUDAError: cuModuleLoadData(&(module_[device_id]), data_.c_str()) failed with error: CUDA_ERROR_INVALID_PTX".

scene2,
I export a tvm model on computer A.
Then i run the model on computer B.
It runs correctly.

So, what is the reason about the above error?
It is about gpu memory ?

**Comment by masahi** [comment]
Please ask questions on the forum. I don't see the difference in your case 1/2.
