### ISSUE TITLE
[TVM_TUNE]how to speed up tvm-tune process?

### ISSUE THREAD

**Issue by bmfire1** [apache/tvm#8667]
**This is my tune process**
============================

[Task  1/15]  Current/Best:  203.76/ 218.31 GFLOPS | Progress: (456/456) | 640.50 s Done.
[Task  2/15]  Current/Best:   80.40/ 419.17 GFLOPS | Progress: (1596/1596) | 4903.65 s Done.
[Task  3/15]  Current/Best:   42.18/ 481.95 GFLOPS | Progress: (2128/2128) | 4875.32 s Done.
[Task  4/15]  Current/Best:   49.33/ 398.59 GFLOPS | Progress: (2128/2128) | 3484.17 s Done.
[Task  5/15]  Current/Best:  165.78/ 452.15 GFLOPS | Progress: (2432/2432) | 7505.86 s Done.
[Task  6/15]  Current/Best:  312.07/ 457.73 GFLOPS | Progress: (2592/2592) | 5653.20 s Done.
[Task  7/15]  Current/Best:  126.27/ 482.35 GFLOPS | Progress: (2592/2592) | 3867.81 s Done.
[Task  8/15]  Current/Best:  177.73/ 489.10 GFLOPS | Progress: (2916/2916) | 8795.57 s Done.
[Task  9/15]  Current/Best:  129.73/ 380.58 GFLOPS | Progress: (1440/1440) | 4954.11 s Done.
[Task 10/15]  Current/Best:  206.29/ 509.71 GFLOPS | Progress: (1440/1440) | 2401.94 s Done.
[Task 11/15]  Current/Best:  259.05/ 366.04 GFLOPS | Progress: (1600/1600) | 7182.31 s Done.
[Task 12/15]  Current/Best:  218.73/ 396.80 GFLOPS | Progress: (1600/1600) | 4050.32 s Done.
[Task 13/15]  Current/Best:  169.96/ 470.15 GFLOPS | Progress: (1600/1600) | 2884.35 s Done.
[Task 14/15]  Current/Best:   56.56/ 194.11 GFLOPS | Progress: (180/180) | 418.50 s Done.
[Task 15/15]  Current/Best:    8.65/ 186.24 GFLOPS | Progress: (4320/4320) | 10059.10 s Done.

==========================
**my tune option**

tuning_option = {
    "log_filename": log_file,
    "tuner": "random",
    "early_stopping": None,
    "measure_option": autotvm.measure_option(
        builder=autotvm.LocalBuilder(),
        runner=autotvm.LocalRunner(
            number=1, repeat=10, min_repeat_ms=0    #, enable_cpu_cache_flush=True
        ),
    ),
}
 target = "llvm -mcpu=core-avx2"

========================
**my perfermance**

inference time
**pytorch: 0.09s
tuned-tvm:0.22s**

**Comment by masahi** [comment]
Please ask questions on the forum.
