### ISSUE TITLE
[CI] Report pytest --junitxml results when tests fail

### ISSUE THREAD

**Issue by areusch** [apache/tvm#8674]
Right now we don't do junit reports when tests fail, so the Tests tab isn't super helpful outside of telling you test runtime. We should fix this so it becomes more useful. Modify the jenkinsfile to always invoke `junit` even if the shell script fails.

@mikepapadim will take a look
cc @leandron @jroesch @denise-k

**Comment by mikepapadim** [comment]
On-going PR in #8757

**Comment by driazati** [comment]
we have this in Jenkins now for every test step, closing
