### ISSUE TITLE
Log autotvm/auto_schduler Builder/Runner/session-ctor stack traces

### ISSUE THREAD

**Issue by areusch** [apache/tvm#8696]
Right now when AutoTVM and auto_scheduler builders and runners encounter exception conditions, the exceptions are caught and stored into result objects, but never printed. This is WAI when the log level is e.g. below logging.INFO, because during autotuning, some schedules are expected to fail to build and autotuning should be robust to that.

However, there are a lot of valid debugging scenarios (e.g. debugging new schedules, debugging targets, debugging changes to autotvm, debugging failed tests) where currently, you first need to modify `python/tvm/autotvm` or `python/tvm/auto_scheduler` code to print out the exception.

The task here is twofold, the second part could be deferred:
part 1:
- [ ] add logging.debug() calls to autotvm and auto_scheduler to print the exception
- [ ] add unit tests to verify these get called

call sites to log exceptions from in autotvm:
1. [builder](https://github.com/apache/tvm/blob/main/python/tvm/autotvm/measure/local_executor.py#L55)
2. [runner](https://github.com/apache/tvm/blob/main/python/tvm/autotvm/measure/measure_methods.py#L618)
3. [establishing the session](https://github.com/apache/tvm/blob/main/python/tvm/autotvm/measure/measure_methods.py#L583) (kind of the same as the previous item, but a different class of errors can occur here--those errors raised from `session_constructor`)

part 2: do this more scalably for autotvm, and provide a way to inspect the autotvm results:
- [ ] improve the return value of autotvm: output some kind of class that summarizes e.g. # successful trials, # failed trials, tune log results by trial, exceptions by trial
- [ ] determine the appropriate way to serialize this to disk for consumption from `tvmc`
- [ ] add testing for the above

@mikepapadim if you have time for at least part 1, that would be quite helpful!

cc @jroesch @tqchen @leandron @denise-k

**Comment by wangzy0327** [comment]
@areusch Hello , Do you know how to control the INFO level in tvm?

If I want to print only higher output level instead of LOG INFO , what can I do to set the log level config?
like the code as below.
```
  auto best_algo = perf_results[0].algo;
  LOG(INFO) << "\tCUDNN Found " << returned_algo_count << " fwd algorithms, choosing "
            << fwd_algo_names[best_algo];
  for (int i = 0; i < returned_algo_count; ++i) {
    LOG(INFO) << "\t\t" << i << ") " << fwd_algo_names[perf_results[i].algo]
              << " - time: " << perf_results[i].time << " ms"
              << ", Memory: " << perf_results[i].memory;
  }
```
include/tvm/runtime/logging.h
```
#define TVM_LOG_LEVEL_DEBUG 0
#define TVM_LOG_LEVEL_INFO 1
#define TVM_LOG_LEVEL_WARNING 2
#define TVM_LOG_LEVEL_ERROR 3
#define TVM_LOG_LEVEL_FATAL 4
#define LOG(level) LOG_##level
#define LOG_DEBUG \
  ::tvm::runtime::detail::LogMessage(__FILE__, __LINE__, TVM_LOG_LEVEL_DEBUG).stream()
#define LOG_FATAL ::tvm::runtime::detail::LogFatal(__FILE__, __LINE__).stream()
#define LOG_INFO ::tvm::runtime::detail::LogMessage(__FILE__, __LINE__, TVM_LOG_LEVEL_INFO).stream()
#define LOG_ERROR \
  ::tvm::runtime::detail::LogMessage(__FILE__, __LINE__, TVM_LOG_LEVEL_ERROR).stream()
#define LOG_WARNING \
  ::tvm::runtime::detail::LogMessage(__FILE__, __LINE__, TVM_LOG_LEVEL_WARNING).stream()
```
