### ISSUE TITLE
[TEST][FLAKY] test_auto_scheduler_layout_rewrite.py::test_correctness_layout_rewrite_rewrite_for_preTransformed

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#8749]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8715/20/pipeline/258

Seems to be a flaky test.

**Comment by junrushao1994** [comment]
@vinx13 @shingjan just wanted to double check with you guys, is this fixed on mainline?

**Comment by vinx13** [comment]
Yes it is fixed
