### ISSUE TITLE
On the parametric search space

### ISSUE THREAD

**Issue by jqzhao7** [apache/tvm#8752]
Dear teacher,
  I am a graduate student studying TVM. First of all, As a very meaningful job, tvm,  I recently encountered a problem:
What is the size of the search space that TVM generates for the model waiting to be optimized? Where should I look up information on this subject? Or what is the definition of the size of the search space?

**Comment by vinx13** [comment]
Relay model is lowered to a few operators in `topi`. Each (tunable) operator has one or more templates in `topi`, for example https://github.com/apache/tvm/blob/596ff5cff576d8ded1251bb936eb7198551cc481/python/tvm/topi/cuda/conv2d_direct.py#L25.  You are encouraged to open a new thread on https://discuss.tvm.apache.org/ as we use the forum for related discussions.
