### ISSUE TITLE
[CI] Rev ci-cpu image to include latest PRs

### ISSUE THREAD

**Issue by leandron** [apache/tvm#8782]
I'm just raising this as a request for the `ci-cpu` image to be updated, to include latest PRs updating dependencies. Specifically, I'm interested to get #8514 into the image.

As a way to simplify the work required by someone with access to upload `tlcpack` images, I've already tested images based on my ongoing work with `tlcpackstaging`. Here is the job in which all tests pass with an updated set of images: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/146/pipeline

So, my understanding of the work needed here is:
```
docker pull tlcpackstaging/ci_cpu:20210815-225913-1a95f9bd0
docker tag tlcpackstaging/ci_cpu:20210815-225913-1a95f9bd0 tlcpack/ci-cpu:v0.76   # already bumped by 0.01
docker push tlcpack/ci-cpu:v0.76
```

Once this is done, we can create a PR to Rev the image version and than make it permanent.

So, the tasks:
 - [x] pull, retag, push docker images using commands above (needs to be done by someone in the list below)
 - [x] submit a PR updating the ci-cpu version on Jenkins (one the one above is done, I can do that myself)

I have no permission to upload images myself, so I'm adding here the people I think have access to do so: @tqchen @areusch @jroesch @zhiics @masahi.

cc @grant-arm @u99127

**Comment by jroesch** [comment]
@leandron I am currently executing the push, will ping back when its done.

**Comment by jroesch** [comment]
@leandron its currently uploading to dockerhub

**Comment by leandron** [comment]
That is completed now. Closing the issue. Thanks @jroesch.
