### ISSUE TITLE
Failed to compile the latest TVM source code with vulkan enabled on Windows10

### ISSUE THREAD

**Issue by kthready** [apache/tvm#8805]
Compiled the latest TVM source code with vulkan enabled on Windows10 with VS2019.
Firstly, I compiled the latest LLVM source code. It was OK.
And then I installed the latest Vulkan SDK.
Finanlly, I compiled the latest TVM source code, but it was failed.
I found that it was failed when compiling the code in the dir tvm\src\runtime\vulkan\
I wonder how to resolve this problem.

The compile log is as below.
5>   Creating library C:/Users/george/Documents/workspace/tvm/build/Release/tvm_runtime.lib and object C:/Users/george/Documents/workspace/tvm/build/Release/tvm_runtime.exp
5>vulkan_instance.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_module.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_stream.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_wrapped_func.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_buffer.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_common.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_device.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>vulkan_device_api.obj : error LNK2001: unresolved external symbol "public: __cdecl tvm::parser::SourceMap::SourceMap(class tvm::runtime::Map<class tvm::SourceName,class tvm::parser::Source,void,void>)" (??0SourceMap@parser@tvm@@QEAA@V?$Map@VSourceName@tvm@@VSource@parser@2@XX@runtime@2@@Z)
5>C:\Users\george\Documents\workspace\tvm\build\Release\tvm_runtime.dll : fatal error LNK1120: 1 unresolved externals
5>Done building project "tvm_runtime.vcxproj" -- FAILED.
6>------ Skipped Build: Project: runtime, Configuration: Release x64 ------

**Comment by kthready** [comment]
@Lunderberg

**Comment by Lunderberg** [comment]
Hmm, a vulkan-specific undefined symbol in tvm_runtime should have been caught during the CI build since #8178 (runs on linux), and in the Windows cuda build.  I can verify on my linux machine that the `libtvm_runtime.so` doesn't include any references to source map.

Looking at `source_map.h`, it does look like the `TVM_DLL` macro on MSVC is expanding to `__declspec(dllexport)` in both `libtvm.dll` and `libtvm_runtime.dll`, which is causing the missing symbol errors.  Does this happen with the cuda runtime as well?   If the unintentional dllexport is the cause, then I would expect it to occur for anything in `src/runtime` that imports `source_map.h`, which would be every runtime.

**Comment by kthready** [comment]
I didn't enable CUDA since there is no NV device in my machine.

**Comment by Lunderberg** [comment]
Got it.  In that case, can you try compiling with `USE_VULKAN=OFF`, and `USE_LLVM=ON`?

**Comment by Lunderberg** [comment]
Found the issue.  I had a `#include <tvm/target/target.h>` that should have been removed.  #8813 removes the include, and should resolve the issue.  Can you test and verify?

**Comment by kthready** [comment]
OK, thx, I will verify it tmr.

**Comment by kthready** [comment]
Verified, it works.
