### ISSUE TITLE
[Tracking Issue][ONNX] Quantized operator support in ONNX importer

### ISSUE THREAD

**Issue by tmoreau89** [apache/tvm#8838]
### Summary

This issue will be used to track ONNX importer coverage progress of standard and non-standard quantized ops in TVM, and can be used to coordinate distributed efforts on improving quantized importer coverage work across organizations. 

### Status

To this day (Aug 24th 2021) we'd like to account for both standard ONNX quantized ops and non-standard quantized contrib ops introduced by ONNXRT, as shown in the table below:

Shortlist of ops that are emitted by ONNXRT static quantization (higher priority), based on https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/registry.py:

| Operator | Standard | Opset | Status | Owner | PR |
|---|---|---|---|---|---|
| [ConvInteger](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvInteger) | Y | 10 | Supported | @jwfromm | https://github.com/apache/tvm/pull/8456 |
| [DequantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#DequantizeLinear) | Y | 13, 10 | Supported | @mbrookhart | https://github.com/apache/tvm/pull/7802 |
| [MatMulInteger](https://github.com/onnx/onnx/blob/master/docs/Operators.md#MatMulInteger) | Y | 10 | WIP | @WenheLI |  |
| [QLinearConv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#QLinearConv) | Y | 10 | Supported | @huochaitiantang | https://github.com/apache/tvm/pull/8007 |
| [QLinearMatMul](https://github.com/onnx/onnx/blob/master/docs/Operators.md#QLinearMatMul) | Y | 10 | Supported | @cconvey  | https://github.com/apache/tvm/pull/8952 |
| [QuantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#QuantizeLinear) | Y | 13, 10 | Supported | @mbrookhart | https://github.com/apache/tvm/pull/7802 |
| [com.microsoft.QAttention](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QAttention) | N | n/a | TODO |  |  |
| [com.microsoft.QLinearAdd](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearAdd) | N | n/a | Supported | @mbrookhart | https://github.com/apache/tvm/pull/8305 |
| [com.microsoft.QLinearAveragePool](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearAveragePool) | N | n/a | Supported | @quic-sanirudh | https://github.com/apache/tvm/pull/9017 |
| [com.microsoft.QLinearConcat](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearConcat) | N | n/a | Supported | @anwang2009 | https://github.com/apache/tvm/pull/8907 |
| [com.microsoft.QLinearGlobalAveragePool](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearGlobalAveragePool) | N | n/a | Supported | @quic-sanirudh | https://github.com/apache/tvm/pull/9017 |
| [com.microsoft.QLinearLeakyRelu](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearLeakyRelu) | N | n/a | Supported | @gayatripk1  | https://github.com/apache/tvm/pull/9063 |
| [com.microsoft.QLinearMul](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearMul) | N | n/a | Supported | @anwang2009 | https://github.com/apache/tvm/pull/8773 |
| [com.microsoft.QLinearSigmoid](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearSigmoid) | N | n/a | Supported | @arangasa | https://github.com/apache/tvm/pull/9028 |

Ops for supporting ORT dynamic quantization:
| Operator | Standard | Opset | Status | Owner | PR |
|---|---|---|---|---|---|
| [DynamicQuantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#DynamicQuantizeLinear) | Y | 11 | Supported | @mbrookhart | https://github.com/apache/tvm/pull/7802 |
| [com.microsoft.DynamicQuantizeLSTM](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.DynamicQuantizeLSTM) | N | n/a | TODO |  |  |
| [com.microsoft.DynamicQuantizeMatMul]( https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.DynamicQuantizeMatMul) | N | n/a | WIP | @quic-sanirudh  |  |

Other integer ops that might be relevant:
| Operator | Standard | Opset | Status | Owner | PR |
|---|---|---|---|---|---|
| [com.microsoft.MatMulInteger16](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.MatMulInteger16) | Y | n/a | Supported | @abhikran-quic | https://github.com/apache/tvm/pull/9186 |
| [com.microsoft.MatMulIntegerToFloat](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.MatMulIntegerToFloat) | N | n/a  | WIP | @onkar-sima-ai |  |
| [com.microsoft.MulInteger](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.MulInteger) | N | n/a | WIP | @tasmia-rahman  |  |
| [com.microsoft.ReduceSumInteger](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.ReduceSumInteger) | N | n/a | WIP |  @FranckQC  |  |

Other ops:
| Operator | Standard | Opset | Status | Owner | PR |
|---|---|---|---|---|---|
| [com.microsoft.QGemm](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QGemm) | N | n/a | WIP | @rasagna-quic |  |
| [com.microsoft.QLinearReduceMean](https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearReduceMean) | N | n/a | WIP | @avquicinc |  |

### Coordination

Improving the importers can be a good onboarding task for engineers that would like to get a more in-depth exposure to the TVM stack. The goal is that if folks want to claim an operator they can feel reassured that their work won't be deprecated by work that is in flight.

We provide reference PRs that can serve as a template to adding a quantized standard op: https://github.com/apache/tvm/pull/7802 by @mbrookhart. As well as non-standard op from the Microsoft ContribOperators set in ONNXRT: https://github.com/apache/tvm/pull/8773 by @anwang2009.

Please comment in this issue if you'd like to add to Relay ONNX importer coverage so I can update the table.

cc @KJlaccHoeUM9l @ehsanmok

**Comment by tmoreau89** [comment]
Adding @cconvey to the table who is working on `QLinearMatMul`

**Comment by WenheLI** [comment]
@tmoreau89 - Can I try to implement `MatMulInteger` this OP?

**Comment by tmoreau89** [comment]
Also CC-@WenheLI

**Comment by kparzysz-quic** [comment]
Could you add
@avquicinc for com.microsoft.QLinearReduceMean
@quic-sanirudh for com.microsoft.QAveragePool, com.microsoft.QGlobalAveragePool

**Comment by anwang2009** [comment]
@anwang2009 for com.microsoft.QLinearConcat

**Comment by tmoreau89** [comment]
Yes, yes, and yes! Thanks folks!

**Comment by kparzysz-quic** [comment]
Please add @tasmia-rahman for com.microsoft.MulInteger.

**Comment by kparzysz-quic** [comment]
Please add @FranckQC for com.microsoft.ReduceSumInteger

**Comment by FranckQC** [comment]
Hi everyone.
Could you please add me for com.microsoft.ReduceSumInteger if it's still available?
I might not be able to start working on it right now, but I'd definitely like to work on it as soon as I'm done with something else!

**Comment by tmoreau89** [comment]
Done and done, thanks all!

**Comment by arangasa** [comment]
Hi All, May I sign up for QLinearSigmoid? Thank you.

**Comment by abhikran-quic** [comment]
Hi @tmoreau89, I would like to sign up for com.microsoft.MatMulInteger16. Could you please assign it on my name. Thanks.

**Comment by rasagna-quic** [comment]
Hi @tmoreau89,  could you please add me for com.microsoft.QGemm? 

> Could you add
> @avquicinc for com.microsoft.QLinearReduceMean
> @quic-sanirudh for com.microsoft.QAveragePool, com.microsoft.QGlobalAveragePool
> 
> Edit: we also have volunteers for com.microsoft.QGlobalAveragePool, com.microsoft.QGemm. You can add my name there, since folks need to create github accounts.

**Comment by arangasa** [comment]
> Hi All, May I sign up for QLinearSigmoid? Thank you.

Hi @tmoreau89, May I sign up for com.microsoft.QLinearLeakyRelu as well? (This is for a team member who needs to create github accounts).

**Comment by gayatripk1** [comment]
> > Hi All, May I sign up for QLinearSigmoid? Thank you.
> 
> Hi @tmoreau89, May I sign up for com.microsoft.QLinearLeakyRelu as well? (This is for a team member who needs to create github accounts).

Could you please assign the op QLinearLeakyRelu on my name

**Comment by kparzysz-quic** [comment]
> Hi @tmoreau89, could you please add me for com.microsoft.QGemm?

Yes, please reassign com.microsoft.QGemm to @rasagna-quic.

**Comment by mbrookhart** [comment]
I think I have it updated with the assignments as volunteered in the comments. Thanks, everyone!

**Comment by jcoplin-quic** [comment]
I'll grab com.microsoft.QuantizeLinear @tmoreau89 @kparzysz-quic

**Comment by tmoreau89** [comment]
Thanks @jcoplin-quic I've added you

**Comment by cconvey** [comment]
QLinearMatMul now has a PR: https://github.com/apache/tvm/pull/8952

**Comment by tmoreau89** [comment]
Thanks @cconvey - I've updated the table!

**Comment by avquicinc** [comment]
I am referring this file to see what all ops would get quantized by ONNXRT. https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/registry.py

@mbrookhart :  As per our previous discussion if this resource is required to be added in the ticket please add it. 
Thanks!

**Comment by xintin** [comment]
Hi @tmoreau89,
May I try com.microsoft.DequantizeLinear if it is still available? Thank you.

**Comment by tmoreau89** [comment]
@avquicinc excellent point and many thanks for digging into the registry. I agree that the focus here is to shortlist these ops to the set defined in the registry. To use the example of `QLinearReduceMean` that gets emitted as `QLinearDequantzie->ReduceMean->QLinearQuantize`, there is no need for TVM to support the `QLinearReduceMean` for now. I will therefore as a next task emphasize the short list of ops that we should support to enable any ONNXRT quantized models.

**Comment by tmoreau89** [comment]
Based on this information, I've broken the tables into several categories, the first one being more important given that these are the ops we can confirm are being emitted by ORT static quantization.

I also upon @avquicinc 's suggestion removed duplicate ContribOps that replicate existing standard ops. This trims the list quite a bit.

**Comment by tmoreau89** [comment]
I removed the following ContribOps: QLinearConv, QuantizeLinear, DequantizeLinear because I _think_ they just replicate functionality from the Standard op set. CC-@jcoplin-quic give that you were assigned `QuantizeLinear`.

**Comment by avquicinc** [comment]
Hey @tmoreau89 , I would like to work on QAttention, since at present we don't have much info. if and till when ORT quantization would have support for generating QLinearReduceMean op node.
Also, I think that QAttention falls in the set : ops for supporting ORT dynamic quantization.

**Comment by jcoplin-quic** [comment]
> I removed the following ContribOps: QLinearConv, QuantizeLinear, DequantizeLinear because I _think_ they just replicate functionality from the Standard op set. CC-@jcoplin-quic give that you were assigned `QuantizeLinear`.

@tmoreau89 Yes as I was looking into it I was beginning to suspect the functionality was duplicated. Thanks very much

**Comment by WenheLI** [comment]
Hi, just wondering how should I test my implementation for the op? Where should I write the test cases?
Thanks

**Comment by anwang2009** [comment]
@WenheLI for `MatMulInteger` because it's an onnx native op you can simply remove this line https://github.com/apache/tvm/blob/main/tests/python/frontend/onnx/test_forward.py#L4761 to enable the ONNX test for `MatMulInteger` by default. You can run the enabled test with `pytest tests/python/frontend/onnx/test_forward.py::test_onnx_nodes -k test_matmulinteger`

**Comment by tmoreau89** [comment]
Linking: https://github.com/apache/tvm/pull/9017 - thanks @quic-sanirudh !

**Comment by arangasa** [comment]
Hi @tmoreau89, I've placed a PR [#9028](https://github.com/apache/tvm/pull/9028) for QLinearSigmoid. Just FYI.

**Comment by tmoreau89** [comment]
Thanks @arangasa - I've added it to the table!

**Comment by tmoreau89** [comment]
Also happy to share that `com.microsoft.QLinearGlobalAveragePool` and `com.microsoft.QLinearAveragePool` are supported, thanks @quic-sanirudh for the support

**Comment by quic-sanirudh** [comment]
@tmoreau89 Thanks for your help in reviewing the AveragePool op support quickly. Shall I pick up the com.microsoft.DynamicQuantizeMatMul op next to work on, if no one else has started working on that. If that's an urgently needed op, I can pick something else as well

**Comment by tmoreau89** [comment]
@quic-sanirudh please go ahead and pick `com.microsoft.DynamicQuantizeMatMul` given that no one else has claimed, it. I can mark you down for it.

**Comment by tmoreau89** [comment]
And thanks to @arangasa , https://github.com/apache/tvm/pull/9028 has been merged! `com.microsoft.QLinearSigmoid` is now supported.

**Comment by abhikran-quic** [comment]
Hi @tmoreau89 , I've raised https://github.com/apache/tvm/pull/9186 for `com.microsoft.MatMulInteger16`. Just FYI.

**Comment by tmoreau89** [comment]
Thanks @abhikran-quic , added

**Comment by tmoreau89** [comment]
QLinearMatMul support is now merged! Thank you @cconvey for completing this task

**Comment by tmoreau89** [comment]
@WenheLI and @gayatripk1, is support for `MatMulInteger` and `com.microsoft.QLinearLeakyRelu` still on your plates? Just checking in periodically.

**Comment by tmoreau89** [comment]
Thank you I somehow failed to catch it, I'm adding https://github.com/apache/tvm/pull/9063 to the table, thank you for your contributions.

**Comment by onkar-sima-ai** [comment]
Hi @tmoreau89 I would like to work on `com.microsoft.MatMulIntegerToFloat` , could you please assign in to my name?

**Comment by tmoreau89** [comment]
Thank you @onkar-sima-ai I entered you in the table.

**Comment by jshuhnow** [comment]
Hi @tmoreau89 , I'd like to work on `com.microsoft.QAttention`. Could you assign it to me, if possible?

**Comment by tlopex** [comment]
Do this issue still need to be worked on? @tmoreau89
