### ISSUE TITLE
[PyTorch] NotImplementedError: The following operators are not implemented: ['aten::stft']

### ISSUE THREAD

**Issue by thecooltechguy** [apache/tvm#8877]
Hi,

When I try to compile a Pytorch model that uses `torch.stft`, I'm getting the following error.

`NotImplementedError: The following operators are not implemented: ['aten::stft']`

Will this operator be supported within Apache TVM?

Thanks!

**Comment by masahi** [comment]
This is hard to support, since it probably involves FFT, which is a very challenging op to implement and optimize.

**Comment by masahi** [comment]
stft added in https://github.com/apache/tvm/pull/11190 is implemented in a very naive way (exactly like 1D convolution). I think istft is easy using the similar approach, but fft / ifft with O(nlogn) complexity would be much more challenging.
