### ISSUE TITLE
[PYTORCH] [FRONTEND] Not handled data types

### ISSUE THREAD

**Issue by alprnbg** [apache/tvm#8880]
Greetings. I encounted the following error while converting a jitted torch model, in which I created multiple boolean tensors whose values never change for different inputs. 
```
 File "/home/libraries/tvm/python/tvm/relay/frontend/pytorch.py", line 3330, in from_pytorch
    ret = converter.convert_operators(_get_operator_nodes(graph.nodes()), outputs, ret_name)[0]
  File "/home/libraries/tvm/python/tvm/relay/frontend/pytorch.py", line 2751, in convert_operators
    inputs, _get_input_types(op_node, outputs, default_dtype=self.default_dtype)
  File "/home/libraries/tvm/python/tvm/relay/frontend/pytorch.py", line 675, in zeros
    dtype = _convert_dtype_value(inputs[1])
  File "/home/libraries/tvm/python/tvm/relay/frontend/pytorch.py", line 2824, in _convert_dtype_value
    raise NotImplementedError(msg)
NotImplementedError: Torch data type value 11 is not handled yet.
```
When I looked at tvm/python/tvm/relay/frontend/pytorch.py, I saw that _convert_dtype_value calls _convert_data_type which supports torch.bool, i guess.  So, I added the item (11: "torch.bool") into the convert_torch_dtype_map and my model was converted successfully and it is running correctly in the application now.

Should the dictionary called "convert_torch_dtype_map"  inside _convert_dtype_value function be updated?

**Comment by masahi** [comment]
Yes, you are welcome to send a PR. Please attach a test case.

**Comment by alprnbg** [comment]
Of course. Could you please provide me with an example test case to give some insight about testing procedure?

**Comment by masahi** [comment]
You just need to add a test case in `tests/python/frontend/pytorch/test_forward.py` that demonstrates that your change fixes the problem you had.

**Comment by alprnbg** [comment]
Hi,
The necessary change was actually very simple, however I couldn't find the time to write the unit test then and tbh I couldn't image how the test should look like since what we add is just a dictionary element. I will create a PR, maybe someone else can add an unit test for it.
