### ISSUE TITLE
Compiling random operation in pytorch to random in relay

### ISSUE THREAD

**Issue by bhahn221** [apache/tvm#8881]
First, I generated a network with `torch.rand` using following code
```
import torch
from torch import nn

class Net(nn.Module):
    def __init__(self, input_shape=(-1, 3, 224, 224)):
        super().__init__()
        self.given_shape = input_shape[1:]

    def forward(self, x):
        return x + torch.rand(size=self.given_shape, device=x.device)

net = Net()

traced_net = torch.jit.trace(net, torch.rand(1, 3, 224, 224))
traced_net.save("random-trace.pt")
```

I want to compile this net down to Relay IR.
My initial stab at this looks like this:
```
import tvm
from tvm import relay

import torch
loaded_model = torch.jit.load("random-trace.pt")
relay_model = relay.frontend.from_pytorch(script_module=loaded_model, 
    input_infos=[("input0", (1, 3, 224, 224))])
```

This gave me:
> NotImplementedError: The following operators are not implemented: ['aten::rand']

My next try used `custom_convert_map`
```
import tvm
from tvm import relay

import torch

loaded_model = torch.jit.load("random-trace.pt")
relay_model = relay.frontend.from_pytorch(script_module=loaded_model, 
    input_infos=[("input0", (1, 3, 224, 224))],
    custom_convert_map={
        "aten::rand": relay.op.random.uniform(key=relay.op.random.threefry_key(0), shape=(3, 224, 224))
    }
)
```

However, this gave me:
>   Check failed: (!checked_type.defined()) is false: Expected Array[RelayExpr], but got Array[index 0: Array]

Most recent try was:
```
import tvm
from tvm import relay

import torch

loaded_model = torch.jit.load("random-trace.pt")
def _rand():
    def _impl(inputs, input_types):
        key = relay.op.random.threefry_key(0)
        return relay.op.random.uniform(key=key, shape=(3, 224, 224))
    return _impl

relay_model = relay.frontend.from_pytorch(script_module=loaded_model, 
    input_infos=[("input0", (1, 3, 224, 224))],
    custom_convert_map={
        "aten::rand": _rand()
    }
)
```

However, this gave me:
> AttributeError: <class 'tvm.ir.type.TupleType'> has no attribute dtype

I think I am doing completely wrong here so I am wondering if I can get some help with this.
My question in one line would be "how can I compile networks with `torch.rand` or `torch.randn`?"

**Comment by masahi** [comment]
Since the call `torch.rand(size=self.given_shape, device=x.device)` doesn't depend on the input, it should be pre-computed in the constructor. That way there is no need to convert torch rand to relay rand.
