### ISSUE TITLE
[Bug] Error when compiling a ONNX model with Split operator

### ISSUE THREAD

**Issue by luyaor** [apache/tvm#8889]
##  Description

When compiling following model with TVM, it will error on parsing. I think it is because Split operation in ONNX specification make some changes from previous version to current version (move split from attributes to inputs). Check here: [current](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Split) and [previous](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Split-1). Correponding code is [here](https://github.com/apache/tvm/blob/400baf2b32d460497c3c65ebb50666536783d49e/python/tvm/relay/frontend/onnx.py#L1360).

 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/7541296/131540675-ae6c9c55-ee6f-415f-b433-faec095342ab.png">

The model(with ONNX as frontend) with error is as follows, check bug.onnx in 
[bug9.zip](https://github.com/apache/tvm/files/7085413/bug9.zip)

## Error Log

```
Traceback (most recent call last):
  File "doublecheck.py", line 40, in <module>
    mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 2806, in from_onnx
    mod, params = g.from_onnx(graph, opset, freeze_params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 2613, in from_onnx
    op = self._convert_operator(op_name, inputs, attr, opset)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 2721, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/onnx.py", line 1130, in _impl_v1
    return AttrCvt("split", ignores=["split"])(inputs, attr, params)
  File "/Users/luyaor/Documents/tvm/python/tvm/relay/frontend/common.py", line 430, in __call__
    return get_relay_op(op_name)(*inputs, **new_attrs)
TypeError: split() got multiple values for argument 'indices_or_sections'
```

## How to reproduce

```
python check.py
```

### Environment

Python3, with tvm, onnx

tvm version: [`c31e338`](https://github.com/apache/tvm/commit/c31e338d5f98a8e8c97286c5b93b20caee8be602) Wed Dec 9 14:52:58 2020 +0900

1. Download [bug9.zip](https://github.com/apache/tvm/files/7085413/bug9.zip)

2. Run `python check.py`.

Hi @jwfromm , please check it out! Thanks!

**Comment by AndrewZhaoLuo** [comment]
I believe this is due to positional arguments being overloaded in kwargs

**Comment by AndrewZhaoLuo** [comment]
Nope this is due to the fact that split operator is not dynamic
