### ISSUE TITLE
[Tracking][Contrib] Known failing unit tests

### ISSUE THREAD

**Issue by Lunderberg** [apache/tvm#8901]
### Summary

Some unit tests were unintentionally disabled in CI, and so regressions weren't been caught.  These tests didn't run on the `ci_cpu` image, because they lacked either GPU hardware or python packages required to run.  They didn't run on the `ci_gpu` image, because they weren't marked with `tvm.testing.uses_gpu`.  PR #8902 allows the tests to run, and marks tests with regressions as expected failures.  These expected failures should be resolved to restore full functionality.

### Status

| File                   | Unit test            | Status | Owner | PR     |
|------------------------|----------------------|--------|-------|--------|
| test_tensorrt.py       | test_dynamic_reshape | DONE   |       | #11203 |
| test_tensorrt.py       | test_alexnet         | DONE   |       | #11203 |
| test_tensorrt.py       | test_resnet18_v1     | DONE   |       | #11203 |
| test_tensorrt.py       | test_resnet18_v2     | DONE   |       | #11203 |
| test_tensorrt.py       | test_squeezenet      | DONE   |       | #11203 |
| test_tensorrt.py       | test_mobilenet       | DONE   |       | #11203 |
| test_tensorrt.py       | test_mobilenet_v2    | DONE   |       | #11203 |
| test_tensorrt.py       | test_vgg11           | DONE   |       | #11203 |
| test_tensorrt.py       | test_densenet121     | DONE   |       | #11203 |
| test_tensorrt.py       | test_dynamic_offload | DONE   |       | #11203 |
| test_coreml_codegen.py | test_annotate        | TODO   |       |        |

**Comment by mikepapadim** [comment]
@Lunderberg I am tracking down the TRT BYOC and I figure out the issue with these tests. It is the mxnet importer plus a guard `ICHECK` on the TRT builder. I am having a small patch fixing it, but it also switches to import these models in `onnx`. The only issue is that to download the models in `onnx` format from GitHub during CI requires the LFS download instead.

**Comment by mbs-octoml** [comment]
All the test_tensorrt.py tests are running except one which deserves a separate issue.
