### ISSUE TITLE
[VOTE] Adopt New Code Review Guideline

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#8928]
Dear Community:

This is a formal vote to adopt the proposed improvements to the code review guidelines. Please see the proposed improvements here  https://discuss.tvm.apache.org/t/improve-code-review-guideline/10898

This is a formal voting thread for the community to adopt the improvements.

Please vote

Vote:
 +1
 0 - I don't feel strongly about it, but don't object
-1 - because..

The VOTE will open for a week.

This thread is mirrored to dev@, please vote by replying to this thread

**Comment by masahi** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by comaniac** [comment]
+1

**Comment by denise-k** [comment]
+1

**Comment by mdw-octoml** [comment]
+1

**Comment by zxybazh** [comment]
+1

**Comment by tmoreau89** [comment]
+1

**Comment by electriclilies** [comment]
+1

**Comment by YuchenJin** [comment]
+1

**Comment by areusch** [comment]
+1

**Comment by leandron** [comment]
+1

**Comment by Hzfengsy** [comment]
+1

**Comment by bgchun** [comment]
+1

**Comment by jcf94** [comment]
+1

**Comment by mehrdadh** [comment]
+1

**Comment by Mousius** [comment]
+1

**Comment by Johnson9009** [comment]
+1

**Comment by gromero** [comment]
+1

**Comment by kparzysz-quic** [comment]
+1

**Comment by csullivan** [comment]
+1

**Comment by jroesch** [comment]
+1

**Comment by tqchen** [comment]
https://github.com/apache/tvm/issues/8997
