### ISSUE TITLE
[CI Problem][FLAKY] Possible flaky ONNX test (nan): test_all_reduce_funcs[cuda]

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#8965]
This happened on my PR:
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-8715/27/pipeline

**Comment by masahi** [comment]
cc @mbrookhart @AndrewZhaoLuo

**Comment by AndrewZhaoLuo** [comment]
This one seems we just need to bump the tolerances. The nans match and we do have nan_equal flag on for `assert_allclose`
