### ISSUE TITLE
[Bug][VM] If not allocate on stack, VM runtime cannot work？

### ISSUE THREAD

**Issue by zhanghaohit** [apache/tvm#8977]
In [`src/tir/transforms/lower_tvm_builtin.cc`](https://github.com/apache/tvm/blob/f6a404447406f91ddf6195ac044dc1f0b0e867e7/src/tir/transforms/lower_tvm_builtin.cc#L116)

```c++
    if (device_type_.defined()) {
      if (const auto* dev_type = device_type_.as<IntImmNode>()) {
        if (dev_type->value == kDLCPU) {
          int32_t constant_size = op->constant_allocation_size();
          if (constant_size > 0 && constant_size * nbytes < runtime::kMaxStackAlloca) {
            return stmt;
          }
        }
      }
    }
```

If the condition `if (constant_size > 0 && constant_size * nbytes < runtime::kMaxStackAlloca)` is not true, the generated IR cannot work in VM runtime. Please see the detailed explanation here #8274.

The bug is not triggering any problem for now, since this condition may be always true in our test. I'm not very sure this is a bug, but we need deeper investigation on this.

**Comment by mbrookhart** [comment]
This is the test that fails in the VM without this code: https://github.com/apache/tvm/pull/9019

**Comment by masahi** [comment]
What is the status of this issue?
