### ISSUE TITLE
[Tracking Issue] SiLU op supported

### ISSUE THREAD

**Issue by jinfagang** [apache/tvm#9037]
Will it considered to support?

**Comment by masahi** [comment]
If you are asking about PyTorch SiLU, it is already supported. https://github.com/apache/tvm/pull/8753

**Comment by jinfagang** [comment]
@masahi Why I build master serveral days ago and I can not pass silu op when tvm build from torchscript model?

**Comment by jinfagang** [comment]
this MR is 14 Aug
