### ISSUE TITLE
[Docs] tvmc call tensorrt partition command line

### ISSUE THREAD

**Issue by luohao123** [apache/tvm#9086]
Does tvmc supports call tensorrt target compile for model generate on cuda? 

I currently tuning a model, the different hardware performance:

CPU: 1s
GPU (cuda): 200ms
TensorRT: unknown

Pytorch: 20ms

How to make GPU speed comparable with pytorch? No matter than using cuda or TensorrT

**Comment by areusch** [comment]
@luohao123 could you raise this on our discussion forum, discuss.tvm.ai? we currently reserve the TVM issue tracker for concrete bugfixes.
