### ISSUE TITLE
[CI] Update ci-cpu image to 20210921-225913-92ca78275

### ISSUE THREAD

**Issue by jtuyls** [apache/tvm#9136]
- [ ] S0. Reason: Update PyXIR dependency to v0.3.1 for testing https://github.com/apache/tvm/pull/8815

- [ ] S1. Tag of nightly build: TAG. Docker hub: https://hub.docker.com/layers/tlcpackstaging/ci_cpu/20210921-225913-92ca78275/images/sha256-b39fe1a9f8778ec315dfce1fb926887a8268a35a770b5ca9840dfe0314380a4e

- [ ] S2. The nightly is built on TVM commit: https://github.com/apache/tvm/commit/92ca78275187ad4db5536a5794d83394c0769cc8. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/51/pipeline/54

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...   Do I have to raise a PR for this on https://github.com/apache/tvm/tree/ci-docker-staging?

- [ ] S4. Retag 20210921-225913-92ca78275 to v0.78:
```
docker pull tlcpackstaging/ci_cpu:20210921-225913-92ca78275
docker tag tlcpackstaging/ci_cpu:20210921-225913-92ca78275 tlcpack/ci-cpu:v0.78
docker push tlcpack/ci-cpu:v0.78
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the ci-cpu version on Jenkins

 @jroesch @areusch @tqchen, could you help with this?

**Comment by Mousius** [comment]
Hi @jtuyls,

Is it possible to update this to `20210929-225912-da5b4fbfe` to also get the fixes in https://github.com/apache/tvm/issues/9158?

**Comment by areusch** [comment]
let us move this effort to #9158
