### ISSUE TITLE
[CI Problem][Flaky] test_meta_schedule_rpc_runner_exception

### ISSUE THREAD

**Issue by Lunderberg** [apache/tvm#9161]
### Branch/PR Failing

PR #9151, which was based on the main branch, and only had changes in an unrelated unit test.

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9151/1/pipeline/#step-244-log-1263

### Flakiness

Jenkins logs show `tests/python/unittest/test_meta_schedule_runner.py::test_meta_schedule_rpc_runner_exception` failing to establish a network connection with the tracker.  I've only seen this particular test fail the one time.  After restarting the CI with no changes, the test passed.

**Comment by junrushao1994** [comment]
Should be fixed by #9172
