### ISSUE TITLE
[Tracking Issue] 请问下tvm runtime c++是怎么调试的？不是指tvm源码，tvm生成的cuda c++的so怎么debug？生成了-g的so但是，gdb跟不进去

### ISSUE THREAD

**Issue by sunshineywz123** [apache/tvm#9182]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### This issue is to track progress for FEATURE NAME
- [ ] P1. Title of this piece of the feature (PR link if available)

**Comment by comaniac** [comment]
Please use English for better participation, and post your question to the forum.

**Comment by tqchen** [comment]
Please ask the question on https://discuss.tvm.apache.org/
