### ISSUE TITLE
[Tracking Issue] C Device API implementation

### ISSUE THREAD

**Issue by areusch** [apache/tvm#9183]
### This issue is to track progress for C Devicea API
- [x] https://github.com/apache/tvm-rfcs/pull/31

**Comment by areusch** [comment]
cc @Mousius

**Comment by tqchen** [comment]
We should perhaps close this tracking issue?

**Comment by areusch** [comment]
we still have more to do on this for Heterogeneous AOT, though we haven't RFC'd the remainder. we could close this if you prefer to.
