### ISSUE TITLE
[Docs] Rust TVM API doc link broken

### ISSUE THREAD

**Issue by rachitnigam** [apache/tvm#9217]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Documentation Title & Type

Rust TVM Crate documentation: https://github.com/apache/tvm/tree/main/rust/tvm

### Additions/Changes Requested

Links to the various API documentation are broken. For example:

> You can find the API Documentation here.

Which points to the broken link: https://tvm.apache.org/docs/api/rust/tvm/index.html

I'm not sure where the API documentation is actually hosted to can't provide a fix.

cc @ehsanmok

**Comment by Yevgnen** [comment]
Where can I read the doc now?

**Comment by areusch** [comment]
@Yevgnen i don't think we publish rust docs right now due to a problem generating them in CI. I think @jroesch might take a stab at re-enabling them, or if you'd like to take a crack at it, feel free to send a PR.
