### ISSUE TITLE
[Bug] CMake Error at CMakeLists.txt:605 (gtest_discover_tests): [cmake]   Unknown CMake command "gtest_discover_tests".

### ISSUE THREAD

**Issue by WenguoLi** [apache/tvm#9239]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

What you were expecting

### Actual behavior

What actually happened

### Environment

Any environment details, such as: Operating System, TVM version, etc

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

**Comment by huajsj** [comment]
once the cmake version is lower then 3.10 or get linked into a old version cmake,  user may see "gtest_discover_tests", use `which cmake` can help for trouble shooting, and update cmake can fix the said issue.

**Comment by areusch** [comment]
closing as we either don't have enough data but suspect the version of cmake used was too old. feel free to re-open if there is another cause.
