### ISSUE TITLE
[CI Image] Update ci_cpu to v0.79

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#9296]
- [x] S0. Reason: Upcoming Conv2d support in CMSIS NN (https://github.com/apache/tvm/issues/8646) and optimising the AOT tests (https://github.com/apache/tvm/pull/9271)

- [x] S1. Tag of nightly build: `20211004-225913-779a50629`. Docker hub: https://hub.docker.com/layers/tlcpackstaging/ci_cpu/20211004-225913-779a50629/images/sha256-aef4438e0a91d8b16a5da96f4c1885a1de8f386612077519dd491fce9b5b97d6?context=explore

- [x] S2. The nightly is built on TVM commit: `95a20315d0d3403e5eea3bfe6ed5e942a51b169d`. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/77/pipeline

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...

- [ ] S4. Retag `20211004-225913-779a50629` to `v0.79`:
```
docker pull tlcpackstaging/ci_cpu:20211004-225913-779a50629
docker tag tlcpackstaging/ci_cpu:20211004-225913-779a50629 tlcpack/ci-cpu:v0.79
docker push tlcpack/ci-cpu:v0.79
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the `ci-cpu` version on Jenkins

**Comment by Mousius** [comment]
CC @ashutosh-arm @areusch

**Comment by areusch** [comment]
this tag isn't validated and it looks like we've been busted for a bit. investigating

**Comment by u99127** [comment]
S2 suggests only ci_gpu is busted as I pointed on discord - what am I missing @areusch  ?

**Comment by leandron** [comment]
After some issues with other images such as `ci_i386` and `ci_gpu`, I'm taking the task of running an _ad hoc_ job to validate the latest `ci_cpu` (`tlcpackstaging/ci_cpu:20211102-232503-054fff568`) and tag it to be `tlcpack/ci-cpu:v0.79` once it is validated.

**Comment by leandron** [comment]
For record keeping, just to make it clear:

* `tlcpackstaging/ci_cpu:20211102-232503-054fff568` became `tlcpack/ci-cpu:v0.79`

**Comment by manupa-arm** [comment]
@areusch @tqchen @leandron, do we need to maintain v0.xx versioning ?

**Comment by areusch** [comment]
@manupa-arm it does seem like we could get rid of that. let's spin this into a discuss forum thread so that others can keep track. seems like we could do this but might want to add e.g. `docker/publish.sh` in case someone manually built images.
