### ISSUE TITLE
static library is slower than shared

### ISSUE THREAD

**Issue by Jillian2017** [apache/tvm#9316]
Hi, 
I want to build the tvm library in static format, the default is shared. 
So I change the CMakelish.txt file as follpws:
    #add_library(tvm SHARED ${COMPILER_SRCS} ${RUNTIME_SRCS}) 
    #add_library(tvm_topi SHARED ${TOPI_SRCS}) 
    #add_library(tvm_runtime SHARED ${RUNTIME_SRCS}) 
    add_library(tvm STATIC ${COMPILER_SRCS} ${RUNTIME_SRCS})
    add_library(tvm_topi STATIC ${TOPI_SRCS})
    add_library(tvm_runtime STATIC ${RUNTIME_SRCS})
After cmake and make, I get static library: libtvm.a, libtvm_runtime.a, libtvm_topi.a
But in test, theses static library is slower than shared.
Anyone can help me?

**Comment by masahi** [comment]
We need more details than that. Please open a thread in the discuss forum.
