### ISSUE TITLE
[CI Problem][Possible Falky Test] tests/python/frontend/tensorflow/test_forward.py::test_forward_resnetv2 

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#9322]
### Branch/PR Failing

https://github.com/apache/tvm/pull/9274

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9274/6/pipeline

### Flakiness

I tested this locally multiple times and it was fine. But it failed on CI.

**Comment by masahi** [comment]
I don't remember seeing this for a while.
