### ISSUE TITLE
[TensorRT] <class ‘tvm.relay.op.op_attrs.PadAttrs’> has no attribute pad_value 

### ISSUE THREAD

**Issue by liyaoshun** [apache/tvm#9340]
https://discuss.tvm.apache.org/t/tensorrt-class-tvm-relay-op-op-attrs-padattrs-has-no-attribute-pad-value/11265

How can I fix this bug. Can I change the following code to solve the bug?
    .add_argument("pad_value", "Tensor", "The value to fill the padded area with") // pad_val

**Comment by masahi** [comment]
This was fixed in https://github.com/apache/tvm/pull/9858
