### ISSUE TITLE
[Bug]  PyTorch and TVM loading problem due to conflicting LLVM symbols

### ISSUE THREAD

**Issue by masahi** [apache/tvm#9362]
Apparently, the new PyTorch release crashes with symbols loaded by TVM, so the following trivial code crashes with `invalid pointer Aborted (core dumped)` upon exit:

```
import tvm
import torch
```

We can workaround this by swapping the import order, but as pointed out in https://github.com/apache/tvm/issues/9349#issuecomment-950685224 this may not always be possible.

Another solution is to remove the use of `RTLD_GLOBAL` in https://github.com/apache/tvm/blob/dfe4cebbdadab3d4e6e6ba3951276a51a4ffeaf6/python/tvm/_ffi/base.py#L57

See related issues in other repos that moved away from using `RTLD_GLOBAL`.
https://github.com/dmlc/dgl/issues/2255
https://github.com/pytorch/pytorch/pull/28536
https://github.com/pytorch/pytorch/issues/3059

Is there any particular reason we are using `RTLD_GLOBAL`? @tqchen @areusch

**Comment by tqchen** [comment]
OK, digged a bit into this. I think I know the possible cause. This is because of the conflict of LLVM symbols(due to different versions of LLVM being used). PyTorch also starts to ship with LLVM. To avoid the problem, we need to do two things

- Turn on static linking of LLVM, this will directly link llvm code into libtvm without relying on dynamic library (that creates global symbols) 
   - `set(USE_LLVM "llvm-config --link-static")` 
-  Turn on `set(HIDE_PRIVATE_SYMBOLS ON)`. This will effectively hide the LLVM related symbols when we load globally from pytorch.

I did a quick experiment locally and when we turn both options ON, things are good, and there will be conflict with either option off.

**Comment by masahi** [comment]
Thanks @tqchen, I confirmed that your solution worked on both of my envrionements too, and also both static link and `HIDE_PRIVATE_SYMBOLS` are required.

Also I realized that when I said "I cannot reproduce the original failure anymore" in https://github.com/apache/tvm/issues/9362#issuecomment-951574017, my cmake config is pointing to a different, custom LLVM build that has only static libs. Moreover, apparently these custom libs were built in a way that `HIDE_PRIVATE_SYMBOLS` doesn't need to be enabled.

So no mystery on my end anymore.

**Comment by Jie-KUN** [comment]
@tqchen  I modified the CMakeLists.txt,

 **tvm_option(USE_LLVM "/path/to/llvm-config --link-static" ON)**

**tvm_option(HIDE_PRIVATE_SYMBOLS "Compile with -fvisibility=hidden." ON)**

But I still found the bug "free(): invalid pointer",

**Comment by tqchen** [comment]
@Jie-KUN you need to set those configurations in config.cmake instead of CMakeLists.txt

**Comment by Jie-KUN** [comment]
@tqchen , thank you sincerely. I still have a question that I tried the code "from_pytorch.py". But I always found the tips:

"One or more operators have not been tuned. Please tune your model for better performance. Use DEBUG logging level to see more details."

Is that normal?

**Comment by masahi** [comment]
Yes that's normal. Please post other questions to the discuss forum.

**Comment by Jie-KUN** [comment]
@masahi  Ok， thank you！

**Comment by tqchen** [comment]
cc @leandron @areusch for awareness, let us update tlcpack config

**Comment by leandron** [comment]
>     * Turn on static linking of LLVM, this will directly link llvm code into libtvm without relying on dynamic library (that creates global symbols)
>       * `set(USE_LLVM "/path/to/llvm-config --link-static")`
>     * Turn on `set(HIDE_PRIVATE_SYMBOLS ON)`. This will effectively hide the LLVM related symbols when we load globally from pytorch.

Thanks for letting us know. It seems that currently, `--link-static` is already there in tlcpack. I added https://github.com/tlc-pack/tlcpack/pull/81 for the workaround discussed here.

**Comment by tqchen** [comment]
reopen, can be closed once we updated the installation guide
