### ISSUE TITLE
[Bug] autotvm.measure.MeasureResult object is not printable

### ISSUE THREAD

**Issue by jeromeyan** [apache/tvm#9403]
The autotvm.measure.MeasureResult is not printable

### Expected behavior

as the purpose of method __repr__ of MeasureResult, we expect the MeasurementResult(namedtuple) to print the detailed attributes.

### Actual behavior

When trying to print(measureResultObj), got the following TypeError, unsupported "in" operation

  File "/usr/lib/python3.8/enum.py", line 352, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumMeta'

### Environment

Linux, TVM commit : e9a66a1a1648b7e06257cc405a3f842a78c23bd9

### Steps to reproduce

Quite easy with the following code, the main issue is with the 2nd parameter, the others are just given None

from tvm.autotvm.measure import MeasureResult
mr = MeasureResult(None, 0, None, None)
print(mr)

**Comment by ZQPei** [comment]
> mr = MeasureResult(None, 0, None, None)

It should be like this,
```python
from tvm import autotvm
mr = MeasureResult(None, autotvm.measure.measure.MeasureErrorNo.NO_ERROR, None, None)
```
