### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by guli333** [apache/tvm#9455]
in my model`s json file I have    
```
 {
      "op": "MakeLoss",
      "name": "makeloss0", 
      "inputs": [[1149, 0, 0]]
    }
```

When i am trying to use this model I am getting the following issue:

```
tvm.error.OpNotImplemented: One or more operators are not supported in frontend MXNet:
MakeLoss: 1
```

but as I see in the code, the make_loss function is implemented. 

```
def _mx_make_loss(inputs, attrs):
    # while doing inference make_loss does not have any effect
    # and it should be mapped to identity
    return inputs[0]
```
So how can i fix this issue?

**Comment by ttenc** [comment]
Actually you dont need make_loss op for inference, it doesnt have any effect at all.

**Comment by comaniac** [comment]
This op is called `make_loss` in MXNet instead of `MakeLoss`. Also please post the similar questions to the discuss forum in the future with proper titles.
