### ISSUE TITLE
[Docs][bug] legacy redirect for docs not working as expected

### ISSUE THREAD

**Issue by denise-k** [apache/tvm#9463]
I recently stumbled upon an [old link](https://tvm.apache.org/docs/dev/index.html) to the TVM developer documentation which is still broken.

`legacy_redirect.py` is supposed to [redirect this link](https://github.com/apache/tvm/blob/main/docs/legacy_redirect.py#L31) to a [valid documentation page](https://tvm.apache.org/docs/arch/index.html):
```
legacy_redirects = [
    ...
    ["dev/index.html", "../arch/index.html"],
    ...
]
```

Unfortunately, that's not working as expected. 😢 

![image](https://user-images.githubusercontent.com/50588693/140599369-0b29bb11-c7bf-488c-b30a-798969bf2ac4.png)

This is happening in multiple cases within the `legacy_redirects` list.

**Comment by tqchen** [comment]
Should work now, was due to delayed update of the docs
