### ISSUE TITLE
[Bug] tvm.micro' has no attribute 'get_microtvm_template_projects

### ISSUE THREAD

**Issue by JKANG94** [apache/tvm#9466]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Expected behavior

What you were expecting

### Actual behavior

What actually happened

### Environment

Any environment details, such as: Operating System, TVM version, etc

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

I used microtvm to autotune model, just like this "https://tvm.apache.org/docs/how_to/work_with_microtvm/micro_autotune.html". But I met an error tvm.micro' has no attribute 'get_microtvm_template_projects.

**Comment by baibeta** [comment]
https://github.com/apache/tvm/commit/54019b943623409b866d898a4c696a617671867b

This API is mereged recently. Did you update local code base? I just try and it works.

**Comment by mehrdadh** [comment]
@JKANG94 If you used TVM head and enable microtvm (USE_MICRO), this API would work fine.

**Comment by JKANG94** [comment]
@baibeta  I just update local code, it works.
