### ISSUE TITLE
[Bug] Check failed: (reporter->AssertEQ(data->shape[data->shape.size() - 1], weight->shape[1])) is false: DenseRel: input dimension doesn’t match, data shape=[1, 512], weight shape=[512, 1000]

### ISSUE THREAD

**Issue by 17818587795** [apache/tvm#9496]
![image](https://user-images.githubusercontent.com/49740899/141278738-d1f13eb5-a194-44b9-94ab-8d92d42650ba.png)
Convert torch model error

**Comment by Liuz233** [comment]
Excuse me, how do you solve this problem. I meet the problem too.

**Comment by wenyi-li** [comment]
Excuse me, how do you solve this problem? I have the problem too.
