### ISSUE TITLE
[CI Image] Update ci_arm to 0.07

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#9502]
- [ ] S0. Reason: Update to ACL 21.08 from #9396

- [ ] S1. Tag of nightly build: 20211112-082025-6159b8e92. Docker hub: https://hub.docker.com/layers/tlcpackstaging/ci_arm/20211112-082025-6159b8e92/images/sha256-947afe5907b88accd775e89450a352b6d4bcf29b71a19d7308f6bd120a326a35?context=explore

- [ ] S2. The nightly is built on TVM commit: 6159b8e925bb77324ecd488e161a6c368b9d4ce7. Detailed info can be found here: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-rebuild/detail/daily-docker-image-rebuild/109/pipeline/59

- [ ] S3. Testing the nightly image on ci-docker-staging: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/ci-docker-staging/...

- [ ] S4. Retag 20211112-082025-6159b8e92 to 0.07:
```
docker pull tlcpackstaging/ci_arm:20211112-082025-6159b8e92
docker tag tlcpackstaging/ci_arm:20211112-082025-6159b8e92 tlcpack/ci-arm:0.07
docker push tlcpack/ci-arm:0.07
```

- [ ] S5. Check if the new tag is really there: https://hub.docker.com/u/tlcpack

- [ ] S6. Submit a PR updating the ci-arm version to 0.07 on Jenkins

**Comment by Mousius** [comment]
CC @leandron @areusch

**Comment by leandron** [comment]
Superseded by #9762
