### ISSUE TITLE
[VOTE] Release Apache TVM v0.8.0.rc0

### ISSUE THREAD

**Issue by junrushao1994** [apache/tvm#9504]
Dear TVM community,

This is a call for vote to release Apache TVM version 0.8.0.  This is a major release with many new features and improvement. All users of Apache TVM 0.7 are advised to upgrade. The release is co-managed by Wuwei Lin (@vinx13).

Link to release notes: 
https://github.com/apache/tvm/releases/tag/v0.8.0.rc0 

Link to release candidate: 
https://dist.apache.org/repos/dist/dev/tvm/tvm-v0.8.0-rc0/

The vote will be open for at least 72 hours. Everyone is welcomed to vote. Please vote by replying to this thread explicitly.

+1 = approve
+0 = no opinion
-1 = disapprove (provide reason)

NOTE: this thread is being mirrored in dev@

**Comment by tqchen** [comment]
+1 (binding), I checked

Signatures and hashes good
LICENSE, NOTICE
Signatures and hashes
No unexpected binary files
Code compiles and import in python

TQ

**Comment by Hzfengsy** [comment]
+1

**Comment by jiangjiajun** [comment]
+1

**Comment by masahi** [comment]
+1

**Comment by ZihengJiang** [comment]
+1

**Comment by zhuwenxi** [comment]
+1

**Comment by Mousius** [comment]
+1 - Let's get this done and get ready for 0.9! :smile_cat:

**Comment by comaniac** [comment]
+1

**Comment by vinx13** [comment]
+1

**Comment by electriclilies** [comment]
+1, notice a typo in the overview though-- robust is misspelled as "robost" :laughing:

**Comment by csullivan** [comment]
+1

**Comment by tvm-archiver** [comment]
+1

**Comment by YuchenJin** [comment]
+1

**Comment by mehrdadh** [comment]
+1

**Comment by areusch** [comment]
+1

**Comment by jwfromm** [comment]
+1

**Comment by mshr-h** [comment]
+1

**Comment by junrushao1994** [comment]
Thanks @electriclilies! The typo is fixed :-)

**Comment by vinx13** [comment]
Thanks everyone for voting. The result has been sent out in https://lists.apache.org/thread/4rdndw0n8mz5mbbwz4p2po7h7y0hv4h2
