### ISSUE TITLE
[BUG] NVPTX as a testable device seems to be not supported anymore 

### ISSUE THREAD

**Issue by wrongtest** [apache/tvm#9513]
Hi there. We have been seen strange warning message `NVPTX support not enabled`  during unittests on environment with cuda enabled.  A reproduce script is as below:
```python
import os
from tvm.testing.utils import device_enabled
os.environ["TVM_TEST_TARGETS"]="llvm;nvptx;cuda"
device_enabled("llvm") # True
device_enabled("cuda") # True
device_enabled("nvptx") # False
```

**Comment by ZQPei** [comment]
@wrongtest I do believe https://github.com/apache/tvm/pull/9585 could solve this bug.
