### ISSUE TITLE
[Bug] Set `TVM_BACKTRACE=0` doesn't suppress C++ stacktrace

### ISSUE THREAD

**Issue by junrushao** [apache/tvm#9567]
### Expected behavior

The snippet below should suppress C++ stacktraces, but actually it doesn't. I digged into the codebase but found nowhere the environment variable is used in C++...

```python
TVM_BACKTRACE=0 python main.py
# main.py is any code that triggers TVMError
```

### Actual behavior

The environment variable isn't in effect

### Environment

OS version is not relevant. TVM version is the current HEAD (328d7c7c09763b8532a6a7359a5dc6d5ee6c8a98)

### Steps to reproduce

Provided in the previous section.

**Comment by ZQPei** [comment]
Seems like for now tvm doesn't support suppressing c++ backtrace with system environment. It can only be suppressed by set(USE_LIBBACKTRACE OFF).

**Comment by ZQPei** [comment]
In my opinion, supporting C++ backtrace suppression by environment might slowdown tvm runtime a little bit. Is it necessary? Or we can just delete the TVM_BACKTRACE in python?

**Comment by junrushao1994** [comment]
@ZQPei We have an assumption that if an error is raised, it’s probably the slow path where we Dian waste reasonable amount of time. If plowing this assumption, the necessary time to read an environment variable is probably acceptable:-)

**Comment by ZQPei** [comment]
I agree. To step further, it would be better to have a `TVM_LOG_LEVEL` environment to control the output of the log level in C++ side. What do you think?

**Comment by junrushao1994** [comment]
@ZQPei I think we already have `TVM_LOG_DEBUG`, but not sure how to use it properly

**Comment by ZQPei** [comment]
> I think we already have `TVM_LOG_DEBUG`, but not sure how to use it properly

`TVM_LOG_DEBUG` is a macro trigger that will send more debugging info if we set it to 1. Seems like it has nothing to do with the tvm logger level.

BTW, is it necessary to create a RFC of adding a `TVM_LOG_LEVEL` environment in the TVM discuss?

**Comment by junrushao1994** [comment]
@ZQPei Sorry for the late reply! That will be very helpful if we could potentially unify these environment variables. Please send an RFC and I'm more than happy to help!

**Comment by ZQPei** [comment]
@yongsun Thank you! I will try to submit an RFC as soon as possible.
