### ISSUE TITLE
[CI Problem]  Crashing with `No such property: docker_type for class: groovy.lang.Binding`

### ISSUE THREAD

**Issue by leandron** [apache/tvm#9591]
CI is crashing with `No such property: docker_type for class: groovy.lang.Binding` message, due to #9556. The potential fix is #9588.

There is a process issue here, because we can't _just merge_ the fix, as it is never going to pass CI, given it is a fix for CI.

We need some help from @tqchen @jroesch @areusch to see how to proceed in this situation, and the implications of just manually `git push` into `main`. Can you please help?

cc @manupa-arm @Mousius @grant-arm

**Comment by tqchen** [comment]
noticed this as well. Note that unfortunately we all do not have perm to force push to main. We will need to figure out a way, perhaps change jenkins policy temporarily to trust Jenkinsfile from PR from certain users

**Comment by tqchen** [comment]
Background: right now the pipeline policy only takes effect after the file is merged into main(to tighten up control), as a result, changes to Jenkinsfile would require a push to ci-docker-staging first

**Comment by junrushao1994** [comment]
Currently TVM DevOps procedure is mostly implicitly specified by convention, and ideally it would probably be desirable to have some explicit documentation on the guidelines

**Comment by leandron** [comment]
> 

Oh I didn't know we don't have access to manually push to main. So I guess you have set the Jenkins configuration in the job to trust certain users and the current job on #9592 is running with the actual proposed Jenkinsfile?

So, given that, we just need for CI to complete and then merge that fix?

**Comment by tqchen** [comment]
#9592
