### ISSUE TITLE
[CI] Clean Jenkins workspace on a new run

### ISSUE THREAD

**Issue by driazati** [apache/tvm#9610]
Jenkins doesn't clean the workspace on each new run. This gives an easy way to get quick rebuilds since most of CMake's previous run is still around. However, it also leads to issues such as https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9584/4/pipeline/#step-35-log-1110. We should be clearing away everything except the build folder to minimize these types of issues

**Comment by tqchen** [comment]
One thing to note is that re-download all test data can be costly and would also cause the remote data server to timout and block the ci node, so we need to enable some folders to be cached.

**Comment by mehrdadh** [comment]
happened here as well: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9631/3/pipeline#step-35-log-1121

**Comment by areusch** [comment]
investigating and i see two things:
1. the workspace is wiped out on that node
2. it seems like we are now creating workspaces per-PR, e.g the paths are like `/home/octo.aws.c4/workspace/tvm_PR-9631`, vs before they were just `/home/octo.aws.c4/workspace/exec_0`. so now i'm wondering if we are in fact reusing build dirs anymore.

**Comment by areusch** [comment]
ignore my previous comment about workspaces--what is [reported](https://ci.tlcpack.ai/job/tvm/job/PR-9631/3/ws/) in Jenkins on the PR doesn't match what docker/bash says:
```
+ docker/bash.sh tlcpack/ci-lint:v0.67 ./tests/scripts/task_lint.sh
REPO_DIR: /home/octo.aws.c4/workspace/exec_2/tvm/sanity
DOCKER CONTAINER NAME: tlcpack/ci-lint:v0.67
```

**Comment by areusch** [comment]
seeing no sanity-check jobs running on `octo.aws.c4.54.184.207.71`, ran:
```
println "rm /home/octo.aws.c4/workspace/exec_1/tvm/sanity/.git/clang-format-index.lock".execute().text
```

in Jenkins script console.

**Comment by areusch** [comment]
also did the same on octo.aws.c4.44.242.35.246
```
println "rm /home/octo.aws.c4/workspace/exec_2/tvm/sanity/.git/clang-format-index.lock".execute().text
```
in Jenkins script console.

I suspect switching to an approach where we pull the build/ dir from a shared cache or use sccache and wiping the workspace is the best use of our time in trying to fix issues like this.

**Comment by driazati** [comment]
this hasn't come up in a while and with autoscaled nodes it's not really a problem
