### ISSUE TITLE
当我make的时候出现该错误，无论是从源码安装还是在docker内安装

### ISSUE THREAD

**Issue by vision-zhu** [apache/tvm#9645]
完全按照源码安装方式，只更改设置了set(USE_CUDA ON)
Ubuntu20.04，CUDA11.0，cudnn8，python3.8

hnu@hnu:~/ZDS/PRJ/tvm/build$ make -j16
Scanning dependencies of target project_libbacktrace
Scanning dependencies of target tvm_libinfo_objs
Scanning dependencies of target tvm_objs
[  0%] Creating directories for 'project_libbacktrace'
[  0%] Building CXX object CMakeFiles/tvm_libinfo_objs.dir/src/support/libinfo.cc.o
[  0%] No download step for 'project_libbacktrace'
[  1%] No checkout step for 'project_libbacktrace'
[  1%] No patch step for 'project_libbacktrace'
[  1%] No update step for 'project_libbacktrace'
[  1%] Performing configure step for 'project_libbacktrace'
/bin/sh: 1: /home/hnu/PRJ/tvm/cmake/libs/../../3rdparty/libbacktrace/configure: not found
make[2]: *** [CMakeFiles/project_libbacktrace.dir/build.make:109: libbacktrace/src/project_libbacktrace-stamp/project_libbacktrace-configure] Error 127
make[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/project_libbacktrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/int_set.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/detect_linear_equation.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/bound_deducer.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/analyzer.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/const_int_bound.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/auto_schedule.cc.o

......
[ 88%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/opt/build_metal_off.cc.o
[ 88%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/opt/build_rocm_off.cc.o
[ 89%] Building CXX object CMakeFiles/tvm_objs.dir/src/relay/backend/contrib/codegen_c/codegen.cc.o
[ 89%] Building CXX object CMakeFiles/tvm_objs.dir/src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc.o
[ 89%] Building CXX object CMakeFiles/tvm_objs.dir/src/relay/backend/contrib/example_target_hooks/target.cc.o
[ 89%] Building CXX object CMakeFiles/tvm_objs.dir/src/relay/backend/contrib/example_target_hooks/tir_to_runtime.cc.o
[ 89%] Building CXX object CMakeFiles/tvm_objs.dir/src/contrib/hybrid/codegen_hybrid.cc.o
[ 89%] Built target tvm_objs
make: *** [Makefile:130: all] Error 2

**Comment by masahi** [comment]
Probably you didn't clone submodules. (`git clone --recursive`).

**Comment by SubjectNoi** [comment]
No, I encounter this problem even if my "3rdparty/libbacktrace/configure" **PHYSICALLY EXISTS ON MY HARD DISK**.

**Comment by vision-zhu** [comment]
> No, I encounter this problem even if my "3rdparty/libbacktrace/configure" **PHYSICALLY EXISTS ON MY HARD DISK**.

你好，我解决了这个问题：在clone了该仓库之后，必须单独clone这个第三方仓库：libbacktrace，并覆盖掉tvm下的3rdparty/libbacktrace仓库，最后成功安装的
