### ISSUE TITLE
[Bug] AttributeError: module 'tvm' has no attribute 'micro' when running `python -m tvm.driver.tvmc --help`

### ISSUE THREAD

**Issue by sky-fun** [apache/tvm#9679]
### Expected behavior

use `python -m tvm.driver.tvmc --help` and get help information

### Actual behavior

get `AttributeError: module 'tvm' has no attribute 'micro'` from `import tvm.micro.project as project` in python/tvm/driver/tvmc/runner.py

### Environment

ubuntu18.04
python3.6.5
commit:c945b24c3693c8859b07d1af682f986e21a6d6bc

### Steps to reproduce

follow the  https://tvm.apache.org/docs/install/from_source.html install step
and use Method 1 in https://tvm.apache.org/docs/install/from_source.html#python-package-installation

it seems that i got `AttributeError` instead of `ImportError`  so the code cannot except it.

**Comment by leandron** [comment]
There was an issue recently fixed by @gromero that addresses something similar to what you're seeing.

In the meantime, would you want to workaround this by setting `USE_MICRO ON` on your config.cmake?

**Comment by mehrdadh** [comment]
@sky-fun PR is merged. Please verify that this PR fixed your issue and then we can close this.

**Comment by sky-fun** [comment]
@mehrdadh i test the latest code, and the issue was fixed.
thanks.
