### ISSUE TITLE
Follow up on PR #9631

### ISSUE THREAD

**Issue by mehrdadh** [apache/tvm#9685]
There are few follow ups on PR #9631 that we need to address:
- It's not clear whether we need to do port forwarding/reversing for Android to run HexagonLauncher: https://github.com/apache/tvm/blob/d13e2b6d65a6e5b8bf230175e9be6cfeceb193e0/python/tvm/contrib/hexagon/build.py#L155
- Currently, close function in HexagonLauncher does not fully close the RPC server on Android. We need to investigate more on that: https://github.com/apache/tvm/blob/d13e2b6d65a6e5b8bf230175e9be6cfeceb193e0/python/tvm/contrib/hexagon/build.py#L257

cc @csullivan

**Comment by TejashShah** [comment]
cc @mehrdadh Is this issue addressed or do we need to follow up on this?

**Comment by mehrdadh** [comment]
@TejashShah we can close this issue.
