### ISSUE TITLE
[Docs] An unclear definition of TensorIR

### ISSUE THREAD

**Issue by ZJUGuoShuai** [apache/tvm#9714]
### Tutorial: [Blitz Course to TensorIR](https://tvm.apache.org/docs/tutorial/tensor_ir_blitz_course.html)

I'm learning TVM these days, both from published papers and the amazing official documentations. Quite a few times, I encountered some terms and abbreviations that looks like related things: **TensorIR**, **TIR**, **Tensor-Level IR**.

I guessed that they were the same thing. So I tried to search in the documentation about it. The only thing I found is [Blitz Course to TensorIR](https://tvm.apache.org/docs/tutorial/tensor_ir_blitz_course.html). But the doc still didn't make it clear. It only described how to use TVMScript to create, build and run an IRModule, as well as how IRModules can be transformed by Schedules.

I still don't know what is TensorIR, TIR or Tensor-Level IR. I guess `tir::PrimFunc` is a kind of TensorIR? I don't know the precise definition.

BTW, the doc [Working with Operators Using Tensor Expression](https://tvm.apache.org/docs/tutorial/tensor_expr_get_started.html) is quite easy to understand what is **Tensor Expression** by giving a lot of examples. I hope there can be a similar doc explaining what is **TensorIR**.

### Additions/Changes Requested

I hope the documentation can make it clear what is TensorIR.

**Comment by ZJUGuoShuai** [comment]
Finally, I found the RFC of TensorIR: [TensorIR: A schedulable IR for TVM](https://discuss.tvm.apache.org/t/rfc-tensorir-a-schedulable-ir-for-tvm/7872), and it's amazing! It explained the motivation of TensorIR. I begin to understand what it is.

**Comment by junrushao1994** [comment]
CC @Hzfengsy
