### ISSUE TITLE
[CI Image] "libgmock.so" does not exist when build tvm inside vitis-ai-tensorflow container with conda vitis-ai-tensorflow env 

### ISSUE THREAD

**Issue by JasonTryharder** [apache/tvm#9772]
I am following this [thread](https://tvm.apache.org/docs/how_to/deploy/vitis_ai.html#setup-instructions),by running : 
`docker run --workdir /home/jasoncat/CAT/tvm --rm --pid=host --net=host --interactive --tty --env CI_BUILD_HOME=/home/jasoncat/CAT/tvm --env CI_BUILD_USER=jasoncat --env CI_BUILD_UID=1000 --env CI_BUILD_GROUP=jasoncat --env CI_BUILD_GID=1000 --env CI_PYTEST_ADD_OPTIONS= --env CI_IMAGE_NAME=tvm.demo_vitis_ai --volume /home/jasoncat/CAT/tvm:/home/jasoncat/CAT/tvm --volume /home/jasoncat/CAT/tvm/docker:/docker --volume /dev/shm:/dev/shm --volume /opt/xilinx/dsa:/opt/xilinx/dsa --volume /opt/xilinx/overlaybins:/opt/xilinx/overlaybins tvm.demo_vitis_ai`
I was able to get inside the container. 
then build TVM with `conda activate vitis-ai-tensorflow`
![Screenshot from 2021-12-18 16-39-19](https://user-images.githubusercontent.com/54369499/146656157-906f38eb-4b3b-45de-8fc4-5a57ecf28edd.png)

error log file : 
[CMakeOutput.log](https://github.com/apache/tvm/files/7740000/CMakeOutput.log)
[CMakeError.log](https://github.com/apache/tvm/files/7740001/CMakeError.log)

I have tried with conda tensorflow2 env as well, but the reason stil because of the above mentioned file missing leading to cmake test cannot perform. 
Thanks !

**Comment by Shantanu-repo** [comment]
I have the same error, I have tried different machines, different setups. Nothing has worked yet

**Comment by abdulazizm** [comment]
There seems to be an issue in finding GTest cmake package. The temporary workaround that I followed is to edit config.cmake file https://github.com/apache/tvm/blob/92eeef6ddde9b113fd8263f1fc20f08c1c3fea0d/cmake/config.cmake#L359

ORIGINAL: `set(USE_GTEST AUTO)`
UPDATE: `set(USE_GTEST OFF)`
