### ISSUE TITLE
[Installation Problem] 

### ISSUE THREAD

**Issue by 43998213** [apache/tvm#9790]
git clone --recursive https://..............
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Linux
-- Build with RPC support...
-- Build with Graph Executor support...
-- Build with profiler...
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- VTA build with VTA_HW_PATH=/home/clb/github/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
-- Found CUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs/libcuda.so
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
-- Found CUDA_NVRTC_LIBRARY=/usr/local/cuda/lib64/libnvrtc.so
-- Found CUDA_CUDNN_INCLUDE_DIRS=
-- Found CUDA_CUDNN_LIBRARY=
-- Found CUDA_CUBLAS_LIBRARY=/usr/local/cuda/lib64/libcublas.so
-- Found CUDA_CUBLASLT_LIBRARY=/usr/local/cuda/lib64/libcublasLt.so
-- Build with CUDA 10.2 support
-- Link with dynamic LLVM library
-- Found LLVM_INCLUDE_DIRS=/usr/lib/llvm-8/include
-- Found LLVM_DEFINITIONS=-D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LLVM_LIBS=LLVM
-- Found TVM_LLVM_VERSION=80
-- Build with LLVM 8.0.0
-- Set TVM_LLVM_VERSION=80
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=124813fc48c235955f872a81ee4bdd97c4ea192e
-- Found TVM_GIT_COMMIT_TIME=2021-12-21 18:38:00 +0000
-- Performing Test SUPPORT_CXX14
-- Performing Test SUPPORT_CXX14 - Success
-- Autoset: USE_LIBBACKTRACE=ON in Linux
-- Building with libbacktrace...
-- Building with TVM Map...
-- Build with thread support...
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Configuring done
-- Generating done
-- Build files have been written to: /home/clb/github/tvm/build
(face_track01) root@clb-desktop:/home/clb/github/tvm/build# make
Scanning dependencies of target tvm_objs
[  0%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/auto_schedule.cc.o
[  0%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/compute_dag.cc.o
[  0%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/cost_model.cc.o
[  1%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/feature.cc.o
[  1%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/loop_state.cc.o
[  1%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/measure.cc.o
[  1%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/measure_record.cc.o
[  1%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_policy/empty_policy.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_policy/search_policy.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_policy/sketch_policy.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_policy/sketch_policy_rules.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_policy/utils.cc.o
[  2%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_task.cc.o
[  3%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/transform_step.cc.o
[  3%] Building CXX object CMakeFiles/tvm_objs.dir/src/auto_scheduler/utils.cc.o
[  3%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/arg_info.cc.o
[  3%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/builder/builder.cc.o
[  3%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/cost_model/cost_model.cc.o
[  4%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/database/database.cc.o
[  4%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/database/json_database.cc.o
[  4%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/feature_extractor/feature_extractor.cc.o
[  4%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/integration.cc.o
[  4%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/runner/runner.cc.o
[  5%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/schedule_rule/schedule_rule.cc.o
[  5%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/search_strategy/replay_trace.cc.o
[  5%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/search_strategy/search_strategy.cc.o
[  5%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/space_generator/post_order_apply.cc.o
[  5%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/space_generator/space_generator.cc.o
[  6%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/space_generator/space_generator_union.cc.o
[  6%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/task_scheduler/round_robin.cc.o
[  6%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/task_scheduler/task_scheduler.cc.o
[  6%] Building CXX object CMakeFiles/tvm_objs.dir/src/meta_schedule/tune_context.cc.o
[  6%] Building CXX object CMakeFiles/tvm_objs.dir/src/node/container_printing.cc.o
[  7%] Building CXX object CMakeFiles/tvm_objs.dir/src/node/reflection.cc.o
[  7%] Building CXX object CMakeFiles/tvm_objs.dir/src/node/repr_printer.cc.o
[  7%] Building CXX object CMakeFiles/tvm_objs.dir/src/node/serialization.cc.o
[  7%] Building CXX object CMakeFiles/tvm_objs.dir/src/node/structural_equal.cc.o
[  8%] Building CXX object CMakeFiles/tvm_objs.dir/src/node/structural_hash.cc.o
[  8%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/adt.cc.o
[  8%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/affine_type.cc.o
[  8%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/attrs.cc.o
[  8%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/diagnostic.cc.o
[  9%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/env_func.cc.o
[  9%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/error.cc.o
[  9%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/expr.cc.o
[  9%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/function.cc.o
[  9%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/instrument.cc.o
[ 10%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/module.cc.o
[ 10%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/op.cc.o
[ 10%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/span.cc.o
[ 10%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/tensor_type.cc.o
[ 10%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/transform.cc.o
[ 11%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/type.cc.o
[ 11%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/type_functor.cc.o
[ 11%] Building CXX object CMakeFiles/tvm_objs.dir/src/ir/type_relation.cc.o
[ 11%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/analyzer.cc.o
[ 11%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/bound_deducer.cc.o
[ 12%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/canonical_simplify.cc.o
[ 12%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/const_int_bound.cc.o
[ 12%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/detect_linear_equation.cc.o
[ 12%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/domain_touched.cc.o
[ 12%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/int_constraints.cc.o
[ 13%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/int_set.cc.o
[ 13%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/ir_mutator_with_analyzer.cc.o
[ 13%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/iter_affine_map.cc.o
[ 13%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/modular_set.cc.o
[ 13%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/rewrite_simplify.cc.o
[ 14%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/solve_linear_equation.cc.o
[ 14%] Building CXX object CMakeFiles/tvm_objs.dir/src/arith/solve_linear_inequality.cc.o
[ 14%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/autodiff/ad_simplify.cc.o
[ 14%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/autodiff/ad_utils.cc.o
[ 14%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/autodiff/adjoint.cc.o
[ 15%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/autodiff/jacobian.cc.o
[ 15%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/compute_op.cc.o
[ 15%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/create_primfunc.cc.o
[ 15%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/cross_thread_reduction.cc.o
[ 15%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/extern_op.cc.o
[ 16%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/hybrid_op.cc.o
[ 16%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/op_utils.cc.o
[ 16%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/placeholder_op.cc.o
[ 16%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/scan_op.cc.o
[ 16%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/tensor_compute_op.cc.o
[ 17%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/operation/tensorize.cc.o
[ 17%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/auto_inline_elem_wise.cc.o
[ 17%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/bound.cc.o
[ 17%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/graph.cc.o
[ 18%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/message_passing.cc.o
[ 18%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/operation_inline.cc.o
[ 18%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/schedule_dataflow_rewrite.cc.o
[ 18%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/schedule_lang.cc.o
[ 18%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/schedule_ops.cc.o
[ 19%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/schedule_postproc_to_primfunc.cc.o
[ 19%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/schedule/verify_compact_buffer.cc.o
[ 19%] Building CXX object CMakeFiles/tvm_objs.dir/src/te/tensor.cc.o
[ 19%] Building CXX object CMakeFiles/tvm_objs.dir/src/autotvm/feature_visitor.cc.o
[ 19%] Building CXX object CMakeFiles/tvm_objs.dir/src/autotvm/touch_extractor.cc.o
[ 20%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/block_access_region_detector.cc.o
[ 20%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/buffer_access_lca_detector.cc.o
[ 20%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/calculate_workspace.cc.o
[ 20%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/deep_equal.cc.o
[ 20%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/device_constraint_utils.cc.o
[ 21%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/expr_complexity.cc.o
[ 21%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/side_effect.cc.o
[ 21%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/var_touch.cc.o
[ 21%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/verify_gpu_code.cc.o
[ 21%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/verify_memory.cc.o
[ 22%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/analysis/verify_ssa.cc.o
[ 22%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/buffer.cc.o
[ 22%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/data_layout.cc.o
[ 22%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/expr.cc.o
[ 22%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/expr_functor.cc.o
[ 23%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/function.cc.o
[ 23%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/script/script_complete.cc.o
[ 23%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/specialize.cc.o
[ 23%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/stmt.cc.o
[ 23%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/stmt_functor.cc.o
[ 24%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/ir/transform.cc.o
[ 24%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/op/builtin.cc.o
[ 24%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/op/op.cc.o
[ 24%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/op/runtime.cc.o
[ 24%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/analysis/analysis.cc.o
[ 25%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/analysis/verify.cc.o
[ 25%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/block_scope.cc.o
[ 25%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/concrete_schedule.cc.o
[ 25%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/error.cc.o
[ 25%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/instruction.cc.o
[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/annotate.cc.o
[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/block_annotate.cc.o
[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/cache_read_write.cc.o
[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/compute_at.cc.o
[ 26%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/compute_inline.cc.o
[ 27%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/for_kind.cc.o
[ 27%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/get_block_loop.cc.o
[ 27%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/loop_transformation.cc.o
[ 27%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/reduction.cc.o
[ 28%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/primitive/sampling.cc.o
[ 28%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/schedule.cc.o
[ 28%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/state.cc.o
[ 28%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/trace.cc.o
[ 28%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/traced_schedule.cc.o
[ 29%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/schedule/transform.cc.o
[ 29%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/arg_binder.cc.o
[ 29%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/bf16_legalize.cc.o
[ 29%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/bound_checker.cc.o
[ 29%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/combine_context_call.cc.o
[ 30%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/compact_buffer_region.cc.o
[ 30%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/convert_blocks_to_opaque.cc.o
[ 30%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/convert_for_loops_serial.cc.o
[ 30%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/coproc_sync.cc.o
[ 30%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/decorate_device_scope.cc.o
[ 31%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/flatten_buffer.cc.o
[ 31%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/hoist_if_then_else.cc.o
[ 31%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/inject_copy_intrin.cc.o
[ 31%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/inject_double_buffer.cc.o
[ 31%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/inject_prefetch.cc.o
[ 32%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/inject_rolling_buffer.cc.o
[ 32%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/inject_virtual_thread.cc.o
[ 32%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/ir_utils.cc.o
[ 32%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/legalize_packed_calls.cc.o
[ 32%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lift_attr_scope.cc.o
[ 33%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/loop_partition.cc.o
[ 33%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_cross_thread_reduction.cc.o
[ 33%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_custom_datatypes.cc.o
[ 33%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_device_storage_access_info.cc.o
[ 33%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_init_block.cc.o
[ 34%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_intrin.cc.o
[ 34%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_match_buffer.cc.o
[ 34%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_thread_allreduce.cc.o
[ 34%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_tvm_builtin.cc.o
[ 34%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/lower_warp_memory.cc.o
[ 35%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/make_packed_api.cc.o
[ 35%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/make_unpacked_api.cc.o
[ 35%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/merge_dynamic_shared_memory_allocations.cc.o
[ 35%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/narrow_datatype.cc.o
[ 35%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/plan_update_buffer_allocation_location.cc.o
[ 36%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/remap_thread_axis.cc.o
[ 36%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/remove_no_op.cc.o
[ 36%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/rewrite_unsafe_select.cc.o
[ 36%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/simplify.cc.o
[ 36%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/skip_assert.cc.o
[ 37%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/split_host_device.cc.o
[ 37%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/storage_access.cc.o
[ 37%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/storage_flatten.cc.o
[ 37%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/storage_rewrite.cc.o
[ 38%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/tensorcore_infer_fragment.cc.o
[ 38%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/texture_flatten.cc.o
[ 38%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/thread_storage_sync.cc.o
[ 38%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/unify_thread_binding.cc.o
[ 38%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/unroll_loop.cc.o
[ 39%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/update_pointer_storage_scope.cc.o
[ 39%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/transforms/vectorize_loop.cc.o
[ 39%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/usmp/algo/greedy.cc.o
[ 39%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/usmp/analysis/extract_buffer_info.cc.o
[ 39%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/usmp/transform/convert_pool_allocations_to_offsets.cc.o
[ 40%] Building CXX object CMakeFiles/tvm_objs.dir/src/tir/usmp/utils.cc.o
[ 40%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/broadcast.cc.o
[ 40%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/elemwise.cc.o
[ 40%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/nn.cc.o
[ 40%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/reduction.cc.o
[ 41%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/schedule.cc.o
[ 41%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/transform.cc.o
[ 41%] Building CXX object CMakeFiles/tvm_objs.dir/src/topi/vision.cc.o
[ 41%] Building CXX object CMakeFiles/tvm_objs.dir/src/driver/driver_api.cc.o
[ 41%] Building CXX object CMakeFiles/tvm_objs.dir/src/parser/meta_ref.cc.o
[ 42%] Building CXX object CMakeFiles/tvm_objs.dir/src/parser/parser.cc.o
[ 42%] Building CXX object CMakeFiles/tvm_objs.dir/src/parser/source_map.cc.o
[ 42%] Building CXX object CMakeFiles/tvm_objs.dir/src/parser/span_check.cc.o
[ 42%] Building CXX object CMakeFiles/tvm_objs.dir/src/printer/doc.cc.o
[ 42%] Building CXX object CMakeFiles/tvm_objs.dir/src/printer/model_library_format_printer.cc.o
[ 43%] Building CXX object CMakeFiles/tvm_objs.dir/src/printer/relay_text_printer.cc.o
[ 43%] Building CXX object CMakeFiles/tvm_objs.dir/src/printer/text_printer.cc.o
[ 43%] Building CXX object CMakeFiles/tvm_objs.dir/src/printer/tir_text_printer.cc.o
[ 43%] Building CXX object CMakeFiles/tvm_objs.dir/src/printer/tvmscript_printer.cc.o
[ 43%] Building CXX object CMakeFiles/tvm_objs.dir/src/support/ffi_testing.cc.o
[ 44%] Building CXX object CMakeFiles/tvm_objs.dir/src/support/hexdump.cc.o
[ 44%] Building CXX object CMakeFiles/tvm_objs.dir/src/support/parallel_for.cc.o
[ 44%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/codegen.cc.o
[ 44%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/compilation_config.cc.o
[ 44%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/func_registry_generator.cc.o
[ 45%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/generic_func.cc.o
[ 45%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/intrin_rule.cc.o
[ 45%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/metadata_module.cc.o
[ 45%] Building CXX object CMakeFiles/tvm_objs.dir/src/target/tag.cc.o
c++: internal compiler error: 段错误 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/tvm_objs.dir/build.make:5390: recipe for target 'CMakeFiles/tvm_objs.dir/src/target/tag.cc.o' failed
make[2]: *** [CMakeFiles/tvm_objs.dir/src/target/tag.cc.o] Error 4
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/tvm_objs.dir/all' failed
make[1]: *** [CMakeFiles/tvm_objs.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Any help would be appreciated

**Comment by 43998213** [comment]
tried gcc-8 also failed

**Comment by 43998213** [comment]
llvm-config --version ==6.0.0

**Comment by 43998213** [comment]
Kib Mem: 32686660
Kib swap: 16343312

**Comment by leeexyz** [comment]
@43998213  Specify the number of jobs `make -j4`
