### ISSUE TITLE
[Bug] ir.IRModule.from_expr return type dismatch

### ISSUE THREAD

**Issue by chuqingG** [apache/tvm#9803]
### Expected behavior

In your [doc](https://tvm.apache.org/docs/reference/api/python/ir.html?highlight=from_expr#tvm.ir.IRModule.from_expr) I found that the return type is `tvm.runtime.Module`

### Actual behavior

When I ran code as following:
```python
mod = tvm.IRModule.from_expr(func)  # note this API
print(mod.imported_modules[0].get_source())
```
It showed that :
```bash
Traceback (most recent call last):
  File "test_api.py", line 11, in <module>
    print(mod.imported_modules[0].get_source())
  File "/home/v-chuqinggao/tvm/python/tvm/runtime/object.py", line 67, in __getattr__
    raise AttributeError("%s has no attribute %s" % (str(type(self)), name))
AttributeError: <class 'tvm.ir.module.IRModule'> has no attribute imported_modules
```
which means the actual return type is `tvm.ir.module.IRModule`

### Environment

tvm=0.9.dev0

your current doc version=0.9.dev182+ge718f5a8a

**Comment by masahi** [comment]
Thanks you are right, the doc is wrong. A PR welcome.

**Comment by chuqingG** [comment]
> Thanks you are right, the doc is wrong. A PR welcome.

thanks, there seems to be a few other errors in the doc, I think I can pr together. : )
