### ISSUE TITLE
[Bug] TensorFlow Hub model compilation failing

### ISSUE THREAD

**Issue by sayakpaul** [apache/tvm#9819]
I am trying to compile the following model using [this guide](https://tvm.apache.org/docs/how_to/compile_models/from_keras.html):

```py
import tensorflow as tf 
import tensorflow_hub as hub


hub_url = "gs://cloud-tpu-checkpoints/efficientnet/v2/hub/efficientnetv2-b2/feature-vector"
efficientv2_b2 = tf.keras.Sequential(
    [
        tf.keras.layers.InputLayer(input_shape=(260, 260, 3)),
        hub.KerasLayer(hub_url, trainable=False),
        tf.keras.layers.Dense(5, activation="softmax"),
    ]
)
```

Compilation code:

```py
from tvm import te
import tvm
import tvm.relay as relay

shape_dict = {"input_1": (1, 3, 260, 260)}
mod, params = relay.frontend.from_keras(efficientv2_b2, shape_dict)
            
target = "cpu"
dev = tvm.cpu(0)

with tvm.transform.PassContext(opt_level=0):
    model = relay.build_module.create_executor("graph", mod, dev, target, params).evaluate()
```

It leads to complaining Hub layers are not being supported by TVM. Is there a workaround? 

### Expected behavior

The compilation would be complete without fail.

### Actual behavior

It leads to complaining Hub layers are not being supported by TVM.

### Environment

I built TVM with NNPack following the guide: https://tvm.apache.org/docs/install/from_source.html. I am using Debian 10 on a GCP machine (`n1-standard-8`). TensorFlow version is 2.7.0. 

### Steps to reproduce

Have already provided it.

**Comment by masahi** [comment]
We don't support TF2 models. Try the onnx path via https://github.com/onnx/tensorflow-onnx.

**Comment by sayakpaul** [comment]
Convert to ONNX first and then compile?

**Comment by masahi** [comment]
Yes. TF -> ONNX -> TVM works well, while our TF direct support is not great.
