### ISSUE TITLE
[Bug] Remove apt cache after apt-get

### ISSUE THREAD

**Issue by areusch** [apache/tvm#9825]
Per https://github.com/apache/tvm/pull/9060#discussion_r746330230, [best practice](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run) for `apt-get install` in docker is to `rm -rf /var/lib/apt/lists/*` after installation. we should change all docker apt-get command to do this.

**Comment by leandron** [comment]
> Per [#9060 (comment)](https://github.com/apache/tvm/pull/9060#discussion_r746330230), [best practice](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run) for `apt-get install` in docker is to `rm -rf /var/lib/apt/lists/*` after installation. we should change all docker apt-get command to do this.

Also it is implied by this change that all our `docker/install/*.sh` files should not assume there is an apt cache, and therefore, they should all `apt-get update` prior to installing any package.

**Comment by areusch** [comment]
maybe we should just write an apt wrapper that handles this and only apt-get update one per CI image build?

**Comment by driazati** [comment]
Fixed in #11470
