### ISSUE TITLE
[Docs] Update InferBound Pass documentation

### ISSUE THREAD

**Issue by haozech** [apache/tvm#9827]
Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first :smile_cat:

Issues that are inactive for a period of time may get closed. We adopt this policy so that we won't lose track of actionable issues that may fall at the bottom of the pile. Feel free to reopen a new one if you feel there is an additional problem that needs attention when an old one gets closed.

### Documentation Title & Type

"InferBound Pass" , Architecture Guide Doc

### Additions/Changes Requested

The Limitations of PassUpDomain section of "InferBound Pass" seems to be out-dated.

In the Limitations of PassUpDomain section of InferBound Pass, I ran the code in Ex.6 in TVM ver0.8. And my result is not the same with the result given in the doc. Doc’s result :
```python
// attr [B] storage_scope = "global"
allocate B[float32 * 16]
produce C {
 for (ci.cj.fused.outer, 0, 4) {
   produce B {
     for (bi, 0, 4) {
       for (bj, 0, 4) {
         B[((bi*4) + bj)] = (A[((bi*4) + bj)] + 2.000000f)
       }
     }
   }
   for (ci.cj.fused.inner, 0, 4) {
     C[((ci.cj.fused.outer*4) + ci.cj.fused.inner)] = (B[((ci.cj.fused.outer*4) + ci.cj.fused.inner)]*3.000000f)
   }
 }
}
```
my result using TVM 0.8:
```python
@main = primfn(A_1: handle, C_1: handle) -> ()
  attr = {"from_legacy_te_schedule": True, "global_symbol": "main", "tir.noalias": True}
  buffers = {C: Buffer(C_2: Pointer(float32), float32, [4, 4], []),
             A: Buffer(A_2: Pointer(float32), float32, [4, 4], [])}
  buffer_map = {A_1: A, C_1: C} {
  allocate(B: Pointer(global float32), float32, [4]), storage_scope = global;
  for (ci.cj.fused.outer: int32, 0, 4) {
    for (bj: int32, 0, 4) {
      B[bj] = ((float32*)A_2[((ci.cj.fused.outer*4) + bj)] + 2f32)
    }
    for (ci.cj.fused.inner: int32, 0, 4) {
      C_2[((ci.cj.fused.outer*4) + ci.cj.fused.inner)] = ((float32*)B[ci.cj.fused.inner]*3f32)
    }
  }
}
```
It seems like the limitation mentioned in the doc has no longer existed. So the doc need to be updated.

Discuss post : https://discuss.tvm.apache.org/t/the-doc-about-inferbound-seems-to-be-out-dated/11798

**Comment by areusch** [comment]
Adding link from discuss: https://tvm.apache.org/docs/arch/inferbound.html
