### ISSUE TITLE
Mismatch of document and code repo

### ISSUE THREAD

**Issue by YukeWang96** [apache/tvm#9837]
In the document, https://tvm.apache.org/docs/dev/tutorial/codebase_walkthrough.html. 
it says there are directory `src/codegen/` with files such as `codegen_cuda.cc` and `codegen.cc` that will generate a `runtime::Module` object. However, in the current release there is no such directory, has it been renamed to `src/target/`?

**Comment by masahi** [comment]
Yes, that document is hopelessly outdated. PR welcome.
