### ISSUE TITLE
[CI Problem] Flaky segfault `test_ethosn/test_addition.py::test_addition` 

### ISSUE THREAD

**Issue by masahi** [apache/tvm#9895]
Happening quite frequently 

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9882/2/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9892/3
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9892/1/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9832/1/pipeline
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9896

@Leo-arm @leandron @Mousius

**Comment by masahi** [comment]
This one is also from `ethosn` but different kind of failure `std: :bad_alloc`

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9892/2/pipeline/268

**Comment by masahi** [comment]
This could be due to https://github.com/apache/tvm/issues/9705

**Comment by Leo-arm** [comment]
I looked through the latest patch, the update to a more recent version of the Ethos-N driver stack and I don't see anything that I would worry about. I also ran everything locally in image 80 and it is not failing for me, so for the moment I am thinking it is a disk space issue.

**Comment by Leo-arm** [comment]
@masahi I think we can close this one as it does not seem to occur any more.

**Comment by masahi** [comment]
Yeah agreed, thanks @Leo-arm
