### ISSUE TITLE
[Bug] M1 Pro macOS unable to build

### ISSUE THREAD

**Issue by jinfagang** [apache/tvm#9944]
```
      tvm::codegen::LLVMModuleNode::Init(tvm::IRModule const&, tvm::Target const&) in llvm_module.cc.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for llvm::raw_svector_ostream", referenced from:
      tvm::codegen::BuildAMDGPU(tvm::IRModule, tvm::Target) in codegen_amdgpu.cc.o
      tvm::codegen::BuildHexagon(tvm::IRModule, tvm::Target)::$_2::operator()(llvm::Module const&, tvm::codegen::BuildHexagon(tvm::IRModule, tvm::Target)::CodeGenFileType) const in codegen_hexagon.cc.o
      tvm::codegen::BuildNVPTX(tvm::IRModule, tvm::Target) in codegen_nvptx.cc.o
      tvm::codegen::LLVMModuleNode::GetSource(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in llvm_module.cc.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for llvm::IRBuilderDefaultInserter", referenced from:
      tvm::codegen::CodeGenBlob(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in codegen_blob.cc.o
      tvm::codegen::CodeGenLLVM::Init(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, llvm::TargetMachine*, llvm::LLVMContext*, bool, bool, bool) in codegen_llvm.cc.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libtvm.dylib] Error 1
make[1]: *** [CMakeFiles/tvm.dir/all] Error 2
make: *** [all] Error 2
```

latest commit in my pulled version: 6eb4ed813ebcdcd9558f0906a1870db8302ff1e0

**Comment by Hzfengsy** [comment]
I build it on my M1Pro without any problem. 

`BuildAMDGPU` and `BuildNVPTX ` are in your log. Is that the problem?

**Comment by jinfagang** [comment]
@Hzfengsy  Hi, what's your config.cmake? I think I turned them off, but only enabled llvm ON. that's all, and I didn't changed any settings by default. it seems related with `ld: symbol(s) not found for architecture x86_64` which M1 Pro doesn't have any x86 arch. It was arm.

**Comment by Hzfengsy** [comment]
I only enabled LLVM ON. Can you check where did you install LLVM (from homebrew or the official website or transferred from old x86 mac)? Also please check if the LLVM is ARM version. I installed my LLVM from homebrew. If the problem still exists, please try to reinstall LLVM

**Comment by jinfagang** [comment]
@Hzfengsy I also install llvm via `brew install llvm`. Tried reinstall it, but same problem still exists.

**Comment by AndrewZhaoLuo** [comment]
Which shell are you using? I use iTerm2 and it seems to source from ~/.bash_profile not bashrc

**Comment by jinfagang** [comment]
@AndrewZhaoLuo I am using zsh. I already set these path in zshrc.

**Comment by jinfagang** [comment]
I removed all build directly and rebuild whole project same error again. Can anybody share the step build on M1 Pro ?

**Comment by zhiqwang** [comment]
Just FYI,

Set `cmake .. -G Ninja -DCMAKE_OSX_ARCHITECTURES=arm64` when building, and use Python 3.8, I guess tvm can be built successfully.

As an example, I run yolov5 https://github.com/zhiqwang/yolov5-rt-stack/blob/main/notebooks/export-relay-inference-tvm.ipynb

**Comment by driazati** [comment]
Closing since there seems to be some workarounds, please re-open if this is still an issue with the latest code from `main`
