### ISSUE TITLE
[Bug]  test_zephyr_aot::test_tflite failure

### ISSUE THREAD

**Issue by tkonolige** [apache/tvm#9967]
https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-9873/3/pipeline/

`tests/micro/zephyr/test_zephyr_aot.py::test_tflite[qemu_x86]` is failing with
```
make[3]: zephyr/CMakeFiles/run.dir/build.make: No such file or directory
make[3]: *** No rule to make target 'zephyr/CMakeFiles/run.dir/build.make'.  Stop.
```

**Comment by driazati** [comment]
closing since we haven't seen this lately afaik
