### ISSUE TITLE
[CI Problem] run one code 2 or more times at once, speeds drop a lot

### ISSUE THREAD

**Issue by Jillian2017** [apache/tvm#9977]
Hi,
I set 'TVM_NUM_THREADS' more than one, and process a video with tvm. While concurrent processing different videos with the same code, the speed will slow down a lot. 
I use htop find that, if only one program running , 4 cores are occupied. While increasing the processing number to 3, the cores are not occupied to 12 as expected, maybe 6 cores are used, even though there are many spare cores to be used in the server,  so the speed slow down. 
Am I clear? 
Looking forward to your reply.

**Comment by masahi** [comment]
Please post your question to the discuss forum.
